### ISSUE TITLE
[META] Prepare for migration of ITS custom D7 sites

### ISSUE THREAD

**Issue by genjohnson** [uiowa/uiowa#120]
- [ ] Audit D7 sites maintained by ITS-CSI. Are there sites that will migrate easily? Sites that will be especially difficult to migrate?
- [ ] Outline content migrations. What content will be migrated? How (with what tools & processes) might the migrations be performed?
- [ ] Create a communications plan for site owners.

**Comment by ethanstjohn** [comment]
I am writing up an excel sheet with my opinions on the difficulty of migrating each custom site. This may take some time.
