### ISSUE TITLE
[META] Paragraph Enhancements

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#126]
@bspeare, @mark-bennett-uiowa and I were reviewing the current paragraphs UI implementation and have some ideas for improving it:

- [ ] Default the Administrative label for sections to the bundle type (Section). Modify the UI to show the Administrative label in place of the bundle type at the top of the section. Allow editing the administrative label to happen in-place where it shows and not as a separate field.
- [ ] Change page level "Content Blocks" field label to "Sections."
- [ ] Change section level "Content Blocks" field label to "Widgets."
- [ ] Remove "to Content Blocks" from the drop-down button for adding paragraphs to each section.
- [ ] Change third_party_settings > field_group > group_uip_settings > weight from 2 to 1 in core.entity_form_display.paragraph.section.default.yml
- [ ] Change "Settings" label to "{Paragraph type} Settings" in core.entity_form_display.paragraph.{paragraph_type}.default.yml

### Issues
- [[META] Alternative UI like divibuilder](https://www.drupal.org/project/paragraphs/issues/2692051)
- [[META] Integrate more nicely with quick edit](https://www.drupal.org/project/paragraphs/issues/2476863)
- [[META] Investigate adoption of outside-in settings tray](https://www.drupal.org/project/paragraphs/issues/2942364)
- [Can we use layout_plugin module to provide different templates for paragraphs](https://www.drupal.org/project/paragraphs/issues/2449347)
- [Managing paragraphs in the frontend](https://www.drupal.org/project/paragraphs/issues/2913857)

### Projects
- [Geysir](https://www.drupal.org/project/geysir)
- [Bootstrap Paragraphs](https://www.drupal.org/project/bootstrap_paragraphs)
- [Paragraphs Frontend UI](https://www.drupal.org/project/paragraphs_frontend_ui)
- [Entity Reference with Layout](https://www.drupal.org/project/entity_reference_layout)
