### ISSUE TITLE
[Story] As a site visitor I can experience reasonable page load times.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#1282]
Initial page loads are quite slow for the homepage and other sites. This may point to a larger performance issue. We should investigate and remediate.

Performance benchmarking (lighthouse, others) so we can address what is quickly addressable, and plan for what is more of an investment (minify, lazy load, strategy for video, etc...)

- [x] uiowa/uiowa#697 - Lazy Load Images @joewhitsitt
- [x] Reduce front page video to <10mb
- [x] Investigate https://docs.acquia.com/acquia-cloud/platformcdn/
- [x] Investigate Big Pipe #1296 
- [x] Investigate Webp https://www.drupal.org/project/webp (+1 jpeg2000)
- [x] Restrict locally-hosted image, video file sizes to cacheable limit
- [x] Investigate why ckeditor.js loads for public facing site #1305
- [x] Move Font Awesome assets to be locally hosted #1306
- [x] Confirm fast_404 is enabled/working.
- [x] Investigate autodiscover requests https://support.acquia.com/hc/en-us/articles/360004553253-Avoiding-404-error-messages-in-your-logs
- [x] Claim New Relic! https://docs.acquia.com/acquia-cloud/monitor/apm/#claiming-your-new-relic-apm-pro-account

**Comment by richardbporter** [comment]
I wonder if this is worth a try? https://www.drupal.org/project/webp

**Comment by richardbporter** [comment]
https://tools.pingdom.com/#5c4755fc48800000

**Comment by bspeare** [comment]
https://www.webpagetest.org

**Comment by richardbporter** [comment]
I don't see anything pointing to backend performance issues. The biggest gains can probably be had on the frontend, anyway. For the front page specifically, the video might be an issue if I understand this correctly: https://docs.acquia.com/acquia-cloud/performance/varnish/files/#files-greater-than-10mb-in-size

**Comment by mjoneill** [comment]
Another tool: https://web.dev/

**Comment by bspeare** [comment]
It looks like 200kb of ckeditor.js is loading for anonymous users: https://www.drupal.org/project/drupal/issues/3037150.  It looks like it also loads on https://hr.uiowa.edu.  Do we know why this is there?

**Comment by richardbporter** [comment]
No clue. I noticed that to.

**Comment by bspeare** [comment]
Is it worth hosting the font awesome files locally?  https://uiowa.local.drupal.uiowa.edu/admin/config/content/fontawesome.   We are currently hosting all of the font files locally (https://www.tunetheweb.com/blog/should-you-self-host-google-fonts/) and it might make sense to self-host the font awesome files too.

**Comment by richardbporter** [comment]
I think this story is complete. A few follow ups could be to lazy load the vertical video placeholder images. We may need to measure the pros/cons of so many HTTP requests for each of the components versus aggregating them.
