### ISSUE TITLE
[Story] Schema.org module (see SiteNow)

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#1290]
- [ ] #1325 [Task] Identify schemas for standard content types
- [x] #1326 [Task] Homepage search schema
- [ ] #1348 Schema for Academic departments (Basic Page content type. Possibly front page as well)
- [ ] #1349 Add schema for colleges
- [ ] #1351 Schema for non-academic departments (Basic page content type. Possibly front page as well)
- [ ] #1350 Add FAQ Schema option (Basic Page/accordion?)
- [ ] #1352 Add Alert schema
- [ ] Speakable content (for articles, mostly (https://developers.google.com/search/docs/data-types/special-announcements)
- [ ] Add Museum content type
- [ ] Add Building content type
- [x] #1291 Developers copy existing CollegeorUniversity schema from current home page and get it firing on new home page
- [x] #1361 Preview image/open graph support
- [x] Check OpenGraph markup
- [x] #2169 Check Twitter Card markup

**Comment by mjoneill** [comment]
@joewhitsitt I have a full person specification I've provided for the people directory integration.  Do we have a separate non-apr integration People content type for which that would be useful?

**Comment by mjoneill** [comment]
@joewhitsitt We've built JobListing and Event schema as well.  I'm assuming that there are no content types for either of those outside of the Event system and the HR Jobs system. Can you let me know if these are content types that are used elsewhere outside of those systems? If so, I can furnish schema.

**Comment by joewhitsitt** [comment]
SiteNow v2 comes with:
- a non-APR content type for person. I am not aware of any D8 work being done for APR.
- events that are pulled dynamically from content.uiowa.edu and can be reworked to provide additional schema/metatag data based on the information coming from content.uiowa.edu

**Comment by joewhitsitt** [comment]
Relates to https://github.com/uiowa/uiowa/issues/2169
