### ISSUE TITLE
As a SiteNow developer, I can deploy a theme that uses UIDS with paragraphs

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1324]
# Next steps
- [x] #1465 Create story task for Events display to use event component styles 
- [x] Article page design https://github.com/uiowa/uiowa/issues/1421
- [x] As a SiteNow user, I can view all uses of the card component as "done"  https://github.com/uiowa/uiowa/issues/1405
- [ ] #1373 Build generalized/abstract templates in uids_base for all UIDS components. @pyrello 
- [x] #1397 Update Lockup form to use UIDS
- [x] #371 Investigate what elements need to go into the base theme and what might need to go into a sitenow-specific subtheme.
- [x] #1304 Audit and create "diff" between SiteNow paragraphs and collegiate layout builder custom blocks.
- [x] uiowa/uids#102 Implement CSS grid utility classes in UIDS.
- [x] Identify and implement bootstrap classes used in SiteNow into uids_base (@bspeare)
- [x] Refactor bootstrap classes being used to use uids flexbox mixin and adjust css that is extending bootstap classses to use flexbox mixin and variables from uids (@bspeare)
- [x] Refactor Article display to use card component for default, grid, and masonry styles (@bspeare)

# Block/paragraph-specific issues
- [x] uiowa/uids#104 Refactor the card component in UIDS

**Comment by pyrello** [comment]
There is some overlap with this story and https://github.com/uiowa/uids/issues/79

**Comment by pyrello** [comment]
@bspeare One thing that will need to be figured out as part of any transition from uiowa_bootstrap to uids_base is how to adapt column layouts from bootstrap into uids.

Currently, SiteNow uses a field attached to each paragraph type as a meta field that allows the user to select the the column width:
https://github.com/uiowa/uiowa/blob/d0c613d47f4eddfdb3a8f7b47d4abed5449a77e8/docroot/modules/custom/sitenow_paragraphs/sitenow_paragraphs.module#L304-L308

Either it will be necessary to create temporary Drupal-only instances of the `.col-*` selectors used or we'll need to come up with something more generalized.

**Comment by bspeare** [comment]
@pyrello I'd like to set something up to use in UIDS that we can utilize within uids_base that accommodate those classes.

**Comment by bspeare** [comment]
Something like https://hacks.mozilla.org/2017/04/replace-bootstrap-layouts-with-css-grid/ looks like a good place to start.

**Comment by joewhitsitt** [comment]
The video/description section on https://brand.prod.drupal.uiowa.edu/ is an example of the col-md(fluid)/col-md-4 but I think the problem I ran into earlier in trying to switch to CSS Grid was where the fluid could come at unexpected times (middle, end) and amongst a wrap. See the Trying to break things... section of this codepen: https://codepen.io/joewhitsitt/pen/yLNzOYE

**Comment by pyrello** [comment]
@joewhitsitt Thanks for the example! I was using the demo site to work against, but I think I'll start using the brand site, both for the reasons discussed in our meeting earlier and because of this.

**Comment by bspeare** [comment]
@joewhitsitt I think this addresses the issue that you pointed out with CSS Grid: https://www.smashingmagazine.com/2017/09/css-grid-gotchas-stumbling-blocks/#should-grid-be-used-for-main-layout-and-flexbox-for-components.    After reading this, it sounds like your setup with SiteNow is geared toward Flex Layout and we should probably keep it that way - is that your impression?

**Comment by joewhitsitt** [comment]
Yes, leave it to smashing to articulate what I was trying to say. If we could stay _flex_ -ible and still adopt uids_base, I think that alleviates my concern surrounding the "fluid" option currently used across several sites.

The column width field on paragraph content blocks is the only place I think SiteNow is using the fluid option.

**Comment by bspeare** [comment]
So maybe for a `POC` for SiteNow integration I will add a specific SiteNow layouts.scss file in uids_base that uses `bootstrap-grid.css` but updated with breakpoint variables and container widths from UIDS.   How does that sound?

**Comment by joewhitsitt** [comment]
`poc` sounds fine. i am fine with stripping out all of the bootstrap classes and framework dependencies as time allows and using uids_base mixins for flex where we can to continue to support these options

**Comment by bspeare** [comment]
@joewhitsitt Do you have a list of the bootstrap classes that are being applied programmatically?  Is this the list: https://github.com/uiowa/uiowa/issues/260?

**Comment by joewhitsitt** [comment]
It is dated and incomplete. I will take some time and update that issue.

**Comment by joewhitsitt** [comment]
Closing!
