### ISSUE TITLE
[Story] Launch Day Checklist

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#1374]
The following should be/need to be done on launch day.

UIowa.edu
- [x] Move uiowa.edu, www.uiowa.edu domain from uiowa701 to uiowa01.
- [x] Clear Varnish for uiowa.edu, www.uiowa.edu.
- [x] Remove uiowa.prod.drupal.uiowa.edu domain from uiowa01 prod env.
- [x] Sync uiowa.edu D7 database and files to dev environment.
- [x] Move uiowa dev domain to uiowa701 dev environment.
- [ ] Launch announcement to UI Web + Friends
- [x] Update schema reference to logo to point to the new Block Iowa 
- [x] Verify robots.txt is configured correctly
- [x] Verify sitemap.xml is present and generating correctly
- [x] Verify old uiowa.edu pages are redirecting to new pages
- [x] Run ScreamingFrog against new site
- [x] Verify GTM is firing correctly
- [x] Verify GA is firing correctly
- [x] Verify that old critical incident plan pages redirect to new pages
- [x] Change feedback link in footer from a mailto: link to the feedback form (and test). See #1364 for context.
- [x] Check schema for logo file. Make sure it's pointing to the new Logo (block Iowa)
- [x] Check for hardcoded references to stage or dev sites (screamingfrog)
- [x] Verify tags are migrated to new site
- [x] Get crazyegg on new site

Brand Site Lockup Gen
- [x] Move brand.uiowa.edu domain from uiowa703 to uiowa.
- [x] Clear Varnish for brand.uiowa.edu.
- [x] Remove brand.prod.drupal.uiowa.edu domain from uiowa prod env.
- [x] Sync brand.uiowa.edu D7 database and files to dev environment.
- [x] Move brand dev domain to uiowa703 dev environment.
- [x] Move GA form old site to new
- [x] Site scans, checks, tests for SEO and quality (see uiowa.edu list)
- [x]  Confirm daily digest is firing

UIDS
- [x] Launch it/ merge PR
- [x] Verify logo is the same as what Joe is using (what Joe has been given)

D7 + D8 Brand Bars

- [x] #1322
- [x] #1327

[@mjoneill]

**Comment by richardbporter** [comment]
Had to run https://github.com/uiowa/uiowa/pull/1589#issuecomment-628173807 again to get robots.txt purged. Should probably document that.

**Comment by joewhitsitt** [comment]
Can we call this one done @mjoneill ?

**Comment by mjoneill** [comment]
> Can we call this one done @mjoneill ?

I just checked and saw the robots.txt exclusion set up and configured correctly/as intended.  Looks good to me.


@joewhitsitt
