### ISSUE TITLE
Document potential changes by users for sitenow uids_base roll out

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1401]
- [ ] Section card alignments set to "none" if you want equal height cards
- [ ] Remove `<p>` or `<h2>` empty tags since padding has increased since `uiowa_bootstrap`
- [ ] Extra padding classes on sections might create a lot of extra padding
- [ ] `<p>` tags inside `<li>` tags will create extra spacing on list items
- [ ] Footer lockup logos removed and available at...? #1829 
- [ ] Footer menus have a new name https://github.com/uiowa/uiowa/issues/1611
- [ ] Top links have a limit of two links and a new location to edit https://github.com/uiowa/uiowa/issues/1817
- [ ] Website header and footer are no longer full-width
- [ ] Site Slogan is gone and Parent Organization/Link is now available

**Comment by richardbporter** [comment]
The uiowa_alerts module will also be enabled so we'll need docs on that. I can help write those.

**Comment by richardbporter** [comment]
> Footer lockup logos removed and available at...?

Like for download and/or historical purposes?

**Comment by joewhitsitt** [comment]
>Previously placed lockups in the footer have been removed and replaced by the block Iowa wordmark per brand guidelines. A copy of the previous lockup should be located on the last page of a website's media overview (admin/content/media). https://sitenow.uiowa.edu/news/2020/07/sitenow-v2-websites-will-be-getting-new-look-and-feel

**Comment by richardbporter** [comment]
Is anything more needed here since this is documented in the article? 
https://sitenow.uiowa.edu/news/2020/07/sitenow-v2-websites-will-be-getting-new-look-and-feel
