### ISSUE TITLE
As a content editor I can add all variations of a card with UIDS styling

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#1405]
# Variations:
- [x] No image
- [x] No link
- [x] Linked with faux button
- [x] Linked without faux button

# Non-card accommodations
- [x] Image only
- [x] Image + link

# UIDS Updates
- [x] https://github.com/uiowa/uids/issues/147
- [x] https://github.com/uiowa/uids/issues/146
- [x] https://github.com/uiowa/uids/issues/145
- [x] https://github.com/uiowa/uids/issues/144
- [x] https://github.com/uiowa/uids/issues/142
- [x] https://github.com/uiowa/uids/issues/152

# Bugs:
- [x] Fix card link https://github.com/uiowa/uiowa/issues/1408
- [x] Fix articles list breakpoint https://github.com/uiowa/uiowa/issues/1410
- [x] Fix image padding for mobile https://github.com/uiowa/uiowa/issues/1411
- [x] Hide Images feature is broken https://github.com/uiowa/uiowa/issues/1414
- [x] Hide on lists option is currently broken for articles #1413 
- [x] Investigate getting "hide on lists" to work on article content type view pages (not a bug)
- [x] Investigate using card component to style people directory (Postponed until future People work).
- [x] Refactor sitenow.scss so paragraph card and article css is in separate partial files (@bspeare)
- [x] Refactor card component in UIDS to use utility mixins so that it can be used within paragraph components @bspeare
