### ISSUE TITLE
Update references to migrated SiteNow footer menus

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#1763]
## Problem
SiteNow footer menus updated in #1611 from `footer` and `footer-second` to `footer-primary` and `footer-secondary`. Intention was for a low-impact update migration, but several updates and some cleaning may be necessary as a result.

## To-do

- [x] Update docs
- [x] Update tours
- [x] Update uiowa_footer module form
- [x] permissions across all splits
- [x] update allowed menus for basic page?
- [x] Update menu breadcrumb config

Blocked by #1611, related to PR #1755.

**Comment by cory-skeers** [comment]
Docs are generic and don't need specific updating. uiowa_footer module form is based on the custom_menu and custom_menu_2 configs that are updated, so is good to go.

**Comment by cory-skeers** [comment]
Files and update hook updated to set webmaster perms for the moved footer menus for the following:
- Default config
- hr config
- ignh config

**Comment by cory-skeers** [comment]
@joewhitsitt re: 'update allowed menus for basic page', would this be for the menu settings on the page, and adding it directly to the footer menu(s) from the basic page edit, or am I missing what the bottom checkbox is referring to?

**Comment by joewhitsitt** [comment]
admin/structure/types/manage/page "Menu settings" where you select the allowed menus

**Comment by cory-skeers** [comment]
Updated basic page allowed menus, tours (links and menu labels), and removed the no longer used footer and footer-second from the breadcrumb config.

A grep on modules and config looks like these were the last references.

**Comment by joewhitsitt** [comment]
Closing, good work
