### ISSUE TITLE
Layout Builder feature maturity

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1778]
# Layout Builder feature maturity
- [x] #1994 Slider (carousel) component.
- [x] #1529 Layout Builder collections: Accordions, Tabs.
- [x] #1523 Provide a way to lock the header section.
- [x] #1789 View blocks for articles/people with a list display. 
- [x] #2071 Custom events block
- [x] #1925 Replace homepage default content with Layout Builder version.
 
# Issues
- [x] #1783 Unable to edit custom blocks on reverted LB node with custom blocks.
- [x] #1890 Granular block permissions
- [x] https://github.com/uiowa/uiowa/issues/1114 Safari icons in tray.
- [x] https://github.com/uiowa/uiowa/issues/596 - deprecate/remove image background media type - appears to be available to layout/collegiate media library
- [x] https://github.com/uiowa/uids/issues/245 Hero block centering bug
- [x] https://github.com/uiowa/uiowa/issues/1457 Flexbox stacking issue in preview mode.
- [x] https://github.com/uiowa/uiowa/pull/1912 Layout builder style to set container alignment.
- [x] https://github.com/uiowa/uiowa/issues/1889 Limit custom fields available in layout builder tray. 
- [x] #1922 Hide Site Improve widget when editing a layout builder page. 
- [x] display title/title on block types does nothing but is visible to webmasters?  (We are currently removing this title from display in twig template: https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/field/field.html.twig.  Do we want to have it available for display?)
- [x] https://github.com/uiowa/uiowa/pull/1917 Layout builder style to remove default padding
- [x] https://github.com/uiowa/uiowa/issues/1688 Container padding when background color is used.
- [x] #960 Remove image button is not very usable in LB tray.
- [x] #1926 Add body field to Page content type.
- [x] #2038 Change component text areas to use `minimal_html` by default or limit toolbar buttons to reduce kitchen sink.  
- [x] https://github.com/uiowa/uiowa/issues/1957 Stat component regressions. 
- [x] https://github.com/uiowa/uiowa/issues/1962 One-col layout fix.
- [x] #1973 Update entity_usage to work with layouts/media library.
- [x] https://github.com/uiowa/uiowa/issues/1987 Card Horizontal formatting and permissions within one-col layout
- [x] Remove Spacer/Separator block or did that already happen in https://github.com/uiowa/uiowa/pull/1979?
- [x] Refactor block templates that use older component structure like in https://github.com/uiowa/uiowa/issues/2046. 
- [x] https://github.com/uiowa/uiowa/issues/955 Using Layout Builder Restrictions module, limit custom blocks that are able to be used in a layout region. 
- [x] #1920 Further investigation of LB/inline block permissions
- [x] https://github.com/uiowa/uids/pull/268 Refactoring Hero component to become both Hero and Banner component in UIDS 
  - [x]  https://github.com/uiowa/uiowa/issues/1928 Refactoring the custom Hero block template in `uids_base` and remove Banner block template.
  - [x] https://github.com/uiowa/uiowa/issues/1908 Page title / hero appearance preview on edit preview pages (This should be fixed by the issues above).
- [x] Investigate restricting layout builder styles to sections.
- [x] #2007 Webform block: fix settings tray configuration
- [x] https://github.com/uiowa/uiowa/issues/2059 Adjust default margins on sections and how they interact with background colors
- [x] https://github.com/uiowa/uiowa/issues/2053 Extended width container padding issue.
- [x] https://github.com/uiowa/uiowa/issues/2054 Default padding for text areas with a background color. 
- [x] https://github.com/uiowa/uiowa/issues/2060 Allow `<hr>` with class within text areas. 
- [x] https://github.com/uiowa/uids/issues/300 Minor UIDS style updates.
- [x] https://github.com/uiowa/uiowa/issues/2063 Margin below feature image. 
- [x] Main content area rendering issue. 

# Nice to have
- [x] #958 Grouping of styles.
- [x] #1366 Improve drag handle. 
- [x] #2045 Add [Layout Builder Operation Link ](https://www.drupal.org/project/layout_builder_operation_link) module to allow content editors to edit a layout from the content overview screen. 
- [x] Confirm oEmbed options are styled in uids_base (vimeo, youtube, kaltura, instagram, twitter, facebook)
- [x] #2055 Rename "CTA" to "Call to action"
- [x] #1946 Update website identifiers (console, toolbar)
- [x] https://github.com/uiowa/uiowa/issues/2084 Horizontal stat variant.

**Comment by joewhitsitt** [comment]
I added a few above, but I also have some other concerns to have further discussion about before deciding if it is an issue or not:

- Webmasters have block and block layout access (which I imagine is needed for layout builder) allowing changes to stuff tracked in configuration (Removing blocks, changing placement, modifying menu block settings, adding any block in the system to page). Is there a contrib project that provides more granular permissions?
- Related, the page title block can be removed from a layout and several blocks have the ability to change heading size (including h1) in any DOM order potentially causing a11y issues. Historically we have tried to protect editors from themselves and maybe I need to let this go and let SiteImprove take over.

**Comment by pyrello** [comment]
@joewhitsitt #1523 above is intended to address locking down the page header section to anyone except people with the right permissions. It looks increasingly like we are moving towards a standard-ish header for pages and articles using the hero image + breadcrumb + title layout. #1622 will be part of making that change. The header area should still be able to be overridden by site admins, or possibly webmasters under the right conditions, but will be set to a nice looking default that makes use of the featured image.

I'm not sure if the block permissions are necessary for LB or not. I would have to test that out to see. I'm sure there is either a contrib module that would provide us with more granular permission options, or we could add that to our `layout_builder_custom` module.

**Comment by bspeare** [comment]
I wonder if we should limit the background color styles available to sections?  I could see only allowing the light gray and then shifting the gold, black, and brain patterns to be only used within components like the Hero or the CTA.

**Comment by bspeare** [comment]
Here are some further adjustments we could make to limit confusion with the current Layout Builder Styles:

**Section classes available:**

- Background: Gray
- Margin: Edge-to-Edge
- Margin: Bottom
- Margin: Extended Width Container
- Padding: Top Extra
- Padding: Bottom Extra

Changes to be made:
Remove default margins to sections using background colors so that they can be stacked.  

**Section classes moved to a text class field for advanced users:**

- Vertical alignment: Start
- Background: Black
- Background: Gold
- Background: Brain Pattern
- Background: Brain Pattern Reversed
- Background: Brain Pattern Black
- Margin: Top
- Margin: Remove Default Margins
- Padding: Remove Default Padding
- Layout: Grid styles

**Comment by joewhitsitt** [comment]
I don't think it is in scope for #1979, but I honestly think for the default config that we hide all "more" blocks until we can figure out a solution to the view mode selection mess. Danielle is uncovering all kinds of "not ready" bugs related to those blocks. Webform might be the exception/priority unless we create a custom block type for that instead.

**Comment by richardbporter** [comment]
> display title/title on block types does nothing but is visible to webmasters? (We are currently removing this title from display in twig template: https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/templates/field/field.html.twig. Do we want to have it available for display?)

Is this a thing still? Any more details for clarity?

**Comment by bspeare** [comment]
@richardbporter Is that related to https://github.com/uiowa/uiowa/pull/1986?

**Comment by richardbporter** [comment]
Yes, sounds like that is a non-issue anymore. Checked.

**Comment by richardbporter** [comment]
>Restrict local video to hero and vertical video only. Don't allow usage in wysiwyg areas.

Anyone have more info on this one?

**Comment by joewhitsitt** [comment]
That's me. The only use-case so far for local video is the looping hero video and the vertical videos. We need to make sure roles can't upload/serve/files outside of those use-cases (add media, wysiwyg media, etc)

That is unless we are changing our local video policy now that everything is restricted to 10 MB or less, in which case we need to update the policy and make sure videos render well in wysiwyg

https://sitenow.uiowa.edu/policies#videos

**Comment by richardbporter** [comment]
I don't see it as available in the WYSIWYG:

![image](https://user-images.githubusercontent.com/1068523/90654927-8d81da00-e206-11ea-8410-1859a8277e9e.png)

I also don't see a LB block that has a media field that allows video. Is there one?

**Comment by joewhitsitt** [comment]
Maybe this is an non-issue. Not sure if the collegiate media library allows it but we will want to confirm that when switching from entity embed to media library.

Can webmasters/editors add media via content/media/add?

Hero has a video media field

**Comment by richardbporter** [comment]
> Can webmasters/editors add media via content/media/add?

Yes but local video is not an option.

**Comment by pyrello** [comment]
I moved the rest of the tasks to #2207 and I think we can consider this closed.
