### ISSUE TITLE
Moving to Layout Builder

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1779]
- [x] #1660 and #1806: Finish SiteNow UIDS integration - This is needed to provide some relief with regard to interest in the new branding and design options that have been repeatedly demoed as part of the home page redesign project.
- [x] #1807: Move current SiteNow (V2) Paragraph config into a split.
- [x] Build SiteNow V3 using Layout Builder 
- [x] #1778: Layout Builder feature completeness
- [x] #1918 Documentation split v2/v3
- [x] Start creating beta V3 sites
- [x] Switch to all new SiteNow sites being created using V3

**Comment by joewhitsitt** [comment]
A few thoughts. I am okay with transitioning to all new SiteNow sites using Layout Builder sooner than later with the "beta" label, letting customers know we are still working on it and the documentation/training that needs to be created. This will allow big sites to start putting content into the correct bucket. The feature parity might not yet be there, but we will communicate those changes as they come.

I am warming up to the idea of calling layouts V3. This will give us enough distinction when creating/organizing docs and support. We have console/meta info that would need to be updated based on the two being used.

I don't see automated migration working 100%. It is not a one-to-one migration and I think that any resources going towards automated migration should go towards getting people off D7.

Instead or at least as a primary step, and thanks to a single theme, I think we should investigate a way to have both on at once, either:

- All new basic pages start as layout pages, customers can transition over time.
- Find a way to have both on at once for existing paragraph pages, a guide for transitioning content to layout/preview and have a webmaster one-time switch to turn the page into a layout page so they can maintain menu placement, etc.

Ultimately, it isn't the most ideal to have two methods, but we had several methods in D7. As long as we prioritize and innovate for one method, with the work we have already done to create splits and separate logic it should be fairly straight forward to support and keep the other one running.

Automated migration D8/9 to D8/9 will always be the thing we never get around to.

**Comment by mjoneill** [comment]
Please keep the conversation going. 

I added a meeting to our calendars to discuss on Wed with the team.  

I’d like to see if there’s a path forward we can all get behind and that allows us to: 

1.	Tell clients just starting redesign work what type of site they should build on (paragraphs/layout builder/Gutenberg)
2.	Tell past clients who already migrated to D8 how they will be brought forward
3.	Tell ourselves that we’re making a good decision with what we know
4.	Start decomposing the vision into actual work (including things we’ll need more clarity on)
5.	Whatever else we make visible…

**Comment by joewhitsitt** [comment]
Honest question, beyond feature parity is the implementation of layouts stable enough to hand out to hundreds of customers or are there tasks that would need to be prioritized just to get more users working with it?

**Comment by mjoneill** [comment]
> Honest question...

I'd like to hear the thinking behind this as well.

**Comment by pyrello** [comment]
I'm doing my best to document these considerations in #1778. It is by no means complete at this point, but meant to be an honest accounting of what it would take.

To some degree, we don't know what we don't know with regard to readiness. This is why I would love to have all the ITS developers give LB a serious test to see what we are missing.

**Comment by joewhitsitt** [comment]
> > Honest question...
> 
> I'd like to hear the thinking behind this as well.

Of course I am biased, but I am personally shifting towards layouts because it is in Drupal core, OSC marketing and because I think it is smart to unify Drupal on campus when possible, not because I have experience with it believe it to be the best method most of the time.

I have not worked with it yet as an editor so I honestly don't know a whole lot. All I have seen are demo experiences and the final homepage product. I don't know what it actually takes to put together pages like that. I plan to take some time to experiment with it today. I will document any issues I find in #1778.

**Comment by pyrello** [comment]
@joewhitsitt To your point earlier about figuring out how to have paragraphs at the same time as LB, I have already done this just to prove to myself that is is possible. In #1622, we are turning on layout builder for managing layout at the template level for pages and articles to allow for creating a standard header experience with a hero image behind the breadcrumb and title. In the page LB template, we just place the section blocks field in the layout and it renders as expected. I have not tested this exhaustively, but what I have seen so far seems encouraging.

In a separate test that I did locally, I also turned on the ability to override LB templates per node for the page content type on the brand site. It is possible to use LB with paragraphs at the same time. There are limitations to this:
* The Paragraph sections are still managed through that interface in the Edit screen.
* You can't do much with the Paragraph sections in LB other than move it around or apply styles to it.

So, it seems totally possible that paragraph pages could be gradually switched over to using LB by just recreating the top-most parts of the page in LB, then removing them from the Paragraph sections.

**Comment by joewhitsitt** [comment]
Is the collegiate split what should be default? permissions, text formats and other things come with it. It isn't just layouts.

One thing that stands out is local video.

**Comment by pyrello** [comment]
Created a follow-up issue defining tasks for after we have moved to V3: #2207. Moved relevant items from this list to that one.

**Comment by pyrello** [comment]
With #2345, I think we have accomplished all the tasks for this Epic!
