### ISSUE TITLE
Re-Organize SiteNow Documentation v2/v3 split

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#1918]
## Problem

Our documentation is written with Paragraphs in mind. We need to split this stuff off and replace with layouts specific docs.

## Proposed Solution

- Identify documentation that is outdated or paragraphs only and establish a v2 section to house it. (e.g. https://sitenow.uiowa.edu/documentation/content-blocks)
- Try to account for unique id and url paths and create redirects to the new locations.

- [x] Update footer documentation based on changes in #1806. https://sitenow.uiowa.edu/documentation/basic-site-settings-and-footer-configuration
- [x] Update "MEDIA" paragraph show Media Library icon (currently in collegiate split) and generalize language so that isn't specific to either method. https://sitenow.uiowa.edu/documentation/wysiwyg
- [x] Remove "ALLOWED CLASSES" paragraph https://sitenow.uiowa.edu/documentation/wysiwyg, create follow-up task to address utility classes in uids base
- [x] Update bottom link to point to new "content blocks" documentation: https://sitenow.uiowa.edu/documentation/basic-page-content-type
- [x] Update menus documentation as there are new menus and behaviors (restricted top links) https://sitenow.uiowa.edu/documentation/managing-menus
- [x] Update to mention that removal of a tracking id currently requires developer assistance. https://sitenow.uiowa.edu/documentation/configuring-google-analytics
- [x] Remove https://sitenow.uiowa.edu/documentation/university-iowa-branding-bar
- [x] https://github.com/uiowa/uiowa/issues/1375 - Google Tag Manager
- [x] https://github.com/uiowa/uiowa/issues/1849 People content block (paragraphs)

**Comment by ethanstjohn** [comment]
I have written the documentation and most of it lies within a test state on the page that represents it. I have some docs that are direct changes to old docs locally as well that I can implement after I share it with some people. I have handed this off to Joe at the moment to find the media icon and review the docs.

**Comment by joewhitsitt** [comment]
Thanks for your work on this @ethanstjohn. I made a few edits and added that media library icon
