### ISSUE TITLE
Layout Builder Documentation

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#1929]
- [ ] Images in Layout Builder https://github.com/uiowa/uiowa/issues/1256
- [x] Layout Builder Blocks  blocks/section styling https://github.com/uiowa/uiowa/issues/1961
- [x] Basic Page CT in Layout Builder https://github.com/uiowa/uiowa/issues/1992
    - Documentation or content type guidelines explaining the multi-step of creating initial content and then going to the layout tab.

**Comment by joewhitsitt** [comment]
I am going to close this and #1961, #1992 and split remaining items into separate tasks:

Events: https://github.com/uiowa/uiowa/issues/2162
More Blocks: https://github.com/uiowa/uiowa/issues/2174
Banner (refactored): https://github.com/uiowa/uiowa/issues/2175

Going to leave #1256 open for uiowa.edu reference.
