### ISSUE TITLE
Port uiowa_maui D7 module to D8.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#2184]
The uiowa_maui module is in use on a few D7 sites, notably registrar.uiowa.edu. It will need to be ported to D8 using Layout Builder blocks.

- [x] Port base functionality - API helper methods, etc.
- [x] Upcoming dates by session (#2714)
- [x] #4935
- [x] #5072
- [x] #4936
- [x] #4937
- [x] #4943
- [x] #4958
- [x] Astra room schedule
- [x] Astra room room data (previously feeds driven for classrooms, registrar)
- [x] #5071
- [x] https://github.com/uiowa/uiowa/issues/5565

**Comment by richardbporter** [comment]
Some follow-up notes after #2714 and a meeting:

- Should we add a subject to change disclaimer? Should it be optional?
- How should we use the new reviewed field?
  - Mark dates where reviewed does not equal TRUE as tentative.
- Automatic session rollover
  - Do we need to extend rollover beyond the session end date? Some academic dates extend beyond the end of a session.
  - How far out should sessions be allowed?
- Cache invalidation
  - Can we detect when dates change and invalidate by tag?
  - Can we move rendering to JS and avoid time-based cache invalidation issues?
- Can we display additional metadata for dates?
  - This would be useful to easily match up front-end facing information with back.
  - Contexts, print date, etc.
  - Tooltips or something?
-  Should we allow multiple category selections?

**Comment by richardbporter** [comment]
A module README documenting the business logic would also be helpful as a reference we could point people at.

**Comment by joewhitsitt** [comment]
For the astra schedule data:

```php
/**
 * Return the schedule for a classroom for a date range.
 *
 * GET /pub/registrar/courses/AstraRoomSchedule/{startDate}/{endDate}/{bldgCode}/{roomNumber}.
 *
 * @param string $startdate
 *        Date formated as YYYY-MM-DD.
 * @param string $enddate
 *        Date formated as YYYY-MM-DD.
 * @param string $building
 *        The building code needs to match the code as it is entered in Astra.
 * @param string $roomnumber
 *        The room number needs to match the code as it is entered in Astra.
 *
 * @return array $data
 *         JSON decoded array of response data.
 */
function uiowa_maui_astra_room_schedule($startdate, $enddate, $building, $roomnumber) {
  $endpoint = 'registrar/courses/AstraRoomSchedule/' . $startdate . '/' . $enddate . '/' . $building . '/' . $roomnumber;

  $data = _uiowa_maui_request($endpoint);
  return $data;
}
```
- profiles/sitenow/modules/custom/uiowa_maui/api/astra.inc

**Comment by joewhitsitt** [comment]
@briand44 can we close this epic?
