### ISSUE TITLE
Post V3 tasks

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2207]
- [x] #865
- [x] #3878 
- [x] #3880 
- [x] Adopt media library wysiwyg for coronavirus.uiowa.edu

# More LB tasks

- [x] https://github.com/uiowa/uids/issues/242 Make components accessible when using all background color options possibly using this solution https://github.com/uiowa/uids/issues/262. 
- [x] #2881 
- [x] #1607 
- [x] What design components are missing that you would expect?
- [x] #2182 Consolidate `div.lb__container` and `div.layout__region`
- [x] Standard page header with featured image + breadcrumb + page title.
- [x] Documentation (#2175, #2174, #2162, #2149)
- [x] https://github.com/uiowa/uids/issues/274 Pre-footer styling updates 
- [x] https://github.com/uiowa/uiowa/issues/2078 Adjust display of moderation control
- [x] #1482  
- [ ] https://github.com/uiowa/uiowa/issues/2056 lb_direct_add usability improvements. 
- [ ] #5240 
  - "Having a second button at the bottom of the edit page to 'Save and Edit Layout'" was suggested by Suzanne Dergacheva after her usability presentation at DrupalConGlobal
- [ ] Develop a more user-friendly css grid section.
- [ ] Establish sensible defaults for quick content creation.
- [x] Ask Brand managers to review how components look in each section in a test site. For instance, do we want to allow hero blocks placed in a four-col layout section?  If so, do we need to target each column size for the component design?

# Maybe/Someday
- [x] #1931 Image/Media block

**Comment by pyrello** [comment]
Taking over the remainder of the tasks from #1778

**Comment by joewhitsitt** [comment]
Can we close this issue? If issues should be captured out of these other checkboxes, let's do that.

**Comment by pyrello** [comment]
Can we consider this moot since we have deprecated the hero block and since then we have allowed for banners to be used in multicolumn layouts?
> Ask Brand managers to review how components look in each section in a test site. For instance, do we want to allow hero blocks placed in a four-col layout section? If so, do we need to target each column size for the component design?

**Comment by pyrello** [comment]
Opened #5240

> What design components are missing that you would expect?

Considering this done based on work to add image block, which at least gets us to component parity.

> Develop a more user-friendly css grid section

Not sure if this refers to #2785 or #4317. @bspeare?

> Establish sensible defaults for quick content creation

Not sure what this means. If nobody else has any ideas, feel free to add them in, but otherwise we can probably consider  this done or moot since it is vague.

**Comment by joewhitsitt** [comment]
Call to again close this issue?

>Develop a more user-friendly css grid section

>>Not sure if this refers to https://github.com/uiowa/uiowa/issues/2785 or https://github.com/uiowa/uiowa/issues/4317. @bspeare?

**Comment by bspeare** [comment]
I am not sure what "Develop a more user-friendly css grid section" is referring to.  We can close and reopen if/when we discover what that means.

**Comment by bspeare** [comment]
It probably refers to https://github.com/uiowa/uiowa/issues/4317, but does that need to be here as a Post V3 task?

**Comment by joewhitsitt** [comment]
I think the idea is to get rid of this stale issue since the follow-ups have been created elsewhere and that we are no longer focusing on post-v3 per-say. Closing.
