### ISSUE TITLE
Layout Builder UX Improvements

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2247]
- [x] Improve field labels: https://github.com/uiowa/uiowa/issues/2246
- [x] Improve usability of stat component: https://github.com/uiowa/uiowa/issues/2240
- [x] Improve design of moderation controls: https://github.com/uiowa/uiowa/issues/2078
- [x] Improve usability of lb_direct_add module: https://github.com/uiowa/uiowa/issues/2056
- [x] Add best practice tips to v3 documentation?
- [x] Double click to edit!
- [ ] Show block description at the top of the form #2722 

Any other suggestions missed?

**Comment by pyrello** [comment]
* Add descriptions for all blocks (necessary for #2056) with links to related SiteNow documentation.
* Show block description at the top of the form.

**Comment by bspeare** [comment]
Closing this now that it is very outdated and mostly complete.  https://github.com/uiowa/uiowa/issues/2722 is still relevant, but doesn't seem necessary to be a part of an epic.
