### ISSUE TITLE
As an admissions stakeholder, I can request design changes and view the status of these requests

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#2321]
**Home Page**

- [ ] Prototype home page design

**Areas of Study page**

- [x] Prototype a page design

**Brand Icons**

- [ ] Provide best practice for integrating/sizing brand icons
  - [x] https://github.com/uiowa/uiowa/issues/6978
  - [ ] https://github.com/uiowa/uiowa/issues/1931

**Banner**

- [x] Add video loop option within banner block or create separate video block: https://github.com/uiowa/uiowa/issues/2403
- [x] Add ability to add button row: https://github.com/uiowa/uiowa/issues/2404
- Additional related issues
  - [x] https://github.com/uiowa/uiowa/issues/2376
  - [ ] https://github.com/uiowa/uiowa/issues/2349
  - [x] https://github.com/uiowa/uids/issues/331

**Featured image**

- [x] Page title banner - add small, medium, large options within Featured Image area: https://github.com/uiowa/uiowa/issues/2405.

**Card**

- [ ] Fixed button position option: https://github.com/uiowa/uiowa/issues/2406.

**Tabs**

 - [ ] Need them: https://github.com/uiowa/uids/issues/391

**Horizontal Menu**

- [x] Design variant for horizontal menu to appear for a more "tab" design and an "arrow" indicating an active state. 
- [ ] Center horizontal menu option?
- Next steps
  - Enhance design of existing horizontal menu
  - Pills vs tabs?
  - Allow ability to center

**Heading Styles**

- [ ] Adjust underline on heading style to clearly display as a link if used as a link
- [ ] Centered vs Left aligned best practices on page designs
- [x] Color contrast a11y: https://github.com/uiowa/uids/issues/330

**Feeds, Events, Articles displays**

- [ ] Sticky items at top of list news and events
- [x] No results text a11y: https://github.com/uiowa/uiowa/pull/2296#issuecomment-714503930
- [ ] Create display options: https://github.com/uiowa/uiowa/issues/2309
- [ ] Create more distinctive event list style: https://github.com/uiowa/uiowa/issues/2727. 

**Tables**

- [ ] Apply table styles via WYSIWYG
- [ ] Ability to set table width?
- Related issues:
  - [x] https://github.com/uiowa/uiowa/issues/139
  - [ ] https://github.com/uiowa/uiowa/issues/995
- Next steps
  - [ ] Add a class that will allow contents of table to determine width
  - [ ] Investigate future work for a more usable interface
  - Lots of stuff being stripped out?

**Stats**
- [x] Remove hover effect: https://github.com/uiowa/uiowa/issues/2583
- How to keep up to date?  Reusable block? 
- Next steps:
  - [ ] Investigate reusable Drupal blocks
  - [ ] Create custom block in block overview, then that block shows up in sidebar for every single page and they can place it that way based on permissions.  The downside to this method is that you have to know where to go to create reusable blocks.  How to present this interface? Core version patch add reusable checkbox to block form? How to prevent block being edited inline instead of at the block overview page?   

**CTA**

- [x] Ability to add line breaks, `<strong>` and `<a>` within CTA: https://github.com/uiowa/uiowa/issues/2710

**Prefooter** 

- [ ] Ability to add call to action with button row, background image.   
- [ ] Prefooter templates: https://github.com/uiowa/uiowa/issues/2209
- [ ] Prefooter: apply layout builder styles outside of layout builder: https://github.com/uiowa/uiowa/issues/2155
- Related issue:
  - UIDS Prefooter discussion: https://github.com/uiowa/uids/issues/275
  - The banner block could take care of mission statements, calls to action if we had ability to add button row.
  - Separate ability to upload sponsor logos and add links - image gallery block?

**Accordion**

- [ ] Allow ability to show all open button: https://github.com/uiowa/uids/issues/112
- [ ] Allow ability to set accordion single select, multi select: https://uids.brand.uiowa.edu/components/detail/accordion--multi.html
- [ ] Allow ability to change color of accordion headings: https://github.com/uiowa/uiowa/issues/1482

**Small text below tables?**
- https://admissions.uiowa.edu/finances/estimated-costs-attendance
- [x] `<small>` with better line-height https://github.com/uiowa/uids/issues/415

**Tuition and fees:**
- https://admissions.unl.edu/cost/#tuition-fees

# Completed
<details>

**Main Menu**

- Add class to last menu item to style as button: https://github.com/uiowa/uiowa/issues/2407
- Next steps:
  - Turn on menu link class module and allow ability to add a class to menu item for admins?
  - Create a designed button class for superfish menu
  - [x] Create prototype for top links in header
  - [x] Implement top links prototype into main service https://github.com/uiowa/uiowa/pull/2538
  - [x] Future work for top links integration for more CTA links

**Viewbook**

- [x] Lightbox/colorbox on image grid https://github.com/uiowa/admissions-viewbook/issues/47
- [x] Adjustments to cta https://github.com/uiowa/admissions-viewbook/issues/47
</details>

**Comment by bspeare** [comment]
I am going to close this in favor of tracking these issues in https://github.com/orgs/uiowa/projects/3.

**Comment by joewhitsitt** [comment]
Updated IS to reflect issue consolidation around https://github.com/uiowa/uiowa/issues/6978
