### ISSUE TITLE
Epic: Areas of Study pages and related functionality for Admissions

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2365]
# Motivation
The current Admissions website has a section where students can browse, search, and filter a list of areas of study. An area of study can include majors, minors, certificates, preprofessional programs, and online/off-campus programs. The student should be able to search by title and filter by type, college, academic group. The student can select an item from the list and view a page with extensive structured information related to the area of study, as in this current example: https://admissions.uiowa.edu/academics/accounting. Each area of study can contain information called "Transfer tips" that populates a section on the page, but also shows up on another listing page (https://admissions.uiowa.edu/transfer-plans) specifically about Transfer information for areas of study that have it. The area of study pages also have carefully designed PDFs that are generated and used internally by Admissions to provide print copies of this information. (https://admissions.uiowa.edu/at-iowa-print). 

Here is some additional requested functionality:
* Add the ability to filter by academic group
* Block on homepage to quickly search all areas of study
* Comparison tool: Select 2 areas of study and have a page comparing them side-by-side (e.g. chemistry and biology)
* Areas of study search widget to allow dropping the search box on other sites and potentially having it pre-filtered to be relevant to the college/program in question
* Explore using faceted search via Acquia Search on the Areas of Study page
* Local forms that can be submitted via API to MAUI

# Proposed solution
This is a large project which can be broken up into the following smaller tasks.
- [x] #2379: Investigate use of MAUI API in relation to this content type.
- [x] #2380: Investigate possible use of shared fields.
- [x] #2438 As a prospective student I can view information about Areas of Study
- [x] #2515: As an Admissions site owner, I can view a minimally styled version of the Area of Study page.
- [x] #2439: Investigate how to handle theming for the A o S page.
- [x] #2441: As an Admissions site owner, I can view a fully styled version of an Area of Study page.
- [ ] #2445: Investigate using Acquia Search to build Areas of Study search page.
- [x] #2444: As a prospective student, I can search and filter a page listing Areas of Study on the Admissions site.
- [x] #2443: As a prospective student, I can start an Areas of Study search on the Admissions homepage.
- [x] #2500: Investigate how to generate PDFs from content in Drupal 8
- [x] #2446: As Admissions staff, I can access a printable version of an Area of Study page
- [ ] Investigate and recommend possible ways of building a comparison tool
- [x] #2501: Migrate areas of study content from existing site into new site.

# Additional notes
Areas of studies can have subprograms, which are lists of related areas. These related areas are referred to differently by individual departments, so there is a subprogram type field that allows choosing from a specified list of items to refer to these as. The subprogram type that is chosen is used as the label for the subprograms on the display.

## Related examples

- **West Virginia** - https://admissions.wvu.edu/ 
This is more of a sorting/block/view that we liked. I don’t think I pulled up the right thing when we were looking at it on Fri. The search is just searching areas of study, but the links below the search are nice too – view all majors, browse by career pathway (this is what we modeled our academic groups listing/view off of).
- **Arizona** - https://www.arizona.edu/degree-search/ 
This has a nice search/filter display. You’re initially presented with something similar to our academic groups as well as a search by keyword. Then you can see a list that gets sorted/filtered by a lot of options. We also like the ability to compare majors side by side.
- **North Dakota (UND)** - https://und.edu/programs/athletic-training-bs/index.html
We liked how this one is designed/broken up on the full area of study pages. I think it’s a little thin on information, but the individual major page is nice. I think we need to find a way to add an image to each area of study (can be used for header or page element as well as the image in the printed handouts). The other thing that’s nice in here is the request information form. The 2 page/screen layout collects just enough information and could be tied to a specific area of study on the page the form is submitted from.
- **UALR (req information)** - https://ualr.edu/academics/program/art/
This one was also in our list for the request information component on the area of study page. I think it’s worth looking at, but the UND example above does a better job of collecting the correct information.
