### ISSUE TITLE
Epic: Grad College Programs and Certificates

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2447]
# Motivation

The Graduate College has listing pages of programs and certificates:
https://www.grad.uiowa.edu/programs/alphabetically
https://www.grad.uiowa.edu/programs/by-discipline
https://www.grad.uiowa.edu/programs/interdisciplinary-graduate-programs
https://www.grad.uiowa.edu/programs/graduate-certificate-programs

The listings link off to associate program pages on the relevant website. These are stored on the current website as content types, but the individual program and certificate pages are not styled and probably should not be able to be displayed. It would be nice to figure out how to consolidate some of these pages (if that makes sense) and to enhance any listing pages with searching capabilities.

# Proposed solution

- [x] #2557 Investigate how to structure Grad College Programs and Certificates entities.
- [x] Build the fragment or content type(s) with the necessary fields.
- [x] Build each view that is necessary.
- [x] If any of this can be captured as shared functionality, create a feature split. Split out any relevant config.
- [x] Any parts of this that are too specific to the Grad College to be shared should be added to the grad.uiowa.edu split.
- [x] Export all relevant configuration to the appropriate splits.
