### ISSUE TITLE
Epic: Prepare platform for upgrade to Drupal 9

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2474]
# Motivation

To stay current with the most recent version of Drupal

# Proposed solution

The following updates will allow us to update to Drupal 9.0.x. Some issues may require checking the warnings generated in the Upgrade Status report available on a site when viewing it locally.

- [x] uiowa/uiowa_bar#59: Update uiowa_bar module to be D9 compatible.
- [x] ~~#2592 Bump `drupal/big_pipe_sessionless:^2.0`~~ - This has to be done at the same time as moving to D9
- [x] #2593 Bump `drupal/components:^2.0@beta`
- [x] ~~#2594 Apply patch from https://www.drupal.org/project/config_ignore/issues/3150462 to make `drupal/config_ignore` compatible.~~ - This is no longer necessary because of #2772 
- [x] #2455 Bump `drupal/devel:^4.0`
- [x] ~~Resolve issues with drupal/field_group, possibly by applying the patch here: https://www.drupal.org/project/field_group/issues/3168213~~ - Not necessary, the library will get updated via D9 upgrade.
- [x] #2872 Bump `composer update drupal/fragments`
- [x] ~~Determine whether additional action is necessary to resolve `drupal/google_analytics` warnings in Upgrade Status~~ - Not necessary as all the warnings relate to an extension being uninstalled that is only required for tests.
- [x] Bump `drupal/honeypot:^2.0`
- [x] #2595 Bump `drupal/imagecache_external:^3.0.`
- [x] Determine whether additional action is necessary to resolve `drupal/media_library_theme_reset` warnings in Upgrade Status
- [x] Resolve `drupal/menu_block` compatibility issues - needs more research about whether patches are compatible with stable version or whether current dev commit hash we are pinned to works
- [x] Resolve `drupal/metatag` compatibility issues - needs more research about whether patch is compatible with stable version or we can roll with the dev version
- [x] ~~Determine whether additional action is necessary to resolve `drupal/paragraphs` warnings in Upgrade Status~~ - Not necessary as all warnings are related to tests or modules that are not installed.
- [x] Investigate purge warnings in Upgrade Status
- [x] ~~Determine whether additional action is necessary to resolve `drupal/search_api` warnings in Upgrade Status~~ - Not necessary as all warnings are related to tests.
- [x] Determine whether additional action is necessary to resolve `drupal/simple_sitemap` warning in Upgrade Status
- [x] #2596 Bump `drupal/webform:^6.0`

**Comment by pyrello** [comment]
We've made a lot of progress on this list!

**Comment by joewhitsitt** [comment]
>Resolve drupal/metatag compatibility issues - needs more research about whether patch is compatible with stable version or we can roll with the dev version

Not sure what the compatibility issues were but 1.5 is D9 compatible. https://github.com/uiowa/uiowa/pull/2897

**Comment by richardbporter** [comment]
I think the menu_block update to 1.6 in #2912 fixes the D9 compatibility issues although we'll want to test out menu_block in general there.

I think all that is left is #2592 but that has to be done simultaneously with D9.
