### ISSUE TITLE
Build full Admissions version of Area of Study

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#2515]
# Story

As an Admissions site owner I can view a minimally styled version of an Area of Study Page.

Follow up to #2438  

# Proposed solution

- Using the admissions site, add all additional fields that are needed for that site specifically to the content type.
- Config split these additional fields and any other needed config into the Admissions site split.
View layout and styles used in the mockup at https://admissions.prod.drupal.uiowa.edu/academics/accounting

# Story Split

- [x] Add missing fields for "Program Types": https://github.com/uiowa/uiowa/issues/3001
- [x] As a site owner, I can create an Area of Study page that has all of the defined fields (https://github.com/uiowa/uiowa/issues/2741)
- [x] As a site owner, I can create an Area of Study page that has defined fields for adding Stats(https://github.com/uiowa/uiowa/issues/2925)
- [x] As a site owner, I can create an Area of Study page that uses a layout builder template (https://github.com/uiowa/uiowa/issues/2815)
- [x] As a site owner, I can place a featured image into my Area of Study page and see it styled like the mockup (https://github.com/uiowa/uiowa/issues/2816)
- [x] As a site owner, I can place Subtitle, Intro, and Why Iowa text into the Area of Study content type and see it styled like the mockup #2926 
- [x] As a site owner, I can create individual Stats for each Area of Study page and see them styled like the mockup #2927  
- [x] As a site owner, I can place Careers & Outcomes and Student Opportunities text into the Area of Study content type and see it styled like the mockup https://github.com/uiowa/uiowa/issues/2932
- [x] As a site owner, I can create a local text area for Admissions Requirements and view it styled like the mockup #2933 
- [x] As a site owner, I can create Admissions Requirements with a separate content type and reference them in the Areas of Study content type and see them styled like the mockup #2934 

- [x] As a site owner, I can enter Scholarship Information in the Area of Study content type and see it styled in the sidebar #2964 
- [x] As a site owner, I can enter Stories in the Area of Study content type and see them styled like the mockup #2965 
- [x] As a site owner, I can enter Related Links in the Area of Study content type and see them styled like the mockup #2966 
- [x] As a site owner, I can enter Program type information in the Area of Study content type and see it styled in the sidebar like the mockup #2967 
- [x] As a site owner, I can expect to see Apply Now and Request Info buttons at the top of every Area of Study page #2968

**Comment by bspeare** [comment]
# Additional notes

## Layout

View layout and styles used at https://admissions.prod.drupal.uiowa.edu/academics/accounting

## Fields

**Feature Image**
* Integrate sizing option from https://github.com/uiowa/uiowa/pull/2711
* Add separate field template for page title to apply bold-uppercase highlight style

**Subtitle**
* Add field template for styling
* Placed in one column under main image

**Intro**
* Text area in main column

**Why Iowa**
* Text area in main column

Stats
* 1-3 status max
* Placed in main column
- [ ] Create layout builder style to allow stats to flex inline
- [ ] Create issue for "Bits"

**Admission Requirements**
* Text area in main column

**Admission Requirements steps**
* Multi-value paragraph field placed in wide one-column
* Styled through using card template

**Careers & Outcomes**
* Text area in main content area below admission requirements

**Student Opportunities**
* Text area in main content area below admission requirements

**Scholarships**
* Text area in sidebar
* Custom template block for theming

**Stories**
* Multi-value paragraph field placed in one-column
* Styled through using card template
* Alternate left/right alignment per entry
- [ ] Create issue for allowing YouTube embeds into card

**Related Links**
* Multi-value link field?
* Custom template block for theming
* Placed in sidebar under Information block

**Information**
* Use all fields in "Program types" fieldset
* Custom view block
* Placed in sidebar under apply now button

**Apply Now Button**
* Placed in sidebar at top of the page

**Request Info Button**
* Dynamically place major name into button text? Or will "Request Info for this Major" be sufficient?
* Placed under apply now button in sidebar
* Will be replaced by link to form on page in the future

**Comment by pyrello** [comment]
Content fields currently related to creating the admissions requirements and application information tabs on the current D7 site are being moved into a separate content type that references the AOS.

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uiowa/issues/2942 (Admissions requirements) is being revisited

**Comment by bspeare** [comment]
@joewhitsitt Do we need to remove or alter https://github.com/uiowa/uiowa/issues/2934?

**Comment by joewhitsitt** [comment]
We could salvage the info from #2934 and move it to #2942. Waiting to hear back from @pyrello about where all this is at

**Comment by bspeare** [comment]
I think we can finally close this epic story split.
