### ISSUE TITLE
Investigate current code @todos for fixing tasks

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2576]
# Story

As a developer, I can maintain a codebase free of todo comments by prioritizing and addressing them instead of reacting to them! Todos are often forgotten and never revisited.

# Proposed solution

Audit our codebase for `@todo` comments. Establish a count to measure against. (Scoped to only docroot/modules/custom, docroot/modules/uiowa, docroot/profiles/custom/sitenow, docroot/sites and docroot/themes/custom/uids_base)

If it is a quick fix, address it as part of this investigation. Try for 30% of total count from above? If more complicated, look for or create an issue to address them.

Update working agreements wiki to encourage the creation of related issues in the backlog when `@todos` are added.

# Todo

- [x] docroot/modules/custom/grad_custom/grad_student_profile/templates/node--student-profile--card.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:48:      // `@todo` Write a patch for layout_builder_styles that adds these options. See
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:121:      // `@todo` Investigate whether this can be added to ListBlock.
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:263:          // `@todo` Re-enable 'tab' after theming/functionality is in place. See
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:504:            // `@todo` Add feedback for user that they didn't upload an image.
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:505:            // `@todo` Add validation to check whether image uploaded or not. See
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:513:          // `@todo` Trigger file deletion if the media item is unused elsewhere. See
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:537:          // `@todo` Should we set a message here to let the user
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:602:      // `@todo` Should this be scoped to a condition checking if layout_builder_styles is enabled?
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:643:            // `@todo` Conditionally require media field when 'background_options'
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:813: * `@todo` Test to see if this is needed anymore.
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:990:  // `@todo` Figure out how to appropriately scope this.
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:1002:    // `@todo` remove card--person-teaser when v2 is no longer in use. - https://github.com/uiowa/uiowa/issues/4948
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:1025:        // `@todo` Check if the style group matches a class that is used for
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:1032:    // `@todo` Add media element classes to a separate variable.
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:1038:  // `@todo` Change this to just match 'card_list' once there is an update hook
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:1112:  // `@todo` Allow view config to override this (non-zero pager id?).
- [x] docroot/modules/custom/layout_builder_custom/layout_builder_custom.module:1134:  // `@todo` Remove this exception when these view displays are removed.
- [ ] docroot/modules/custom/layout_builder_custom/src/EventSubscriber/ReplicateSubscriber.php:171:    // `@todo` Possibly remove in the future?
- [ ] docroot/modules/custom/layout_builder_custom/src/EventSubscriber/SectionComponentSubscriber.php:63:            // `@todo` Remove the duplicate section of code below once the
- [ ] docroot/modules/custom/layout_builder_custom/src/LayoutBuilderPreRender.php:40:              // `@todo` Get style name
- [ ] docroot/modules/custom/layout_builder_custom/src/LayoutBuilderPreRender.php:55:                // `@todo` Remove this once we determine a way to consistently
- [ ] docroot/modules/custom/layout_builder_custom/src/Plugin/Display/ListBlock.php:128:    // `@todo` Possibly wire this up to the views title?
- [ ] docroot/modules/custom/layout_builder_custom/src/Plugin/Display/ListBlock.php:141:      // `@todo` Remove once exposed filters patch is added.
- [ ] docroot/modules/custom/layout_builder_custom/src/Plugin/Display/ListBlock.php:373:        // `@todo` The user should be able to select an entity type. Will be fixed
- [ ] docroot/modules/custom/layout_builder_custom/src/Plugin/Display/ListBlock.php:607:    // `@todo` Remove this exception when these view displays are removed.
- [ ] docroot/modules/custom/layout_builder_custom/src/Plugin/Display/ListBlock.php:626:    // `@todo` Remove this exception when these view displays are removed.
- [ ] docroot/modules/custom/layout_builder_custom/src/Plugin/Display/ListBlock.php:698:      // `@todo` '<front>' is valid input for BC reasons, may be removed by
- [ ] docroot/modules/custom/layout_builder_custom/src/Plugin/Display/ListBlock.php:710:      // `@todo` Support entity types other than 'node'. Will be fixed in
- [ ] docroot/modules/custom/layout_builder_custom/tests/src/Functional/MenuBlockCustomTest.php:149:    // `@todo` Test menu orientation field is showing only once.
- [ ] docroot/modules/custom/layout_builder_custom/tests/src/Functional/MenuBlockCustomTest.php:150:    // `@todo` Test parent field is hidden when follow is checked.
- [ ] docroot/modules/custom/layout_builder_custom/tests/src/Functional/MenuBlockCustomTest.php:151:    // `@todo` Test initial visibility field is hidden when follow is checked.
- [ ] docroot/modules/custom/layout_builder_custom/tests/src/Functional/MenuBlockCustomTest.php:152:    // `@todo` Test text 'Make sure that "Initial visibility level" is set to "1"
- [ ] docroot/modules/custom/layout_builder_custom/tests/src/Functional/MenuBlockCustomTest.php:154:    // `@todo` Test 'Visibility options' is showing and not 'Advanced'.
- [ ] docroot/modules/custom/layout_builder_custom/tests/src/Functional/MenuBlockCustomTest.php:155:    // `@todo` Test that depth options are 1-3.
- [ ] docroot/modules/custom/layout_builder_custom/tests/src/Functional/MenuBlockCustomTest.php:156:    // `@todo` Test that follow is set to 1 if the add block form is being used.
- [ ] docroot/modules/custom/sitenow_articles/sitenow_articles.module:614:    // `@todo` Do we need to do anything besides this?
- [ ] docroot/modules/custom/sitenow_articles/sitenow_articles.module:618:  // `@todo` Is this appropriate when there is no value?
- [ ] docroot/modules/custom/sitenow_events/sitenow_events.module:250:      // `@todo` Finish this logic to render the virtual details and location.
- [ ] docroot/modules/custom/sitenow_events/sitenow_events.module:410: * `@todo` Remove this after sitenow_events_paragraph is uninstalled.
- [x] #5028
- [x] docroot/modules/custom/sitenow_events/sitenow_events.module:586: * `@todo` Replace with an API endpoint that outputs an entire vocabulary tree.
- [ ] docroot/modules/custom/sitenow_events/tests/src/Kernel/EventFeatureTest.php:87:    // `@todo` Check that event date is displaying.
- [ ] docroot/modules/custom/sitenow_events/tests/src/Kernel/EventFeatureTest.php:89:    // `@todo` Check that event virtual details are displaying.
- [ ] docroot/modules/custom/sitenow_events/tests/src/Kernel/EventFeatureTest.php:90:    // `@todo` Check that event location is showing.
- [ ] docroot/modules/custom/sitenow_find_text/sitenow_find_text.module:57:          // `@todo` Find a better way to handle this. Currently skipping rabbit hole
- [ ] docroot/modules/custom/sitenow_find_text/tests/src/Functional/FindTextAjaxTest.php:199:    // `@todo` Search for the body text. This doesn't seem
- [x] #5029
- [x] docroot/modules/custom/sitenow_migrate/sitenow_migrate.install:63:  // `@todo` Do we need to catch if this directory doesn't exist?
- [x] docroot/modules/custom/sitenow_migrate/src/EventSubscriber/PostRowSaveEvent.php:73:      // `@todo` Remove this after ITU Physics migrate.
- [x] docroot/modules/custom/sitenow_migrate/src/EventSubscriber/PostRowSaveEvent.php:80:      // `@todo` Remove this after ITU Physics migrate.
- [x] docroot/modules/custom/sitenow_migrate/src/EventSubscriber/PostRowSaveEvent.php:174:   * `@todo` Remove this after ITU Physics migrate.
- [x] docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/ProcessMediaTrait.php:197:        // `@todo` Remove the hardcoding for physics.uiowa.edu/itu.
- [ ] docroot/modules/custom/sitenow_people/sitenow_people.module:265:      // `@todo` Clean this up. We are
- [ ] docroot/modules/custom/sitenow_people/sitenow_people.module:288:  // `@todo` Potentially set the correct values here?
- [ ] docroot/modules/custom/sitenow_people/sitenow_people.module:319:  // `@todo` Do these modifications need to be scoped to just run when
- [ ] docroot/modules/custom/sitenow_people/sitenow_people.module:380:    // `@todo` Remove this line and just use $entity->bundle() instead.
- [ ] docroot/modules/custom/sitenow_people/sitenow_people.module:924:    // `@todo` Do we need to do anything besides this?
- [ ] docroot/modules/custom/sitenow_people/sitenow_people.module:928:  // `@todo` Is this appropriate when there is no value?
- [ ] docroot/modules/custom/sitenow_people/src/Form/SettingsForm.php:328:      // `@todo` Store as configuration and just toggle the exposed status.
- [x] docroot/modules/custom/sitenow_people/tests/src/Kernel/PeopleBlockViewTest.php:82:    // `@todo` Check that event date is displaying.
- [x] docroot/modules/custom/sitenow_people/tests/src/Kernel/PeopleBlockViewTest.php:84:    // `@todo` Check that event virtual details are displaying.
- [x] docroot/modules/custom/sitenow_people/tests/src/Kernel/PeopleBlockViewTest.php:85:    // `@todo` Check that event location is showing.
- [x] docroot/modules/custom/studentlife_topics/templates/node--topic-collection--teaser.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [ ] docroot/modules/custom/studentlife_topics/templates/node--topic-collection--teaser.html.twig:102:  {# `@todo` Add content_attributes.addClass('node__content media-body') #}
- [x] docroot/modules/custom/uiowa_alerts/src/Form/SettingsForm.php:76:    // `@todo` Figure out why required state results in console error on submit.
- [x] docroot/modules/custom/uiowa_area_of_study/templates/node--area-of-study--teaser.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [ ] docroot/modules/custom/uiowa_area_of_study/templates/node--area-of-study--teaser.html.twig:100:  {# `@todo` Add content_attributes.addClass('node__content media-body') #}
- [x] #5032
- [ ] docroot/modules/custom/uiowa_core/src/Element/Headline.php:25: * `@todo` Finish this plugin class.
- [ ] docroot/modules/custom/uiowa_core/src/Element/Headline.php:40:      // `@todo` Determine whether a #process implementation is necessary.
- [ ] docroot/modules/custom/uiowa_core/src/Element/Headline.php:46:        // `@todo` Determine whether this #pre_render is necessary.
- [ ] docroot/modules/custom/uiowa_core/src/HeadlineHelper.php:40:   * `@todo` Adjust how these classes are added.
- [ ] docroot/modules/custom/uiowa_core/src/HeadlineHelper.php:72:   * `@todo` Investigate creating a custom render element for this.
- [ ] docroot/modules/custom/uiowa_core/tests/src/Traits/ConfigSplitTestTrait.php:28:    // `@todo` Add check that split exists.
- [ ] docroot/modules/custom/uiowa_core/tests/src/Traits/ConfigSplitTestTrait.php:49:    // `@todo` Figure out how to fix message about staged configuration.
- [x] #5034
- [x] docroot/modules/custom/uiowa_hours/src/Form/HoursFilterForm.php:240:        // `@todo` Add block config to get categories and render them here.
- [x] docroot/modules/custom/uiowa_hours/src/Plugin/Block/HoursBlock.php:170:    // `@todo` Create config to render quick links like tomorrow, next week, etc.
- [x] docroot/modules/custom/writinguniversity_migrate/src/Plugin/migrate/source/Category.php:95:      // `@todo` Do we need to handle the case where it doesn't?
- [x] docroot/profiles/custom/sitenow/sitenow.install:1177:  // `@todo` Possibly add checks for sites who have not updated
- [x] docroot/profiles/custom/sitenow/sitenow.install:1337:  // `@todo` Batch the work.
- [x] docroot/profiles/custom/sitenow/sitenow.install:2113:      // `@todo` Handle case where no bundles exist?
- [x] docroot/profiles/custom/sitenow/sitenow.install:2187:                      // `@todo` Parse out view mode from the existing embed.
- [x] docroot/profiles/custom/sitenow/sitenow.install:3189:    // `@todo` Batch this.
- [x] docroot/profiles/custom/sitenow/sitenow.install:3308:  // `@todo` check the temp storage
- [x] docroot/profiles/custom/sitenow/sitenow.install:3678:    // `@todo` confirm sort weights are set correctly.
- [x] docroot/profiles/custom/sitenow/sitenow.profile:113:  // `@todo` Refactor this to move sitenow last and then alter the altered query. - https://github.com/uiowa/uiowa/issues/5023
- [x] docroot/profiles/custom/sitenow/sitenow.profile:989: * `@todo` Return additional information like if any other splits are active that might impact functionality. - https://github.com/uiowa/uiowa/issues/5021
- [x] docroot/profiles/custom/sitenow/sitenow.profile:1097:                // `@todo` Make length a configuration setting. - https://github.com/uiowa/uiowa/issues/5024
- [x] docroot/sites/admissions.uiowa.edu/modules/admissions_core/admissions_core.module:358:          // `@todo` Move this to admissions_core_preprocess_node(). See
- [x] docroot/sites/admissions.uiowa.edu/modules/admissions_core/src/EventSubscriber/SectionComponentSubscriber.php:97:              // `@todo` Remove the duplicate section of code below once the
- [x] docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/node--area-of-study--pdf.html.twig:68: * `@todo` Override for area_of_study PDF layout. See
- [x] docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/node--page--pdf.html.twig:68: * `@todo` Override for area_of_study PDF layout. See
- [x] docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/node--scholarship--teaser.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [x] docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/node--transfer-tips--teaser.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [x] docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/views-view-unformatted--student-profiles.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [x] docroot/sites/admissions.uiowa.edu/modules/admissions_migrate/src/Plugin/migrate/source/AreaOfStudy.php:106:    // `@todo` Figure out why this event fires multiple times.
- [x] docroot/sites/brand.uiowa.edu/modules/brand_core/templates/node--lockup--full.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [x] docroot/sites/grad.admissions.uiowa.edu/modules/grad_admissions_core/grad_admissions_core.module:127:          // `@todo` Move this to admissions_core_preprocess_node().
- [x] docroot/sites/grad.admissions.uiowa.edu/modules/grad_admissions_core/templates/node--area-of-study--teaser.html.twig:26:  {# `@todo` Add content_attributes.addClass('node__content media-body') #}
- [x] docroot/sites/grad.admissions.uiowa.edu/modules/grad_admissions_migrate/src/Plugin/migrate/source/AreaOfStudy.php:101:    // `@todo` Figure out why this event fires multiple times.
- [x] docroot/sites/hr.uiowa.edu/modules/hr_core/templates/node--faq--teaser.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [x] docroot/sites/ighn.international.uiowa.edu/modules/ighn_core/templates/node--ighn-person--full.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [x] docroot/sites/ighn.international.uiowa.edu/modules/ighn_core/templates/node--ighn-person--teaser.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [x] docroot/sites/ighn.international.uiowa.edu/modules/ighn_core/templates/node.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [x] docroot/sites/itu.physics.uiowa.edu/modules/itu_physics_migrate/src/Plugin/migrate/source/Courses.php:83:    // `@todo` Do we need to map this category anywhere,
- [x] docroot/sites/itu.physics.uiowa.edu/modules/itu_physics_migrate/src/Plugin/migrate/source/Labs.php:84:    // `@todo` Do we need to map this category anywhere,
- [x] docroot/sites/uipress.uiowa.edu/modules/uipress_core/templates/node--book--teaser.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [x] docroot/sites/uipress.uiowa.edu/modules/uipress_migrate/src/Plugin/migrate/source/Authors.php:72:      // `@todo` Determine what minimum dimensions to use.
- [x] docroot/themes/custom/uids_base/gulpfile.js:75:  // `@todo` Watch other changes?
- [x] docroot/themes/custom/uids_base/scss/admin/_lb-direct-add.scss:59:// `@todo` Remove this when a corresponding change is made to lb_direct_add module.
- [ ] docroot/themes/custom/uids_base/scss/components/alert.scss:5:// `@todo` Move this to UIDS?
- [ ] docroot/themes/custom/uids_base/scss/components/blockquote.scss:20:// `@todo` move to CSS container queries when available.
- [x] docroot/themes/custom/uids_base/scss/components/blockquote.scss:93:// `@todo` remove with v2. - https://github.com/uiowa/uiowa/issues/4948
- [ ] docroot/themes/custom/uids_base/scss/components/card.scss:5:// `@todo` move back to UIDS
- [ ] docroot/themes/custom/uids_base/scss/components/grid.scss:42:// `@todo` Move to UIDS
- [x] docroot/themes/custom/uids_base/scss/components/menus/main-menu.scss:5:// `@todo` remove from UIDS. - This is being resolved in #4956
- [x] docroot/themes/custom/uids_base/scss/components/menus/main-menu.scss:12:// `@todo` move back to UIDS. 
- [x] docroot/themes/custom/uids_base/scss/components/menus/main-menu.scss:28:// `@todo` remove once https://github.com/GoogleChromeLabs/container-query-polyfill/issues/23 is resolved.
- [ ] docroot/themes/custom/uids_base/scss/components/pagination.scss:5:// `@todo` move back to UIDS
- [ ] docroot/themes/custom/uids_base/scss/components/search-toggle.scss:8:/* `@todo` Remove this when .hds-search class has been converted to .uids-search */
- [ ] docroot/themes/custom/uids_base/scss/components/slider.scss:5:// `@todo` Make this better.
- [ ] docroot/themes/custom/uids_base/scss/content/sitenow-event-single.scss:42:// `@todo` remove when https://github.com/uiowa/uiowa/issues/2756 is completed.
- [x] docroot/themes/custom/uids_base/scss/fields/fields.scss:173:// `@todo` When #2325 is closed, either delete this comment
- [x] docroot/themes/custom/uids_base/scss/fields/fields.scss:176:  // `@todo` Add a general mixin for link fields
- [ ] docroot/themes/custom/uids_base/scss/global.scss:99:  // `@todo` Should this be moved to the header layout scss file?
- [ ] docroot/themes/custom/uids_base/scss/global.scss:185:  // `@todo` Where should this live?
- [ ] docroot/themes/custom/uids_base/scss/global.scss:634:// `@todo` remove
- [ ] docroot/themes/custom/uids_base/scss/layouts/fourcol.scss:8:      // `@todo` Move to UIDS as a four column mixin.
- [ ] docroot/themes/custom/uids_base/scss/layouts/fourcol.scss:21:// `@todo` remove this when https://github.com/uiowa/uiowa/issues/4317 is complete. 
- [ ] docroot/themes/custom/uids_base/scss/layouts/fourcol.scss:59:// `@todo` remove when IE11 support is dropped.
- [ ] docroot/themes/custom/uids_base/scss/layouts/onecol--background.scss:27:  // `@todo` Move this to a more appropriate location.
- [ ] docroot/themes/custom/uids_base/scss/layouts/page--left-sidebar.scss:19:// `@todo` Remove if unnecessary.
- [ ] docroot/themes/custom/uids_base/scss/layouts/threecol.scss:82:// `@todo` remove when IE11 support is dropped.
- [ ] docroot/themes/custom/uids_base/scss/layouts/twocol.scss:85:// `@todo` remove when IE11 support is dropped.
- [ ] docroot/themes/custom/uids_base/scss/paragraphs/uiowa-paragraphs-lists.scss:200:      // `@todo` Remove when uiowa/uiowa#2670 and uiowa/uiowa#2554 are resolved.
- [ ] docroot/themes/custom/uids_base/scss/paragraphs/uiowa_paragraphs.scss:241:// `@todo` Remove if unnecessary.
- [ ] docroot/themes/custom/uids_base/scss/paragraphs/uiowa_paragraphs.scss:278:   * `@todo` Should this be moved to scss/layouts/onecol.scss or
- [ ] docroot/themes/custom/uids_base/templates/block/block--inline-block--uiowa-hero.html.twig:32:{# `@todo` Replace this with adding classes to <section> via attributes. #}
- [x] docroot/themes/custom/uids_base/templates/content/node--area-of-study--full.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [x] docroot/themes/custom/uids_base/templates/content/node--article--full.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [x] docroot/themes/custom/uids_base/templates/content/node--article--teaser.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [ ] docroot/themes/custom/uids_base/templates/content/node--article--teaser.html.twig:115:  {# `@todo` Add content_attributes.addClass('node__content media-body') #}
- [x] docroot/themes/custom/uids_base/templates/content/node--event--teaser.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [ ] docroot/themes/custom/uids_base/templates/content/node--event--teaser.html.twig:126:  {# `@todo` Add content_attributes.addClass('node__content media-body') #}
- [x] docroot/themes/custom/uids_base/templates/content/node--page--full.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [x] docroot/themes/custom/uids_base/templates/content/node--page--teaser.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [ ] docroot/themes/custom/uids_base/templates/content/node--page--teaser.html.twig:101:  {# `@todo` Add content_attributes.addClass('node__content media-body') #}
- [x] docroot/themes/custom/uids_base/templates/content/node--person--teaser.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [x] docroot/themes/custom/uids_base/templates/content/node--teaser.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [x] docroot/themes/custom/uids_base/templates/content/node.html.twig:68: * `@todo` Remove the id attribute (or make it a class), because if that gets
- [ ] docroot/themes/custom/uids_base/templates/layout/footer.html.twig:24:          {# `@todo` Remove header_type condition when uiowa sub-theme is functional. #}
- [ ] docroot/themes/custom/uids_base/templates/layouts/layout.html.twig:32:{# `@todo` Remove this when it is possible to add the library via preprocess. #}
- [ ] docroot/themes/custom/uids_base/templates/navigation/superfish.html.twig:15: * `@todo` Investigate a way of handling hidden labels dynamically.
- [ ] docroot/themes/custom/uids_base/templates/uids/banner.html.twig:46:          {# `@todo` Determine if it is better to programatically set level and class via preprocess. #}
- [ ] docroot/themes/custom/uids_base/templates/uids/card.html.twig:46:      {# `@todo` Add image template #}
- [ ] docroot/themes/custom/uids_base/templates/uids/card.html.twig:63:          {# `@todo` Determine if it is better to programatically set level and class via preprocess. #}
- [ ] docroot/themes/custom/uids_base/templates/uids/link.html.twig:11: # `@todo` Add 'target' property.
- [ ] docroot/themes/custom/uids_base/templates/uids/link.html.twig:24:      {# `@todo` Allow icon placement before text. #}
- [ ] docroot/themes/custom/uids_base/uids_base.theme:172:        // `@todo` Remove this when config is updated for all sites.
- [ ] docroot/themes/custom/uids_base/uids_base.theme:179:        // `@todo` Remove this when config is updated for all sites.
- [x] docroot/themes/custom/uids_base/uids_base.theme:276:    // `@todo` Remove after v2 dies. - https://github.com/uiowa/uiowa/issues/4948
- [ ] docroot/themes/custom/uids_base/uids_base.theme:357:        // `@todo` 2020/12/08 Add check to see if video is paused in 'uiowa-video'
- [ ] docroot/themes/custom/uids_base/uids_base.theme:414:  // `@todo` Is this code still necessary?
- [ ] docroot/themes/custom/uids_base/uids_base.theme:436:  // `@todo` Is this necessary? Possibly we can
- [ ] docroot/themes/custom/uids_base/uids_base.theme:449:    // `@todo` Scope this to target layout so it doesn't run
- [x] docroot/themes/custom/uids_base/uids_base.theme:568:    // `@todo` Remove after v2 dies. - https://github.com/uiowa/uiowa/issues/4948
- [x] docroot/themes/custom/uids_base/uids_base.theme:605:  // `@todo` Combine this section with the section before it.
- [x] docroot/themes/custom/uids_base/uids_base.theme:775:    // `@todo` Remove this when it is no longer necessary.

**Comment by pyrello** [comment]
Here is an example of how I think this should go: https://github.com/uiowa/uiowa/pull/4479/commits/185cc2f704a6f930871812ba4f030bda606fda65

**Comment by GaryRidgway** [comment]
I went through and `Find in files`'d each of the folders referenced and got the following counts:

## docroot/modules/custom
89

## docroot/profiles/custom/sitenow
11

## docroot/sites
20

## docroot/themes/custom/uids_base
92

**Comment by joewhitsitt** [comment]
Looking to jump in on this, but recall @GaryRidgway talking about a stepping on toes avoidance workflow. Could I get some details?

**Comment by richardbporter** [comment]
Looks like there is a GitHub app that auto-creates issues for todo items: https://github.com/apps/todo

Anyone have thoughts on if that might be worth testing out after we go through all existing todos?

**Comment by joewhitsitt** [comment]
Robots are taking our jobs!

**Comment by GaryRidgway** [comment]
I'm open to experimenting with that, it might be cool!

**Comment by richardbporter** [comment]
I'm thinking this already-run update hook todo can be removed? 
https://github.com/uiowa/uiowa/blob/1f9ac86cceee1764b30d6710079bfff2d6e917ca/docroot/profiles/custom/sitenow/sitenow.install#L1167-L1181

**Comment by richardbporter** [comment]
Updated issue description with a list of todos - file path, line number, first line.

**Comment by joewhitsitt** [comment]
Maybe all of the sitenow.install update hook ones could just be changed to a "note for next time"?

**Comment by pyrello** [comment]
> I'm thinking this already-run update hook todo can be removed?

I feel like there is no reason we couldn't pull this in: https://github.com/uiowa/uiowa/issues/4952

(edit) Is it really more desirable to go through them and individually remove todos?

**Comment by richardbporter** [comment]
I think I've quickly scanned these and hit the ones I was familiar with.

**Comment by joewhitsitt** [comment]
Added a proposed update to the working agreement: https://wiki.uiowa.edu/display/drupaldev/Working+agreements

**Comment by pyrello** [comment]
@bspeare Any idea what this is referring to?
https://github.com/uiowa/uiowa/blob/bba45460a6924a278b748d0599fc8e81bc7ce3fd/docroot/themes/custom/uids_base/scss/admin/_lb-direct-add.scss#L59-L62

I'm not seeing an open issue in the `lb_direct_add` module, at least as far as I can tell.

**Comment by bspeare** [comment]
Maybe we just keep it as our own modification and remove the todo?
