### ISSUE TITLE
Estimate migrating articles from engineering.uiowa.edu to engineering.prod.drupal.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2652]
# Story

As a College of Engineering webmaster I want articles migrated from the Engineering Drupal 7 site to engineering.prod.drupal.uiowa.edu so that users will be able to view all of the past news articles.

# Proposed solution

- [ ] Research both content types to determine amount of effort this will take. Need to determine if this can be done in a sprint or if need to break this into smaller tasks and we should also give Engineering a rough estimate of time this will take.
- [ ] Break down into smaller vertical slices if needed.

**Comment by joewhitsitt** [comment]
One thing to note as this is the first Engineering issue is that articles and people from the main site are pulled into the department sites. Work needs to be done to make sure nothing "breaks" if/when these feeds no longer exist (assumes main site switches before department sites)

**Comment by joewhitsitt** [comment]
Title | title
Author | field_author | Text | Text field - _This is a first/last name split IEF field in v3 so I don't know how the text would be split consistently into this structure. Could this be pre-pended to the Organization field and manual fixed later?_
Source | field_article_source | Text | Text field - _Organization in SiteNow v3?_
Image | field_image | Image | Media browser
Caption | field_image_caption | Long text | Text area (multiple rows) - _255 char limit in SiteNow v3?_
Body | body | Long text and summary | Text area with a summary - _summary would have to map to field_teaser_
Primary Department | field_primary_department | Entity Reference | Select list - _Prefix and map to field_tags?_
Department Feeds | field_department | Entity Reference | Check boxes/radio buttons _Prefix and map to field_tags?_
Audience | field_audience_multi | Entity Reference | Check boxes/radio buttons _Prefix and map to field_tags?_
Tags | field_tags | Term reference | Autocomplete term widget (tagging)


## Legacy

_Legacy import info from their site before it was SiteNow. I doubt these are needed but should check._

Imported | field_imported | Boolean | Single on/off checkbox
Legacy NID | field_legacy_nid | Text | Text field
Temp Date | field_temp_date | Date | Text field
Temp Department | field_temp_department | Text | Text field
Temp Audience | field_temp_audience | Text | Text field

## Other Notes

Do path redirects and metatags also need to be migrated?
Path: news/node:title

**Comment by joewhitsitt** [comment]
Bill responded via email:

>Do we need to provide redirect for the paths as the new format includes the date? **No**

>Do metatags need to be mapped over? **No**

>Are any of the legacy import data from the old old site need to be brought over? **I'm not 100% clear on this one.**

Bill will add to this issue when he returns from break.

**Comment by cory-skeers** [comment]
Should be fairly straightforward to get a custom migration up and running off of the base sitenow_migrate article migration. YAML configuration and a source plugin similar to what was done in grad_migrate.

> Author | field_author | Text | Text field - _This is a first/last name split IEF field in v3 so I don't know how the text would be split consistently into this structure. Could this be pre-pended to the Organization field and manual fixed later?_

Adding it to the Organization field is an option, and would be the most straightforward from our end, while providing nearly the same end-user experience. Migrating into the V3 IEF would be possible, but if the source is a free-text field, worry about naming inconsistencies ("Dr. Smith" in one place, and "John Smith" another). Also extra logic to handle people who aren't already in place on the existing site, choosing whether they should not display on lists if they don't have a full profile, etc...

> Caption | field_image_caption | Long text | Text area (multiple rows) - 255 char limit in SiteNow v3?

We have a semi-supervised approach to truncate text (used to create summaries out of body text if no summary is present). Could either use that out of the box or with minor modification--basically just trims backward until it finds a "natural" stopping point, either with end punctuation or appending an ellipsis to a full word. Doesn't guarantee there isn't data loss, but can be adjusted to at least help keep things from 'looking' like there was data loss.

> Body | body | Long text and summary | Text area with a summary - summary would have to map to field_teaser

Just need to note this in the YAML mapping 👍 

> Primary Department | field_primary_department | Entity Reference | Select list - _Prefix and map to field_tags?_
> Department Feeds | field_department | Entity Reference | Check boxes/radio buttons _Prefix and map to field_tags?_
> Audience | field_audience_multi | Entity Reference | Check boxes/radio buttons _Prefix and map to field_tags?_
> Tags | field_tags | Term reference | Autocomplete term widget (tagging)

I think these look like a good use of the tags, as long as their prefixed well to separate the categories, like you suggested. It also wouldn't prevent moving the data into custom fields if the need did arise later, and it's a pretty straightforward migration task to concat a prefix in either the YAML or a row preprocess.

## Tasks (to be updated)

- [ ] Add engineering migration module/split
- [ ] Write engineering article migration YAML
- [ ] Write engineering article migration source plugin
- [ ] Legacy import data?
- [ ] Map author field--prepend to Organization?
- [ ] Map primary department, department feed, and audience fields--include as prefixed tags?

**Comment by mjoneill** [comment]
Do we know enough to estimate yet?

**Comment by joewhitsitt** [comment]
I have to defer to @cory-skeers on an actual hours estimate for this work.

**Comment by cory-skeers** [comment]
With a few assumptions (that we:
 * can leave out the legacy import data, 
 * map the author field to the organization which would require manual cleanup by engineering after if they want complete mapping with people, and 
 * we map the various extra fields to a simple prefixed tag)
I think we're looking at about one day of one FTE work to setup the split and basic YAML/source plugin. 

Migrating into tags (for the final assumption) hasn't been done yet in any of our work, so it'll take some time to get a process in place as well as the engineering-specific work. It's pretty standardized, so once the general process/outline is in place, I think it'd be about an additional FTE day to two days of work to get the engineering-specific setup in place, as well as minor testing.

In the past, once everything for a migration is in place, the full process of pulling the prod site down, migrating locally, and pushing back up takes several hours.

So: 20-25 hours on the high end, optimistically more like 8-12 hours on the low end. Some time to be added or removed based on the assumptions above.

**Comment by joewhitsitt** [comment]
This portion is done. Once we communicate with Engineering, we can map out steps.
