### ISSUE TITLE
As an Admissions stakeholder, I can have a site to demonstrate next steps for admitted students.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#2751]
# Story

As an Admissions stakeholder, I can have a site to demonstrate next steps for admitted students.

They would like to replicate the experience of the [Admissions Viewbook](https://viewbook.admissions.uiowa.edu/) with content directed towards next steps for admitted students.

It was discussed to not create any new design elements as part of this process to be able to deliver this quickly.

# Proposed solution

* [x] #2809 Create empty GitHub repo for template application
* [x] #2810 Create empty GitHub repo for Next Steps application
* [x] #2808 Create template from existing Viewbook application
* [x] #2812 Build out the new Next Steps site using the template.

**Comment by pyrello** [comment]
I added some notes under "Proposed solution" based on what was discussed at the meeting where this came up.

**Comment by bspeare** [comment]
Should we transfer this to https://github.com/uiowa/admissions-viewbook?

**Comment by bspeare** [comment]
I've added a mockup below with an outline of the proposed changes from Scott. 

<details>

![Admitted-Students-Site](https://user-images.githubusercontent.com/1036433/103574664-f4dab680-4e95-11eb-861c-0870a4048e0c.jpg)

</details>

**Comment by bspeare** [comment]
I think we can close this specific issue.
