### ISSUE TITLE
Duplicate page or select template functionality

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#2848]
# Story

As a webmaster, I want to quickly recreate certain layout pages on my site without configuring every section manually.

# Proposed solution

Some further discussion is most likely needed and a research spike into which solution will work best for our setup, but this has been repeatedly requested by customers.

## Potential Solutions
- [x] Investigate Entity Clone 
  - https://github.com/uiowa/uiowa/issues/129
  - https://www.drupal.org/project/quick_node_clone
  - https://www.drupal.org/project/entity_clone/issues/3060223
- [x] Investigate Replicate module (It works)
  - https://www.drupal.org/project/replicate
  - https://www.drupal.org/project/replicate_ui
- [ ] Investigate layout_library
  - https://github.com/uiowa/uiowa/issues/2378
  - https://www.drupal.org/project/layout_library
- [ ] Investigate Section Template library picker.
  - https://www.drupal.org/project/section_library
- [ ] Investigate Page template module
  - https://www.drupal.org/project/pate
    - https://www.drupal.org/project/pate/issues/3238285

**Comment by bspeare** [comment]
The layout builder library is intriguing with this description "Site admins can prevent content-editors from creating their own bespoke layouts but give them the ability to customise layouts on a per-content-item basis."  I think this would be an ideal solution to have in place to limit content editors for creating layout and component combinations.

**Comment by pyrello** [comment]
> The layout builder library is intriguing with this description "Site admins can prevent content-editors from creating their own bespoke layouts but give them the ability to customise layouts on a per-content-item basis." I think this would be an ideal solution to have in place to limit content editors for creating layout and component combinations.

@bspeare Are you talking about for content types where we don't allow for per item customization? Or pages? Or both?

I would have concerns about shutting down people's ability to use LB to create their own layouts with the page content type. With the patches to core and this module however, we could use multiple layouts as a starting point to providing better starting point suggestions for users.

One downside to the layout library module is that its current UI is a set of checkboxes on the node edit screen. For that to work, we would probably need to incorporate some icons (which I think would require some customizations on top of the module) and/or really good textual descriptions of the layouts themselves.

**Comment by pyrello** [comment]
For the clone options, we would need to see how they work with our nested items, such as Accordions.

The section template library looks promising, but it would depend on being able to limit the creation of section templates to Admins only, since I don't think we want people defining their own. Also, I'm pretty sure that this module creates the section templates as content and not config, so they would be strictly per site, unless we wanted to go to the trouble of defining a process for importing a set of them into each site.

**Comment by bspeare** [comment]
@pyrello I think instead of limiting access we first need to design/provide some example layouts that we can direct users to during trainings and possibly integrate into using with the Layout Library module.

**Comment by pyrello** [comment]
After spending a little time exploring `layout_library` as an option again, now that is is unblocked by our move to Drupal 9.1, I am realizing that it will have some significant limitations in terms of what we can provide. Similar to how we were not able to add a text area block to the Admissions Area of Study content type layout to handle displaying buttons at the top of the page, we are also going to face this limitation with any layout template we would provide. The issue is that, because the layout for a content type - as well as layout templates created via Layout Library - is/are stored in config, we cannot a block to that config that depends on an item that is content, such as a text area block. This means that layout templates can only be built using blocks that are stored in configuration, which excludes the possibility of using any of our custom block types to provide example content in a layout.

We might ultimately still be able to provide useful layout options even with that restriction, but it is important to consider from the outset as we are deciding which path to pursue.

**Comment by bspeare** [comment]
As mentioned in Slack, https://www.lullabot.com/articles/improve-editorial-experience-type-tray-and-page-templates could be another approach to pursue.

**Comment by benlewzz** [comment]
We would really love this... we have dozens of sites that would use this functionality, not only in starting up their site but as a regular function of maintaining their content.

**Comment by bspeare** [comment]
Adding this here: https://www.drupal.org/project/replicate.

**Comment by bspeare** [comment]
https://www.drupal.org/project/replicate
https://www.drupal.org/project/replicate_ui

Added the above modules, went to content overview and right-clicked on the operations dropbutton:

<img width="1869" alt="Screen Shot 2021-09-28 at 2 30 58 PM" src="https://user-images.githubusercontent.com/1036433/135153629-64a0024d-58a8-4e6d-84d9-52dba05721e2.png">

Next screen:

<img width="1164" alt="Screen Shot 2021-09-28 at 2 31 05 PM" src="https://user-images.githubusercontent.com/1036433/135153668-ad482a02-eedd-4dc6-963b-c24ef67cc9c6.png">

Duplicate home page with blocks and paragraphs:

<img width="1849" alt="Screen Shot 2021-09-28 at 2 31 30 PM" src="https://user-images.githubusercontent.com/1036433/135153729-5ba1f339-4ae3-4b70-a6bc-0161ce74d1b2.png">

**Comment by pyrello** [comment]
See my comments here: https://github.com/uiowa/uiowa/pull/4214#issuecomment-929709156

**Comment by pyrello** [comment]
I believe that this issue should be split out into 2-3 issues:
* #4223  As a content editor/webmaster, I would like to be able to duplicate an entire page.
* (Possibly #2378) As a content editor/webmaster, I would like to be able to select from several template options when creating a new page for the first time.
* As a content editor/webmaster, I would like to reuse blocks/sections within my layouts.

The reason that I think these should be split out is that they are 3 very distinct user stories that all seem to have been wrapped up into this issue by virtue of the module suggestions that got attached to this issue. How we solve each issue is going to be different and I think that considering them and investigating them in tandem is ultimately confusing and makes it harder to get any one of them done.
