### ISSUE TITLE
CLAS Needs and Wants

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#2902]
# Story

As a CLAS Developer, I want to describe changes I would like to discuss university wide design ideas that would be helpful in my own development.

This is strictly for discussion purposes in development meetings for future changes, not necessarily items holding up my own development. Items are listed in order of "importance".

## Important Needs (4-21-2021)
- [ ] Creation of "profiles" or "spotlight" content type and design of placeable blocks in layout builder. See #2823.
- [x] Migration of news articles for CS and Physics/Astronomy sites. See #3357 and See #3369.
- [x] Migration of events from CS and Physics/Astronomy sites to events.uiowa.edu. Not possible based on latest info.
- [x] Ability to filter people based on person type (and research areas) in addition to relationship tags. See #2587.
- [x] Add Alumni (et al) as default Person Types for all sites. See #3310.

## Less Immediate Wants
- [ ] Creation of "seminars" content type, or solution for pulling seminars directly from events.uiowa.edu. See #2588.
- [x] Discover method to create default standard architecture automatically or through SQL import????
- [x] Update styling of People view page. See #2871.
- [x] Update styling of News view page. See #2871.
- [x] Update styling of Events view page (Seminars view page would carry over this styling). See #2871.
- [x] Implement site-wide pre-footer region for donate blocks.
- [ ] Finish and implement the program block feature. Launch on all CLAS department sites. See #1550.

**Comment by mark-bennett-uiowa** [comment]
Here is an idea for People page.
![people_list_idea](https://user-images.githubusercontent.com/3067017/105272914-e8c24a80-5b5f-11eb-84b9-007278a78148.jpg)

**Comment by mark-bennett-uiowa** [comment]
Here is an idea for News page.
![news_page_idea](https://user-images.githubusercontent.com/3067017/105272987-07284600-5b60-11eb-9482-659c42f4f374.jpg)

**Comment by mark-bennett-uiowa** [comment]
Here is an idea for Events page.
![events_page_idea](https://user-images.githubusercontent.com/3067017/105273031-1dce9d00-5b60-11eb-9423-dafe1612c8eb.jpg)

**Comment by mark-bennett-uiowa** [comment]
Here is what I am currently using for the "pre-footer" region that I would like to extend to all pages of the site (CTA with small text in the left column, link to donation site):
<img width="1465" alt="Screen Shot 2021-01-20 at 8 19 16 PM" src="https://user-images.githubusercontent.com/3067017/105273089-3a6ad500-5b60-11eb-812b-0a7987bbbe55.png">

**Comment by mark-bennett-uiowa** [comment]
Closing this and marking as done. Remaining needs from OP are either no longer important, already handled, or posted as separate issues.
