### ISSUE TITLE
Epic: Menu block improvements

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#3200]
# Motivation

We have gotten several requests for different types of improvements to the menu system. This is a spot to collect and track them all.

# Tasks
* [x] #4703 
* [x] #4701 
* [x] #4823
* [ ] #4711
* [x] #4544 
* [ ] #4712
* [ ] https://github.com/uiowa/uiowa/issues/4764
* [ ] https://github.com/uiowa/uiowa/issues/7092
* [ ] https://github.com/uiowa/uiowa/issues/7764
* [ ] https://github.com/uiowa/uiowa/issues/9539

# Questions
- Do we want to limit this to only administrators?  If we are switching layouts based on the menu style in the future slice, does access to the per page overrides need to be restricted?
- Allow dropdown menus? https://github.com/uiowa/uiowa/issues/3200#issuecomment-1007513375

**Comment by bspeare** [comment]
Here are a few creative examples of sites trying to create their own "menus" that could benefit from the ability to set the initial visibility level to "Active menu item" to display a sidebar navigation or a horizontal menu:

<img width="1474" alt="Screen Shot 2021-03-08 at 1 47 14 PM" src="https://user-images.githubusercontent.com/1036433/110373364-07e44100-8015-11eb-85fe-42a7352eb81c.png">

<img width="1762" alt="Screen Shot 2021-03-08 at 1 46 43 PM" src="https://user-images.githubusercontent.com/1036433/110373371-0a469b00-8015-11eb-871a-96dc7469916c.png">

<img width="1474" alt="Screen Shot 2021-03-08 at 1 45 39 PM" src="https://user-images.githubusercontent.com/1036433/110373384-0ca8f500-8015-11eb-9e16-aec66140fd13.png">

**Comment by bspeare** [comment]
After discussion:

- Allow changing active or children with explanations that make more sense?
- Button block allow multiple, display as menu?

**Comment by makurj** [comment]
I'd like to pair on this.

**Comment by bspeare** [comment]
I've updated the proposed solution to reflect our grooming discussion today.

**Comment by bspeare** [comment]
Added a pharmacy tag because they were also interested in this functionality.

**Comment by bspeare** [comment]
I've updated the proposed solution to reflect our conversation from this morning.  I will work on adding some screenshots/gifs of how the dropdowns might look on our current pages.  

One question that I have is whether we want to limit the individual page menu block overrides to only administrators? If we will need to switch layouts based on the menu style in the future slice, does access to the individual page menu block configuration need to be restricted?

**Comment by bspeare** [comment]
Here's a look at what the horizontal menu with dropdowns would look like:

https://user-images.githubusercontent.com/1036433/148568497-782d3c16-c0f2-4244-9289-d27fb7bc2d38.mov

**Comment by bspeare** [comment]
Here's the downside of the horizontal menu clashing with the top menu if there is no featured image:

https://user-images.githubusercontent.com/1036433/148568667-d872ed5d-36f8-40f4-bb20-381971930435.mov

**Comment by bspeare** [comment]
Here's a possible alternative proposal making the mega menu sticky and allow 4 levels of depth:

https://user-images.githubusercontent.com/1036433/148568909-25ff6c07-7dd9-4a42-8990-7e39cc53c977.mp4

**Comment by pyrello** [comment]
I like the proposal for handling drop-down menus in secondary horizontal navigation blocks. I am not a fan of trying to use mega-menus as a workaround for that as I don't think it actually satisfies the requirements in a satisfactory way. I'm not opposed to making those changes to mega-menus available also as they might be the right solution in some cases, just not as a way to handle this feature request. I acknowledge the potential issue with overlapping menus that could occur. I believe this is the price of building a robust toolset and that this is something that is best handled by continuing to promote best practices that would discourage usage that results in the issue.

**Comment by briand44** [comment]
Sounds like there still needs more conversations and grooming related to the second slice.

**Comment by briand44** [comment]
I am not opposed to allowing drop downs in the secondary horizontal navigation. I have concerns with bad usability opening this up to all but maybe there are ways we can try and help prevent those?

**Comment by bspeare** [comment]
Here's another possible alternative, a faux-breadcrumbs menu that only shows a dropdown if the active page has child pages.  This method would cut down on the number of dropdown flyouts while still showing the depth available within a section. 

https://user-images.githubusercontent.com/1036433/149000621-25cbd483-cec2-451e-a8f7-c9fc6a52e93e.mov

**Comment by quamsta** [comment]
@bspeare that looks really slick

**Comment by quamsta** [comment]
Here were some of the example menus that @bewoldt posted on Zoom during grooming today:

https://www.muhlenberg.edu/aboutus/
https://www.trincoll.edu/admissions/

**Comment by bspeare** [comment]
Here's a quick screen capture using the muhlenberg approach:

https://user-images.githubusercontent.com/1036433/149030388-b51ec93d-2073-4a14-8e21-466889e8a3b0.mov

**Comment by joewhitsitt** [comment]
Only one vote, but I like the muhlenberg method if we are going to continue to entertain additional dropdowns to show more levels. it seems a few of us are concerned about the additional duplicate expand on hover type experience (mouse traps, flyouts). I think the arrow on this is opposite of our accordion though which is throwing me off.

<img width="506" alt="Screen Shot 2022-01-11 at 4 41 59 PM" src="https://user-images.githubusercontent.com/4663676/149032980-1927eae5-b50a-417c-9172-237c0e9265db.png">

**Comment by bspeare** [comment]
Thanks @joewhitsitt you are right about the arrows.  I forgot to change them for that example.   This is the example they were meant for the closed by default version:

https://user-images.githubusercontent.com/1036433/149033674-bc9cfae6-6387-4242-9ea8-f03c71fd3086.mov

**Comment by bspeare** [comment]
I ran the muhlenberg approach by Tippie and they requested that we remove the toggle button option to open/close the section but add dropdowns to the items within the section.   The video below shows the menus opening by hover, but we could make them open based on click instead to avoid mouse traps.   What do you think @joewhitsitt?

https://user-images.githubusercontent.com/1036433/149578971-9f0f41c7-e638-4f34-98fb-9312a82bba18.mov

**Comment by joewhitsitt** [comment]
Added a sub-bullet to the first slice, "What tells the per page menu block to use menu block settings instead of the global options?"

With featured image, it has a "use system default" as an option. I am still thinking in some form, we are extending menu_block's block plugin to have this do everything we need it to do by either overridding the option list or creating a checkbox like "disregard settings here, use system set default"

**Comment by pyrello** [comment]
I think the idea of a checkbox is good, but I would have it be unchecked by default and have a label like "Customize menu settings in block" or something similar. This means that the user has to take a specific action to change a particular blocks settings away from what the default is. Additionally, unchecking the block would effectively serve to "clear" the settings out.

**Comment by pyrello** [comment]
> I ran the muhlenberg approach by Tippie and they requested that we remove the toggle button option to open/close the section but add dropdowns to the items within the section. The video below shows the menus opening by hover, but we could make them open based on click instead to avoid mouse traps.

I definitely liked the version where it shows/hides the whole thing at once better than this. It's just so much more action required by the user to figure out how to get where they are going. If we have to go with something like this, then definitely it should be click-based instead of hover-based to avoid page content jumping around unexpectedly on non-touch devices.

**Comment by bspeare** [comment]
@joewhitsitt @GaryRidgway Do your thumbs up on @pyrello's comment indicate you prefer to try to go back to https://github.com/uiowa/uiowa/issues/3200#issuecomment-1010437430 or that if we do pursue https://github.com/uiowa/uiowa/issues/3200#issuecomment-1013445525 that the menu expansion should be click based?

**Comment by joewhitsitt** [comment]
>I definitely liked the version where it shows/hides the whole thing at once better than this.

>should be click-based instead of hover-based to avoid page content jumping around unexpectedly on non-touch devices

Sean articulated most of my opinions on this.

>If we have to go with something like this...

Then I will understand and not make a fuss.

**Comment by GaryRidgway** [comment]
> Customize menu settings in block

Yes, I like [this one the most](https://github.com/uiowa/uiowa/issues/3200#issuecomment-1010437430). I think it is a bit more user friendly.

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module#L317 should be updated as part of the first-slice. Currently restricted to admins, and defaults are set.

**Comment by joewhitsitt** [comment]
I mentioned this a bit to @GaryRidgway yesterday. I don't think we can sneak by without extending the menu block plugin as we are trying to introduce a new field that is saved. Additionally, by extending I think that means it will be a separate block (diff id) that we will be targeting both in code and in allowed lb blocks. This means we will have to do a block swap update hook similar to ListBlock and the old articles block.

**Comment by pyrello** [comment]
Chatted a little bit with @joewhitsitt about this. I’m about 90% certain that if we have access to the submit handler, that we can store data in block config that just gets saved as part of a serialized object. This data can be completely arbitrary in nature. I originally suggested the form alter approach because extending the menu block has potential implications for being able to implement contrib modules.

**Comment by joewhitsitt** [comment]
Capturing the latest:

- So far, the form_alter custom submit handler method of adding the "customize settings" checkbox to the block and having the saved value persist is not working. Sean reached out in Slack to see if there is something we are missing.
- An alternative solution would be to use layout builder styles to create a separate group with this "style" option in it. We know that these save and that we can reference them.

Starting to think ahead to the render, are we sure we can get the site-wide settings in place before all of the menu logic starts kicking off? hook block prebuild?

- The final idea is to go forth and extend MenuBlock to add the field, save the value, get the site-wide setting before the build.
- There doesn't seem to be a feature request for a site-wide/global settings in menu_block’s issue queue.

**Comment by pyrello** [comment]
So... it seems that in a future version of Drupal (>=9.4.x), we will be able to handle this without having to resort to extending the MenuBlock class because we will be able to make use of `thirdPartySettings` on the LB component: https://www.drupal.org/project/drupal/issues/3015152. In the meantime, there just doesn't seem to be any way to set values on the block that are not defined in a `defaultConfiguration` method because those values get cleared out when the block is instantiated.

This is all to say that I have finally convinced myself that we are not going to get it done with `hook_form_alter` and custom submit handlers.

**Comment by pyrello** [comment]
Next steps:
- [ ] Create custom class to extend Drupal\menu_block\Plugin\Block.
- [ ] Add `defaultConfiguration` method which calls `parent::defaultConfiguration()` and then adds a `customize_settings` property to configuration.
- [ ] Add `blockForm` method which calls `parent::blockForm()` and adds the `customize_settings` field to the form. This is also where the addition of the states logic for the existing fields will get added to hide them when customize settings is unchecked.
- [ ] Add `blockSubmit` method which calls `parent::blockSubmit()` and then saves the value of the `customize_settings` field to the block configuration.
- [ ] Add `build` method` which copies the existing code from the `MenuBlock` class and then modifies it to change the `$build` based on the presence or absence of the `customize_settings` configuration value.

**Comment by briand44** [comment]
So what I was originally thinking when we split this into two slices is that the first slice would focus on allowing webmasters of SiteNow v3 sites to be able to control the initial visibility level and the number of levels to display for the vertical secondary menu. I understand we are currently running into issues with a global setting but I was under the impression we would allow users to override on a block by block instance as well. Is there a path forward here as part of the first slice where we can deliver value to the service by allowing block by block configuration for initial visibility level and number of levels to display for the vertical menu while not opening up the ability for the horizontal menu as part of this slice? Interested in feedback on this or hearing where this breaks down. Trying to keep it simple and add value to the service for all.

**Comment by joewhitsitt** [comment]
I think the only gotcha is that the style option is currently available to webmasters and if the horizontal style is not ready for different combinations of starting level and depth, we could get some interesting menus. That said, the first slice was originally going to run into this same issue.

I might not have this straight but I think this issue was originally created to facilitate the vertical menu options for all v3 sites, not scoped just to Tippie, so why the sudden "limit to Tippie" bit?

**Comment by pyrello** [comment]
Honestly, I think we need to regroup on this. It doesn't even seem like we came away from our last meeting with the same understanding of what we want to do and why we are doing it.

**Comment by bspeare** [comment]
As @joewhitsitt mentions, the horizontal style is not ready for the depth.    Do we reset the depth if the horizontal option is selected?  Or do we just hide the depth with CSS?  We are still trying to prototype a horizontal mega version (https://github.com/uiowa/uiowa/issues/3200#issuecomment-1013445525) that could handle the depth where we would end up with three menu options:

- Vertical
- Horizontal
- Mega
