### ISSUE TITLE
SEO settings for Admissions

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#3216]
# Story

As an admissions user, I want to be able to configure the SEO settings for the available custom content types

# Proposed solution

Setup basic SEO settings for custom admission content types. Meta description and the related SEO description fields should have a default "[Admissions Label Token] at Iowa" that can be overridden by webmasters at least. Identify this new configuration and admissions split it.

- [x] Setup SEO settings for the AOS content type #3215 
- [x] Setup SEO settings for the Student Profile content type #3218
- [x] Setup SEO settings for the Scholarship content type #3217
