### ISSUE TITLE
Anchors: A Love Story

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3311]
# Epic

As an editor, I want and easy way to add anchors to my content and to be able to find existing anchors to use and link to.

Currently in v3, anchors are an afterthought and can only be added to the HTML markup manually on `<a>` and `<h*>` tags using the `id` attribute.

# Additional information

Requested by IMU, CLAS, ITI, Law. Captured from https://wiki.uiowa.edu/display/drupaldev/Customer+Feature+Requests 

# Proposed solution

- [ ] Investigate which solutions might be best for v3.
  - Consult with other academic institutions that use layout builder and see how they address this functionality. 
- [ ] Consider implementing one or more of the following existing issues:
  - ~~Headline id field - https://github.com/uiowa/uiowa/issues/2569~~ _not available on all blocks, placement not always at the scroll point folks want._
  - Consider an automatic id based on headline value - https://github.com/uiowa/uiowa/issues/4349
  - Fix anchor links within linked cards - https://github.com/uiowa/uiowa/issues/2277
  - CKEditor button of sorts - https://github.com/uiowa/uiowa/issues/1412
  - Allow id attribute on more HTML elements https://github.com/uiowa/uiowa/issues/2826
  - Id field per block type and collection item (similar to v2) https://github.com/uiowa/uiowa/issues/3567
  - Id field on sections
- [ ]  Look into ways to "discover" existing current content anchors while editing content. This is tricky because some are generated on render, and some are in different blocks, etc.
- [ ] Consider the upgrade path for v2 sites. - Would be best addressed by https://github.com/uiowa/uiowa/issues/3567
- [ ] Would this or headings be a better base for https://github.com/uiowa/uiowa/issues/140
- [ ] Add `id` and `name` to more elements. Look into complex elements like table, caption, drupal-media, iframe before adding because we might be programmatically doing stuff with those.

- [ ] Account for logged-in offset

**Comment by joewhitsitt** [comment]
I think using anchor_link's anchor button and adding an anchor name field to the headline field should be the next steps. Discoverability is still an issue, but if we implement the headline field similar to v2's solution, editors will at least be able to go into the block and see what they are without inspecting the source.
