### ISSUE TITLE
Flip HR to UIDS_Base

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3707]
Continue work in #3709

## TODO

- [x] Communicate with HR about what work is going to be done before, in dev and after go-live.
- [x] Remove footer sidebar menu blocks
- [x] Place Unit Contact Information Block
- [x] Style Unit Contact Information Block
- [x] Style FAQs similar to uids_base accordions
- [x] Update hook to fix section containers in the absence of a sidebar?

Keep review window short.

## HR Action Items (After Deployment)

- [ ] Find home for Related Content
- [ ] Convert FAQs to Accordions
- [ ] Find spot in main menu for Administrative Services tree.
- [ ] Swap icons in cards

## Once done and workflow agreement with HR is agreed upon.

- [x] Sync HR to DEV/Push Feature Branch

**Comment by richardbporter** [comment]
Added hr.dev.drupal.uiowa.edu to uiowa dev env.

**Comment by pyrello** [comment]
@richardbporter Thanks!

This has been done in #3709 and deployed to dev for review by the customer. I think this is blocked until we know what our next steps are.

**Comment by briand44** [comment]
Where would HR be working on their action items? Dev/Stage/Prod? Would there need to be a content freeze?

**Comment by joewhitsitt** [comment]
I am going to reach out to HR about the first bullet point.

**Comment by dnkemper** [comment]
Going to remove assignment for now since moved as far forward as we could. Not sure how the contact info block is desired to be styled

**Comment by joewhitsitt** [comment]
>Going to remove assignment for now since moved as far forward as we could. Not sure how the contact info block is desired to be styled

I missed the last big of the mob yesterday so I don't know how it ended but, I think we should take an initial stab at styling the block and I am in favor of kicking the block label refactor down the road and adjusting the template for this particular block in hr_core.

**Comment by pyrello** [comment]
We got the FAQ as accordion styling working. @dnkemper was interested in styling the contact block, but I suggested that we hold off until there was clarity on how to proceed with that, since I was not privy to any discussion about how it should be handled.

**Comment by joewhitsitt** [comment]
It was discussed in parking lot to move forward with styling the contact block similar to one of the admissions sidebar blocks. https://admissions.uiowa.edu/academics/accounting

**Comment by dnkemper** [comment]
@joewhitsitt AWESOME! Already started on that yesterday so I can keep on keeping on if no one is working on this!

**Comment by richardbporter** [comment]
>Update hook to fix section containers in the absence of a sidebar?

Are there any more details on this? 

Noticed the footer content is not readable but I'm assuming they'll just update that after this goes to prod.

**Comment by dnkemper** [comment]
> > Update hook to fix section containers in the absence of a sidebar?
> 
> Are there any more details on this?
> 
> Noticed the footer content is not readable but I'm assuming they'll just update that after this goes to prod.

From what I remember when we mobbed, we couldn't find a section without a sidebar present? I could be wrong though.

**Comment by pyrello** [comment]
We didn't find any examples of pages without sidebars, but its definitely possible that it could occur. I'd say it seems like something that can be fixed manually if/when those pages are found.

**Comment by bspeare** [comment]
Do all of the pages listed here look good now?  https://github.com/uiowa/uiowa/issues/2629#issuecomment-870057933

**Comment by dnkemper** [comment]
@bspeare  define good haha. I'm trying to fix a weird rendering things going on but can push up what I have in the mean time?

**Comment by bspeare** [comment]
Yeah, good is probably not the best term.   The pages are probably no longer broken because they have a contact sidebar.

**Comment by dnkemper** [comment]
They definitely look a lot better with the sidebar!

**Comment by joewhitsitt** [comment]
I unchecked `Convert FAQs to Accordions` because that is for HR to manually change their FAQ paragraphs instances to the Accordion paragraph on each page.

**Comment by dnkemper** [comment]
@joewhitsitt @bspeare Alright. Believe this is ready to be looked over now 🤞
