### ISSUE TITLE
UIDS SiteNow Sub-Theme

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#371]
Leveraging the new UIDS (https://github.com/uiowa/uids), create a new component base theme for the SiteNow service that will replace uiowa_bootstrap for all sites but HR (for now).

More details will need to be flushed out for this or separated in to separate tasks. Should be addressed in conjunction with #260

- [x] #1304 Audit differences between paragraphs and components.
- [ ] Enable uids_base on SiteNow Demo and start adopting global regions
  - [ ] Move away from uiowa_footer by programmatically adopting uids_base equivalents.
  - [ ] Move away from uiowa_bar by programmatically adopting uids_base equivalents.
  - [ ] Superfish
- [ ] Initialize new uids sub theme
- [ ] Mimic uids where we need to for faster adoption (sections, column widths, carousel, featured content)
- [ ] See if we can reduce unused CSS: https://www.previousnext.com.au/blog/performance-improvements-drupal-8-libraries
- [ ] Contribute back to uids_base regarding site wide theme settings (e.g. #587, #94)
- [ ] Address #260 before going to far with design.
- [ ] Contribute back as much a11y work that has already been done (landmarks, aria, html5 semantics, headings)
- [ ] Fix SEO issues from our current theme:
  - [ ] https://developers.google.com/web/fundamentals/design-and-ux/responsive#optimize_text_for_reading
  - [ ] https://developers.google.com/web/fundamentals/accessibility/accessible-styles#multi-device_responsive_design

**Comment by joewhitsitt** [comment]
Work has started to compare the differences between SiteNow paragraph bundles and existing UIDS components #1304

**Comment by joewhitsitt** [comment]
Marking as blocked. Good info, but work is being done to just use uids_base instead of sub-theming

**Comment by joewhitsitt** [comment]
Much of this is either done or will be handled later through their respective tasks. Marking for reference but closing. Further work is being done towards this in #1324 and #1660
