### ISSUE TITLE
As a MarTech person, I want our CRM module enabled in Tippie so that we can use it for recruitment

### ISSUE THREAD

**Issue by makurj** [uiowa/uiowa#3811]
# Story

TIPPIE - As a MarTech person, I want our CRM module enabled in Tippie so that we can use it for recruitment.

Pardot module: copy/edit/create https://www.drupal.org/project/pardot
https://git.drupalcode.org/project/pardot/-/blob/8.x-1.x/pardot.info.yml
https://www.drupal.org/project/pardot/issues/3176074
https://help.salesforce.com/s/articleView?id=000312312&type=1

An anonymous cookie is dropped via GTM when a user visits Tippie. Their browsing history is captured in that. Then once they submit a Drupal webform, the Pardot module takes their anonymous browsing history and attaches it to their known ID (which is coming from the webform). So basically pre-webform-submission browsing history and post-webform-submission browsing history are attached to a known ID that is then passed to Pardot.

From user: "The Pardot cookie basically allows Pardot to take their “anonymous cookie” – the one they got the moment they visited a Tippie web property – and tie it to their “known cookie”, the one that contains their name and email. This is how we can see someone’s browsing history once they’ve converted… not just the pages they visit AFTER filling out the conversion form/RFI… but everything they did before conversion on our site."

# Proposed Solution
Using test accounts that Makur and Joe have try to send data to Pardot using one of the following making sure that the GTM pardot code is included in the DOM:

- [x] ~~Re-visit https://www.drupal.org/project/pardot and try the 2.x dev branch - _installed_~~
  - [x] ~~Try the webform integration patch https://www.drupal.org/project/pardot/issues/2878909~~
  - [x] ~~Generally see how the module development is going and see if it is worth waiting or put effort in there.~~
  - [x] ~~Reach out to EduDu Slack group and see if they have made progress with Pardot for D8/9~~
- [x] ~~In a tippie_core module try something similar to the D7 versions where they make a client side request using a faux object: https://github.com/uiowa/uiowa/issues/3811#issuecomment-1009381466, https://github.com/uiowa/uiowa/issues/3811#issuecomment-1022319225~~
- [x] Remove previous iframe related code from tippie_core
- [x] Referencing https://github.com/uiowa/uiowa/issues/3811#issuecomment-1055931872, create a JS script that is loaded into webform (form_alter) if remote post and a certain hidden visitor_id field is set by the form editor. Get the visitor_id cookie and make it the value of that hidden input.
- [ ] Have customer test in DEV
- [ ] Before merge to main, make sure environment based check on google tag manager in uiowa_core is set

**Comment by briand44** [comment]
Provide test account credentials for Pardot.

**Comment by briand44** [comment]
We likely will want an investigation slice to figure out best path forward here.

**Comment by makurj** [comment]
https://www.youtube.com/watch?v=i3I4LDV67p0

**Comment by makurj** [comment]
https://help.salesforce.com/s/articleView?id=sf.pardot_prospects.htm&type=5
**Anonymous Visitors**
An anonymous visitor is someone who has visited a page with your Pardot tracking code on it, but hasn’t converted to a prospect yet. Prospects are visitors who have an associated email address in Pardot.

https://help.salesforce.com/s/articleView?id=sf.pardot_converting_visitors_to_prospects.htm&type=5 
**Converting Visitors to Prospects**
In Pardot, a prospect is a visitor with a known email address. Here are the most common ways an anonymous visitor converts to a prospect.

Submits a Pardot form that is in an iframe on your web page
Submits a form on your site that’s connected to a Pardot form handler
Submits a form on a Pardot landing page
Is manually associated with a prospect

**Comment by joewhitsitt** [comment]
I thought this was already being done with webform remote post. With browser trackers allowed I see the pardot stuff including a user id:
<img width="610" alt="Screen Shot 2021-12-14 at 3 48 04 PM" src="https://user-images.githubusercontent.com/4663676/146085189-ff7a7c62-437f-46ef-804f-93fc07ce1b63.png">

So then _if_ configured correctly, the remote post here https://tippie.prod.drupal.uiowa.edu/form/pardot will take my email input and associate it with the visitor_id above making me a verified prospect.

This makes me think that the remote post is not configured correctly.

The glue if any from all of the links above makes it seem that just specifying the remote post url is not enough to create the link and that the visitor id has to be sent with the post.

```php
+    // Look for the visitor ID cookie and pass the value alongside the request.
+    $visitor_id = '';
+    $cookies = \Drupal::request()->cookies->all();
+    foreach ($cookies as $cookie_name => $cookie_value) {
+      if (preg_match('/visitor_id\d+$/', $cookie_name)) {
+        $visitor_id = $cookie_value;
+        break;
+      }
+    }
```
https://www.drupal.org/files/issues/2021-01-12/pardot-visitor-prospect-association-webform.patch
This can either populate a hidden field on load or it can be part of a custom submit handler.

**Comment by makurj** [comment]
Based on my reading yesterday, I would agree with you that we need the JS above with the post. Does that mean I should add that script to the "updated" field of remote post?

**Comment by joewhitsitt** [comment]
I would ask whoever maintains `https://go.tippie.uiowa.edu` what the expected POST format should be for that URL in the remote post settings. Once we know that we can determine what should be included with that and how to go about it.

**Comment by makurj** [comment]
After meeting with our Pardot/Salesforce maintainer, I have found that the D7 Pardot module enabled the use of a Pardot form handler on a Drupal webform, which would associate the visitor_id with the prospect_id.

**Comment by makurj** [comment]
https://git.drupalcode.org/project/pardot/-/tree/8.x-1.x

**Comment by makurj** [comment]
Tried installing https://www.drupal.org/project/pardot/releases/8.x-1.x-dev but it errored out. 

![image](https://user-images.githubusercontent.com/52135878/146828211-1177d63f-9ad4-46d6-80ab-261400449a9c.png)

Back to square one of writing a custom module.

**Comment by makurj** [comment]
https://help.salesforce.com/s/articleView?id=000322102&type=1

**Comment by makurj** [comment]
https://developer.salesforce.com/docs/marketing/pardot/guide/getting-started.html

**Comment by briand44** [comment]
there is a working d7 implementation that could be referenced. Also, Makur checking on using pardot form.

**Comment by makurj** [comment]
Response from user on why we can't use Pardot forms:

1. The Pardot form styling is horrible and extremely difficult to get it to match our website’s
2. We’d have to use an iframe – not a good experience for accessibility
3. We can’t use conditional logic with a Pardot form
4. A pardot form wouldn’t provide a failsafe – we need the data to go to two places, if at all possible. We had an issue back in 2015, when we were using a Drupal form that only integrated with Pardot… it didn’t keep a copy of the data on our webserver. After 3 months we discovered about 40% of our inquiries were going into the ether and were lost. So from that point on we decided we needed redundancy since the inquiry data was so important.
 
#4 is probably the one that we can flex on, provided whatever solution we come up with is super stable. But 2 and 3 are deal-breakers.

**Comment by makurj** [comment]
Meeting scheduled with Salesforce/Pardot for Wednesday, January 5.

**Comment by joewhitsitt** [comment]
It was re-scheduled for today.

Current issue is that pardot is expecting a client side post instead of the current server side remote post. _If_ we were to get the visitor_id from GTM into the submission data, it wasn't clear from Pardot support what the key name would be and if it would be accepted.

The redundant data (webform submission) is still required because of a bad data experience and the lack of export/backup tools available to the customer.

https://git.drupalcode.org/project/pardot/-/blob/7.x-1.x/pardot.module#L226 and https://git.drupalcode.org/project/pardot/-/blob/7.x-2.x/pardot_webform/pardot_webform.admin.inc#L127 look like they do some odd things to send as "client side"

This makes me think the the remote post of d9 webform is too far in the process.

**Comment by joewhitsitt** [comment]
Just tried to install the 2.x version with more success than https://github.com/uiowa/uiowa/issues/3811#issuecomment-998245142 but reached a point that I wasn't ready to bite off quite yet:

`You must enable the Salesforce JWT Auth Provider, Salesforce Integration, Key, Typed Data modules to install Pardot.`

**Comment by briand44** [comment]
Could possibly reach out to Colorado folks if needed?

**Comment by makurj** [comment]
Installed pardot 2.x-dev locally which asks a few other modules to be enabled. Once enabled, there's no configure button for the Pardot module in Extend or in Configuration. You have to manually append /admin/config/services/pardot to get there and once there, you cannot save any account info without entering something into "Salesforce Auth Provider" which only has "None" as the dropdown option. Leaning towards custom module.

**Comment by joewhitsitt** [comment]
I think I found the easiest slice (no-code) solution using `?pi_list_email=[webform_submission:webform:element:email]` appended to the confirmation URL. This will allow the webform to go anywhere (e.g. drupal page, unbounce) as long as it includes the Pardot Javascript tracking code.

https://help.salesforce.com/s/articleView?id=000315015&type=1

https://pi.pardot.com/visit/read/id/318773578/prospect_id/67706984

**Comment by mjoneill** [comment]
> I think I found the easiest slice (no-code) solution using ?pi_list_email=[webform_submission:webform:element:email] appended to the confirmation URL. 

Hmmm...  Seems to be an [email specific solution](https://help.salesforce.com/s/articleView?id=000315015&type=1). I'd worry that taking this approach _may_ lead the CRM to (mis) attribute activities to emails.  

Apologies if I'm misapprehending something and are actually trying to figure out the email attribution piece.  :P

**Comment by makurj** [comment]
I'll test this out locally and have our Martech person look at it also.

**Comment by makurj** [comment]
Spoke with Lydia and our Salesforce account allows multiple prospects with the same email. During some testing, it's not clear why my test submission from yesterday only shows my browsing history from yesterday but the overview tab (with the same email) shows history going back to 2020. Will try removing pardot.com and go.tippie cookies and trying again.

**Comment by joewhitsitt** [comment]
I am definitely not an expert here, but my understanding is that the webform remote post is already sending first/last/email in the submission to pardot, but this token paired with the client side JS is creating the link between the on-page cookie and the email address submitted. This results in pre-submit and post-submit traffic being captured and associated with the prospect.

**Comment by joewhitsitt** [comment]
>The second one Joe sent (https://pi.pardot.com/visit/read/id/318773578/prospect_id/67706984) shows one page of browsing history before he submitted the drupal form.

>Can we do additional testing but several minutes of browsing history before submitting the form?

Sent another test case for review where it has activity before submit and tracks my movement from tippie.prod to tippie.uiowa.edu: https://pi.pardot.com/prospect/read/id/67728380

Though I understand it isn't showing the same audit process as the current tippie site has, we are using a different process that does still seem to log my ISP information and browsing leading up to submit.

Additionally, which might be related I was seeing inconsistencies with the js where it didn't fully fire and/or assign a visitor_id while browsing.

**Comment by makurj** [comment]
Will have Lydia weigh in again but I am seeing presubmission browsing history and post for https://pi.pardot.com/visitorAudit/index/prospect_id/67728380
![image](https://user-images.githubusercontent.com/52135878/151188262-7cecd430-4a79-420c-93b9-7eb371f06167.png)
The difference is before when a form was submitted and a visitor was converted from a visitor to a prospect, you'd see "Converted from visitor" info.
![image](https://user-images.githubusercontent.com/52135878/151188614-642b4395-eaf9-476b-9c74-2960053a8df9.png)

**Comment by joewhitsitt** [comment]
_If_ we need a different approach, my thought is to do the "iframe" method by either customizing the current remote post handler or creating a custom one:

customize existing:
<https://www.chapterthree.com/blog/drupal-8-how-to-extending-a-webform-remote-post-handler>

create new:
<https://www.drupal.org/files/issues/2020-11-10/2878909-webform-integration-5.patch>

downside to this approach will be that the confirmation page must be a drupal page

**Comment by joewhitsitt** [comment]
Lydia has been testing and is getting some mixed results and might reach out to Salesforce about the method currently in place.

**Comment by joewhitsitt** [comment]
Lydia said by way of Makur that the email token will not be a suitable solution.

**Comment by makurj** [comment]
Next steps:

- [x] Add config to add per handler endpoint URL
- [x] Investigate dynamically adding webform values
- [x] Put it on dev to have user test it.
- [ ] ~~Investigate alternative confirmation options (for example, URL) before the iframe gets inserted~~
- [x] Shift "Edit" under operations. 
![image](https://user-images.githubusercontent.com/52135878/153028189-fa5945ea-39d4-48ed-bfae-c2020c985912.png)

**Comment by makurj** [comment]
Going to move tippie.dev.drupal.uiowa.edu from 703 to uiowa02.
May need a new container for tippie.dev.drupal.uiowa.edu created in GTM as the Pardot JS is not firing on each page locally.

**Comment by joewhitsitt** [comment]
>Investigate dynamically adding webform values

Instead, we are providing handler guidelines on the assumptions we made and I wrapped our processConfirmation code in some validation with a log message if iframe isn't being rendered.

**Comment by joewhitsitt** [comment]
I can help get this code to DEV once the site is there and waiting with pardot js

**Comment by makurj** [comment]
Tippie Dev ready on uiowa02 dev. GTM Pardot tag not firing. Troubleshooting.

**Comment by makurj** [comment]
Tested it on dev and it appears to be working as expected. Will have user test it when they're back next week.

**Comment by makurj** [comment]
Met with Lydia and here is some further work that needs to be done on this:

1. Lydia would like to capture data from other fields in addition to firstname, lastname and email. She is compiling a list and will send them to me. Not all forms have all the fields.
2. She would like to revert the field keys to Drupal's default of first_name, last_name instead of firstname, lastname. She says she can customize these on the Pardot side, so she will make them Drupal's default so that in case she forgets there's no data loss. See screenshot below. 

![image](https://user-images.githubusercontent.com/52135878/154352012-2349010c-0c31-4dbc-a6a8-460c4aaf840f.png)

**Comment by makurj** [comment]
@joewhitsitt @richardbporter Do we need to wait for Lydia to give us the keys to start work on this?

**Comment by makurj** [comment]
URL Parameters discussion summary: Lydia can use the Pardot API. In that scenario, Drupal and Pardot never actually connect so OSC wouldn’t need to build anything, as long as we can pass the prospect ID to her (fill a hidden field on the form with the prospect ID from the browser, so it can be passed to Pardot through the form handler). She can make the visitor id and prospect id connection in the API inside Pardot. She also doesn’t care if the pre-submission browsing history is missing. The form handler will take care of the form submission data and it won’t be exposed anywhere.

She has an API developer/vendor in mind and there's budget for it.

**Comment by makurj** [comment]
https://developer.salesforce.com/docs/marketing/pardot/guide/version5overview.html

**Comment by joewhitsitt** [comment]
> OSC wouldn’t need to build anything, as long as we can pass the prospect ID to her

So the d8/9 version of pardot with the webform patch is setup this way: https://www.drupal.org/project/pardot. [we stopped going this route because of the of the authentication piece](https://github.com/uiowa/uiowa/issues/3811#issuecomment-1015799122),  but also because even with the contact form (not webform), the module is having troubles passing that data to pardot: https://www.drupal.org/project/pardot/issues/3176074

Also a beta or stable release has stalled:
https://www.drupal.org/project/pardot/issues/3046186

To do a thin-slice of this on our own without the module, we would need to tap into to the remote post handler before POST and while we still have headers, pull out the visitor_id attach to a field that exists on the form (always named the same). Assuming it gets to pardot, then the association needs to happen by their developer and it is not clear that pre-traffic would be captured this way.

**Comment by joewhitsitt** [comment]
Poked at this a bit more this morning. Tried to pull out just a piece of the patch here https://www.drupal.org/project/pardot/issues/3176074 as it relates to getting the cookie to pass in.

```
// Look for the visitor ID cookie and pass the value alongside the request.
  $visitor_id = '';
  $cookies = \Drupal::request()->cookies->all();
  foreach ($cookies as $cookie_name => $cookie_value) {
    if (preg_match('/visitor_id\d+$/', $cookie_name)) {
      $visitor_id = $cookie_value;
      break;
    }
  }
```

In my attempts, no cookies were being returned which led me to https://drupal.stackexchange.com/questions/199519/how-can-i-check-in-drupal-8-an-externally-set-cookie where it says if they aren't the same-origin then you can forget about it:

>You can always only access cookies from the same origin. You can't access cookies from other origins. Imagine if that were possible. I could then write a web application that would harvest your gmail cookies, and log into your gmail remotely to do whatever I like. 

I suspect this goes back to why all of the authentication is needed for the new pardot module.

_I should note that all of this cross-site stuff is relatively new to me so I don't know what I don't know._

**Comment by makurj** [comment]
![image](https://user-images.githubusercontent.com/52135878/156252064-8f9e6090-254b-403d-b5fe-3933c38ea8ca.png)

**Comment by joewhitsitt** [comment]
Based on Lydia's suggestion, we could do a pure JS approach (bypassing the structures of Drupal, remote post would still be needed to send the values) assuming the webform field component exists however there are still issues with not getting _all_ the cookies added to the page:

The browser shows these cookies:
<img width="1107" alt="Screen Shot 2022-03-01 at 4 35 40 PM" src="https://user-images.githubusercontent.com/4663676/156260650-d094262f-519f-4d2d-8450-018d4aa78138.png">

Local JS can only get a subset:
<img width="413" alt="Screen Shot 2022-03-01 at 4 36 16 PM" src="https://user-images.githubusercontent.com/4663676/156260760-1ea1f418-bda5-4b3d-b6be-0d4cb005534a.png">

So it does appear under ideal conditions to provide a visitor_id... cookie we can work with. The JS would need to load after pardot stuff loads and the cookies set but before the user submits the form. The JS should probably be loaded with a form_alter checking to make sure the hidden field is available before attaching.

`document.cookie.split(';');` or something similar would fetch all of the cookies which includes visitor_id{unique number}: {visitor_id} and visitor_id{unique number}-hash: {long hash}. Lydia mentioned that the former is what we want, so getting the cookie that starts with `visitor_id` but does not end with `-hash`. I assume get the first one and hope there isn't multiple of similar name.

If the browser blocks the cookie or is not available for some other reason, I imagine the field would be sent up empty.

From the meeting, to answer Lydia's question about why the Drupal pardot module needs to authenticate, it looks like it is attempting to do the work of assigning the visitor id to the prospect email. `$pardot_client->assignPardotProspect($visitor_id, $prospect_id);`

**Comment by joewhitsitt** [comment]
Updated the proposed solution

**Comment by joewhitsitt** [comment]
Need to know the machine name of the hidden field Lydia plans on using to capture the visitor id so we can target it.

**Comment by makurj** [comment]
Wrote her to get the machine name.

**Comment by richardbporter** [comment]
Is that number after `id` always the same, `visitor_id683163`? I see the same thing.

**Comment by joewhitsitt** [comment]
I wouldn't hardcode it and instead match against it

untested: `preg_match('/visitor_id\d+$/', $cookie_name)` like in https://github.com/uiowa/uiowa/issues/3811#issuecomment-1055732486 

or 

>so getting the cookie that starts with visitor_id but does not end with -hash

https://github.com/uiowa/uiowa/issues/3811#issuecomment-1055931872

**Comment by makurj** [comment]
Machine name for the hidden field on forms will be "visitorid".

**Comment by richardbporter** [comment]
>Referencing https://github.com/uiowa/uiowa/issues/3811#issuecomment-1055931872, create a JS script that is loaded into webform (form_alter) if remote post and a certain hidden visitor_id field is set by the form editor. Get the visitor_id cookie and make it the value of that hidden input.

This is essentially done but done via PHP and not JS. JS wasn't working on dev. I got cookies working locally by adding a FQDN under `tippie.uiowa.edu` to ddev. This gets cookies working for subdomains and they are submitted with every request.

**Comment by makurj** [comment]
Thanks so much @joewhitsitt and @richardbporter!
