### ISSUE TITLE
As a website owner/operator, I have an Areas of Study tool that allows me to search filter degrees/programs (like we see on the Admissions site) and link off to a page of my choosing.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#3837]
As a website owner/operator, I have an Areas of Study tool that allows me to search filter degrees/programs (like we see on the Admissions site) and link off to a page of my choosing.

## Proposed Solution

Continuing in https://github.com/uiowa/uiowa/pull/3926

- [x] audit sites using areas_of_study split
- [x] see what functionality in areas_of_study split is worth keeping
- [x] move what is not desired to admissions only
- [x] so far i am hearing title, faceted filters, link to desired location
- [x] filtering view page links to desired location
- [x] #4034
- [x] #4041
- [x] #4069
- [x] #4073
- [x] #4074
- [x] Conversation with Admissions to see if they want any of this functionality or whether we should create a clean split.

## Postponed

- [ ] link fields to maui and admissions equivalent to establish some kind of bridge if paths align in the future.

**Comment by joewhitsitt** [comment]
Previously I think there was discussion about reclaiming the feature split and move everything existing to admissions only? wasn't grad using this?

**Comment by mjoneill** [comment]
Prospective undergrad insterested in studying Jazz. Here is some information they might consume: 
* https://stories.uiowa.edu/iowa-nations-next-hotbed-jazz
* https://catalog.registrar.uiowa.edu/liberal-arts-sciences/music/#programstext
* https://admissions.uiowa.edu/academics/music
* https://music.uiowa.edu/future-students/undergraduate-students-areas-degrees/jazz-studies-bm
* https://music.uiowa.edu/future-students/graduate-students-areas-degrees/jazz-studies-ma

**Comment by mjoneill** [comment]
Arizona offers a nice mix of a similar tool in use across admissions + at the college level:
* College of Education Finder: https://coe.arizona.edu/majors
* Admissions: https://www.arizona.edu/degree-search/
* https://www.arizona.edu/degree-search/majors/early-childhood-education
* https://coe.arizona.edu/programs/early-childhood-education-bae

@ABoston88

**Comment by joewhitsitt** [comment]
Looks like a lot was captured already here: https://github.com/orgs/uiowa/projects/1#card-59038297

**Comment by mjoneill** [comment]
This slice is not scoped to solve for streaming content from canonical sources.  That's going to be a much bigger and more complex conversation around content governance and authorship that we'll have to sort through...but I do believe this is a direction we'd like to head in when we have the opportunity.  Right now, having locally managed content in such a tool is a win.

**Comment by joewhitsitt** [comment]
To grab statuses on each application:
`./vendor/bin/blt ume "config:get config_split.config_split.areas_of_study status"`

Update: As far as I can tell, admissions is the only one using the feature split.

**Comment by joewhitsitt** [comment]
Here is the AoS feature default functionality. Quite more than what is necessary for this issue.

![default local drupal uiowa edu_node_add_area_of_study](https://user-images.githubusercontent.com/4663676/128240414-c34bec7d-fcf8-4b1a-ba91-2ea5e33a7fd9.png)

**Comment by joewhitsitt** [comment]
Education requested the following:

- "Search" block similar to admissions.uiowa.edu that sends queries to view page.
- synonyms (associated terms) plain long text field that can combine filter on (not rendered to display)
- sitenow articles/people functionality as it relates to view page title, path, header content. 

Learning format filter?: https://github.com/uiowa/uiowa/pull/3926#issuecomment-896046010
Clean break for admissions? https://github.com/uiowa/uiowa/pull/3926#issuecomment-896053512

**Comment by mjoneill** [comment]
> Education requested the following:
> 
> * "Search" block similar to admissions.uiowa.edu that sends queries to view page.
> * synonyms (associated terms) plain long text field that can combine filter on (not rendered to display)
> * sitenow articles/people functionality as it relates to view page title, path, header content.
> 
> Learning format filter?: [#3926 (comment)](https://github.com/uiowa/uiowa/pull/3926#issuecomment-896046010)
> Clean break for admissions? [#3926 (comment)](https://github.com/uiowa/uiowa/pull/3926#issuecomment-896053512)

Anything strike you that didn't come up as an ask/request?

**Comment by joewhitsitt** [comment]
>Anything strike you that didn't come up as an ask/request?

- Feels more likely that a clean break for admissions may be warranted.
- I forgot the trouble allowing site owners to change the paths for content when using a feature split. Not sure how to go about that.

**Comment by briand44** [comment]
Blocked until we get some feedback from Admissions

**Comment by joewhitsitt** [comment]
Scott didn't seem interested in any of the new functionality. It will be easier in the long run to separate the base feature from Admissions than to keep the link going.

**Comment by joewhitsitt** [comment]
Admissions might be interested in what develops in this feature for grad.admissions but it sounds like they want that to be custom as well.

**Comment by mjoneill** [comment]
I was able to reach out and hear back from Registrar.  Right now they are mostly confident that the label for "Learning Format" is actually "Delivery Mode".

They are trying to confirm with someone...

**Comment by mjoneill** [comment]
Full answer from Registrar came in:

> In respect to terminology for a class format or what we refer to as a delivery mode these are the definitions –
> 
> •	Web is defined as “This course will be taught online.”
> 
> •	Virtual is not currently defined as a delivery mode option in our SIS.
> 
> •	Hybrid is defined as “A flexible course where students will have both face to face and virtual instruction.”
> 
> In terms of a program of study, it is referred to as “online”.  Where course work is concerned, it is referred to as “online” where both work and content is online.
> 
> As you can see, we are using these words somewhat interchangeably, especially in the list of bullets.

**Comment by joewhitsitt** [comment]
Found this today https://github.com/uiowa/uiowa/issues/3347

Admissions wanted it to be a view block and to have the search block be configurable as well..

**Comment by briand44** [comment]
Sounds like there is still an areas of study search block that can be deprecated as well as some documentation. Also, will this require dev to turn on or are we making this available to anyone?

**Comment by joewhitsitt** [comment]
Correct. https://github.com/uiowa/uiowa/issues/4082 is the left to do. Historically we have not created documentation for feature/site split functionality.

We could split out `link fields to maui and admissions equivalent to establish some kind of bridge if paths align in the future` into a separate card or issue and close this.

This is not on by default and I don't think it should be.

**Comment by briand44** [comment]
Created a follow up for future enhancement https://github.com/uiowa/uiowa/issues/4117
