### ISSUE TITLE
P2LB to-dos for site self-transition phase

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#3878]
# Problem #
#3792 revealed some bugs to fix before the p2lb module can be rolled out to customers wanting to self-transition their sites to v3

## Add
- [x] #6680
- [x] #6681
- [x] #5633
- [ ] P2LB - Create action to revert to V2 version of page
- [ ] Run P2LB to see what's what
- [ ] Investigate outstanding issues to see if they are still issues

Check on Brand
```
ddev blt ds --site brand.uiowa.edu && ddev drush @brand.local config-split:activate p2lb -y && ddev drush @brand.local uli admin/content/sitenow-converter
```

Check on HMB
```
ddev blt ds --site hawkeyemarchingband.uiowa.edu && ddev drush @hawkeyemarchingband.local config-split:activate p2lb -y && ddev drush @hawkeyemarchingband.local uli admin/content/sitenow-converter
```

## Fix/Update
- [ ] Carousel items without captions are not being converted but do not throw an error/inform you that carousel items need a caption to be converted. 
- [ ] Cards - Videos - added in v2 text field not captured when page is converted. 
- [ ] Cards - Images - needs to convert to image block if card is image only
- [ ] Cards previously did not have buttons.  Are we ok with all P2LB cards having buttons?
- [ ] Background images/banners: Do we need to convert these to image blocks if there is no text area in use?  The default gradient gets in the way. 
- [ ] ListBlock (Articles and People): Update `sitenow_p2lb_process_paragraph` to set tags in new block based on tags in paragraph settings. Added todo comments in #5613.
- [ ] Sidebar menus: All pages need the `Page w/ left sidebar` layout with the `Main navigation` block set to `Vertical` that sidebar menus will work for converted pages. 
- [ ] Events block: Audit again to account for recent updates (eg date range, changes to how past/future events are selected, etc)
- [ ] if https://github.com/uiowa/uiowa/issues/5025 is done, update field_teaser to body summary as part of this transition.

### Done
- [x] #5254
- [x] #5317
- [x] #5318
- [x] Articles: `This block is broken or missing. You may be missing content or you might need to enable the original module`
- [x] Background images/banners: V3 draft does not display background images
- [x] Blockquote: V2 blockquotes need to be mapped to new blockquote blocks now available. Previously these were mapped/styled into text area blocks.
- [x] Events: converting page will give error message even though it does convert correctly `Notice: Trying to get property 'value' of non-object in sitenow_p2lb_process_paragraph() (line 629 of modules/custom/sitenow_p2lb/sitenow_p2lb.module).`
- [x] Cards: The text format is not set for the card description field. If you edit this field it won’t save until you’ve chosen a format. Do we need to set this to be `minimal_html`?
- [x] People: v3 block not editable in layout builder
    -  Needs to be converted to use List Block `Warning: strtoupper() expects parameter 1 to be string, array given in Drupal\views\Plugin\views\query\Sql->addOrderBy() (line 1053 of core/modules/views/src/Plugin/views/query/Sql.php).`
- [x] Add link to SiteNow Converter tool - Fixed in #5613 
- [x] ListBlock blocks (People, Articles): Consolidate how to account for the [v2 disabling of ListBlock](https://github.com/uiowa/uiowa/blob/main/docroot/modules/custom/layout_builder_custom/layout_builder_custom.module#L1240) - Fixed in #5613 
- [x] ~#5635~
- [x] #5246
- [x] #5863

### Possible improvements

I think we will want to have some logic that checks to see if the conversion is run (that a value has been set on the conversion tracking field) and disable the paragraphs field on the edit page and include a note that the page either needs to be edited through layout builder or reverted.

## Setup instructions
- `ddev blt ds --site hawkeyemarchingband.uiowa.edu` or another V2 site.
- `ddev drush rsync @hawkeyemarchingband.prod:%files @hawkeyemarchingband.local:%files`
- `ddev drush @hawkeyemarchingband.local uli admin/config/development/configuration/config-split`
- Enable P2LB split
- `ddev drush @hawkeyemarchingband.local cim`
- Visit converter tool at https://hawkeyemarchingband.uiowa.ddev.site/admin/content/sitenow-converter

```[tasklist]
### Tasks
```

**Comment by e-marie-w** [comment]
@briand44 making visible this was moved to backlog after standup.

**Comment by bspeare** [comment]
I've spent some time today testing and updating the tasks on this issue.  I moved all the headline related bugs into https://github.com/uiowa/uiowa/issues/5318 and I've tested out and added more detail to each task.

**Comment by e-marie-w** [comment]
While working on the default styles, I noticed that for articles, events, and people, any custom paths (internal or external) for the Display More link are not captured when converted and instead the default Display More link for the block is used.

**Comment by joewhitsitt** [comment]
Events will need to be reviewed again based on the recent changes

**Comment by cory-skeers** [comment]
> Events will need to be reviewed again based on the recent changes

Added an additional checkbox so we don't miss this.

**Comment by pyrello** [comment]
Closing in favor of #6706
