### ISSUE TITLE
Arts Iowa requirements for v3

### ISSUE THREAD

**Issue by richardbporter** [uiowa/uiowa#3932]
Starting an epic to collect Arts Iowa requirements for v3 site.

- [ ] Investigate option for aggregating sitenow_events either by event with "X more instances" or by date/time.
- [ ] Investigate adding a date picker component to sitenow_events with presets.
- [ ] Investigate displaying keywords option for sitenow_events. They specifically want pa_recitial_attendance to show as a checkbox but some general way to display keywords might be useful for others.
- [ ] Use existing page building tools to create "featured events" on the front page and demo to customers. Banner and/or slider would be obvious choices.
- [ ] Re: above "featured events" - figure out how to link to an event (next instance) and not a specific event instance so front page links don't break or point to an old instance.
- [ ] Uncheck all "Display more link" configs from all existing blocks and demo to customer.
- [ ] Add additional fields to sitenow_events single event display:
  - department (possibly override for "presented by" label for Arts Iowa)
  - event type
  -  ticket URL
  - ticket cost
- [ ] #725
- [x] #2739 
- [x] #3809
- [ ] Probably #3274 based on current site images.
- [x] #2998
- [x] #2262

**Comment by richardbporter** [comment]
I don't think all of these are required for launch. Waiting to split out individual issues until we confirm with customer to proceed.

**Comment by bspeare** [comment]
@briand44 can we close this too?

**Comment by briand44** [comment]
yes
