### ISSUE TITLE
Concept3D replacement for maps.uiowa.edu

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#3957]
# Story

As a site visitor, I can find building information using the new Concept3D solution.

# Proposed Solution

- [x] Bring team up to speed
- [x] #4024
- [x] #4006
- [x] #4025
- [x] Get Concept3D CMS training roster identified
- [x] Reach out to Facilities about Concept3D next steps - @joewhitsitt will reach out initially about unique id, sharps/gender-inclusive/lactation room data, categories
- [x] #4076
- [x] #4212
- [x] Figure out building pages strategy
- [x] #4350 
- [x] #4351 
- [x] Ask Facilities to invest in getting the info identified in 4351 to a consumable state
- [x] #4574
- [x] Establish workflow with facilities to provide updates to building data
- [x] #4575
- [x] Clean up CMS display
  - [x] #4541
  - [x] #4542
  - [x] #4566
  - [x] Consider social media icons that match brand guidelines (single-color off-black)
  - [x] #4567
- [x] #4616
- [x] #4591
- [x] #4578
- [x] #4656

# Later On

- [ ] Investigate how we can update data.its to clean up data for periodic sync to Concept3D
  - Combine/clean up address data, lactation, gender-inclusive data.
- [ ] #5926
- [ ] Update facilities website to pull in new data (gender inclusive, lactation, hearing loops)
- [ ] https://github.com/uiowa/uiowa/issues/4677
- [ ] Computer labs/ITCs/Study spaces
- [ ] Inventory of UrgentCare/QuickCare location points and content work to add those to the map (point of contact Max Freund?).
- [ ] Hospital parking sub-category
- [ ] Non-building points like track and field, cross-country, points of interest
- [ ] https://github.com/uiowa/uiowa/issues/4676
- [ ] https://github.com/uiowa/uiowa/issues/4675

<details>
<summary>Original details</summary>

- Identify top-level categories (point of interest, housing, parking construction projects, etc.)
  - Identify any sub-categories (e.g. on-campus housing, off-campus housing? public vs permit parking?)
  - See if this can be updated in facilities data?
- Determine which set of data should be imported (maps.uiowa.edu uses active, in construction) or import all and use visible (front map)/private (public but need to know link) options in CMS.
- Identify unique identifier to be used (BuildingID?). Confirm with Jay that it doesn't change.
- Determine beyond basics (title, category, location, visible, private), what initial data should be captured from ArcGIS/maps.uiowa.edu and what initial data should added to the import or handled manually after import (e.g. description, picture)
- Create an initial csv export of data from our sources (arcgis/drupal) in the format that concept3d wants (building name, reference (arcgis endpoint), lat/long(combined, comma separated), year built?, etc.). https://help.concept3d.com/hc/en-us/articles/360019217413-Bulk-Upload-
- Fill in any manual content into csv before import.
- Fill out "Iowa Data Feed Template" for what content should be updated when ArcGIS data is updated.

</details>

**Comment by joewhitsitt** [comment]
Finding smaller slices of this.

**Comment by mjoneill** [comment]
Can we add a checkbox/card to capture "Get CMS training roster identified"

**Comment by richardbporter** [comment]
Added a checkbox for v1 integrations.

**Comment by joewhitsitt** [comment]
Reached out to Facilities to ask about a good unique id, an initial csv export of building info and whether there is data related to sharps disposal, etc. that we could pull from instead of manually maintain.

**Comment by joewhitsitt** [comment]
Jay from Facilities said `BuildingID` would be best for unique id, that he would help us get the initial csv dump and that DWProd has gender-inclusive restroom and lactation room data that we could pull from.

**Comment by mjoneill** [comment]
Followup re: custom fields

I asked today about custom fields.  Patrick said it's pretty easy. Should just be a matter of adding a column and making sure that everything is still tied to the uniqueID/buildingID.  He's going to check with the integration manager and follow up with an email and likely an invitation to discuss.

I'm not sure just adding the field means everything gets displayed as we'd expect, etc...

**Comment by mjoneill** [comment]
Followup re: CMS Training

In discussion with Patrick, it sounds like initial training audience should be the folks making decisions and working on building the initial site.  Future trainings can cast wider and wider nets.  

Based on where we our now in our process and our journey, this would include:

- Some mix of folks on the web dev team
- TM W
- Scott F (optional)

**Comment by mjoneill** [comment]
Followup re: our current building pages

Currently most of our maps.uiowa.edu website traffic is around buildings.  It suggests that peope are searching for a specific building, then going to the building page (presumably to find out how to get there, where it is, etc....  Example building page: https://maps.uiowa.edu/mlh

Concept3d equivalent of these are what they call "Static Maps" (pages).  We'll train on these + they are going to share an example or two in the next day or so

**Comment by joewhitsitt** [comment]
Categories from https://github.com/uiowa/uiowa/issues/4024 will need to be manually added to buildings in the final csv. A building could have multiple categories

**Comment by joewhitsitt** [comment]
> Currently most of our maps.uiowa.edu website traffic is around buildings. It suggests that peope are searching for a specific building, then going to the building page (presumably to find out how to get there, where it is, etc.... Example building page: https://maps.uiowa.edu/mlh
> 
> Concept3d equivalent of these are what they call "Static Maps" (pages). We'll train on these + they are going to share an example or two in the next day or so

From what I saw, it doesn't look like it provides building pages but they do provide a map widget to place on a building page. This is good news for sitenow_map_panes but it sounds like we will be on our own for hosting/maintaining building pages going forward.

Example: 
https://www.wpi.edu/about/locations/alumni-stadium

**Comment by joewhitsitt** [comment]
Added potential other data to the IS above (ADA, computer labs, study spaces)

**Comment by joewhitsitt** [comment]
A couple notes/findings from the meeting with Concept3D.

- Their bulk upload functionality has changed (easier), the docs on their website haven't be updated yet. After initial import, this can be used for other data but can't be used as a way to update existing.
- The reference (BuildingID) column in the spreadsheet is the unique identifier so we don't have to rely on BuildingCommonName in the future for synced data. Fun fact: BuildingID starts with the building number and the building abbreviation so that is something we could leverage for data outside ArcGIS.
- "Building pages" don't exist in Concept3D. They have share links that zoom to and bring up a building point. They don't have a redirection service so if we give them the entire maps.uiowa.edu domain, we will have to update links and integrations to point to the share points. It was recommended that we have external building pages like https://www.wpi.edu/about/locations/george-c-gordon-library if we need to have them.
- lat/long points can be shifted if not part of a sync.
- https://www.colorado.edu/map/?id=336 was provided as an example of how to organize data/categories. "Rooms" was an example of external data being pulled in that is separate from the building points.
<img width="1082" alt="Screen Shot 2021-10-01 at 12 41 03 PM" src="https://user-images.githubusercontent.com/4663676/135664073-991ea757-3431-430a-b3b7-4b1af36e38b0.png">

**Comment by richardbporter** [comment]
>"Building pages" don't exist in Concept3D. They have share links that zoom to and bring up a building point. They don't have a redirection service so if we give them the entire maps.uiowa.edu domain, we will have to update links and integrations to point to the share points. It was recommended that we have external building pages like https://www.wpi.edu/about/locations/george-c-gordon-library if we need to have them.

Maybe https://www.facilities.uiowa.edu/buildings could work for that. I know that data is dynamically pulled and displayed from FM DB.

**Comment by joewhitsitt** [comment]
>Maybe https://www.facilities.uiowa.edu/buildings could work for that.

I think I recall a previous concern over sending the wrong traffic there. Prospective students/visitors all of a sudden find themselves amongst building coordinator information and energy consumption data.

**Comment by joewhitsitt** [comment]
Capturing thoughts from multiple emails:

Jay clarified that while there is accessibility data available (e.g. https://maps.facilities.uiowa.edu/accessibility/), it would be premature to say it could just be wired up to Concept3D.

Patrick mentioned in an early email if TM had a comprehensive list of all the ADA routes through campus. That and the entrances to buildings would help them get started with the way finding functionality.

To me, the next step sounds like finding out what format those features need to be (get an example from Patrick) and then have a meeting with Facilities to see if we can get that information without too much fuss. We could also talk about the building pages.

With the features that Jay described, a decision should be made which of those features we would like included and then go about seeing if we can get that data (preferably synced) to Concept3D.

**Comment by mjoneill** [comment]
OK.  Thanks for sharing all this.  Thinking through the comments, it sounds like these are next steps: 
1- we need to have a conversation with Jay or site stakeholder to learn if there are concerns with having the facilities building pages as the canonical source for building information. 
2- Ask Patrick for an example/template of ADA routes and entrances
3- Future conversation with Jay once we get the examples/templates from Patrick to see what we can do with data import functionality

Missing anything?

**Comment by joewhitsitt** [comment]
- Got buy-in to move forward with facilities building pages serving as the canonical source.
  - Put together a list of redirects from maps.uiowa.edu, consider other in-site redirects to help non-building number queries.
  - Account for "explore" and "things here" info that would be lost during redirect period.
  - See if "explore" and "things here" info can be maintained and pulled in along side the rest of the data that makes up the facilities pages.
  - Investigate a workflow for building page updates (webform to facilities?) since these are not CMS driven.

**Comment by joewhitsitt** [comment]
@mjoneill, Jay says that while there is entrance data, it is not tied to the buildings (BuildingID) and there is no designation of a main/primary entrance. This data could start to be captured, but that we probably don't have the right data for what is needed right now for way finding.

**Comment by mjoneill** [comment]
New related issue @ #4374

**Comment by joewhitsitt** [comment]
Added a note to lower TTL for moving the domain and to clean up the CMS representation

**Comment by joewhitsitt** [comment]
Capturing some contrast issues related to link color:

<img width="168" alt="Screen Shot 2021-11-09 at 5 03 15 PM" src="https://user-images.githubusercontent.com/4663676/141019600-9afeeb4d-15bd-429c-9a55-11ab5e3a24b2.png">
<img width="504" alt="Screen Shot 2021-11-09 at 5 04 22 PM" src="https://user-images.githubusercontent.com/4663676/141019604-285c635a-8b8d-4956-800f-d7aa8c27636a.png">


UPDATE: changed to #00558c, the brand's primary link color.
<img width="128" alt="Screen Shot 2021-11-10 at 12 06 57 PM" src="https://user-images.githubusercontent.com/4663676/141168869-3b813246-4a20-4d58-8956-991cea5ad390.png">
<img width="293" alt="Screen Shot 2021-11-10 at 12 06 43 PM" src="https://user-images.githubusercontent.com/4663676/141168874-be00eb3f-e12b-45c5-af54-3ad738275c6f.png">

**Comment by mjoneill** [comment]
Thanks for this investment, @joewhitsitt.

Based on this, it looks like the following can happen concurrently (the first two, anyways), and should get started:

- Build categories/front end experience (currently planned)
- Audit building information #4351
- Ask Facilities to invest in getting the info identified in 4351 to a consumable state (likely blocked by previous)

Let me know if I'm missing something (or missing a sequencing issue/dependency).

**Comment by richardbporter** [comment]
Combined update code references and sitenow_maps into one issue since they're the same thing: https://github.com/uiowa/uiowa/issues/4591

**Comment by briand44** [comment]
removed 175 walking tour as a task and closed that issue since it is no longer a requirement.

**Comment by e-marie-w** [comment]
Update Buildings Label information (needs to be done by Concept3d?)
- Macbridge Hall needs to be changed to Macbride Hall
- Any buildings we want to add a label for?
- - Law, Health Policy and Disability Center?

**Comment by joewhitsitt** [comment]
Macbride Hall uilding label has been updated:
<img width="353" alt="Screen Shot 2022-01-19 at 4 10 18 PM" src="https://user-images.githubusercontent.com/4663676/150222303-03fdcd17-e7e1-4e08-9e76-289818eadb07.png">

**Comment by joewhitsitt** [comment]
>Establish workflow with facilities to provide updates to building data

I _think_ this is done for now.

>Please go ahead and use [fm-concept3d@uiowa.edu](mailto:fm-concept3d@uiowa.edu) for any building content-related questions/issues. If there’s something GIS/data specific, [we can reach out to Jay directly].
