### ISSUE TITLE
Additional text content search in SiteNow Find Text

### ISSUE THREAD

**Issue by cory-skeers** [uiowa/uiowa#4268]
# Story

As a content editor I want to search all text and/or link fields so that I can easily scan my site for content or link references.

# Proposed solution

Update SiteNow Find Text module to check additional areas, including menu links, re-usable block content (footer contact info), and potentially other areas (Article source link may not be getting seen? Uncertain.)

Part of this may be extending the scope of the field search--we're currently limiting it to node, block_content, and paragraph:

```
    if (!in_array($entity_type_id, ['block_content', 'node', 'paragraph'])) {
      continue;
    }
```
Adding taxonomy to this list may be all that is needed, for instance.

Other areas, such as menu links, may require more work and/or additional approaches.

- [x] #4445
- [x] #4589
- [ ] Re-usable blocks
- [ ] Article source link(?)
- [ ] [SiteNow Articles and People header content text areas](https://github.com/uiowa/uiowa/issues/4268#issuecomment-946976763)
- [ ] Make any necessary updates to docs

**Comment by joewhitsitt** [comment]
SiteNow Articles and People header content text areas? Ignored view config stored in active db

/admin/config/sitenow/sitenow-people
/admin/config/sitenow/sitenow-articles

<img width="698" alt="Screen Shot 2021-10-19 at 1 14 20 PM" src="https://user-images.githubusercontent.com/4663676/137967456-160d5e11-ffa7-4836-809c-c89a17db8a59.png">

**Comment by briand44** [comment]
Scope this next slice to main menu links and any supporting documentation related to that.

**Comment by makurj** [comment]
I would like to pair on this.
