### ISSUE TITLE
Reorganize/Update SharePoint docs

### ISSUE THREAD

**Issue by dnkemper** [uiowa/uiowa#4270]
Our environment installation information is all over the place (https://wiki.uiowa.edu/pages/viewpage.action?pageId=276470718, https://wiki.uiowa.edu/display/drupaldev/Local+Development+Environment+-+DrupalVM, https://github.com/uiowa/uiowa. After the recent slack huddles, we should find a way to update and consolidate our information. Making it current and putting all info in one place to make it easier to troubleshoot in the future. 
```[tasklist]
### Tasks
- [ ] https://github.com/uiowa/uiowa/issues/7737
- [ ] https://github.com/uiowa/uiowa/issues/7806
- [x] Move any Drupal 7 ITS Docs to https://docs.prod.drupal.uiowa.edu?
- [ ] Signage OneNote Docs
- [ ] Any refactoring/reorganization of docs on https://docs.prod.drupal.uiowa.edu?
```

**Comment by joewhitsitt** [comment]
With the adoption of DDEV, our docs are really out of date for what we need them to do. @dnkemper is currently running into the headaches associated with this.

**Comment by joewhitsitt** [comment]
Took a stab this morning at getting the onboarding docs moved and updated. Added deprecated warnings on the others.

https://wiki.uiowa.edu/display/drupaldev/Developer+Onboarding

**Comment by joewhitsitt** [comment]
Additionally, the wiki is vpn only currently due to a security vulnerability. Maybe we should move and work with a clean slate of sorts.

We could create a private repo within https://git.uiowa.edu/its-web and use the wiki feature (after confirming the feature will stick around with the ITS wiki folks)

**Comment by joewhitsitt** [comment]
>Depending on how you use the wiki, other solutions (Office 365, SharePoint, Teams, etc.) may meet your needs, see [https://teach.uiowa.edu/wiki/alternatives](https://link.uiowa.edu/l/b0abe7b1-d5fa-4cde-9ac2-798b9339666a?m=6380d6d9-cc0f-4b10-993d-6adff686b5d5&c=d.OTLT-EIT&i=202210) for more information. Due to the price increases, users who choose to continue using the wiki may be asked to contribute to the overall license cost.

**Comment by joewhitsitt** [comment]
I am really used to using markdown for GH comments, readme files, etc., so I would hate to lose that.

Hot take but how about a git.uiowa.edu private repo of markdown files (single-sign-on (SSO)) or github.com (no SSO) with Obsidian/Foam.io support for local use?! 

For github.com, the team already has access but anyone else, there would be more barrier to view them. also note that github's wiki and pages features require public visibility.

GitLab.com allows private repo with private pages (static site gen), but the campus single sign-on doesn't support gitlab pages.

git.uiowa.edu has "wiki" but it is through confluence which i am sure will have the same cost issue.

I looked at OneNote yesterday and though I think it would be _fine_, I don't love it. No markdown support, horrible links, slow to access online or offline.

I am not sure where ITS is heading with their Internal Support Articles/Support articles content types for their v3 site, but we should keep that in mind. https://github.com/uiowa/uiowa/labels/its.uiowa.edu.

Finally, since this is internal documentation, it would probably be good that there are several ways to access it so that if services go down (Acquia, o365, etc.), there is a chance there is a recent offline version on someone's machine.

**Comment by joewhitsitt** [comment]
>Hot take but how about a git.uiowa.edu private repo of markdown files (single-sign-on (SSO)) or github.com (no SSO) with Obsidian/Foam.io support for local use?!

Worked with the wiki today, and I am leaning back towards a private repo on git.uiowa.edu or github.com. It is a lot easier to place code examples and is closer to our work. It looks like more than our team can see the wiki (security concern?) but if we needed to allow that, git.uiowa.edu with SSO would work better. If only a few others need to see it, we have previously worked with folks to give access collaborative access to the repo.

**Comment by joewhitsitt** [comment]
Change is coming to the Wiki service. https://teach.uiowa.edu/wiki/service-change

I think we should take advantage of OTLT's migration service even if it just becomes a read-only archived version of our internal docs.

**Comment by briand44** [comment]
Our Wiki docs have been migrated to SharePoint.

https://iowa.sharepoint.com/sites/Drupal-7-ITS-Docs/SitePages/Drupal%207%20ITS%20Docs.aspx
https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/Drupal%20Developer%20Documentation.aspx

So far, it has been complicated to add new pages, etc. so not sure this is the final resting place. Sounds like GitLab or OneNote are possible options.

**Comment by bspeare** [comment]
After trying to read https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/Acquia%20Cloud/Acquia%20Cloud.aspx, I would be in favor of moving our docs to https://github.com/uiowa/uiowa/issues/4270#issuecomment-1448495956 or anywhere else that has had a theme update since 2003.   The visual hierarchy, contrast, code formatting and spacing that the Wiki had are mostly lost in SharePoint.

**Comment by joewhitsitt** [comment]
Just to create more flip-flop uncertainty of our move here, ckeditor 5 in [10.1 has markdown auto formatting](https://www.drupal.org/node/3227354) making the sitenow docs behind authentication more interesting. folks would need to sync a copy down periodically though to ensure we can access them if hosting goes down etc. This way we would be eating our own dog food.

The ITS team used to have docs in a drupal site but moved to the wiki at some point. @briand44 might remember they reasoning.

**Comment by pyrello** [comment]
Maybe we can figure out a static site generator that runs periodically to create an offline version?

**Comment by joewhitsitt** [comment]
>Maybe we can figure out a static site generator that runs periodically to create an offline version?

Do you mean a sitenow site that generates a static copy? https://www.drupal.org/project/tome (i think there is another option out there)

**Comment by pyrello** [comment]
I think the problem we are going to run into with having an "offline" copy of our dev docs is keeping everyone's local copy in sync. With the wiki, we didn't have an offline copy, but we were at least depending on a different system than the one that we would be troubleshooting by using the wiki. It was still possible for both systems to be down, but that usually didn't happen. So, maybe what we are looking for is a way to generate a static dev docs site that is hosted on a different service than AC.

**Comment by joewhitsitt** [comment]
>Hot take but how about a git.uiowa.edu private repo of markdown files (single-sign-on (SSO)) or github.com (no SSO) with Obsidian/Foam.io support for local use?!

>For github.com, the team already has access but anyone else, there would be more barrier to view them. also note that github's wiki and pages features require public visibility.

>GitLab.com allows private repo with private pages (static site gen), but the campus single sign-on doesn't support gitlab pages.

during profdev i explored my git/obsidian idea and got a static site generated off it as well either for local use or if we find an authenticated way of hosting the site. https://iowaweb.slack.com/archives/C0406A9VB5L/p1696015433721389

**Comment by joewhitsitt** [comment]
If we consolidate signage docs as part of this, we will need to make sure the HelpDesk and others are aware that we moved them. This includes the Signage Support Decision Tree (linked within the OneNote Signage Docs)

This could be reason to not fully go behind individual access authentication as the HelpDesk needs access.

**Comment by joewhitsitt** [comment]
The fact that we may continue to share certain docs with other groups on campus led me to experiment a bit more with OneNote in our Teams directory. It should be fairly easy to copy over from those sharepoint backups, but I don't think you can link to an individual page within the notebook. We do that a lot. "Here are the Content type creation notes notes to look at as you are developing this new content type"

The other pros it has is that we can limit visibility to certain people/groups, supported by ITS, and has hawkid auth.

**Comment by briand44** [comment]
>The other pros... 

Signage docs are already in OneNote

**Comment by briand44** [comment]
> I don't think you can link to an individual page

https://iowa.sharepoint.com/sites/CSI-Drupal2/_layouts/15/Doc.aspx?sourcedoc={daaa6395-ba30-4645-9e96-eebb4881293b}&action=edit&wd=target%28Untitled%20Section.one%7C19a5edf7-81f1-4caa-8776-da8f655fd62d%2FInitial%20Steps%20to%20add%20someone%20to%20Drupal%20Signage%7Ce8f87f48-fa8b-46f0-9b56-5d6118e113e4%2F%29&wdorigin=NavigationUrl

Is this a link to an individual page?

**Comment by pyrello** [comment]
I was able to get this link via the share link: https://iowa.sharepoint.com/:o:/r/sites/CSI-Drupal2/Shared%20Documents/Signage/Signage%20Docs?d=wdaaa6395ba3046459e96eebb4881293b&csf=1&web=1&e=qBt1Ry

My guess is that this link will only be valid for a certain period of time as that seems to be how share links work in Microsoft 365 generally.

**Comment by joewhitsitt** [comment]
Ah. Should have looked a bit closer. I was expecting it in the upper right Share dropdown. 

<img width="331" alt="Screenshot 2023-10-11 at 1 37 05 PM" src="https://github.com/uiowa/uiowa/assets/4663676/49873604-8c3d-4c2a-ad17-8fa30f1d0cb3">

**Comment by pyrello** [comment]
It drives me a little nuts that OneNote doesn't have some internal linking suggestions in their Insert Link widget. Here are the instructions for linking to Notebooks/Sections/Pages: https://support.microsoft.com/en-gb/office/create-links-to-notebooks-sections-pages-and-paragraphs-in-onenote-for-windows-10-48dd0e82-623c-405d-b63a-df4eaf55c72a

**Comment by joewhitsitt** [comment]
With OneNote handling the ToC with the sidebar, we don't do a whole lot of cross-linking between pages, but yes, coming from Obsidian, it does seem like a big step backwards. The URL structure too just bugs me.

**Comment by joewhitsitt** [comment]
I must be on crazy pills because I reconsidered using SiteNow behind authentication for our docs/signage docs yesterday evening after battling with sharepoint docs and onenote. Could be another internal prod that never goes live, requiring hostmaster approval, ssl. docs.prod.drupal.uiowa.edu?

- Restricted to our group (hawkid auth), but we could give helpdesk access via AD. Non-technical access for Brian, Michael and Megan.
- Partial markdown auto formatting.
- Code blocks, inline code snippets. language specific syntax highlighting on render could be a nice feature enhancement.
- Paste from sharepoint is pretty good meaning only internal cross links will have to be corrected if they aren't already broken from the move.
- Cross-linking going forward.
- Friendly URLs.
- Eat our own dog food.
- 99.999% uptime as recently reported. Folks could sync down a copy periodically for emergency usage.
- Drush ULI access if campus auth is down.
- Topic collections add-on if we need more organization.

Looking through our current docs, we don't seem to have anything besides the Outages page that would be crucial info in an emergency.

**Comment by bspeare** [comment]
> I must be on crazy pills because I reconsidered using SiteNow

I like this idea, let's do it!

**Comment by briand44** [comment]
>Restricted to our group (hawkid auth), but we could give helpdesk access via AD. Non-technical access for Brian, Michael and Megan.

Need to think about UIHC MarCom access as well here.

**Comment by joewhitsitt** [comment]
Wonder if we can get this started a bit by provisioning the site this sprint so it is ready for content when this is pulled in. `docs.prod.drupal.uiowa.edu` aka docs.uiowa.edu (never go live, never needs approval, never needs SSL)

**Comment by joewhitsitt** [comment]
After mentioning this in stand-up, I requested the site through the form. 🤞

**Comment by briand44** [comment]
Grooming conversation... Site has been requested and provision started. We are wanting to slice this to focus on moving the SiteNow Drupal 9 portion (page and children) as they are now (without refactoring) of the Developer Documentation https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/SiteNow%20Drupal%209/SiteNow%20Drupal%209.aspx. This way we can learn what is takes to move so we can better scope future slices.

We should link that section from Sharepoint to the new docs.

Future slices would include rest of Drupal Developer Sharepoint docs, Possibly some of the Drupal 7 Sharepoint docs and Signage OneNote Docs.

**Comment by cory-skeers** [comment]
site is available: https://docs.prod.drupal.uiowa.edu/

**Comment by e-marie-w** [comment]
Two of the SiteNow Drupal 9 pages will need to have links updated after the rest of our documentation is migrated. Specifically https://docs.prod.drupal.uiowa.edu/sitenow-drupal-9/website-requests-sitenowuiowaedu links to the Development Workflow section and https://docs.prod.drupal.uiowa.edu/sitenow-drupal-9/domain-changes-within-sitenow links to a page under Miscellaneous.

**Comment by pyrello** [comment]
Since it came up in Slack, I would like to register my opinion that we should collect all docs relevant to our ongoing operations in the new docs site, regardless of where we might have chosen to put them before. It is not intuitive to look up 95% of the information about operation and maintenance of SiteNow websites on that site, but then to have to remember that we put one piece of information in a README file in a repo somewhere.

**Comment by e-marie-w** [comment]
> Two of the SiteNow Drupal 9 pages will need to have links updated after the rest of our documentation is migrated. Specifically https://docs.prod.drupal.uiowa.edu/sitenow-drupal-9/website-requests-sitenowuiowaedu links to the Development Workflow section and https://docs.prod.drupal.uiowa.edu/sitenow-drupal-9/domain-changes-within-sitenow links to a page under Miscellaneous.

I made these two updates. https://docs.prod.drupal.uiowa.edu/miscellaneous/developer-onboarding has one link to our d7 documentation that will need updating if/when we move those.

**Comment by e-marie-w** [comment]
For the Signage OneNote docs, the Info-setup, Healthcare Signage, and Feature Requests sections (along with any subpages) have been migrated. 

I created pages for How To's and Troubleshooting, but all the subpages still need to be migrated.

~~Additionally, there are two links on https://docs.prod.drupal.uiowa.edu/support/digital-signage/info-setup/initial-steps-add-someone-drupal-signage that will need to be updated once those pages exist on the new site.~~ This has been done.

Update: the Troubleshooting section's pages are now also migrated.

**Comment by joewhitsitt** [comment]
@e-marie-w you ran with this earlier on. would you say this is now done/good enough? i have a feeling the myweb stuff might still be around but we shouldn't invest in moving d7 stuff.

**Comment by e-marie-w** [comment]
> [@e-marie-w](https://github.com/e-marie-w) you ran with this earlier on. would you say this is now done/good enough? i have a feeling the myweb stuff might still be around but we shouldn't invest in moving d7 stuff.

Yes, I never finished migrating all the Signage pages but since we're building a new system it no longer matters. I think we can close it.

**Comment by joewhitsitt** [comment]
Thanks for all of the hard work!

Hopefully myweb and d7 stuff can just be removed and not moved over. 🤞
