### ISSUE TITLE
Hours Block Enhancements

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#4570]
- [ ] Handle multiple resources in the same block
- [ ] Style options (e.g. background color) using ListBlock type implementation
- [ ] Add block config to allow displaying event categories as badges (cool gray?)
- [ ] Add (module or block?) configuration to color-code categories, e.g. Open -> Green, Closed -> Orange
- [ ] Add structured data available to google/crawlers/bots/ai

**Comment by joewhitsitt** [comment]
We would need to know what styles they want. Background color if implemented properly, provides padding. It would split the layout builder styles config to add certain styles to the block. Then getLayoutBuilderStyles() needs to be used similar to ListBlock to get the form data and pass it through to the block config.

As mentioned here https://github.com/uiowa/uiowa/pull/4549#issuecomment-993875860, the multiple resource solution is limited by the assumption that no data returned = closed. Either we would have to start leveraging categories or the endpoint needs to return more information.

**Comment by bspeare** [comment]
Do we need to add the background colors?  It seems like it might be useful to not to have to add those options available in every listblock.

**Comment by joewhitsitt** [comment]
This hours block is not a list block. This is what they are running into. I gave them a workaround, but this is their ideal.
<img width="472" alt="Screen Shot 2021-12-15 at 1 02 30 PM" src="https://user-images.githubusercontent.com/4663676/146248852-29c1fb62-c42e-4795-b1a4-2af8a365ba71.png">

**Comment by joewhitsitt** [comment]
I just realized that not many blocks have background color style options so instead of my original thought that this should have those same options is less founded.

**Comment by joewhitsitt** [comment]
Re closures:

I think we can still default to closed if no event but then adjust the card to use the categories provided (Hours vs Closure) here https://hours.iowa.uiowa.edu/api/Hours/FusionRecServ/RES-REC-CR-CWALL?start=04/07/2023&end=04/07/2023 to mark these as closed.

**Comment by joewhitsitt** [comment]
RecServ added a few "Closure" examples to their calendar where we can target the category to show a closed label instead of a open label. Since this was built for more than RecServ in mind, we would need to document and get agreement on this category for others to use properly.

https://hours.iowa.uiowa.edu/api/Hours/FusionRecServ/res-rec-cr-cpooln?start=04/19/2023&end=04/19/2023

<details>
<summary>json output</summary>

```json
// 20230413163156
// https://hours.iowa.uiowa.edu/api/Hours/FusionRecServ/res-rec-cr-cpooln?start=04/19/2023&end=04/19/2023

{
  "20230419": [
    {
      "$id": "2",
      "id": null,
      "summary": "CRWC Competition Pool: Lap Swim ",
      "description": "",
      "textDescription": "",
      "location": " CRWC Competition Pool",
      "organizerEmail": null,
      "organizerName": null,
      "start": "2023-04-19T10:30:00Z",
      "startHour": "05:30:00",
      "end": "2023-04-19T13:00:00Z",
      "endHour": "08:00:00",
      "isAllDay": false,
      "categories": [
        "Hours",
        "Open Recreation"
      ],
      "iso8601Start": "2023-04-19T05:30:00",
      "iso8601End": "2023-04-19T08:00:00",
      "lastUpdated": "2023-04-13T21:30:07Z",
      "isPrivate": false
    },
    {
      "$id": "3",
      "id": null,
      "summary": "CRWC Competition Pool Closed",
      "description": "",
      "textDescription": "",
      "location": "CRWC Competition Pool",
      "organizerEmail": null,
      "organizerName": null,
      "start": "2023-04-19T13:00:00Z",
      "startHour": "08:00:00",
      "end": "2023-04-19T15:30:00Z",
      "endHour": "10:30:00",
      "isAllDay": false,
      "categories": [
        "Closure",
        "Open Recreation"
      ],
      "iso8601Start": "2023-04-19T08:00:00",
      "iso8601End": "2023-04-19T10:30:00",
      "lastUpdated": "2023-04-13T21:30:07Z",
      "isPrivate": false
    },
    {
      "$id": "4",
      "id": null,
      "summary": "CRWC Competition Pool: Lap Swim ",
      "description": "",
      "textDescription": "",
      "location": " CRWC Competition Pool",
      "organizerEmail": null,
      "organizerName": null,
      "start": "2023-04-19T15:30:00Z",
      "startHour": "10:30:00",
      "end": "2023-04-19T18:30:00Z",
      "endHour": "13:30:00",
      "isAllDay": false,
      "categories": [
        "Hours",
        "Open Recreation"
      ],
      "iso8601Start": "2023-04-19T10:30:00",
      "iso8601End": "2023-04-19T13:30:00",
      "lastUpdated": "2023-04-13T21:30:07Z",
      "isPrivate": false
    },
    {
      "$id": "5",
      "id": null,
      "summary": "CRWC Competition Pool Closed",
      "description": "",
      "textDescription": "",
      "location": "CRWC Competition Pool",
      "organizerEmail": null,
      "organizerName": null,
      "start": "2023-04-19T18:30:00Z",
      "startHour": "13:30:00",
      "end": "2023-04-19T21:30:00Z",
      "endHour": "16:30:00",
      "isAllDay": false,
      "categories": [
        "Closure",
        "Open Recreation"
      ],
      "iso8601Start": "2023-04-19T13:30:00",
      "iso8601End": "2023-04-19T16:30:00",
      "lastUpdated": "2023-04-13T21:30:07Z",
      "isPrivate": false
    },
    {
      "$id": "6",
      "id": null,
      "summary": "CRWC Competition Pool: Lap Swim ",
      "description": "",
      "textDescription": "",
      "location": " CRWC Competition Pool",
      "organizerEmail": null,
      "organizerName": null,
      "start": "2023-04-19T21:30:00Z",
      "startHour": "16:30:00",
      "end": "2023-04-20T03:00:00Z",
      "endHour": "22:00:00",
      "isAllDay": false,
      "categories": [
        "Hours",
        "Open Recreation"
      ],
      "iso8601Start": "2023-04-19T16:30:00",
      "iso8601End": "2023-04-19T22:00:00",
      "lastUpdated": "2023-04-13T21:30:07Z",
      "isPrivate": false
    }
  ],
  "$id": "1",
  "resourceAlias": "res-rec-cr-cpooln"
}// 20230413163156
// https://hours.iowa.uiowa.edu/api/Hours/FusionRecServ/res-rec-cr-cpooln?start=04/19/2023&end=04/19/2023

{
  "20230419": [
    {
      "$id": "2",
      "id": null,
      "summary": "CRWC Competition Pool: Lap Swim ",
      "description": "",
      "textDescription": "",
      "location": " CRWC Competition Pool",
      "organizerEmail": null,
      "organizerName": null,
      "start": "2023-04-19T10:30:00Z",
      "startHour": "05:30:00",
      "end": "2023-04-19T13:00:00Z",
      "endHour": "08:00:00",
      "isAllDay": false,
      "categories": [
        "Hours",
        "Open Recreation"
      ],
      "iso8601Start": "2023-04-19T05:30:00",
      "iso8601End": "2023-04-19T08:00:00",
      "lastUpdated": "2023-04-13T21:30:07Z",
      "isPrivate": false
    },
    {
      "$id": "3",
      "id": null,
      "summary": "CRWC Competition Pool Closed",
      "description": "",
      "textDescription": "",
      "location": "CRWC Competition Pool",
      "organizerEmail": null,
      "organizerName": null,
      "start": "2023-04-19T13:00:00Z",
      "startHour": "08:00:00",
      "end": "2023-04-19T15:30:00Z",
      "endHour": "10:30:00",
      "isAllDay": false,
      "categories": [
        "Closure",
        "Open Recreation"
      ],
      "iso8601Start": "2023-04-19T08:00:00",
      "iso8601End": "2023-04-19T10:30:00",
      "lastUpdated": "2023-04-13T21:30:07Z",
      "isPrivate": false
    },
    {
      "$id": "4",
      "id": null,
      "summary": "CRWC Competition Pool: Lap Swim ",
      "description": "",
      "textDescription": "",
      "location": " CRWC Competition Pool",
      "organizerEmail": null,
      "organizerName": null,
      "start": "2023-04-19T15:30:00Z",
      "startHour": "10:30:00",
      "end": "2023-04-19T18:30:00Z",
      "endHour": "13:30:00",
      "isAllDay": false,
      "categories": [
        "Hours",
        "Open Recreation"
      ],
      "iso8601Start": "2023-04-19T10:30:00",
      "iso8601End": "2023-04-19T13:30:00",
      "lastUpdated": "2023-04-13T21:30:07Z",
      "isPrivate": false
    },
    {
      "$id": "5",
      "id": null,
      "summary": "CRWC Competition Pool Closed",
      "description": "",
      "textDescription": "",
      "location": "CRWC Competition Pool",
      "organizerEmail": null,
      "organizerName": null,
      "start": "2023-04-19T18:30:00Z",
      "startHour": "13:30:00",
      "end": "2023-04-19T21:30:00Z",
      "endHour": "16:30:00",
      "isAllDay": false,
      "categories": [
        "Closure",
        "Open Recreation"
      ],
      "iso8601Start": "2023-04-19T13:30:00",
      "iso8601End": "2023-04-19T16:30:00",
      "lastUpdated": "2023-04-13T21:30:07Z",
      "isPrivate": false
    },
    {
      "$id": "6",
      "id": null,
      "summary": "CRWC Competition Pool: Lap Swim ",
      "description": "",
      "textDescription": "",
      "location": " CRWC Competition Pool",
      "organizerEmail": null,
      "organizerName": null,
      "start": "2023-04-19T21:30:00Z",
      "startHour": "16:30:00",
      "end": "2023-04-20T03:00:00Z",
      "endHour": "22:00:00",
      "isAllDay": false,
      "categories": [
        "Hours",
        "Open Recreation"
      ],
      "iso8601Start": "2023-04-19T16:30:00",
      "iso8601End": "2023-04-19T22:00:00",
      "lastUpdated": "2023-04-13T21:30:07Z",
      "isPrivate": false
    }
  ],
  "$id": "1",
  "resourceAlias": "res-rec-cr-cpooln"
}// 20230413163156
// https://hours.iowa.uiowa.edu/api/Hours/FusionRecServ/res-rec-cr-cpooln?start=04/19/2023&end=04/19/2023

{
  "20230419": [
    {
      "$id": "2",
      "id": null,
      "summary": "CRWC Competition Pool: Lap Swim ",
      "description": "",
      "textDescription": "",
      "location": " CRWC Competition Pool",
      "organizerEmail": null,
      "organizerName": null,
      "start": "2023-04-19T10:30:00Z",
      "startHour": "05:30:00",
      "end": "2023-04-19T13:00:00Z",
      "endHour": "08:00:00",
      "isAllDay": false,
      "categories": [
        "Hours",
        "Open Recreation"
      ],
      "iso8601Start": "2023-04-19T05:30:00",
      "iso8601End": "2023-04-19T08:00:00",
      "lastUpdated": "2023-04-13T21:30:07Z",
      "isPrivate": false
    },
    {
      "$id": "3",
      "id": null,
      "summary": "CRWC Competition Pool Closed",
      "description": "",
      "textDescription": "",
      "location": "CRWC Competition Pool",
      "organizerEmail": null,
      "organizerName": null,
      "start": "2023-04-19T13:00:00Z",
      "startHour": "08:00:00",
      "end": "2023-04-19T15:30:00Z",
      "endHour": "10:30:00",
      "isAllDay": false,
      "categories": [
        "Closure",
        "Open Recreation"
      ],
      "iso8601Start": "2023-04-19T08:00:00",
      "iso8601End": "2023-04-19T10:30:00",
      "lastUpdated": "2023-04-13T21:30:07Z",
      "isPrivate": false
    },
    {
      "$id": "4",
      "id": null,
      "summary": "CRWC Competition Pool: Lap Swim ",
      "description": "",
      "textDescription": "",
      "location": " CRWC Competition Pool",
      "organizerEmail": null,
      "organizerName": null,
      "start": "2023-04-19T15:30:00Z",
      "startHour": "10:30:00",
      "end": "2023-04-19T18:30:00Z",
      "endHour": "13:30:00",
      "isAllDay": false,
      "categories": [
        "Hours",
        "Open Recreation"
      ],
      "iso8601Start": "2023-04-19T10:30:00",
      "iso8601End": "2023-04-19T13:30:00",
      "lastUpdated": "2023-04-13T21:30:07Z",
      "isPrivate": false
    },
    {
      "$id": "5",
      "id": null,
      "summary": "CRWC Competition Pool Closed",
      "description": "",
      "textDescription": "",
      "location": "CRWC Competition Pool",
      "organizerEmail": null,
      "organizerName": null,
      "start": "2023-04-19T18:30:00Z",
      "startHour": "13:30:00",
      "end": "2023-04-19T21:30:00Z",
      "endHour": "16:30:00",
      "isAllDay": false,
      "categories": [
        "Closure",
        "Open Recreation"
      ],
      "iso8601Start": "2023-04-19T13:30:00",
      "iso8601End": "2023-04-19T16:30:00",
      "lastUpdated": "2023-04-13T21:30:07Z",
      "isPrivate": false
    },
    {
      "$id": "6",
      "id": null,
      "summary": "CRWC Competition Pool: Lap Swim ",
      "description": "",
      "textDescription": "",
      "location": " CRWC Competition Pool",
      "organizerEmail": null,
      "organizerName": null,
      "start": "2023-04-19T21:30:00Z",
      "startHour": "16:30:00",
      "end": "2023-04-20T03:00:00Z",
      "endHour": "22:00:00",
      "isAllDay": false,
      "categories": [
        "Hours",
        "Open Recreation"
      ],
      "iso8601Start": "2023-04-19T16:30:00",
      "iso8601End": "2023-04-19T22:00:00",
      "lastUpdated": "2023-04-13T21:30:07Z",
      "isPrivate": false
    }
  ],
  "$id": "1",
  "resourceAlias": "res-rec-cr-cpooln"
}
```
</details>

**Comment by joewhitsitt** [comment]
Added a request from dining.uiowa.edu to make the hours of operation more consumable by Google and AI. Right now, the google place for Burge Marketplace is not accurate.

https://developers.google.com/search/docs/appearance/structured-data/local-business

I suggested they attempt to make claim to the place via a google business account to have more control.
