### ISSUE TITLE
Card block titles overflow below the container breakpoint

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#4678]
# Story

As a SiteNow user, I can use cards with long titles in 3 and 4 column grids without the titles overflowing the cards. 

As a follow-up to https://github.com/uiowa/uiowa/pull/4674, we identified the need to adjust the grid layout gutter below the container breakpoint to allow more space for the components on smaller devices and avoid orphan column breaks often seen with the three column grid. 

# Proposed solution

```[tasklist]
### Tasks
- [ ] Implement Container Queries in `uids` - https://github.com/uiowa/uids/issues/888
- [ ] Review comments on https://github.com/uiowa/uiowa/issues/6386
- [ ] Review work in progress at https://github.com/uiowa/uiowa/pull/6412
```

**Comment by bspeare** [comment]
Chatted with @pyrello about this and we discussed a few options:
- Investigate implementing CSS hyphens https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens with noting https://github.com/uiowa/uiowa/issues/5946#issuecomment-1315847858. 
- Set up a CSS rule for cards in four column layouts where we force them into a "stacked" orientation if they are set to align right or left within a column.   This would be something we could put in place before we implement container queries. 
- We could have the four column layout adjust to two-columns at a smaller breakpoint or anything below 1100 pixels, for example.

**Comment by pyrello** [comment]
Eventually we should invest in container queries to improve this.

**Comment by bspeare** [comment]
If we are going to fix this bug, maybe we should implement container queries as outlined in https://github.com/uiowa/uiowa/issues/6386?

**Comment by bspeare** [comment]
I updated this with a task list linking to two separate issues describing the work necessary for this bug to be fixed.

**Comment by bspeare** [comment]
Here are some UX improvements that we might want to make:

## Card block

1. If `Media position` `right` or `left` is selected add an inline message `Note: left or right media positions will adjust to the stacked media position when the browser is at smaller widths`.  This option would require container queries. 
2.  If a card is placed within a 4 column layout, or a 3 column 25% width column, remove the `Media position` option and set to `stacked` as a default. 

## Card list blocks

1. If `Display list as` `Grid` is selected, remove the `Media position` option and set to `stacked` like in the current Featured Content block. 

## Container queries

1. Implement container queries approach as well in UIDS for cards.

**Comment by briand44** [comment]
Grooming conversation... implement container queries to force cards aligned left or right to stack. Some ground work already laid out from Alan's work last year. Work would need to start in uids and then in existing PR. Could be a decent amount of testing here. May need to rework button position at bottom.

Our grid system in uids base isn't exactly same as in uids, is that going to complicate things? The work Alan started should help with this https://github.com/uiowa/uids/blob/4.x/src/scss/components/_inline.scss#L73

Discussed making the changes to both uids and uids base in this slice rather than splitting them out.

Not anticipating update hooks with this work but may need to communicate changes.

**Comment by briand44** [comment]
Adding blocked label as Ben mentioned #7379 needs to be finished before starting this work.

**Comment by pyrello** [comment]
I don't think this should actually be closed by the UIDS issue since we still need to update the `uiowa` project with these changes.
