### ISSUE TITLE
Epic: Add ability to publish collection of writing periodically

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#4724]
# Epic

As a site owner I want publish a collection of writing or stories periodically so that I can publish a digital magazine or newsletter.

# Motivation

91st Meridian is a digital publication, which is published a handful of times each year: https://iwp.uiowa.edu/91st/index.html. Each issue provides a self-contained experience to navigate around inside it.

Another similar example: https://english.uiowa.edu/reading-matters/volume-27-issue-4

# Tasks

- [ ] Compile a list of known sites that need this functionality.
- [ ] Compare existing sites to see where functionality overlaps to try to determine a core feature set.
- [ ] Determine whether the Writing content type and Writing Collection vocabulary being introduced in #4643 could be used as the basis for this feature. If so, this could be turned into a feature and have the translation functionality stripped out of it, which instead could be add just via the WhitmanWeb site split.

**Comment by joewhitsitt** [comment]
Just chiming in with more possible examples. Not sure how related they are but Education had a "magazine" which consisted of several articles published at the same time (https://education.uiowa.edu/about/news-and-media/alumni-magazine-2020). teach.its a similar but more structured approach that ends in an organized archive and a constant contact email type thing: https://teach.its.uiowa.edu/news

**Comment by pyrello** [comment]
Here are a few examples that have come up:

- https://iowareview.org/
- https://ilr.law.uiowa.edu/
- https://jcl.law.uiowa.edu/
- https://tlcp.law.uiowa.edu/articles
- https://jgrj.law.uiowa.edu/

And an outside example as well:
- https://harvardlawreview.org/

**Comment by quamsta** [comment]
We manage a few journals that are organized in a couple of different ways:

- [Exchanges Literary Journal of Translation](https://exchanges.uiowa.edu), organized like:
```
- Issue (contains an issue title, eg., "Spring 2022," but no explicit issue number.)
   - Article
   - Article
     [...]
```
- [Iowa Law Review](https://ilr.law.uiowa.edu), [The Journal of Gender, Race & Justice](https://jgrj.law.uiowa.edu), organized like:
```
- Issue (contains an issue number property, and a volume number property, template is organized accordingly)
  - Article
  - Article
  [...]
```
- [Journal of Corporation Law](https://jcl.law.uiowa.edu), organized similarly to ILR and JGRJ above except done completely in Layout Builder

**Comment by pyrello** [comment]
@quamsta It seems like the first example could use the same system as the second example, but just omit the issue number and volume number?

**Comment by quamsta** [comment]
> @quamsta It seems like the first example could use the same system as the second example, but just omit the issue number and volume number?

Yeah, I forgot to mention that they are fairly close in structure, but are presented differently in their respective issue archives:

Exchanges Archives (simply lists the issues):
https://exchanges.uiowa.edu/issues/

ILR Archives (organizes automatically by volume number, then by issue):
https://ilr.law.uiowa.edu/print/

**Comment by pyrello** [comment]
This might get in the way of my ambitions to use a vocabulary as the container for a collection of writing: https://www.drupal.org/project/drupal/issues/3047110
