### ISSUE TITLE
Academic calendar list

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4937]
As a Registrar site owner, I would like the ability to display academic dates in a list format for better usability and accessibility.

# Additional Info

Epic https://github.com/uiowa/uiowa/issues/7257

They would like to have both #4936 and list display but also brought up accessibility and want to make sure this is an accessible solution. Joe asked if we could do away with the calendar display and they sounded like they would like to keep it if possible. Mentioned that some peer institutions only have list view. 

D7 implementation is using Full Calendar https://registrar.uiowa.edu/academic-calendar

Currently we are showing the current session + 4 sessions. Going forward they would like to display the current session + 5 sessions.

category filter - default to "All Student Dates" - Josh thought we are currently suppressing some date categories and wants to start with the same categories they have now.

Need ability to show subsessions

Need to look at the datelookup "Is Web Display" = Yes and "is reviewed" = yes - may be "is print" in MAUI
display date, web description, session/subsession

when session ends auto updates to show current session + 5 - Registrar was going to chat some more about this.

# Proposed Solution
```[tasklist]
### Tasks
- [x] Create a `registrar_core` module for the Registrar site
- [ ] Create a site split for the Registrar site. Include the custom module and all custom config defined in the following steps
- [ ] Define an Academic Date content type with at least: title, unique ID (to store the ID from the API), start date and end date (note that time is not necessary for these), and session
- [ ] Add a method to the `Drupal\uiowa_maui\MauiApi` class to fetch the required MAUI dataset
- [ ] Use our Importer Pattern (entity processor, entity item processor, and drush command) to create an import system to import the records returned by the new API method into the Academic Date content type
- [ ] Create a views block for displaying the content items for the current session + next 5 sessions. Row display can just be the teaser for each record
- [ ] Validate that we can get the same results from this approach as we get from the current academic calendar: https://registrar.uiowa.edu/academic-calendar
```

**Comment by richardbporter** [comment]
This checkbox was actually in reference to a custom content pane called academic_dates_list:
<img width="315" alt="image" src="https://user-images.githubusercontent.com/1068523/157758042-99e06f79-8d12-430b-9f39-ebd7ffc1fe2a.png">

The list view on https://registrar.uiowa.edu/academic-calendar is functionality provided by FullCalendar and would probably just be done in #4936.

I'm not sure who is using academic_dates_list in D7. I don't _think_ its in use on registrar but it might worth double checking that and possibly other sites.

Sorry for the confusion.

**Comment by briand44** [comment]
@richardbporter I think the academic dates list in D7 is being used for the homepage of registrar.uiowa.edu. That is no longer needed. I doubt others are using this if that is what it is so I am going to assume that this functionality you are referring to is not needed. I am going to keep this as it is in case we don't go with full calendar and need a separate solution for the list view. If it makes sense to tackle it along with #4936 that is fine.

**Comment by briand44** [comment]
Grooming conversation... We don't have any full calendar integration outside of views displays currently. We need to determine early on if we are going to import into Drupal or call API's and dynamically display? How often does the data need updated? Discussed trying to go the import route first to see if we run into any issues with that approach. Discussed that course deadlines seems a bit different than the academic calendar, five year calendar and dates by session so we can evaluate that at a later time. Probably need a unique identifier, title, date, session at a minimum as part of the content type to import into. Also include importing into content type. Include displaying list of dates for current session + 5.

It was mentioned that this data eventually ages out and that we would likely rabbit hole these entities at some point.

**Comment by briand44** [comment]
Josh thought updating the data once a day would be sufficient. In regards to storing the data there weren't any business rules that he could think of that would cause problems with us storing the data, his only concern was performance. He did mention that there have been conversations in the past around having the academic dates in the University Events system and that could happen to some degree at some point down the road. He thought it was odd/interesting that there could be individual pieces of content for all of these dates.

**Comment by pyrello** [comment]
On the current site, the academic calendar is provided by a Panels pane, which allows it to be configured to "Current session" or several "Current session + n sessions". In my mind, this is how I was imagining that the block would work. Whatever selection is made controls the parameters of the API request that is sent to get the data.

Thinking about this in the context of academic dates being imported into the site, if we wanted to make this configurable at some level yet still only have our content importer/processor maintain the current available set of dates on the site, we would need to have our API request pull all dates that could possibly be allowed to show. For example if the maximum configurable option is "current session + 5" then regardless of whether that option was chosen or not, we would need for our API call to get those results for the current session + 5 to ensure that all possible dates could be displayed. In this way the configuration logic gets decoupled from the API call logic, which is currently not the case.

Making this configurable is definitely not needed for this slice or possibly even for the registrar site. But the way that it was all built in D7 suggests that there may have been a desire at some point to have this pane/block be available to other sites to allow them to display a calendar and possibly have it set to parameters (e.g. current session + 2). I may be overthinking it but wanted to raise this as a point of consideration before we get too far into this work.

**Comment by joewhitsitt** [comment]
>He thought it was odd/interesting that there could be individual pieces of content for all of these dates.

This gave me some pause yesterday during planning. Could be a lot of dates especially if

>...we would need to have our API request pull all dates that could possibly be allowed to show

**Comment by pyrello** [comment]
> > He thought it was odd/interesting that there could be individual pieces of content for all of these dates.
> 
> This gave me some pause yesterday during planning. Could be a lot of dates especially if
> 
> > ...we would need to have our API request pull all dates that could possibly be allowed to show

To be clear, I'm not worried about this from a performance/resources standpoint. I doubt this would compare to the amount of time necessary for the Facilities building import.

**Comment by pyrello** [comment]
We didn't really discuss it during grooming, but I guess I'm assuming that we want to handle sessions similarly to commencement. As in having a vocabulary and a term reference field.

**Comment by pyrello** [comment]
> We didn't really discuss it during grooming, but I guess I'm assuming that we want to handle sessions similarly to commencement. As in having a vocabulary and a term reference field.

I guess for the purposes of proving the concept, I could just use a text field maybe.

**Comment by pyrello** [comment]
Some observations thus far:
- Just plugging in the [existing code](https://github.com/uiowa/uiowa/blob/1fa22dee737d44b49e9170cde2681054a11db962/docroot/modules/custom/uiowa_maui/src/MauiApi.php#L221-L254) to pull dates by session (which appears to be a pretty faithful reproduction of the D7 code), I'm getting results from 2023. I believe there is a web-based MAUI UI where you can return results for basic API endpoints, but I'm not finding it. I was going to use it try to validate the results I'm seeing.
- Full calendar view plugin out of the box doesn't have any clever mechanism for loading data sets per "page" (e.g. switching  months) and depends on having all the results loaded already. This is potentially problematic depending on how many results there actually are. I'm having trouble telling at the moment (see previous bullet point) but an initial import using the importer and following the logic of how the result set is constructed in the D7 calendar (+ hard-coding the + 5 sessions) got me almost 700 results. I tried loading all the results in a basic unformatted list view and got a 500 error. Regardless of whether the number ends up being less than that or not, if its in the hundreds of results, its probably going to be a problem to load them all at once.
- There are some strategies for potentially re-working the implementation so that full calendar is AJAX loading JSON results instead (which can be fed by a view). But at that point we are doing a custom implementation of the calendar and that is what we were trying to avoid by going the importer + views route.
  - https://fivejars.com/blog/all-you-need-know-about-fullcalendar-view-module
  - https://www.drupal.org/project/fullcalendar_view/issues/2960335 - TL;DR: Issue discussing how to work around the loading issues and several proposals and patches. However the maintainer has opted to stop allowing new features into the module and is module support to just maintenance. Several patches seem promising but then have multiple reports of X thing in views doesn't work correctly now. 
  - https://www.drupal.org/project/fullcalendar_block - The maintainer of the fullcalendar views module created a new module that allows feeding a views JSON output into a block configuration, but loses all the capabilities of a views block (e.g. exposed filters, sorting, etc.). This is his solution to the previous issue thread.
  - https://www.drupal.org/project/fullcalendar_dynamic - Another person took the initiative to create a module that is a forked version of the fullcalendar views module with one of the patches from the previous issue applied. I haven't looked into which patch or whether they were able to sort out any reported bugs for it.
- At this point I'm leaning towards this being a failed experiment and that we should instead do our own fullcalendar implementation with some type of route controller to handle processing the API request, caching, etc.

**Comment by joewhitsitt** [comment]
>I believe there is a web-based MAUI UI where you can return results for basic API endpoints, but I'm not finding it.

@pyrello is this whas you were looking for? https://api.maui.uiowa.edu/maui/pub/webservices/documentation.page

The session id for 2023 appears to be 94 (https://api.maui.uiowa.edu/maui/api/pub/registrar/sessions) so https://api.maui.uiowa.edu/maui/api/pub/registrar/session-dates?sessionId=94

>do our own fullcalendar implementation with some type of route controller to handle processing the API request, caching, etc.

Based on what you have presented and recent experience with large views, I think this makes sense to at least get them off D7.

**Comment by pyrello** [comment]
Based on the conversation at EoD, we are going to close this issue in favor of #7788, which will employ an alternative approach.
