### ISSUE TITLE
Five-year academic calendar

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4943]
As a Registrar site owner, I would like the ability to display the five-year calendar.

# Additional Info

Existing D7 implementation https://registrar.uiowa.edu/five-year-calendar.

API should have some sort of "Five Year Date" flag in MAUI (also should be "reviewed = true" and "printDate = true")

Dates should be grouped by academic year/session rather than by month.

Ability to filter by academic year https://github.com/uiowa/uiowa/issues/4943#issuecomment-2195448532. current academic year +/- 5.

Ability to show sub-sessions.

# Proposed Solution
```[tasklist]
### Tasks
- [ ] Add a new route in `registrar_core.routing.yml` that points to a new method in the controller we created for the Academic Calendar
- [ ] The new route method can share whatever logic sets the API call to return results where `reviewed = true` and `printDate = true` but also needs to add `fiveYearDate = true`
- [ ] Add a new JS file/library to encapsulate a new Drupal behavior that can be applied for the 5-year calendar
- [ ] Build the JS logic to fetch results from the controller route and display the events grouped by year and then by session
- [ ] Figure out how to toggle showing sub-sessions
```

**Comment by briand44** [comment]
From Josh, related to the year filter.

>What we're thinking is those drop downs should be academic years. On the current site it looks like it's defaulting to the current academic year which is 2023-24 starting with fall '23 and ending with summer of '24.
> 
> So I think on the new site we would like those drop downs (change "start year" to "academic year") to read 2023-24, 2024-25, etc going forward and back five academic years. And then if you selected an academic year it would take you to a section with a header of "Academic Year 2023-24" and that section would contain Fall '23, Winter '23, Spring '24, Summer '24 and all Summer '24 subsessions. (for example).

**Comment by briand44** [comment]
Grooming conversation... It was mentioned possibly moving away from drop down filter to navigate between academic years. Brian to check with Josh on if they still want to show five years worth of dates from a specific academic year chosen. The calendar should default to the current academic year and auto update once we are in a new academic year. Was brought up that this feels a little different that the calendar list and dates by session and we should probably address this separately. Could use same controller for accessing data. We may need a separate route since we need to pull only dates where fiveYearDate = true.

**Comment by briand44** [comment]
Got some feedback from Josh on displaying one academic years dates at a time vs displaying 5 years worth of dates:

> Great question! So my kneejerk reaction is that we need to display 5 years at a time, but think my brain keeps defaulting to trying to recreate that word doc that isn't really used the same way anymore.
> 
> Let's try with just displaying one academic year at a time? And then have some easy way of selecting a new academic year to view? And then maybe it outputs something similar to what our current skip links are doing?
> 
> https://registrar.uiowa.edu/five-year-calendar#uiowa-maui-five-2025
> 
> So say you selected a future or past session it would go to a new page with a unique url like /five-year-calendar#2025-26? And then just show the dates associated with that session?
> 
> Seems like that might reduce some scrolling? Does that make any sense?
