### ISSUE TITLE
University Classrooms and Specialty Spaces

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#4966]
# Story

As Classrooms and Registrar site owners, I would like to display University classrooms and specialty spaces on the Classrooms website so users can find detailed information about these rooms.

# Additional Info
Data is managed in Adastra and fed into MAUI. MAUI is our source to retrieve data.
The logic to pull classroom information is slightly different that the logic to pull ucr/sps space information.
Data will be retrieved on a regular scheduled interval (still need to determine this interval).
In addition to pulling this information from MAUI and displaying it, there is some additional data that is not available in the source and needs to be manually created/edited.
Display of classrooms will likely be different than the display of ucr/sps.
There are currently csv exports of the ucr/sps info, one public and one administrative, administrative contains additional internal info. (need to verify this is still needed)
Lots of filters/search capabilities
https://registrar.uiowa.edu/ucr-sps
https://classrooms.uiowa.edu/

# Proposed solution

- [x] #5520
- [x] #5814
- [x] #5895 
- [x] #5771
- [x] #5769
  - [x] https://github.com/uiowa/uiowa/issues/6033
  - [x] https://github.com/uiowa/uiowa/issues/6032
  - [x] https://github.com/uiowa/uiowa/issues/6041
- [x] #6044
- [x] #6045
- [x] #6098
- [x] #6131
- [x] #6179
- [x] #6180
- [x] #6395
- [x] #6436
- [x] #6434 
- [x] #6435 
- [x] https://github.com/uiowa/uiowa/issues/6138
- [x] #6437
- [x] Room schedule pager - https://classrooms.prod.drupal.uiowa.edu/ucc-1100
- [x] #6477 
- [x] https://github.com/uiowa/uiowa/issues/6488
- [x] https://github.com/uiowa/uiowa/issues/6560
- [x] #6592
- [x] #6623
- [x] #6467
- Nice to have
- [ ] #6557
- [ ] List view switcher for classroom search page - default to grid
- [ ] Homepage grid issue https://github.com/uiowa/uids/issues/721#issuecomment-1544478236
- [ ] Excel export of rooms - they are checking on if there are existing solutions already

**Comment by briand44** [comment]
We need to verify what logic, if any, is correct moving forward. The existing D7 classroom site is consuming data using the logic in https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/blob/main/app/Http/Controllers/ClassroomsController.php.

The logic for the Registrar site is in /docroot/sites/registrar.uiowa.edu/modules/custom/registrar_feeds/registrar_feeds.module.

**Comment by richardbporter** [comment]
> We need to verify what logic, if any, is correct moving forward. The existing D7 classroom site is consuming data using the logic in https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/blob/main/app/Http/Controllers/ClassroomsController.php.
> 
> The logic for the Registrar site is in /docroot/sites/registrar.uiowa.edu/modules/custom/registrar_feeds/registrar_feeds.module.

It sounds like both sets of logic are correct, just different. For example, the classrooms site is intentionally not importing rooms with the `1) Programmed Classrooms - Level 2` designation.

The basic room data for both sites is the same however and it seems reasonable that one data feed on one site could work. The display of the information between the general classrooms and UCR/SPS pages would have to be different though. This could be challenging.

Further, there is slightly different override functionality on both sites that lets users edit certain fields after import. This would need further investigation. They mentioned the automated import is preferable to the manual import. They will need a way to unpublish certain nodes.

Additionally, there are some taxonomy term mappings happening on the registrar site that give them more control over how the information is presented to the end user. One example is mapping on the `Tables` feature but presenting the term name `Tables and Chairs`.

**Comment by joewhitsitt** [comment]
If we import existing and make adding new ids a manual process, the cache clearing might be more complex if certain fields override the api data. Yes, a simple save could purge the cached api data call, but saving one node by itself won't re-render/override all other nodes.

unless we do a similar node type cache tag like we did for Admissions and Pharmacy's map

**Comment by richardbporter** [comment]
In a quick test on stage, using the "Save content" bulk operation seemed to purge all nodes that were selected in the content overview page.

**Comment by richardbporter** [comment]
The registrar_feeds callback is constructing an ID that combines the building code and the room number. I think this was because there is no ID provided by MAUI and room numbers can exist in multiple buildings.

**Comment by pyrello** [comment]
Potential first slice: build a proof of concept that involves creating the node type, adding a field to store the unique ID from MAUI, and pulling that data back to render it. Also figuring out what the MAUI ID will be.

**Comment by joewhitsitt** [comment]
- Need a human friendly name instead of "ABW 240"
- Featured image
- Gallery field to replace carousel
- Registrar rooms are classified as Level 1 and Spceialty Spaces, "roomCategory": "SPECIALTY_SPACE", "roomCategory": "UNIVERSITY_CLASSROOM", (Level 1)
- Room and Tech features are pulled in (currently one feed item, but could loop through and be string match to the separate taxonomy vocabularies)

mockups:
https://classrooms.prod.drupal.uiowa.edu/art-building-west
https://classrooms.prod.drupal.uiowa.edu/home/find-university-classroom

**Comment by briand44** [comment]
Grooming conversation - Start with a mockup of a classroom page and also figure out how we want to display specialty spaces so we have an idea of how to handle references that only exist on specialty spaces. We don't need to worry too much on filters at this point.

Try to get more clarity on how we are getting building information.

**Comment by joewhitsitt** [comment]
https://github.com/uiowa/uiowa/issues/6032 and https://github.com/uiowa/uiowa/issues/6033 were split off #5769

**Comment by joewhitsitt** [comment]
Notes from today:

- [x] Link room type button on full node to go to definition page (https://classrooms.prod.drupal.uiowa.edu/node/206) _will be addressed in https://github.com/uiowa/uiowa/pull/6110_
- [x] Move things on full node based on feedback (hope Ben took better notes) _addressed in https://github.com/uiowa/uiowa/pull/6110_
- :sweep under rug:
- [x] Filter out field_room_instruction_category != PROGRAMMED_CLASSROOM from room list view _https://github.com/uiowa/uiowa/pull/6122/commits/40df624e68edab2afa1483bf6442efaeb6a10aee_
- Separate view "program room list" of field_room_instruction_category = PROGRAMMED_CLASSROOM with exposed building filter (requires `uiowa_core_config_entity_filter_select()`) - _captured in https://github.com/uiowa/uiowa/issues/6131_

**Comment by joewhitsitt** [comment]
Notes from today:

On room page:
- Gray brain section, move tech features up
- There are a couple situations where there is not a maps.uiowa.edu map.
- Hide CTAs if PROGRAMMED_CLASSROOM?

On room list:
- Filter order: Buildings, Occupancy, Type, Technology Features, Room Features, Scheduling Regions
- Shorten label for technology features (technology), max occupancy (occupancy)

On programmed list:
- Change field order
    - move seating type to bottom
    - building first, then room name

On unit:
- Fix icons
- Need to make sure responsible unit term pages are outputting the way we want. Showing contact information for that particular unit

Need to setup periodic import via node_save. Ideally, it would be adjusted to check for a diff before running the full save. I believe the facilities building import process does this check. Once a day should be sufficient.

**Comment by briand44** [comment]
I've updated Joe's notes to include shortening labels for filters, the order of fields on programmed list and possibly theming unit terms

**Comment by briand44** [comment]
I will create a separate issue for the migration of University Classroom rooms and possibly the unit taxonomy pages. We do not need to migrate programmed classrooms as those will be manually entered by Classrooms folks.

**Comment by briand44** [comment]
Closing this as everything required for launch is complete and we are scheduled to launch on Wednesday, July 26th.
