### ISSUE TITLE
Education Events Enhancements

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5128]
# User Stories

As a College of Education site owner, I would like to be able to display events (past and upcoming) based on the parameters chosen, rather than have the number limited to 50 or 1 year.

As a College of Education site editor, I would like to be able to create pages that can display events based on a date range as well as a topic so that I can create an archive of events by semester. (Would need to display both past and upcoming events together).

As a College of Education event creator, I would like the ability to add a summary to events in content.uiowa.edu and have those summaries used as the teaser text on my website so that I have more control over what is output on event teasers.

# Additional Information
They would like this functionality by Fall 2022 (Aug 15th).

Related/Existing issues:
- #3809
- #2739
- https://github.com/uiowa/uiowa/issues/5192

# Additional items to be considered in the future:
- [ ] https://github.com/uiowa/uiowa/issues/5521?
- Have new/updated/cancelled events show immediately (5-10 mins max)
- Ability to delete events on content.uiowa.edu (dupes, etc.)
- private events to not show on keyword filtered pages on events.uiowa.edu - they are supposed to provide an example - This would likely need to be addressed by the app dev group.

# Proposed Solution

- [x] Initial slice https://github.com/uiowa/uiowa/issues/5189
- [x] Probe https://github.com/uiowa/uiowa/issues/5187
- [x] Implement based on what we learned from probe https://github.com/uiowa/uiowa/issues/5187
- [x] #5503 
- [x] https://github.com/uiowa/uiowa/issues/5518

**Comment by joewhitsitt** [comment]
Notes from the meeting:

- the date range _could_ be satisfied by semester based tagging to be paired with topic tag to filter on.
- private: not listed on main listings, but keyword displays on events.uiowa.edu?

**Comment by joewhitsitt** [comment]
Brian brought up a good point about the summary request. We could start making use of it on SiteNow (extra "show summary" option), but for it to be used elsewhere (non-sitenow, events.uiowa.edu), coordination would have to happen.
