### ISSUE TITLE
Epic - Migration improvements

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5299]
# Motivation

There are some improvements that we could make to our migration classes that would allow us to simplify the process of creating future migrations. We have a lot of processing that we do in custom migration source plugin classes that we could move to process plugins, which would allow us to define their usage in the migration config yaml and potentially avoid needing to create custom source classes altogether. Instead we could use the generic `Drupal\sitenow_migrate\Plugin\migrate\source\Node` class.

# Proposed tasks
- [x] #5298 
- [x] #5297 
- [ ] Migrate - Add a console log to image processing errors (404s, etc) in addition to migrate message
- [ ] Migrate - Move body processing functionality to process plugin
- [ ] Migrate - Adapt code for limiting migration by creation date and add to `BaseNodeSource` and add possibility to configure it via YAML
- [ ] Move `reportPossibleBrokenLinks` into `BaseNodeSource` and add an option to toggle it on/off (and configure) via YAML

**Comment by cory-skeers** [comment]
> [ ] Migrate - Adapt code for limiting migration by creation date and add to `BaseNodeSource` and add possibility to configure it via YAML

I've made an adjustment in #5281 to make this change and provide the option. As the migrations in there don't require date limiting, though, it would be good to put it through its paces in another migration. Leaving it unchecked for now.
