### ISSUE TITLE
Update PHP to 8.1 for D9 applications

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5315]
https://support-acquia.force.com/s/article/4415906788759-PHP-7-4-Retirement-FAQ

PHP.net is ending support for PHP 7.4 on 28 November 2022

After 3 October 2022, Acquia will remove PHP 7.4 from the Acquia Cloud platform and convert all remaining environments at that time to PHP 8.0

Acquia will be offering extended long-term support for PHP 7.4 for Cloud Platform Enterprise, Acquia Site Factory applications, and Cloud Platform Professional applications in an effort to provide additional time for our customers to make the transition to a supported version of Drupal and to PHP 8.0. This service will be provided at additional nominal cost. If you are interested in accessing long-term support for PHP 7.4, contact your account manager.

Acquia is currently running PHP 8.1.7 so we shouldn't have to worry about https://github.com/php/php-src/issues/8164

D9 applications
- ~uiowa~
- ~uiowa01~
- ~uiowa02~
- ~uiowa03~
- ~uiowa04 (done)~

# Proposed Solution

- [x] understand costs of extended support and if other Acquia customers have had success with Php 8 for D7
- [x] Determine if we will be updating D7 or using extended support
- [x] #5579 
- [x] #5389 
- [x] Update D9 dev applications
- [x] https://www.drupal.org/project/purge/issues/3259320
- [x] https://www.drupal.org/project/redirect/releases/8.x-1.7
- ~~Check https://www.drupal.org/project/drupal/issues/2942975~~
- [x] Update ddev/travis/blt/composer php
- [x] Document process for updating local PHP to be compatible
- [x]  Update D9 stage applications
- [x] Update D9 prod applications

**Comment by pyrello** [comment]
I added a bullet point related to documenting the process for developer to update their local version of PHP so that we are running a compatible version locally also.

**Comment by pyrello** [comment]
I'm not sure if we have a game plan for getting `uiowa04` set up yet, but we might be able to use that application to test PHP 8 in a production setting without having to turn it on for one of our other applications.

**Comment by joewhitsitt** [comment]
For D9.4, 8.1.6 is recommended to position for D10 https://www.drupal.org/node/3295154

**Comment by briand44** [comment]
Referencing a previous update in case it is helpful. https://github.com/uiowa/uiowa/issues/3975

**Comment by briand44** [comment]
Start with local environment and dev environment to start identifying issues.

**Comment by joewhitsitt** [comment]
added setup instructions to https://github.com/uiowa/uiowa/pull/5611

**Comment by joewhitsitt** [comment]
I don't see uiowa04 in my list of applications. Do we need to do https://github.com/uiowa/uiowa/issues/5522 to even move forward here?

Also, any concern about updating php in dev as it relates to https://github.com/uiowa/uiowa/pull/4643 @pyrello or should we identify which application that one is on and avoid it for now?

**Comment by briand44** [comment]
>I don't see uiowa04 in my list of applications. Do we need to do https://github.com/uiowa/uiowa/issues/5522 to even move forward here?

No, I can update all environments on uiowa04 to php 8.1 now

**Comment by briand44** [comment]
I'll also add that app to our team

**Comment by briand44** [comment]
I've updated uiowa04 dev/stage/prod to 8.1. Also, added the ITS team access to uiowa04. We'll eventually need to add additional teams to that app but didn't want to cause any confusion now since that app isn't setup.

**Comment by joewhitsitt** [comment]
>Check https://www.drupal.org/project/drupal/issues/2942975

This is already addressed in:
https://github.com/uiowa/uiowa/pull/5625/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R226

**Comment by joewhitsitt** [comment]
Not sure we can do codesniffing yet: https://github.com/PHPCompatibility/PHPCompatibility/issues/1299

**Comment by pyrello** [comment]
> Also, any concern about updating php in dev as it relates to https://github.com/uiowa/uiowa/pull/4643 @pyrello or should we identify which application that one is on and avoid it for now?

No concerns. If we need to fix something, we will.

**Comment by joewhitsitt** [comment]
uiowa to uiowa03 DEV have been updated to 8.1. As Brian mentioned, uiowa04 is already done.

**Comment by pyrello** [comment]
> Not sure we can do codesniffing yet: [PHPCompatibility/PHPCompatibility#1299](https://github.com/PHPCompatibility/PHPCompatibility/issues/1299)

It looks like we added this dependency here: https://github.com/uiowa/uiowa/commit/0303d1d06b2827cfc1284b7d52bf45bbf4148b77

I wonder if we still need it to be a specify it?

**Comment by pyrello** [comment]
> > Not sure we can do codesniffing yet: [PHPCompatibility/PHPCompatibility#1299](https://github.com/PHPCompatibility/PHPCompatibility/issues/1299)
> 
> It looks like we added this dependency here: [0303d1d](https://github.com/uiowa/uiowa/commit/0303d1d06b2827cfc1284b7d52bf45bbf4148b77)
> 
> I wonder if we still need it to be a specify it?

Hmm... I'm really not sure how we get around this. It looks like they are working on a 10.x version of the of that library. We might be able to figure out how to force a dev version despite having other dependencies that rely on it.

However, this seems like an odd oversight. Like surely we are not the first people to be trying to upgrade to 8.1 with this setup. It makes me think that maybe we are missing something else.

**Comment by joewhitsitt** [comment]
There are dozens of us: https://drupal.slack.com/archives/C9NJK8319/p1658939353306289

Wonder if opening an Acquia ticket for this would help at all

**Comment by joewhitsitt** [comment]
Starting in the #blt channel first. https://drupal.slack.com/archives/CBH49JN2H/p1663173091174089

**Comment by joewhitsitt** [comment]
Capturing the latest developments:

- Worked with one of the blt maintainers to get our phpcs working and prepped for when php-compatibility is updated for php8+
- Changed the purge module update
- Team is going through and manually updating our codebase to reduce the chance of one of our comparisons from being interpreted incorrectly https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.core.string-number-comparision

**Comment by joewhitsitt** [comment]
Here is the latest:

- Comparison operator changes is done (will need testing).
- Opened ticket with Acquia https://github.com/uiowa/uiowa/pull/5611#issuecomment-1252660135 - this branch is not auto deploying to acquia and a manual code switch causes a bunch of other issues.
- Update acquia blt and dependencies in an attempt to fix things. Didn't.

Lot of good stuff in this PR, but with the latest news from Acquia, the priority of this work seems lower.

**Comment by pyrello** [comment]
> Lot of good stuff in this PR, but with the latest news from Acquia, the priority of this work seems lower.

If we are not going to merge this in the immediate future, I think we are abandoning some or all of this work until it becomes a priority again. Given the changes in the PR as well as the extra hurdles required to switch into and out of it, it seems like more work to try to keep it open for any extended length of time. There will inevitably be quite a few merge conflicts that need to be resolved.

It seems like we should be able to keep the comparison operator updates since those shouldn't be affected by staying on PHP 7.4. Maybe there are also some dependency updates that are also compatible with PHP 7.4 we could keep? I guess what I'm recommending is that we figure out what we can salvage here and strip out the parts that we are not ready for. Then when the time comes where we and Acquia are ready for the switch to 8.1, we start the work over at that point.

**Comment by joewhitsitt** [comment]
> I guess what I'm recommending is that we figure out what we can salvage here and strip out the parts that we are not ready for.

👍 

My hope is that the blt file, travis file and phpcs file are the php 8 only bits. The composer updates should all be backwards compatible.

**Comment by joewhitsitt** [comment]
Was able to move forward with this and keep the 8.1 upgrade in place. https://github.com/uiowa/uiowa/pull/5611 is ready for review

**Comment by pyrello** [comment]
As part of merging #5611 and deploying to stage, each application's stage environment has been updated to PHP 8.1

**Comment by joewhitsitt** [comment]
This has been deployed to prod on all d9 applications. Closing
