### ISSUE TITLE
PhD Program Dashboard

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5362]
The Grad College currently has this PhD Program Data dashboard on its site: https://grad.uiowa.edu/programs/phd-program-data. The current dashboard is built in PowerBI, which has some known issues with usability, accessibility, and ability to be styled in line with brand guidelines. There is the also the desire on the part of programs to be able to display this information on their own site limited to just the relevant data.

To accommodate this request and to be able to have more control over the UX of the provided data, we are going to build an API on data.its that will provide data or widgets for sites to display. Exactly what the API provides and how it gets consumed and displayed is still open to discussion.

# Proposed solution
- [ ] #5361 
- [ ] Add PhD Program Data API to data.its
- [ ] Build a PhD Program Data module for SiteNow
- [ ] Roll out to early adopter sites

**Comment by pyrello** [comment]
Capturing some notes I wrote about this previously. 

* SiteNow plugin component to consume API data
* Application to serve as API endpoint for program data
	* Industry/Categories
	* Location
	* Time to degree
	* Outcomes
* Data will live on-premises in a SQL Server database, most likely
* Need to account for subscriber being able to request a specific data set and that the name of the program and it's MAUI ID might change over time
