### ISSUE TITLE
Build Content Hub 2.0

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#5374]
# Motivation

The current version of content hub is on D7 where we would like to not invest anything else into it. From a strategic standpoint, we would like to continue to have a university-wide event management system similar to what we have now and have had previously. Based on this, some sites have been moving all their events to Content Hub rather than building them out as local content type. There are a number of requests for improvements to the functionality of Content Hub as well as how we integrate with it, but we are currently frozen on whether we should make those changes because we are not sure about future of the system.

## Pros
- We maintain control of this important system that has historically been part of our portfolio.
- Future integration with SiteNow is easier because we control both ends of the integration. SiteNow is likely one of the biggest consumers of this service, so this also makes sense.
- We get the enjoyment of working on a different type of application than SiteNow. There will be different types of problems to solve and different UI/UX to design and build.
- We get experience working with distributed content, possibly via JSON:API, which opens up the possibility of new options for future site building using Drupal with headless applications.

## Cons
- If this was a perfect world, we probably wouldn't choose to take this on until we had cleared out some of our other major priorities.
- Current Content Hub can be a headache. Next version would probably share this feature too.
- Once we open up this line of work, we are on the hook for it going forward meaning that it may put the squeeze on other things we might want/need to work on.

# Proposed solution

Let's start to imagine how we would build out the next version of our events system so that we can start to get a sense of the scope of work. This should help us decide whether this is a viable or desirable option. Some members of the team have expressed interest in owning this project and continuing to be responsible for its future development and maintenance.

## List of steps
- [ ] Decide: Should this new site be entirely custom (have its own source of truth for configuration other than default) or use config split to manage its customizations?
- [ ] Create a plan for coordinating how the roll out happens. There are multiple moving parts that need to happen at about the same time, specifically switching DNS for Content Hub and deployment of updates of `uiowa_events` module. How do we make sure this goes smoothly. Also need a communication plan.
- [ ] Mockup new event pages. Account for single and repeating events.
- [ ] Account for existing feature requests: #5192
- [ ] Create a plan for how to handle the part of the system that is an App Dev application.
- [ ] Build event content type. Audit current version in CH1 and work with team to generate possible updates.
- [ ] Investigate methods for delivery of distributed content: Views, JSON:API, etc. Recommend the best approach for our situation.
- [ ] Build distributed content delivery system based on previous step.
- [ ] Write migration for existing event content.
- [ ] Update `uiowa_events` module to handle new delivery workflow.
- [ ] Execute communication and launch plans.

## Future enhancements
- [ ] News articles
- [ ] IowaNow integration
- [ ] Events created in each SiteNow site can get pulled into Content Hub. Users can just create their event content locally rather than going into the new site to do it.
- [ ] Event registration, possibly using something like https://www.drupal.org/project/rng

**Comment by joewhitsitt** [comment]
Capturing thought: Of course the events.uiowa.edu url path ids don't align with the content hub ids so that would have to be accounted for if we retain past events in a new system.

https://content.uiowa.edu/node/89036/edit
https://events.uiowa.edu/58771

**Comment by joewhitsitt** [comment]
Ownership has been transferred to AIS.
