### ISSUE TITLE
Privacy Acknowledgement Popup

### ISSUE THREAD

**Issue by mjoneill** [uiowa/uiowa#5446]
As a visitor to any uiowa.edu web experience, I acknowledge the link to the UI Privacy Statement.

- Acknowledgment will last for [6 months], after which time the acknowledgment will re-appear.
- Acknowledgement dismisses the popup experience.
- Acknowledgment granted on SiteA.uiowa.edu will be applicable to any site on *.uiowa.edu
- The experience should be platform agnostic (visitors to websites using different frameworks or CMSes can provide the same experience regardless of platform)

This issue is connected to Strategy Epic: [Privacy/GDPR Consent Solution ](https://github.com/orgs/uiowa/projects/1#card-42012637) even though this story is **NOT** to implement [cookie consent](https://github.com/uiowa/uiowa/issues/3943) (just privacy acknowledgement).  

# Proposed Solution
- [x] Connect with OneTrust
- [x] https://github.com/uiowa/uids/issues/736
- [x] https://github.com/uiowa/uiowa/issues/5493
- [x] https://github.com/uiowa/uiowa/issues/5494

**Comment by mjoneill** [comment]
I'd be curious to have a grooming conversation around what would be the best way to approach something like this (acknowledgement).  Build in UIDS4? Buy OneTrust for just Acknowledgement and make it available to all devs?

**Comment by mjoneill** [comment]
There was a desire to have acknowledgement trave with visitors to healthcare properties and vice versa.  I said that might not be possible (3rd party cookies?). 

Also strikes me that if we go this route, we might have a collision with off-brand sites.

**Comment by joewhitsitt** [comment]
Does this replace https://github.com/uiowa/uiowa/issues/3943?

Oops. Read Joe: "This issue is connected to Strategy Epic: [Privacy/GDPR Consent Solution ](https://github.com/orgs/uiowa/projects/1#card-42012637)even though this story is NOT to implement cookie consent (just privacy acknowledgement)."

**Comment by mjoneill** [comment]
> Ooops...

Thank you for the link to #3943!  Was trying to find that!

**Comment by briand44** [comment]
Grooming conversation determined that we should start an initial slice in UIDS while also reaching out to OneTrust. We should take advantage of any previous work in https://github.com/uiowa/uiowa/pull/4107 if possible as part of the UIDS work.

**Comment by GaryRidgway** [comment]
Sounds like we are splitting this in to two slices, and they will be as follows:

Slice 1: Do design of CTA that will be used for the acknowledgement. Construct in UIDS4 to see how we would add JS for this and offer options for this specific style of CTA. Then, implement this in to uids_base.

Slice 2: address what JAvascript actually needs to be added, and additionally hook in to cookies to save this for individual users as described at the top of this thread.

**Comment by briand44** [comment]
I am closing these since we will be using OneTrust for this. We can re-open if any of these are still needed.
