### ISSUE TITLE
Transition Iowa Now to v3

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5474]
# Story

As an Iowa Now site owner, I would like to transition to SiteNow v3 and create a faculty/staff information hub so that we can share information on the latest SiteNow platform and serve as the go-to resource to for faculty/staff in addition to existing audience.

# Proposed solution

- [x] https://github.com/uiowa/uiowa/issues/5335
- [x] https://github.com/uiowa/uiowa/issues/5283
- [x] https://github.com/uiowa/uiowa/issues/5403
- [x] #5485
- [x] #5524
- [x] #5562 
- [x] #5575
- [x] #5626
- [x] Person content type development to support migrating "Person and Contact" content
    - [x] https://github.com/uiowa/uiowa/issues/5675
    - [x] https://github.com/uiowa/uiowa/issues/5670
- [x] #5821
- [x] #5507
- [x] https://github.com/uiowa/uiowa/issues/3561
- [x] #6025
- [x] #6147
- [x] #6150 
- [x] #5887
- [x] https://github.com/uiowa/uiowa/issues/6093
- [x] https://github.com/uiowa/uiowa/issues/6196
- [x] https://github.com/uiowa/uiowa/issues/6197
- [ ] ~Communication with campus and/or other tasks in regards to https://github.com/uiowa/uiowa/issues/6093~ - Iowa Now folks will handle this communication.
- [x] #6423
- Not planning to launch until Fall so they can shop it around

**Comment by pyrello** [comment]
> Migrate photo galleries as basic pages with image block link to the article using the related content. Maybe use first gallery image as the featured image for teaser references?

I think I have mentioned this before, but I am a fan of the idea of either a) changing the current field_image field on the article content type to allow multiple images or b) adding a new field for additional images. In either case, I would then present the additional images as a thumbnails under the featured image. When clicking the thumbnails, whatever our current lightbox solution is would pop up and show the larger image and controls to view the next image.

It would be very similar to the current experience: https://now.uiowa.edu/2022/07/community-assists-iowa-research-during-bioblitz. Also I think it would be a good addition to the entire platform.

**Comment by bspeare** [comment]
I'd like to see something done within the Articles page for a photo gallery as well.   Doing something like what @pyrello suggests above or turning on layout builder to use the image block seem like they would provide better value/UX.

**Comment by pyrello** [comment]
> Doing something like what @pyrello suggests above or turning on layout builder to use the image block seem like they would provide better value/UX.

I would prefer a dedicated field or expanding the existing `image_field` over the layout builder approach is because I think it would be better to have a standard way of doing this. I can be persuaded otherwise, but I'm worried about a bunch of bespoke pages with image galleries implemented differently.

**Comment by cory-skeers** [comment]
> > Doing something like what @pyrello suggests above or turning on layout builder to use the image block seem like they would provide better value/UX.
> 
> I would prefer a dedicated field or expanding the existing `image_field` over the layout builder approach is because I think it would be better to have a standard way of doing this. I can be persuaded otherwise, but I'm worried about a bunch of bespoke pages with image galleries implemented differently.

I'd second this. I think there will still be a need for full layout builder articles as well in some cases, but the more that can be the exception, the better in my mind.

**Comment by bspeare** [comment]
Meeting notes from 12/13

- Move https://now.dev.drupal.uiowa.edu/news-faculty-and-staff to be the home page without a special Faculty and Staff label
- Featured story at the top of the page
  - Remove main featured story section.  They are not ready for it yet. 
- Featured Headlines
  - Move "Featured Headlines" up to the first spot.  Switch to 6 items and show images and use migrated content in an article list block. 
- Headlines
  - Change to "Around campus"
  - They are considering whether to use aggregator here or create duplicate copies on their site and adjust the canonical url to point to the story source. 
- Resources
  - They still like the idea of this in a sidebar.  Perhaps clone the updated home page after all the changes have been made and experiment with its placement.  
- Media Highlights
  - This can be removed for now.  They are not ready for it yet. 
- Share News CTA and webform
  -  They are wondering if Share your news webform can be split with https://now.uiowa.edu/grant-awards-intake-form.   Perhaps having users select "Share your news" or "Grant Awards Intake Form" to conditionally show different form fields.

**Comment by briand44** [comment]
Created an issue for ^^ at https://github.com/uiowa/uiowa/issues/6025

**Comment by briand44** [comment]
I would like to discuss the subheadlines comment from here to see if that is something the team thinks we should address. https://github.com/uiowa/uiowa/issues/6006#issue-1485117691

If we decide not to address that, I think we should groom https://github.com/uiowa/uiowa/issues/6093

**Comment by joewhitsitt** [comment]
Talked about adding https://github.com/uiowa/uiowa/issues/6147 to migrate sub heads into for now migration.

**Comment by briand44** [comment]
Closing this as all of the issues represented here that we are responsible for have been completed. They don't plan to launch until August though.
