### ISSUE TITLE
Setup iowalakesidelab.org as an off-brand SiteNow v3 site

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5602]
# Story

As a site owner for Iowa Lakeside Laboratory, I would like a site provisioned and setup that uses an off-brand theme since this site is a Board of Regents site.

# Additional Information

If they had this in October they would be happy. They would like to be able to launch in January so it is ready when registration opens in February 2023.

Original site request which is currently locked - https://sitenow.uiowa.edu/admin/structure/webform/manage/request_a_site/submission/12366?destination=/admin/structure/webform/manage/request_a_site/results/submissions%3Fsearch%3Dlakeside

Initial investigation
https://github.com/uiowa/uiowa/issues/5007

Recap from probe
https://docs.google.com/document/d/1rc4S0CX08DIc1ZMbW6x1OMPb77aCTIgQTVDUVHmQxPE/edit#heading=h.1wm7kd5iux6w

# Details

- They have a logo that they would like to use. It can be seen on https://www.continuetolearn.uiowa.edu/Mylakeside/studentportal
- They are ok with similar color scheme to what they have - whites, grays, etc. This seems like a good site to use this color scheme as a default going forward for other off-brand sites.
- They currently do not have search functionality but would like it. Not critical though so this should not hold up getting it in the hands of our partners to start content work, etc.
- They have some course information https://iowalakesidelab.org/courses, that may require some custom development in a future slice, but they will see if they can accommodate with existing functionality.

# Proposed solution

- [x] Provision site
- [x] Implement solution for setting custom CSS variables to provide a different color palette. Initial solution will be one fixed color palette for all custom sites. https://github.com/uiowa/uiowa/issues/6204

Future Slice
- [x] #6212
- [x] #6231
- [x] https://github.com/uiowa/uiowa/issues/6232
- [x] Follow up with other folks interested (ihspa, ILEB, ~iowateacherintern.org~) to set up a conversation with Jess, etc. to discuss getting approval.

**Comment by bspeare** [comment]
Contact [michelle-sillman@uiowa.edu](mailto:michelle-sillman@uiowa.edu) regarding the IHSPA when off-brand sites are available.

**Comment by pyrello** [comment]
I updated the proposed solution because it was still referencing a custom theme, which is not how this is going to get done.

**Comment by pyrello** [comment]
Contact bramowj@iowa.uiowa.edu regarding the Iowa Lions Eye Bank site when off-brand sites are available.

**Comment by briand44** [comment]
First Slice... Implementation of css variables for different color scheme and some sort of theme setting (UI not required) in order to enable it.

Medium

**Comment by briand44** [comment]
Grooming Slice 2 - Logo - Uploading this can be a developer task at this point. Option for not having a logo.

**Comment by pyrello** [comment]
Re: logo slice: I believe the current template is just pulling the logo directly from UIDS. We'll need to update the logo template to check for a theme setting for the logo and use that if it exists, defaulting to the current logic if not.

**Comment by joewhitsitt** [comment]
Re: logo slice: 
- Current logo code is also taking in and preparing an SVG with PNG fallback. Should we adjust template to handle non-SVG since we don't have a secure solution for SVG upload? https://github.com/uiowa/uiowa/issues/130
- I think the plan is to use the same asset for footer.

**Comment by briand44** [comment]
Closing this as all the planned work has been completed and I have let Jess know she can start conversations with IHSPA and Iowa Lions Eye Bank
