### ISSUE TITLE
Epic: As a developer, I can create a custom structure for festivals for the Iowa Summer Writing Festival site.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa#5732]
Placeholder for more details. The Iowa Summer Writing Festival is moving to a new Drupal 9 version of their existing site. After two years of going online for the festival, they are moving back to in-person, and will need to have their Festival structure recreated/improved for the upcoming festival and beyond.

For each festival, they have sessions, which contain multiple events/courses, which are led by one or more instructors. Site will need to have searchable views for upcoming, register-able events, instructor bios with events led lists, etc.

- [x] #5810
- [x] #5879
- [x] #5886
- [x] #5931
- [x] #5968
- [x] https://github.com/uiowa/uiowa/issues/5939
- [x] https://github.com/uiowa/uiowa/issues/5940
- [ ] https://github.com/uiowa/uiowa/issues/5910

**Comment by pyrello** [comment]
Looks like this is the current site? https://iowasummerwritingfestival.org/

Noting the custom domain. Also, it looks like this is a slightly custom design. Do you think that they will be okay with a branded experience?

**Comment by mark-bennett-uiowa** [comment]
@pyrello You are correct, that is the current site. We have a new D9 site setup at [https://iowasummerwritingfestival.prod.drupal.uiowa.edu/](https://iowasummerwritingfestival.prod.drupal.uiowa.edu/) that they were okay moving to or we can move them back to the custom domain.

**Comment by mark-bennett-uiowa** [comment]
The Iowa Summer Writing Festival occurs every summer, with new online courses taking place even outside the normal summer window. Registration for the upcoming summer begins in January, so this would need to be completed this fall to allow time for the ISWF (primarily Amy Margolis) to set the schedule of events, enter all of the information into the site, and prepare for the next festival.

Amy has requested similar functionality to their existing site, updated with current changes/needs, including:

- a searchable list of current and upcoming Workshops (filtering for date, session type, genre, and instructor)
- instructor profiles that include blocks that link to current/upcoming events they are associated with
- more added here based on future discussion...

Here is there current structure for Festival > Sessions > Workshops > Instructors:

### Festival
_Use festivals to add all of the data related to a festival, including sessions and events (workshops, lectures, etc.)._

- Dates - startdate* and enddate*
- Dates, line 2 - textfield
- Location, line 1* - textfield
- Location, line 2 - textfield

### Sessions
_This is a session that will be included in a Festival._

- Session Dates - startdate and enddate
- Session Type* - select list (Weekend, Weeklong, Two-Weeklong, _Online_)
- Status* - Published/Unpublished

### Workshops (currently named Events, moving 11th Hour Lectures out to Content Hub as public facing events)
_Use workshops ~events~ for workshops, ~lectures~, etc._

- Workshop ~Event~ Name* - textfield
- ~Event Type* - select list (Eleventh Hour Lecture, Workshop)~ only Workshops now, field not needed
- Genre* - select list (All Genres, Children's, Essay, Fiction, Hybrid Forms, Memoir, etc)
- Instructor(s)* - entity reference (add new, add existing)
- Location
- Workshop ~Event~ Description* - textarea
- Registration link - link (new field for entering registration URL for workshop)
- Status* - Published/Unpublished

### Instructor

- First Name* - textfield
- Last Name* - textfield
- Bio
- Picture
- Status* - Published/Unpublished

## Important Updates after 10-5-2022 meeting with Amy

- There will be "two" Festivals per year, one in-person festival (e.g. 'Summer Festival 2023') and one online festival (e.g. 'Online Festival 2023')
   - The **in-person summer Festival** begins in June and runs through July:
     - The in-person festival contains multiple Sessions, each with its own start date and end date.
     - These Sessions either run over a weekend, over an entire week, or over a two-week period.
     - Each session contains multiple Workshops, and a particular workshop can occur in multiple sessions.
     - These workshops occur over the entirety of the session(s) in which they are associated, so their start date and end date are tied to their "containing" session(s).
     - Each session can have multiple Instructors, and an instructor can teach multiple workshops.
   - The **online festival** is throughout the year, and does not contain "sessions":
     - Each online workshop has its own start date and end date, rather than being tied to a "containing" session.
     - Each online workshop can have multiple Instructors, and an instructor can teach multiple online workshops.
- **11th Hour Lectures** were originally tied together with Workshops under an Events label. Want to separate these from workshops and create them in Content Hub instead.
   - Lectures are public events open to anyone
   - Lectures are not restricted to a festival or any sessions within
   - Lectures are additional events that festival participants can engage in while active in the festival, but are not "required"
   - Lectures occur for one hour, on one day during the week.
   - Moving these out from the ISWF site and onto Content Hub will provide more visibility and participation from the public.

Relationship Diagram:
Festival --< Session >--< Workshop >--< Instructor

**Comment by briand44** [comment]
Grooming conversation - probe existing functionality (event series from Admissions, local events, people, etc) to see what we can accomplish using existing before building custom. Scope would be to identify what can be reused and what makes sense to build custom.

**Comment by pyrello** [comment]
> Each online workshop has its own start date and end date, rather than being tied to a "containing" session.

My thought about this is that we could still have the session be the container for a workshop in the online festival. The difference would be that instead of containing multiple workshops, an online session would only contain one workshop. This would avoid us having to build two similar but slightly different sets of entities or two have to blur the lines between what is a session and what is a workshop in terms of which fields are tied to each. If we added a boolean field to the festival to indicate whether it was online or not, we could potentially use this value in its children to control how the session displays, either making it more prominent as a separate thing (in-person festival) or blending in more with the workshop it represents (online festival).

**Comment by joewhitsitt** [comment]
Creating a person type `instructor` seems valuable if the filterable view for events is a dropdown or autocomplete entity reference view of just instructors and not all people on the website.

**Comment by mark-bennett-uiowa** [comment]
> Creating a person type `instructor` seems valuable if the filterable view for events is a dropdown or autocomplete entity reference view of just instructors and not all people on the website.

@joewhitsitt What if we add a person type "presenter" to match the label of the field? Just so there isnt any misunderstanding.

UPDATE: Added this into the ISWF site split. "Presenter" label with "performer" machine_name to match schema.

**Comment by joewhitsitt** [comment]
If that works for ISWF, that works for me.

**Comment by pyrello** [comment]
Wondering if this still needs to be open since we already have one festival in the books for the V3 version of the site?
