### ISSUE TITLE
Law Library development needs

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5857]
- We want to add an hours option similar to [Rec Services](https://recserv.uiowa.edu/). I would guess this is a webform of some sort, but I wasn’t sure how to create it. Can you please provide guidance?

- I need the search block we have placed on the center of the home screen to search [InfoHawk+](https://search.lib.uiowa.edu/primo-explore/search?vid=01IOWA). Can you tell me how to accomplish this?

- The directory option is fantastic, but rather than “Research Areas,” we would like the term on our website to be changed to something more appropriate for a staff directory, rather than a faculty directory. Would this be something you could change on our website?

# Stories
As an owner of library.law.uiowa.edu, I would like to use Exchange to manage Library and Reference hours similar to Rec Services so that we can schedule hours and not have to make updates to the website when hours are regularly changing.

As an owner of library.law.uiowa.edu, I would like to have a search box on my website where users can search InfoHawk+.

As an owner of library.law.uiowa.edu, I would like to be able to enter service areas related to a staff member and be able to filter by those service areas on the staff directory page so users can quickly find the correct contact person.

# Additional Info
Want to launch in May

# Proposed Solution

- [x] https://github.com/uiowa/uiowa/issues/5875
- [x] https://github.com/uiowa/uiowa/issues/5874
- [x] https://github.com/uiowa/uiowa/issues/5876

**Comment by briand44** [comment]
Just capturing the asks here for now to be used as a reference for our meeting with them. Will provide more information and split these into user stories after we meet.
