### ISSUE TITLE
ITS Alerts System

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#5952]
# Story

As an ITS website owner I would like to be able to notify students, faculty and staff when there is a problem/change with a service so that they can be aware of any impacts to them.

# Additional Information

**Notifications**
via email - daily digest - real time notification
Dashboard on ITS website

Not necessary for launch:
RSS
Text Messages
Teams Chat
Slack
Help Desk Phone Greeting
in Cherwell
Ability to choose which services they want to get notified about

**Calendar view of alerts**
Displays all types of alerts
Way to differentiate between alert types (color, etc)
Both future and past
Mobile friendly/readable/usable (wrapping etc.)

Nice
Show other important academic dates along with alerts (calendar combiner/MAUI Academic calendar/deadlines)
possibly alternate list view if needed for usability/accessibility

**Buildings**
Ability to designate one or more buildings affected by an alert
Adrienne to clarify if building continue to be manually maintained of if come from Facilities.

**Service status page**
Current page (https://its.uiowa.edu/alerts/status-history)
List of every service and status for the last 5 days (current and four previous)
Link service title to service landing page
Open to changes on this display - Searchable/Filterable vs alpha listing vs categorized

Individual service status history

**Alert Types**
Ability to categorize as one of these types:
- Outage
    - Possibly Normal Outage and Major Outage
- Planned Maintenance
- Degradation of Service
- Service Announcement

**Services**
Ability to relate an Alert to one or more services

**Workflow**
Moderation - some roles can create but need approval to publish

# More

- Ability to clone alerts (Will the replicate feature in v3 work for this?)
- Alerts are frequently updated, where the updates (with time and date stamp) are published to both site and as a notification when necessary.
- Ability to notify subscribers when an alert is closed
- Ability for a service owner to add an update or close an alert (they can’t do this now)
- Alerts should publish on the alerts page and to the calendar view
- Ability for Help Desk staff to publish an alert, close an alert, send the alert email notification all from the same page
- Ability for the Help Desk staff to sort and filter previous alerts by service, alert type, or date
- Ability to post an alert for more than one service and have the services listed in the title
- Ability to choose an alert template (text) when publishing an alert (wish list)
 
Also, I wanted to document all of the current fields that are available on the current Alert content type:  
- Description field (free text)
- Start and end date (time, day, month, year)
    - Check box to display the end time if it is know (ex: planned maintenance window)
- Checkbox for marking an alert closed
- Severity (Currently a dropdown with ‘normal’ and ‘major’ we also discussed not doing severity…)
- Type drop down (Outage, service announcement, maintenance, degradation of service)
- Service (ability to tie an outage to a service…auto populates list when typing)
- Additional title details (ability to amend the title if type of service isn’t valid)
- Building field (auto populates list when typing)
- Internal fields:
    - Text field for who is requesting the alert (We rarely/never use this)
    - Text field for internal details (We rarely/never use this)
    - Email log: displays which user sent notifications and date/time (The is nice to have…currently, Moderation/Revisions do not show when an email was sent so it’s nice to see a log to know when notifications have been sent)

# Proposed solution

```[tasklist]
### Tasks
- [ ] https://github.com/uiowa/uiowa/issues/7035
- [ ] https://github.com/uiowa/uiowa/issues/7058
- [ ] https://github.com/uiowa/uiowa/issues/7060
- [ ] https://github.com/uiowa/uiowa/issues/7059
- [ ] https://github.com/uiowa/uiowa/issues/7197
- [ ] #7216
- [ ] #7217
- [ ] https://github.com/uiowa/uiowa/issues/7225
- [ ] https://github.com/uiowa/uiowa/issues/7147
- [ ] https://github.com/uiowa/uiowa/issues/7234
- [ ] https://github.com/uiowa/uiowa/issues/7283
- [ ] https://github.com/uiowa/uiowa/issues/7360
- [ ] https://github.com/uiowa/uiowa/issues/7350
- [ ] https://github.com/uiowa/uiowa/issues/7373
- [ ] https://github.com/uiowa/uiowa/issues/7384
- [ ] https://github.com/uiowa/uiowa/issues/7433
- [ ] https://github.com/uiowa/uiowa/issues/7460
- [ ] https://github.com/uiowa/uiowa/issues/7456
- [ ] https://github.com/uiowa/uiowa/issues/7417
- [x] Individual service status history - Leave this off for now.
```

**Comment by briand44** [comment]
Some notes from 10/24/23:

- They'll need an alerts landing page
    - They like their existing page https://its.uiowa.edu/alerts
    - Show outages/Degredation of Service first
    - Planned maintenance in the next 7 days
    - Service Announcements in the next 7 days
    - Status History over the last 5 days
    - No longer need Ongoing Issues
- View all Services Status History over the last 5 days https://its.uiowa.edu/alerts/status-history
- Calendar view of Alerts - https://its.uiowa.edu/alerts/calendar
    - Differentiate by category
    - Include legend here
    - Ability to view past alerts on calendar
    - Would like improvements on mobile view of calendar
- They are going to start fresh with alerts, not moving old alerts over
- RSS not widely used, nice but not necessary for launch
- They would like moderation
    - Only HD Full Time staff and webmasters can publish and send notifications
    - Anyone else with site access can create but not publish and a notification should be sent to HD
- It's critical that the emails are sent right away
- Need a daily digest email
- Ability to add updates to an alert and choose to send an update email
- Replicate functionality on alerts would be nice to have
- Email log would be nice to have but may not be required for launch

**Comment by pyrello** [comment]
Building the actual UI for the alerts landing page seems like it is related to #7030

**Comment by joewhitsitt** [comment]
> Building the actual UI for the alerts landing page seems like it is related to #7030

We discussed this in grooming that there are multiple views at play and other elements currently that would most likely be better served by individual blocks whereas the solution in #7030 is view page based.

**Comment by joewhitsitt** [comment]
While working on https://github.com/uiowa/uiowa/issues/7059, I am going to touch on a few points of this epic.

- We have not accounted for the featured services status history and don't have a 90-day on the service node. We do have a "View status history" link on the landing page mockups, but so far I imagine we will do a simple chronological listing possibly with a filters for title contains, services, buildings. This could also be auto filled and linked to from a service page. This would also help with, _"Ability for the Help Desk staff to sort and filter previous alerts by service, alert type, or date"_
- _"Ability to clone alerts (Will the replicate feature in v3 work for this?)_" - I think it should, but we may want to wipe out scheduler field data.

**Comment by joewhitsitt** [comment]
Digging up my old notes about "Alert Close" since it has been an issue in the past and we will soon be discussing it.

- Originally, the request was to "close" an alert if the end date was unique and in the past. Core date stores the initial end date with the same value as the start date. There is a 5 min cron task to look through alerts and automagically close them if that criteria is true. This also disables the date field so that changes can't be made and have it accidentally show up on the website, in a digest, etc. This solution came about to handle staff members from forgetting to close the alert, avoiding date/close mismatches but also having certain planned maintenance alerts close without further staff interaction.
- Once it was closed it couldn't be reopened and the guidance was to create a new alert and reference the old closed alert. Later on, there were issues where they made a mistake about the end date and and wanted to correct it. I think there was an instance or two where as admins and through the DB, we adjusted those for the historic record. It is complicated by https://www.drupal.org/node/1387890
- ITS at one point requested it be updated, but Adam had noted that adjusting it would require refactoring the whole behavior and wasn't worth it for a few instances where they had a bad date added. We were also cost-recovery at the time..

**Comment by joewhitsitt** [comment]
It is important to them that the "send email" is part of the edit form (not triggered elsewhere). Perhaps a "Send email on save" checkbox would work where the value isn't stored but is acted upon during presave. That way the email sends with the latest saved content.

We didn't discuss this, but I also like the idea of the updates (previously a front-end field collection) being in the node form too. Only showing the field if the node is not new and only allowing one new entry per node save? Perhaps paragraphs consisting of content/date and having the date field populated by modified date.

**Comment by briand44** [comment]
They would like to have some sort of informational popup on the alert edit form next to the category field that pulls in descriptions of the categories so folks created the alert understand the different types and choose the correct type.

They mentioned they see service announcements separate from an news article and they need to be displayed on the alert calendar, in emails, etc. so they would prefer to keep these as alerts.

They had some concerns about the title on the content overview but we discussed possibly having a filterable alert history page that could help alleviate this concern.

**Comment by joewhitsitt** [comment]
>They would like to have some sort of informational popup on the alert edit form next to the category field that pulls in descriptions of the categories so folks created the alert understand the different types and choose the correct type.

I think we can use the existing select widget but change the reference method to call an entity reference view. The entity reference view could have a `title | description (strip tags)` result for each row. If the descriptions are long maybe the help text could link to an article. If we run into trouble with formatting a select list dropdown, we could switch to radio list since it is single value, required.

**Comment by briand44** [comment]
Going to close this now since everything is complete. Any additional feedback related can be captured on the overall Epic #6189
