### ISSUE TITLE
Set standards for naming things visible to users

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6004]
# Motivation

We are currently inconsistent about how we name things like entity types and field labels. We sometimes capitalize every word and other times we only capitalize the first word. This is problematic when it comes to user-facing labels. The inconsistency looks unprofessional and unintentional.

# Proposed solution

```[tasklist]
### Tasks
- [x] Add notes to our content creation documentation to provide better guidance for developers making these decisions going forward
- [ ] Update labels based on the standard we set
- [ ] Debate what the standard should be
- [ ] Identify any user facing types of labels
```

**Comment by pyrello** [comment]
I just want to note that I have contributed to this mess as much as anyone and I have evolved in my position about what should be capitalized and what should not.

**Comment by bspeare** [comment]
Do we want to settle on sentence case?  Perhaps form field labels would fall under the "et cetera" here?

<img width="649" alt="Screenshot 2024-07-15 at 4 18 16 PM" src="https://github.com/user-attachments/assets/5b029d63-e8c8-4e6f-9bd0-70f722521ea3">

**Comment by bspeare** [comment]
Checked with brand team and confirmed.   Sentence case is the recommended path here.  Should we add this to our content type best practices?  https://docs.prod.drupal.uiowa.edu/development-workflow/content-type-best-practices
