### ISSUE TITLE
ITS Website Development

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6189]
Overall Epic encompassing all of the ITS development work

- [x] https://github.com/uiowa/uiowa/issues/5952
- [x] https://github.com/uiowa/uiowa/issues/6190
- [x] https://github.com/uiowa/uiowa/issues/6191
- [x] ~Software~
- [x] https://github.com/uiowa/uiowa/issues/7474
- [x] https://github.com/uiowa/uiowa/issues/6009
- [x] #7510
- [x] #7519 
- [x] Run service and support article migrations in dev environment
- [x] #7791 
- [x] #8037

**Nice to have - Not required for launch**
- [ ] #6889 
- [ ] Expiring service content/Service owner group - very nice to have but could launch without

**Comment by briand44** [comment]
Joe's notes from 2/14/2023

- Article
  - is pretty much good to go and they don't want to migrate.
  - Still see a value in info center relationship (point of contact field?)
  - Keywords and Audiences to tags.
- Support article
  - Would love to migrate if possible
  - title, short description, body, faqs (accordions), info center, category (single), keywords, it support info (internal), moderation.
  - Accordions are still important
  - Categorization and sorting on the info center still a big thing (draggable views).
  - Single info center assignment (serves as content owner).
  - Better search down the road.
  - it support info could find a new home in Teams.
- Internal
  - Roughly the same as the SA. Might not be needed.

**Comment by joewhitsitt** [comment]
My notes from attending ITS editors training (8/21)
- Draft option desired for service and support articles. Wait for discussion with James/Adrienne
- Alerts calendar is not displaying?! siteimprove errors in console.
- Alert title field is showing again in form display settings...
- Desire for building abbreviations to speed up entry (possibly append abbr to option label for autocomplete)
- From its-web email related to ITS alerts workflow - Change alert workflow labels and/or transitions so that it is either "draft" or "submit" instead of "draft" or "review"?
- UIDS syntax highlighting to make use of the CKEditor code block feature
