### ISSUE TITLE
ITS Support Articles

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6191]
# Story

As an ITS website owner, I would like to have support articles on our new website so that we can continue to share support information for our services.

# Additional Info

- They would like to migrate support articles from their existing website.
- Separate content type? title, short desc, body, faqs (accordions), infocenter, category (single), tags, moderation.
- Published date is not important but last updated date is.
- Accordions are still important
- Categorization and sorting on the infocenter still a big thing (draggable views?). They are looking for suggestion on how to best categorize and display these support articles. Some infocenters have over 100.
- Single infocenter assignment (serves as content owner)
- Don't need internal support information on support articles and no longer need separate internal support article content type.
- They also are looking into Chat Bots. This is something they have seen others have success with. Not sure how this relates at this point but worth noting.

They mentioned the Help Desk currently references/uses the node id when supporting campus. I'm not sure I understand exactly how they are currently using this and if there would be a reason to migrate the old node id into a field on the new site or if they can just change their process to not be dependent upon the node id?

# Proposed solution

```[tasklist]
### Tasks
- [ ] https://github.com/uiowa/uiowa/issues/7378
- [ ] https://github.com/uiowa/uiowa/issues/7414
- [ ] https://github.com/uiowa/uiowa/issues/7418
- [ ] https://github.com/uiowa/uiowa/issues/7462
```

**Comment by briand44** [comment]
Grooming conversation... Mockup is using narrow article theming but articles don't support accordions. Seems like were leaning towards support article content type for ITS separate from existing articles content type. Scope next slice to content type, fields and theming of support article node. We still need to learn more and figure out how to handle node id's/redirects but not in scope for this slice. Limit content type to fields represented in mockup. Size as large.

**Comment by briand44** [comment]
Closing this as well. Migrating support articles and any additional feedback that comes up can be captured on the overall epic #6189
