### ISSUE TITLE
Media roadmap 

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6262]
# Story

As a SiteNow user, I want to be able to embed lazy-loaded images into my pages and have them appear as the actual size described in the image style and be responsive. 

# Proposed solution

- [x] https://github.com/uiowa/uiowa/issues/6263
- [ ] [Remove legacy S, M, L image sizes and update those styles into responsive image styles.](https://github.com/uiowa/uiowa/issues/7195)
- [ ] Implement inline styles from UIDS?

**Comment by joewhitsitt** [comment]
If we plan to investigate the picture element as part of #6263, I'd like to see if there are other bits from https://github.com/uiowa/uiowa/issues/5121#issuecomment-1116499116 that we could incorporate (e.g., changing the image media type display setting), though I am pretty sure we don't want to poke the bear too much with our referringItem logic.
