### ISSUE TITLE
Review SiteNow platform spam measures and adjust as necessary

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6470]
# Motivation

We have noticed - and received reports of - increased spam submissions on webforms. 

# Proposed solution

- Audit what measures are already in place to reduce spam submissions
- Review what is available in the contrib module space to see if there are any new options available and do some initial due diligence on any options found
- Search for techniques that can be employed to reduce non-bot spam submissions (AI?)
- Provide recommendations to the team
- Possibly implement any proposed changes
- Follow up with Modei Akyea about what we did

```[tasklist]
### Tasks
- [ ] https://github.com/uiowa/uiowa/issues/7394
- [ ] https://github.com/uiowa/uiowa/issues/7657
- [ ] Probe webform spam words
- [ ] Add https://www.drupal.org/project/riddler as a CAPTCHA option for webfoms in addition to math CAPTCHA
```

**Comment by joewhitsitt** [comment]
>I know that campus is probably Google cautious right now which might make adding reCaptcha a dead end, so I will suggest another rising competitor which is supposed to be more “privacy focused” - https://www.hcaptcha.com/

https://iowaweb.slack.com/archives/C0164FNN1PV/p1684852856172879

**Comment by joewhitsitt** [comment]
We've already lost: https://captchaai.com/

**Comment by joewhitsitt** [comment]
>I've found that the best way to avoid that type of sophistication is to remove financial incentive for attackers.  This involves carefully monitoring PPC spending and only working with advertising partners that actually perform. We've cut almost all Bing spending due to what appears to be pay per click fraud. - https://drupal.slack.com/archives/C78MFLN9K/p1698766208300329

Thread does go on to say they have Google ReCAPTCHA v3 implemented through custom code so that the page can still be cached.

**Comment by joewhitsitt** [comment]
UI Pharmaceuticals has been getting hit quite a bit lately and is interested in additional measures to combat spam.

**Comment by joewhitsitt** [comment]
I've noted in a couple support threads recently that adding some element validation (e.g. min/max counts) can be a workaround to trip up some bots at least temporarily.

**Comment by joewhitsitt** [comment]
Getting support tickets related to the antibot time restriction on some forms (particularly short multi-page forms). The current config is wildcard matching all webforms, so there isn't an easy way to ignore certain forms.

**Comment by joewhitsitt** [comment]
For _some_ of these support issues, the users are testing the forms before going live. We should note that `Antibot will be bypassed for` roles viewer and up.

**Comment by GaryRidgway** [comment]
[Created a new slice for deciding on path forward on form spam protection.](https://github.com/uiowa/uiowa/issues/7247)

**Comment by briand44** [comment]
Admissions reported a lot of spam coming from https://admissions.uiowa.edu/contact-us

**Comment by briand44** [comment]
Frank Delin also reported lots of spam recently. Trying to confirm what site/form.

Update - The spam they are receiving is related to their existing shl.uiowa.edu site, not a v3 site. I think they are just trying to understand if launching on SiteNow will help with this.

**Comment by briand44** [comment]
>Getting support tickets related to the antibot time restriction on some forms (particularly short multi-page forms). The current config is wildcard matching all webforms, so there isn't an easy way to ignore certain forms.

>For some of these support issues, the users are testing the forms before going live. We should note that Antibot will be bypassed for roles viewer and up.

Honeypot is what is enforcing the time restriction on forms not Antibot, correct? 
https://www.drupal.org/project/honeypot
https://www.drupal.org/project/antibot

**Comment by bspeare** [comment]
New email this morning from transportation about spam.  I added their domain to the labels.

**Comment by bspeare** [comment]
Added the `studentlife` label for @benlewzz and @bewoldt.

**Comment by joewhitsitt** [comment]
> > Getting support tickets related to the antibot time restriction on some forms (particularly short multi-page forms). The current config is wildcard matching all webforms, so there isn't an easy way to ignore certain forms.
> 
> > For some of these support issues, the users are testing the forms before going live. We should note that Antibot will be bypassed for roles viewer and up.
> 
> Honeypot is what is enforcing the time restriction on forms not Antibot, correct? https://www.drupal.org/project/honeypot https://www.drupal.org/project/antibot

@briand44 thanks for checking my comment. you are right I got slightly mixed up here. honeypot is the time based lock and we could allow webmasters to bypass it with the `Bypass Honeypot form protection.`

Honeypot is a single toggle within webform config so the idea of ignoring certain forms will still be tricky.

And on top of that, these comments relate more to improving the webmaster and actual user experience versus preventing spam which this issue seems to be leaning. Perhaps I can delete my existing comments  https://github.com/uiowa/uiowa/issues/7247 and have that conversation there.

**Comment by joewhitsitt** [comment]
Been thinking about this a bit:

- a platform wide WAF is probably too far-off of a solution given the sudden rise/interest.
- clearly honeypot/antibot combo is no longer cutting it and is affecting actual users of the website.
- accessibility has been a previous concern with reCAPTCHA and hCAPTCHA. The former is supposedly works with major screen readers like ChromeVox, JAWS, NVDA, and VoiceOver to assist users with visual impairments. The latter is supposedly Section 508 and WCAG 2.1 AA compliant.
- data sharing upstream is a concern with Google reCAPTCHA.
- [a shared IP ban list is a possibility](https://github.com/uiowa/uiowa/issues/6242#issuecomment-1814957005)
- There might be some other strategies for webform spam from https://www.drupal.org/docs/contributed-modules/webform/webform-add-ons#spam like maintaining a shared list of spam words to validate/reject against: https://www.drupal.org/project/webform_spam_words
- caching had been a previous concern at one point with certain CAPTCHA solutions, but I just realized/remembered that honeypot prevents caching already.. "Page caching will be disabled on any page where a form is present if the Honeypot time limit is [not disabled]."

**Comment by briand44** [comment]
oneit.uiowa.edu is reporting lots of spam from webforms.

**Comment by bspeare** [comment]
I'd be interested in an experiment with:

- Regex validation on emails (gmail, edu, yahoo, etc)
- Regex on email names that use numbers in username
- Regex check on links in text fields or text areas
- [Spamwords ](https://www.drupal.org/project/webform_spam_words) - for further validation

**Comment by pyrello** [comment]
Grooming conversation:
- Looking for a next slice through this. Issue as currently defined is "too big"
- We are agreed that we want to focus on fastest path to reducing spam and we think a CAPTCHA solution gets us there fastest.
- We would prioritize getting a solution in place over accessibility in the near term.

Proposed solution:
- Build a solution adding a CAPTCHA on forms on a partner website who is experiencing issues with spam.
- Work with TM/ISPO to resolve accessibility/security concerns.
- Potentially transition the solution from a site split to a feature split.

**Comment by joewhitsitt** [comment]
This was just bumped in an accessibility channel I watch: [Inaccessibility of CAPTCHA](https://www.w3.org/TR/turingtest/)

Of the alternatives, it seemed like the spam words validation would be the easiest for us since we can't handle user accounts for all.

**Comment by pyrello** [comment]
> There might be some other strategies for webform spam from https://www.drupal.org/docs/contributed-modules/webform/webform-add-ons#spam like maintaining a shared list of spam words to validate/reject against: https://www.drupal.org/project/webform_spam_words

I had occasion to look into this module recently. A little bit of info about how it works:
- Global configuration of word list - this means there is one list and no tuning for a particular form or form field.
- WSW is implemented as a Webform handler plugin, meaning it is something that gets added to the webform on a per form basis. The downside to this is that it either requires the webform workflow to include this step or for us to figure out how to do it programmatically. We'd have to figure out if we want and opt-in model or every form has this validation. The upside is potentially that it could be configurable per webform. Probably ideally, we'd want it as an opt-out model, where every webform has it by default but it could be removed from individual webforms if it was causing problems.

**Comment by joewhitsitt** [comment]
With the hCaptcha solution stalling due to accessibility concerns. It seems folks have had partial success with https://www.drupal.org/project/riddler

We could have a default list of Q/As but maybe allow one-offs to be created that make sense in the context of the website.

Between this and the default math option that comes with the CAPTCHA module, site owners could choose with one they implement on a per form basis.

**Comment by pyrello** [comment]
I think we should really consider figuring out an implementation for Webform Spam Words module. We have focused a lot on how to reduce bot related spam, but I think that a lot of the spam coming through is from humans. Humans can get past whatever captcha challenges we put in their way. The Spam Words module gives us tools for discouraging human spam by making it harder to just copy/paste in whatever their message is.

**Comment by briand44** [comment]
Discussed webform spam words and that we want to do some investigation there to understand how this can be implemented in a way that the list of spam words can be defined for a given form. Could move forward with CAPTCHA Math Challenge in the meantime.

**Comment by pyrello** [comment]
Just came across this: https://www.drupal.org/project/spamicide. It sounds like another version of honeypot. Maybe two honeypots per form would be better?
