### ISSUE TITLE
OneTrust privacy acknowledgement

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6490]
# Story

As a member of ISPO, I would like to have an acknowledgement banner that links to the University privacy statement on all sites using the brand bar tag manager container.

# Additional Info

Coming off of some conversations late on Friday...have something of a sense of priorities. 

We're going to want to prioritize a OneTrust acknowledgement experience (just a banner that links to /privacy) in the next sprint or two.  

Consent will come after that.

I know we have cards for this in our backlog. Haven't even looked for them yet (next step for me).  . . 

Also, got a signal that it was fine if we wanted to test the privacy ack on https://itprivacy.uiowa.edu before deploying it broader.  I thanked KC for the offer and said that if we did that, the sequence would probably be:

Step 1: popup shows up on that site.  If good and we move forward, step 2.
Step 2: popup shows up on all Drupal sites using the brand bard tag manager container. 

^^^ options, not recipe.

https://github.com/uiowa/uiowa/issues/5446
https://github.com/uiowa/uiowa/issues/3943
https://github.com/uiowa/uiowa/pull/4107

# Proposed Solution

- [x] #6492
- [x] show banner on homepage site (https://uiowa.edu)
- [ ] Communicate about this to campus
- [ ] Show banner on all uiowa.edu properties that use brand bar tag manager container - If acknowledge on one, don't show on any property for 1 year?

**Comment by briand44** [comment]
grooming conversation... 1st slice medium
