### ISSUE TITLE
Design banner in OneTrust and output on https://itprivacy.uiowa.edu for review

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6492]
# Story

As a ISPO (Information Security and Policy Office) team member, I would like to be able to see a OneTrust privacy acknowledgement on https://itprivacy.uiowa.edu so that we can provide feedback prior to implementing on all uiowa.edu properties using the brand bar tag manager container.

# Additional Info

https://app.onetrust.com/auth/login - If you don't have an account Michael, Brian, or Ben should be able to grant you access

https://my.onetrust.com/s/article/UUID-e7563ab0-d1f6-8a0f-a2c6-101b7e363fba

We will also want to understand if it is possible to no longer display the privacy acknowledgement for a specific time period on all uiowa properties once acknowledgement has happened. Not a requirement of this slice, just something to keep in mind while working on this.

# Proposed Solution

- [x] Create Privacy acknowledgement template
- [x] Deploy to https://itprivacy.uiowa.edu via brand bar tag manager
- [x] Share with Kirk Corey for feedback

# Video Recording
A recording of the onboarding/implementation call with OneTrust is available here: https://iowa-my.sharepoint.com/:v:/g/personal/mjoneill_uiowa_edu/ETu-b84M3sZClpygy6qNIMcB5kiNTOcw4_B-9VHFazZ3bw?e=tA8pQr
```[tasklist]
### Tasks
- [x] Work with Max to get both banners to look the same
- [x] Run through all the various settings in OneTrust with MO
- [x] Wait for Max to figure out how to set his banner template for uihc.org
```

**Comment by bspeare** [comment]
I an unable to view the https://my.onetrust.com/s/article/UUID-e7563ab0-d1f6-8a0f-a2c6-101b7e363fba.   I can log into https://app.onetrust.com but not the my.onetrust.com link.

**Comment by bspeare** [comment]
Which template do we want to use here?

<img width="1537" alt="Screenshot 2023-06-12 at 10 09 58 AM" src="https://github.com/uiowa/uiowa/assets/1036433/b3882237-fa4e-471f-8f15-535295b6a88b">

**Comment by briand44** [comment]
My thoughts are we either create a custom template or try the generic cookie banner.

**Comment by briand44** [comment]
@bspeare do you have the ability to create an account at https://my.onetrust.com/?

**Comment by bspeare** [comment]
No, and I already have an account on https://app.onetrust.com. 
<img width="580" alt="Screenshot 2023-06-12 at 10 19 20 AM" src="https://github.com/uiowa/uiowa/assets/1036433/0525d036-e8ef-45b6-b353-5bf6839d1e6c">

**Comment by bspeare** [comment]
We didn't cover any of this in the video, but do we want to try to deploy their production script so we can preview this while it is being developed?  <img width="1028" alt="Screenshot 2023-06-12 at 10 20 17 AM" src="https://github.com/uiowa/uiowa/assets/1036433/1a3c9f0b-5576-42fe-a4d7-3c77eb8d005a">

**Comment by bspeare** [comment]
This is the generic template content.   Do we know what we want to customize here?

<img width="790" alt="Screenshot 2023-06-12 at 10 22 20 AM" src="https://github.com/uiowa/uiowa/assets/1036433/cc2890d7-5c4d-4599-9357-e3a75a3fbd26">

**Comment by bspeare** [comment]
I'm having difficulties accessing the documentation so I will un-assign myself.  Here's what I did so far:
- Created banner https://app.onetrust.com/cookies/templates
- Added website to https://app.onetrust.com/cookies/websites
- Test script available at https://app.onetrust.com/cookies/script-integration
- Implemented test script in tag manager
  - Created Onetrust banner tag and IT Security page trigger at:
https://tagmanager.google.com/?authuser=0#/versions/accounts/1184129026/containers/6453475/versions/64

**Comment by bspeare** [comment]
Looks like the banner is now showing on https://itprivacy.uiowa.edu/ after I updated a few settings.  I'll try working on the styling now.

**Comment by bspeare** [comment]
Workflow notes:
- Edit banner at https://app.onetrust.com/cookies/templates then go to https://app.onetrust.com/cookies/scan-results/1a94bea5-5892-4aa3-aff9-99c69622f667/reports and click "Publish test" to deploy changes to the bar.

**Comment by bspeare** [comment]
Still to do (follow documentation) and based on 14:10 in the workshop video:
- Create data layer variable
- Create trigger:
  - Activate, block

**Comment by briand44** [comment]
@bspeare I'm not sure we need to do the items mentioned in https://github.com/uiowa/uiowa/issues/6492#issuecomment-1587954879 as it relates to this issue. I believe those items are related to cookie consent and this issue is scoped to privacy acknowledgement. Looking into this more.

**Comment by briand44** [comment]
Seeing the following on https://itprivacy.uiowa.edu

When I close the popup, I see an icon in the footer.

![Screenshot 2023-06-12 at 3 24 44 PM](https://github.com/uiowa/uiowa/assets/1017022/77aaae4a-82ec-4e8c-93a8-e16e4a01b469)

Once clicked opens up the consent popup and allows users to manage consent, which we don't want to be displaying at this point.

![Screenshot 2023-06-12 at 3 24 32 PM](https://github.com/uiowa/uiowa/assets/1017022/eda61b7b-a9f3-44b7-afea-fac84b029a3a)

**Comment by briand44** [comment]
Additional question probably for @mjoneill. Should this be tied to the itprivacy website scan in OneTrust or to the uiowa.edu one and then limited to only showing on itprivacy through GTM?

Update... I guess it is already limiting to the itprivacy website via GTM. Maybe the website scan this is tied to doesn't matter at this point until we get into cookie consent.

**Comment by mjoneill** [comment]
@bspeare: I've asked Moomal for help with the documentation links.  Not sure what's going on. I can't access either.

**Comment by mjoneill** [comment]
> Additional question probably for @mjoneill. Should this be tied to the itprivacy website scan in OneTrust or to the uiowa.edu one and then limited to only showing on itprivacy through GTM?
> 
> Update... I guess it is already limiting to the itprivacy website via GTM. Maybe the website scan this is tied to doesn't matter at this point until we get into cookie consent.

This sounds like a question for Moomal. I don't know that it makes a difference, or the downstream consequences of a decision today.  My gut read is that we can use the campus wide GTM and scope it to the site we are testing on via GTM...  But we should be comfortable engaging Moomal directly with questions, etc.

**Comment by mjoneill** [comment]
I'll ask about this one and put y'all on copy

**Comment by briand44** [comment]
>Should this be tied to the itprivacy website scan in OneTrust or to the uiowa.edu one and then limited to only showing on itprivacy through GTM?

The more I think about this, I don't think it matters at this point. I believe it will matter when we get into cookie consent because it will use the cookie categories that exist for that "website" but since this is just acknowledgment I doubt it matters.

**Comment by briand44** [comment]
@bspeare I see an example we had in https://github.com/uiowa/uiowa/pull/4107 of text and button. Maybe we should go with that text and button so we are forcing a user to "accept" rather than just allowing them to dismiss?

**Comment by bspeare** [comment]
Onetrust banner z-index sits above everything, but also when paired with after-content region it will look like this:

<img width="1628" alt="Screenshot 2023-06-13 at 10 19 23 AM" src="https://github.com/uiowa/uiowa/assets/1036433/0dd118fa-0add-4e42-8e53-bf853b681889">

**Comment by bspeare** [comment]
Because of the after-content conflict, we might want to switch to a floating banner like this:

<img width="1393" alt="Screenshot 2023-06-13 at 11 18 17 AM" src="https://github.com/uiowa/uiowa/assets/1036433/82fdbe5f-6e6e-49aa-b789-1ae9d0b6dd34">

**Comment by bspeare** [comment]
- Updated the banner to floating left as displayed in the screenshot above. 
- I tried switching this to the uiowa.edu website but received error messages when publishing test. 
- Still need to disable the "Preference center" floating green cookie without hiding with CSS.
- Need to ask how to change gray "X" background image "svg" to white instead of gray.

**Comment by bspeare** [comment]
I have paused the tag displaying the OneTrust banner on https://itprivacy.uiowa.edu/.  What is our next step here?

**Comment by mjoneill** [comment]
> I have paused the tag displaying the OneTrust banner on https://itprivacy.uiowa.edu/. What is our next step here?

I've been considering itprivacy.uiowa.edu as our dev site for this project.  This is what Kirk suggested we use as we build, test, and validate before deploying.

I onboard if we want to switch to another site.    Is it just a matter of changing the GTM trigger to fire on another site that also has the brand bar?

**Comment by bspeare** [comment]
You could try changing that trigger first.  If that doesn't work then:
- Add a website to https://app.onetrust.com/cookies/websites
  - Click the "publish test" button

That site should show up in https://app.onetrust.com/cookies/script-integration
- Click "Publish test" here when you click into the site entry. 
  - Compare scripts provided with the scripts use in the current paused tag.

**Comment by briand44** [comment]
@bspeare can we try adding this to sandbox.prod.drupal.uiowa.edu by changing the trigger?

**Comment by bspeare** [comment]
It is now displaying on https://sandbox.prod.drupal.uiowa.edu/.

**Comment by briand44** [comment]
@mjoneill who needs to see this? Is it just Kirk or others? I think it is ready to share from the teams perspective and then blocked until we get feedback.

**Comment by briand44** [comment]
I will share with Kirk and Max for feedback.

**Comment by bspeare** [comment]
I updated this issue with a few remaining tasks in a task list.

**Comment by briand44** [comment]
I think this can be closed as we have approval to turn this on for uiowa.edu. Going to close this and create a new issue for turning on for the homepage site.
