### ISSUE TITLE
Update to Drupal core 10.1

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6538]
# Motivation

To take advantage of fun new experimental features like SDC, it is necessary to get to Drupal 10.1.

# Proposed solution

To check if all our dependencies are compatible with Drupal 10.1, run the following command:

```
ddev composer prohibits drupal/core 10.1
```

Once all dependencies that need to be upgraded to be compatible and can be upgraded ahead of time have been upgraded, we can run the following command:

```
ddev composer require drupal/core-recommended:^10.1 drupal/core-composer-scaffold:^10.1 drupal/core-project-message:^10.1 drupal/linkit:^6.1@RC --update-with-all-dependencies
```

Please note that the linkit module needs to be upgraded at the same time as core because the version that is compatible with >=10.1 is not compatible with 10.0.

If there are problems with the above command, it is also possible to update the version constraints for the above packages in composer.json and then run

```
ddev composer update --lock
```
```[tasklist]
### Tasks
- [x] Fix deprecations
- [x] Fix tests
- [x] Fix PHPCS updates
- [x] Update `allowed_formats` module
- [x] Update default config
- [x] Update config split config
- [x] Figure out new block content permissions
- [x] Review P2LB config updates to decide whether to keep or ignore them
- [x] Figure out how to set new image loading config
```

**Comment by pyrello** [comment]
This is blocked by #6537

**Comment by pyrello** [comment]
Dropping some notes here for consideration so that we can be more prepared for this than one than we were for the D10.0 upgrade:
- Dependency update gotchas: There were items that didn't get reported with the `composer prohibits` command above.
- Having to run `composer update` instead of something more targeted.
- Config update exports from synced site and fresh install.
- Updating config splits for features and sites.
- Updated coding standards?

**Comment by pyrello** [comment]
Only one dependency being reported by `composer prohibits`:
```
drupal/linkit            6.0.2     conflicts         drupal/core (>=10.1) 
```

We know from our previous experience that we will probably have to make other updates, but we won't find those out until we try to actually run the update. Based on this, I think we can probably skip having a separate step for updating dependencies first.

**Comment by pyrello** [comment]
I'm running into issues related to https://www.drupal.org/project/drupal/issues/3326339:

![Screenshot 2023-11-13 at 1 38 21 PM](https://github.com/uiowa/uiowa/assets/709009/9a473bd0-d702-46b7-bc5a-0c3fc666d401)

_Edited to update issue link._

**Comment by pyrello** [comment]
> I'm running into issues related to https://www.drupal.org/project/drupal/issues/3326339

10.1 changed the CSS for the node form again, which broke our previous workaround from #3065. There is a patch in the issue linked above that does a good enough job fixing the form experience (making it wider) that we are able to remove our previous fix. Discussed this with the team at EoD and this was decided on as the way forward.

**Comment by pyrello** [comment]
As I'm working through config splits, I'm getting some indications that there are more changes that are not going to show up until things are saved. I already went through the feature splits, but I'm going to work back through a couple of them to see if I can trigger any changes that did not previously present themselves.

**Comment by pyrello** [comment]
For reasons I'll probably never understand, the introduction of allowed formats in core did not provide an upgrade path for folks that were using the contrib module:
https://git.drupalcode.org/project/drupal/-/blob/11.x/core/modules/text/text.post_update.php?ref_type=heads#L25-41

Meaning that we have to update them manually :|

**Comment by joewhitsitt** [comment]
@pyrello I thought allowed_formats had the upgrade path: https://www.drupal.org/project/allowed_formats

>In the 3.0.0 release, the allowed formats feature has been removed as obsolete, but we provide an update path from existing sites to move the allowed formats, as they were stored by the previous versions of the module, to Drupal >=10.1.0 way, in field settings.

**Comment by pyrello** [comment]
It did not occur to me that updating the contrib module would be the upgrade path. Thanks for making this visible.

**Comment by joewhitsitt** [comment]
Drupal. Keeping you on your toes since like forever.

**Comment by pyrello** [comment]
Putting the P2LB diff here so I can look at it again later: https://gist.github.com/pyrello/2e8faabba421c592ef3cd7707c8a2789

**Comment by pyrello** [comment]
There was a change in 10.1 that introduces a new permission `delete own files`, which is getting added automatically to roles when a site gets updated. My assumption is that we don't want to add this permission because we don't want people directly messing with files at all, since they should be working with media entities instead. I've been removing it when I notice it. Not sure if there would be an indirect issue with someone trying to delete a media entity that they had created because they weren't allowed to delete the file that was referenced?

**Comment by joewhitsitt** [comment]
>Not sure if there would be an indirect issue with someone trying to delete a media entity that they had created because they weren't allowed to delete the file that was referenced?

This is what jumped into my mind. Is there a new interface available for the user to delete a file from the media entity? If not, I am not even sure where they would encounter this action unless it is one of our few file fields (e.g. theme logo)

**Comment by pyrello** [comment]
> > Not sure if there would be an indirect issue with someone trying to delete a media entity that they had created because they weren't allowed to delete the file that was referenced?
> 
> This is what jumped into my mind. Is there a new interface available for the user to delete a file from the media entity? If not, I am not even sure where they would encounter this action unless it is one of our few file fields (e.g. theme logo)

I'm not seeing any new interface in the media edit/delete screens. I'm guessing that there would be something in the files management UI but that is suppressed/disabled when you implement media ecosystem.

**Comment by pyrello** [comment]
Whew... those config updates were a doozy!

**Comment by pyrello** [comment]
It appears that the granular block permissions we were using before never actually had an impact on a user's ability to create/update/delete inline blocks inside Layout Builder. It actually controlled access to the ability to create those blocks in the regular block management UI. For now, I think we don't want people to be able to do that, so I'm not going to populate the permissions for each block type that we had previously.

**Comment by pyrello** [comment]
New 10.1 feature:

![Screenshot 2023-11-17 at 8 50 30 AM](https://github.com/uiowa/uiowa/assets/709009/a4f504b7-68aa-4e9c-a248-6d28b81aaee5)

This is effectively an alternate way to get to editing the footer contact info block. Totally overkill, but ultimately harmless because there doesn't appear to be a way to actually do anything else.

**Comment by pyrello** [comment]
> Figure out how to set new image loading config

10.1 introduced a new core setting for displaying image fields:
```yml
      image_loading:
         attribute: eager
```
`eager` is the default because it is the behavior that predates the introduction of lazy-loading images. However, I'm thinking that we actually probably want this set to `lazy` in every case. Any cases where we should set this to `eager` instead?

**Comment by pyrello** [comment]
> > Figure out how to set new image loading config
> 
> 10.1 introduced a new core setting for displaying image fields:
> 
> ```yaml
>       image_loading:
>          attribute: eager
> ```
> 
> `eager` is the default because it is the behavior that predates the introduction of lazy-loading images. However, I'm thinking that we actually probably want this set to `lazy` in every case. Any cases where we should set this to `eager` instead?

Actually, I'm just noticing that this gets set on the media entity rather than the field that references it. Sort of interesting because it means that you can set the behavior per instance of a media reference field. I guess that's how the old behavior worked too, I just didn't realize it before.
