### ISSUE TITLE
Facilities Alerts

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6559]
# Story

As a Facilities website owner, we would like to recreate our existing alert functionality on our SiteNow v3 site so that we can continuing displaying active alerts to our users and be able to schedule Dispatch communications for each alert.

# Additional Information

- Construction Managers create alerts but don't have the ability to create other content

- They want the ability to schedule when an alert is published

- Alert content type should be similar to what they have now but mentioned that location probably should be a required field.

- They would like a block they can place using layout builder that displays current closures
    - Existing example https://www.facilities.uiowa.edu/alerts
    - They said they can be a little flexible here with how things are output, possibly teaser with title, dates, categories, that links to full node
    - Alerts/closures should no longer display once the end date has passed
    - These should stay published though, just not displayed

- They want to show alerts that reference a building on the building page and link to the full node similar to https://sandbox.prod.drupal.uiowa.edu/chemistry-building-mockup

- When an alert is created it should also create a dispatch communication?

- They would like the ability to schedule the Dispatch communication from their site and see communications that have been scheduled for the alert. Existing example https://www.facilities.uiowa.edu/node/5631/dispatch 

```[tasklist]
### Issues
- [x] https://github.com/uiowa/uiowa/issues/6561
- [ ] https://github.com/uiowa/uiowa/issues/6637
- [x] #6659
- [x] #6658
- [ ] #6677
- [ ] https://github.com/uiowa/uids/issues/770
- [ ] https://github.com/uiowa/uiowa/issues/6722
- [ ] #6805
- [ ] #6689
- [ ] https://github.com/uiowa/uiowa/issues/6813
- [ ] https://github.com/uiowa/uiowa/issues/6823
- [ ] https://github.com/uiowa/uiowa/issues/6852
- [ ] https://github.com/uiowa/uiowa/issues/6855
- [ ] https://github.com/uiowa/uiowa/issues/6880
- [ ] https://github.com/uiowa/uiowa/issues/6865
- [ ] https://github.com/uiowa/uiowa/issues/6972
- [ ] https://github.com/uiowa/uiowa/issues/6973
- [ ] https://github.com/uiowa/uiowa/issues/6897
- [x] Add label on alert node and email template for Reason for Closure
```

**Comment by joewhitsitt** [comment]
Scheduling content sounds like a slice by itself https://github.com/uiowa/uiowa/issues/723

**Comment by briand44** [comment]
Grooming conversation... 

Possibly provide ability to cancel, they have only had to cancel one that they can recall.

We may want to create a separate campaign, population, etc so we are not sending communications out to their existing subscribers.

May want to start with creating content type so that is in place for working on the scheduling content and Dispatch stuff.

- Scheduling not included in first slice.
- Create fields that currently exist on their site with the exception of the scheduling
- No moderation
- theming can come later

**Comment by joewhitsitt** [comment]
>When an alert is created it should also create a dispatch communication?

Saving the node was wired up to send a notification to Facilities web managers but isn't anymore. Without moderating the content, not sure if this is necessary anymore.

Scheduling the dispatch communication (sometimes multiple) is a separate step.

**Comment by joewhitsitt** [comment]
Just capturing that they said inactive should fall off from displays but still be published/available for those clicking-through from past emails.

**Comment by bspeare** [comment]
As a part of this work and https://github.com/uiowa/uiowa/issues/6563 and https://github.com/uiowa/uiowa/issues/6086 we should do https://github.com/uiowa/uids/issues/770 to create more variants for inline alerts.  Our current alert component is not configured for this type of implementation.  I think we should reserve the top of the page alerts for more sitewide alerts and focus the inline variants for alerts like this work and https://sandbox.prod.drupal.uiowa.edu/its-serviceinfocenter-mockup-office-365-copy and https://sandbox.prod.drupal.uiowa.edu/chemistry-building-mockup.

**Comment by joewhitsitt** [comment]
Meeting notes:

- Alert categories - would like to make it easier for construction managers to select the right ones. Currently there are only Building Entrance Closure, Parking Lot Closure, Road Closure, Sidewalk Closure, Other as checkboxes.
- There is a bit of confusion about the published/unpublished scheduling dates and the closure dates and which makes the alert visible on the alerts block. Should unpublished scheduling be disabled?
- "Project Title" is usually what they use to name the alert which comes from BuildUI.
- There was talk about the building or other location info fields but I didn't quite capture the new way to try it. @bspeare?
- Remove "Reason and details of closure" field and instead label the body that way, change the format to be minimal? This field can contain all of that and be used to capture contact information if it is a City of Iowa City type alert.

**Comment by bspeare** [comment]
Added similar meeting notes to https://github.com/uiowa/uiowa/issues/6722#issuecomment-1686861900.

**Comment by pyrello** [comment]
Since I already built an admin UI for setting the campaign ID and communication ID, I think it makes sense to leave it in. However, I think we should limit that to developers only and have the config values for campaign ID and communication ID be stored in managed configuration (`facilities_core.settings`). This means that changing those values permanently would require a code release. But I think that makes sense as we would not want to be changing those config values on the fly since the process is heavily dependent on having a communication with the correct placeholders on the template. The admin UI is effectively a convenience for us should we ever need to change to a different communication.

**Comment by cory-skeers** [comment]
Agreed re: limiting this to developers. Similar to the Thank You email stuff, I think it's too fragile to have it as an open settings for people to change without significant investment.

> The admin UI is effectively a convenience for us should we ever need to change to a different communication.

I like this idea, since it's already in place. Especially given the confusion keeping track of the differences between campaign, communication, message. And having the option of using the UI, exporting, and creating a PR also doesn't prevent just changing the settings directly and creating a PR, if a dev is comfortable.

I was initially thinking it might be good to add a message to the page to the effect of "this config is not ignored, and therefore requires a deployment" to avoid confusion, but at the same time, that's the case for a majority of our config, so maybe it's not necessary.

**Comment by briand44** [comment]
Closing this as all of the tasks have been completed for Facilities alerts that we are aware of. Turning on the production population is captured as part of the overall Facilities development epic. If we get any additional feedback related to alerts once they fully test, we can create follow ups.
