### ISSUE TITLE
`uids_base` UIDS3/4 cleanup

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6584]
# Story

As a developer, I can import UIDS4 base components for all `uids_base` components:

- _variables.scss";
- _utilities.scss";
- headings.scss";
- headline.scss";
- typography.scss;
- lists.scss
- Use https://github.com/uiowa/uids/tree/4.x/src/assets/scss as the complete list of files. 

After working on https://github.com/uiowa/uiowa/pull/6576/files, there is a number of components pulling in UIDS3 and UIDS4 components.  We might even be loading duplicate files from each library in some cases. 

# Proposed solution

```[tasklist]
### Tasks
- [ ] Audit usages of @import "uids3/ in uids_base and see if any of them can be replaced using the files in https://github.com/uiowa/uids/tree/4.x/src/assets/scss.
- [ ] Like we are doing in, https://github.com/uiowa/uiowa/pull/6654,  audit UIDS3 components that will not be moved to 4 and move them into uids_base
- [ ] Pull out V2 specific mixins from https://github.com/uiowa/uids/blob/4.x/src/assets/scss/_utilities.scss#L209-L317 and move them to uids_base for use in sitenow.scss.
- [ ] Revert the work done in [Bug] V2 card titles on dark backgrounds #6581.
- [ ] Change sitenow.scss to sitenow_v2.scss for clarity.
```
