### ISSUE TITLE
Additional Uiowa Profiles updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6618]
# Story

As an owner of Academic Profiles we would like the SiteNow team to make necessary adjustments so that existing integrations will continue to work when we launch the new Academic Profiles service.

# Additional Info

It sounds like Denny created a PR with some changes. https://github.com/uiowa/uiowa/pull/6670

These will need to be reviewed and rolled out to dev to test tippie.dev.drupal.uiowa.edu against. We won't want to roll these out to prod because they will break existing Directory Profiles functionality.

# Proposed Solution
```[tasklist]
### Tasks
- [x] Sync prod to dev for law
- [x] Check meta and seo custom code to see if it still working
- [x] Change dev endpoint back before merge?
```

**Comment by joewhitsitt** [comment]
Noticing some differences in content output:

https://tippie.uiowa.edu/people/kurt-anstreicher
https://tippie.dev.drupal.uiowa.edu/people/kurt-anstreicher

Would be nice to know what the expected output should be. Maybe they haven't finished migrating?

/sitemap still works and matches PROD.

$structured (schema) looks cleaner.

**Comment by joewhitsitt** [comment]
# DEV
<img width="807" alt="dev" src="https://github.com/uiowa/uiowa/assets/4663676/982919b2-3eae-4197-95d9-d8417c824b7a">

# PROD
<img width="674" alt="prod" src="https://github.com/uiowa/uiowa/assets/4663676/98291974-3a33-4134-bb74-07072de420f6">

**Comment by joewhitsitt** [comment]
Emailed Denny that the law.dev site is available for testing. Asked about the content diff.

**Comment by mjoneill** [comment]
Nice catch on the schema.  

If you want another set of eyes on anything, I'll need a couple of URLs to look at.

**Comment by mjoneill** [comment]
Ugh, just saw these URLs at the top.

https://tippie.uiowa.edu/people/kurt-anstreicher
https://tippie.dev.drupal.uiowa.edu/people/kurt-anstreicher

I'm going to do some SEO checking.

**Comment by joewhitsitt** [comment]
>The content differences is due to different databases and some config we’re missing in the new system.

- Denny

**Comment by mjoneill** [comment]
OK.  So, aside from the html pollution in the schema json, I'm ok with what I'm seeing elsewhere.  

Big caveat though: once this goes live, we DO need to test with Google Search Console to get them to index a page and validate the meta description, canonical, schema, etc... is coming through and not getting lost due to dom/shadow dom shenanigans (again).

**Comment by joewhitsitt** [comment]
Split off https://github.com/uiowa/uiowa/issues/6748 from this issue. Academic profiles has gone live and @pyrello rebuilt develop
