### ISSUE TITLE
Theme individual alert nodes

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6659]
# Story

As a SiteNow site owner using the alert feature, I would like my individual alert information to display in the proper order and the pages to look good.

# Additional Info

https://facilities.prod.drupal.uiowa.edu/17-2135-22-lfc-dental-science-building-and-carver-hawkeye-arena-steamcondensate-and-forced-sewer

Old site didn't have a full node display available to visitors but info can be seen https://www.facilities.uiowa.edu/alerts

# Proposed Solution
```[tasklist]
### Tasks
- [x] Enable Layout Builder for alert content type template
- [ ] Set default feature alert full node fields display/order
- [ ] Set facilities alert teaser fields display/order
- [ ] Set facilities alert full node fields display/order
- [ ] Add templates as/if necessary
```

**Comment by briand44** [comment]
Grooming conversation.... Scope to both default and Facilities, not introducing new alert type styles here.

**Comment by bspeare** [comment]
I wonder if we can use our two column with card sidebar layout for this?  Perhaps Traffic information can go in the main content area and Closure dates, Building information, Category, and Reason for Closure can go in the sidebar?

It would also be great if we could split the long titles up.  Perhaps adding in an "Alert Subhead" field would help break up the information presented here?  "_17-21/35-22 LFC Dental Science Building and Carver-Hawkeye Arena_" and _"ENGIE Project 17-21/35-22 LFC Dental Science Building & Carver Hawkeye Arena Steam/condensate and forced Sewer"_ are really long titles. 

 
![Screenshot 2023-07-21 at 10 38 05 AM](https://github.com/uiowa/uiowa/assets/1036433/377cedbe-5769-4a9e-a7b0-900a0d9f9565)

**Comment by joewhitsitt** [comment]
I like the look of the subhead, but keep in mind this data needs to wire up to dispatch where there are character length limits. I wonder if additional buckets will let them type freely and they will be caught off guard when a part is not included in the email.

I also like the yellow top-border on the sidebar.

**Comment by bspeare** [comment]
I know there's Dispatch integration that limits us, I just wonder if this would help users structure their alerts moving forward?  Maybe we could join the title and subtitle into one line for teasers?

**Comment by briand44** [comment]
My initial thoughts are that I think it looks nice. The concern I would have is that it seems like what I assume is the most important information is being displayed in the sidebar in the smaller column. Maybe that aligns with how we've themed other things but I guess it seemed like that was not the information that caught my attention first.

I like the idea of the subhead rather than the crazy long titles but I don't know enough about why they title these the way they do to understand the effects of that. We could reach out to Wendy in email to see if we could get feedback if we think that would be helpful?

**Comment by bspeare** [comment]
### Layout 

Information priority is definitely important here.  Could we perhaps switch the sidebar to display first in a `33-67` Layout?

<img width="1525" alt="Screenshot 2023-07-21 at 3 28 11 PM" src="https://github.com/uiowa/uiowa/assets/1036433/dc826491-7b4c-4509-86f3-103ae8c064b3">

## Subhead

For the subhead, could we propose that we remove the page title field and construct the title so that we can have a consistent format for campus?

Could we do this through `Product/Building + Subtitle` or something for our custom alert partners?

ITS Alert example:
`Office 365 - Otter.AI to be blocked on Office 365 - Service Announcement on Jun 30, 2023, 1:00pm - Jul 7, 2023, 1:00pm`
Facilities Alert:
`17-21/35-22 LFC Dental Science Building and Carver-Hawkeye Arena steam/condensate and forced sewer`

**Comment by GaryRidgway** [comment]
I really like the sidebar to the left! I think that allows it to be seen first for sure. Does it seem reasonable to reduce the text size on the right then? I feel like the size of that text is trying to jockey with the sidebar for relevance, and if it were maybe a little smaller, it would feel more natural

**Comment by briand44** [comment]
One other quick piece of feedback... The building for Facilities should be a link. Can't tell that by the screenshot

**Comment by bspeare** [comment]
I agree we could dial down the text size.  But maybe a slight increase with the `lead` class would help bump it up slightly to help counterbalance the card sidebar?   

<img width="1447" alt="Screenshot 2023-07-21 at 3 48 09 PM" src="https://github.com/uiowa/uiowa/assets/1036433/e58efd74-56df-47e8-9833-3dcdbe900bfc">

**Comment by pyrello** [comment]
# Suggestions:
## Default
- Place the category field in the main content under the body. I believe this is an established pattern with tags/taxonomy.
- Add "Start" and "End" labels for the two dates in Dates Affected. This will make it easier to understand the relevant information than the `[date] - [date]` format.
- Add an "Active" label to the alert full node view when Dates Affected overlaps the current moment. It will make it easier to tell at a glance that an alert is active.

## Facilities
- Add a building icon next to the building field and remove the label
- Add a date icon next to the Dates of Closure and remove the label (Still add the "Start" and "End" labels in default.

**Comment by bspeare** [comment]
I also noticed that the card image markup was rendering some extra space on the facilities layout.  We might want to look into that as well.

**Comment by pyrello** [comment]
> I also noticed that the card image markup was rendering some extra space on the facilities layout. We might want to look into that as well.

I played with this a little bit. I wasn't able to fix it by adding logic to the template file to `render|strip_tags|trim`. Might need to poke around in `preprocess_layout` to see what's going on.

**Comment by pyrello** [comment]
> > I also noticed that the card image markup was rendering some extra space on the facilities layout. We might want to look into that as well.
> 
> I played with this a little bit. I wasn't able to fix it by adding logic to the template file to `render|strip_tags|trim`. Might need to poke around in `preprocess_layout` to see what's going on.

Fixed.

**Comment by bspeare** [comment]
I've adjusted the layout based on @pyrello's feedback and a few other items listed below:

- Outputting "Traffic plan" as a button. 
- Moved location into the sidebar card with icon and proximity to building. 
- Gave the bus routes some extra visual treatment in the content area. 
- Moved the categories into the content area

I didn't see an obvious way to add "Start" and "End" labels through the date formatter.   Should we pursue this now or in a later alerts slice?

### Default:

<img width="1462" alt="Screenshot 2023-07-28 at 1 14 02 PM" src="https://github.com/uiowa/uiowa/assets/1036433/4aa838ca-5273-4711-9bed-2f5b49a30f5a">

### Facilities:

<img width="1488" alt="Screenshot 2023-07-28 at 1 10 28 PM" src="https://github.com/uiowa/uiowa/assets/1036433/a7c0a2b0-facc-473d-8e1f-4a96432e36db">

**Comment by pyrello** [comment]
> I didn't see an obvious way to add "Start" and "End" labels through the date formatter. Should we pursue this now or in a later alerts slice?

I took a look at the options and they were not what I was expecting. I thought there would be an obvious way to display the start and end date of a range separately and that they would have their own labels. I didn't see a way to do that, so let's either forget about it or look into in a future update.
