### ISSUE TITLE
As a Journal site owner, I can toggle the display of the Iowa logo in the footer

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6661]
As a Journal site owner, I can use SiteNow without the Iowa logo in the header so that I can provide a journal experience without immediate association with the University of Iowa. 

# Proposed solution
 

```[tasklist]
### Tasks
- [ ] Add a new option to the uids_base theme settings form to toggle whether the footer logo is displayed
- [ ] This new option should only be available and set if the regents theme option is also selected
- [ ] Adjust any styles based on the absence of the logo in the footer.
- [ ] Set the 91st website to use the regents theme for now, holding on setting this new footer logo option.
```

**Comment by bspeare** [comment]
Screen capture of what this would look like:

https://github.com/uiowa/uiowa/assets/1036433/aeb30a35-a115-487c-a1e3-3068f46052f2

**Comment by GaryRidgway** [comment]
I think the Regents theme is the best place for this. We are currently removing all Iowa logos with one settings, so splitting that in two seems like a good enough refactor. additionally including that in the regents theme means that it gets all updates that are introduced in the future for a theme that we maintain without splitting.

**Comment by bspeare** [comment]
According to https://brand.uiowa.edu/product-branding, only the standard Iowa logo in the footer is required.

- Iowa favicon can be the default, with the option to override (regents)
- University of Iowa should appear in all page titles (regents)
- Theme setting to show Iowa logo in footer

Maybe the only development task here would be to add a theme setting checkbox to show/hide the Iowa logo for the footer on the regents theme?

**Comment by briand44** [comment]
Grooming conversation... This option to hide logo in footer would only be available if the Regents theme option is selected. We should set the Regents option for 91st as part of this.
