### ISSUE TITLE
Rebuild icons.brand.uiowa.edu in Drupal

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6704]
# Story

As an OSC Icon creator, I would like to be able to manage, upload, and update Icons for the Icon Browser on brand.uiowa.edu. 

```[tasklist]
### Tasks
- [ ] Create a content type on brand.uiowa.edu where we capture the __icon name__, __keywords__, __categories__, and __publish date__.
- [ ] Figure out how to attach icons from https://github.com/uiowa/brand-icons
- [ ] Figure out how to generate png variants, currently being built with https://github.com/uiowa/brand-icon-browser/blob/main/imageBuild.js
- [ ] Recreate keyword search in Drupal
- [ ] Make sure GA4 events are also still tracked
- [ ] Use drupal/svg_image_field?
```

**Comment by bspeare** [comment]
I've added some tasks here outlining what the move to Drupal would look like.    Please feel free to attach new tasks that I've missed!

**Comment by quamsta** [comment]
Another thing ya'll may want to think about is ensuring GA4 events are also still tracked. @bewoldt and I built an analytics report for the existing site as well: https://lookerstudio.google.com/reporting/175ee5af-346a-43fd-87e2-a47e86ae42c9/page/vrexC

**Comment by bspeare** [comment]
Thanks @quamsta, yes they have mentioned that they use that a lot and love it!
