### ISSUE TITLE
Get P2LB ready for customer testing

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6706]
We are going to get P2LB ready for customer testing by sites who are interested in early adoption.

## User stories
- As a v2 site owner, I would like to be able to migrate a single page to its v3 version so that I can see how it works and get comfortable with it
- As a v2 site owner, I would like to be able to migrate multiple/all of my pages to their v3 versions so I can check to make sure that they are ready
- As a v2 site owner, I would like to be able to revert a single page from its v3 to its v2 version so that I can easily undo all changes to a page since it was migrated.
- As a v2 site owner, I would like to be able to revert multiple/all of my pages in case I need to start over.
- As a v2 site owner, I would like to be unable to delete the revision of my page that allows me to revert it to its v2 version.

```[tasklist]
### Tasks
- [ ] #6680
- [x] Update block styles - @bspeare #6716
- [ ] #5633
- [ ] https://github.com/uiowa/uiowa/issues/6714
- [ ] https://github.com/uiowa/uiowa/issues/6733
- [x] - ListBlock (Articles and People): Update `sitenow_p2lb_process_paragraph` to set tags in new block based on tags in paragraph settings. Added todo comments in #5613. (@cory-skeers)
- [ ] #6681
- [ ] https://github.com/uiowa/uiowa/issues/6735
- [ ] https://github.com/uiowa/uiowa/issues/6707
- [x] Ensure that paragraphs are properly removed every time when a page is converted - Brand's "Web" page shows both blocks and paragraphs after conversion - handled in #6718
- [x] Clear tempstore on conversion and reversion (https://github.com/uiowa/uiowa/issues/6706#issuecomment-1660934479)
- [ ] https://github.com/uiowa/uiowa/issues/6859
- [ ] https://github.com/uiowa/uiowa/issues/7049
- [ ] https://github.com/uiowa/uiowa/issues/6879
```

### Previously identified issues
- ~~Cards previously did not have buttons.  Are we ok with all P2LB cards having buttons? - Ben~~ Added task above. 
- Background images/banners: Do we need to convert these to image blocks if there is no text area in use?  The default gradient gets in the way. - Sean
  -  We could do https://github.com/uiowa/uiowa/issues/6368 or image block? - Ben
- Sidebar menus: All pages need the `Page w/ left sidebar` layout with the `Main navigation` block set to `Vertical` that sidebar menus will work for converted pages. 
  -  See https://hawkeyemarchingband.uiowa.ddev.site/drumhawk/drumline-auditions as an example - Ben
- Events block: Audit again to account for recent updates (eg date range, changes to how past/future events are selected, etc)
  - Events v2 currently has a bug for past events. - Ben
- if https://github.com/uiowa/uiowa/issues/5025 is done, update field_teaser to body summary as part of this transition.

### Commands to enable P2LB feature
Brand
```
ddev blt ds --site brand.uiowa.edu && ddev drush @brand.local config-split:activate p2lb -y && ddev drush @brand.local cim -y && ddev drush @brand.local uli admin/content/sitenow-converter
```

HMB
```
ddev blt ds --site hawkeyemarchingband.uiowa.edu && ddev drush @hawkeyemarchingband.local config-split:activate p2lb -y && ddev drush @hawkeyemarchingband.local cim -y && ddev drush @hawkeyemarchingband.local uli admin/content/sitenow-converter

**Comment by GaryRidgway** [comment]
For persisting v2 revisions, I have a proposition for an enhancement.

- When converting, we flag the v2 revision as `persistent`
- Whenever a user saves a page, we count the `total number` of revisions, and we count the number of `persistent` revisions.
- Then, we delete non-`persistent` revisions from oldest to newest until the total number of non-`persistent` revisions is equal to the `max amount of revisions - persistent revisions`
- This should keep the amount of revisions to the max while keeping all persistent revisions

**Comment by cory-skeers** [comment]
It was possible to have a 5 column section eg https://brand.uiowa.edu/platform

There's not a great matchup for this. Right now, p2lb creates a 4 column section followed by a 1 column section, leading to one really big card for the fifth.

**Comment by pyrello** [comment]
> When converting, we flag the v2 revision as persistent

@GaryRidgway The conversion process already includes a process where we track the last revision ID before the conversion happened:
https://github.com/uiowa/uiowa/blob/93816fd85a80bd6ee71447892014e934445802c1/docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.module#L105-L117

**Comment by GaryRidgway** [comment]
> > When converting, we flag the v2 revision as persistent
> 
> @GaryRidgway The conversion process already includes a process where we track the last revision ID before the conversion happened:
> 
> https://github.com/uiowa/uiowa/blob/93816fd85a80bd6ee71447892014e934445802c1/docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.module#L105-L117

Sweet! That is super helpful!

**Comment by pyrello** [comment]
It appears that sometimes the paragraph contents of `field_section_content_block` does not get properly removed at the end of a conversion. I've observed it when converting the "Web" page on the Brand website.

Added an item to the tasks above.

**Comment by pyrello** [comment]
> Carousel items without captions are not being converted but do not throw an error/inform you that carousel items need a caption to be converted.

I think this is flying under the radar a little bit as a potential bit of functionality that doesn't exist in p2lb yet but it's actually something we need to figure out and its a blocker for eventually rolling this out until we do.

The carousel paragraph in V2 is being converted into a slider in V3. A slider item requires a headline. A carousel item consist of just an image, option caption, styles, and unique ID. So the caption is the only thing we could potentially use to create a headline in the slider item. The fact that it isn't filled in is a problem for being able to migrate the data.

Here are some possible solutions:
- Track down all the empty image captions in carousel's and force users to update them :|
- Make the headline of the slider item not required
- Create a carousel block in V3
- Map the carousel to another block type like the image gallery

**Comment by cory-skeers** [comment]
> Here are some possible solutions:
> 
> * Track down all the empty image captions in carousel's and force users to update them :|
> * Make the headline of the slider item not required
> * Create a carousel block in V3
> * Map the carousel to another block type like the image gallery

Another (more complicated and mixed) option could be to check if all items have a caption, and if so, convert to a slider, and if not, convert to an image gallery.

As I typed that up, though, I'm not sure I like the idea of having two very completely different outcomes based on whether or not all captions were used. I do think the image gallery is an effective conversion path for carousel, though, and I believe we've done that elsewhere going from v1 to v3 (maybe classrooms?).

**Comment by pyrello** [comment]
Just encountered this error while doing a conversion:

```
Warning: Undefined array key 0 in sitenow_p2lb_process_section() (line 241 of modules/custom/sitenow_p2lb/sitenow_p2lb.module)
```

**Comment by bspeare** [comment]
I think removing the required headline on the slider would be my favorite solution here.

**Comment by pyrello** [comment]
> Cards - Videos - added in v2 text field not captured when page is converted

The card in V2 body format allows media elements. The card in V3 excerpt format does not allow media elements.

Some options:
- Allow media in V3 card excerpt field
- Data loss in the conversion
- Figure out some rules that allow us to deal with this in a graceful way (e.g. split the video out into a text area immediately following the card)

**Comment by pyrello** [comment]
> I think removing the required headline on the slider would be my favorite solution here.

So, I was on board with this until I realized that the carousel item field allows unlimited elements. The slider has a max of 4

**Comment by GaryRidgway** [comment]
A compromise would be to take the first four items of a carousel, put those in a slider, then put the rest in an image gallery? That would be a consistent implementation, and would allow us to cover all bases?

I'm not sure how many times carousels would be converted to slider vs slider+gallery, but I can't imagine its a ton of times?

**Comment by bspeare** [comment]
I like @GaryRidgway's suggestion.

**Comment by pyrello** [comment]
Here is another issue with compatibility between the carousels and sliders: Sliders are limited to one column sections, while carousels can be used in sections with any number of columns. Here is an example of a carousel that would not be possible with our current limitations on sliders (and I think would not look good as a slider + image gallery): https://hawkeyemarchingband.uiowa.edu/meet-next-generation-marching-herky

The more that we are discussing it, the more I think that the slider is just not aligned in purpose with the carousel and therefore makes it a bad place to move that content. I'm definitely leaning towards just using the image gallery, which seems more aligned in purpose to the carousel.

**Comment by GaryRidgway** [comment]
I am completely fine with just doing a gallery then, the galleries look good!

Edit:[ I guess it depends on your pictures though](https://sandbox.prod.drupal.uiowa.edu/meet-next-generation-marching-herky)

**Comment by pyrello** [comment]
An issue with carousel => image gallery: Each carousel item has a caption that is stored with it. This caption is different from the global caption that is stored on the image media entity. Our images field in our image gallery block is just a direct reference to a media item - as opposed to an intermediate paragraph acting as a field collection, which is what is happening with the carousel item. In fact the image gallery has no notion of a caption at all. The global caption doesn't even show up.

**Comment by pyrello** [comment]
> Cards - Videos - added in v2 text field not captured when page is converted

If anyone is aware of any examples in the wild of this, it would be helpful.

**Comment by cory-skeers** [comment]
> An issue with carousel => image gallery: Each carousel item has a caption that is stored with it. This caption is different from the global caption that is stored on the image media entity. Our images field in our image gallery block is just a direct reference to a media item - as opposed to an intermediate paragraph acting as a field collection, which is what is happening with the carousel item. In fact the image gallery has no notion of a caption at all. The global caption doesn't even show up.

The global caption should be getting output as the photo gallery caption, like in https://now.prod.drupal.uiowa.edu/news/2022/10/recapping-weekend-basketball-football-and-fun-iowa

Edit: It doesn't help that it in v2 the carousel caption can be different from the global caption, though.

Also, realized you may be referring to the on-page display, in which case there are no captions--caption is only visible in the expanded lightbox.

**Comment by pyrello** [comment]
> caption is only visible in the expanded lightbox

Good catch. I missed that.

In my mind, messing with the global caption as part of this update is a whole can of worms. The image can theoretically be used in multiple places. What if there is already a global caption on the image?

**Comment by cory-skeers** [comment]
Ran into an issue with

https://github.com/uiowa/uiowa/blob/3558b3161fcc40f3b7aa45c00bb96a70e6fae4b8/docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.module#L98-L100

The `sitenow_p2lb_process_section` can return `FALSE` in the case where a paragraph section couldn't be loaded, but there's no check here for that case, and so you end up with a boolean being set as part of the layout section list.

I've only run into it in a case where I'd been messing around with things and had ended up with deleted paragraph references, but we should either skip that paragraph section assuming it is missing or broken, or fail the full node's transition and report an error.

Update: I added a quick check for this, where for each paragraph section processed, it will only update if it was successful. This is effectively skipping over any paragraph sections that failed to load, but continues processing the rest of the node.

**Comment by cory-skeers** [comment]
> > caption is only visible in the expanded lightbox
> 
> Good catch. I missed that.
> 
> In my mind, messing with the global caption as part of this update is a whole can of worms. The image can theoretically be used in multiple places. What if there is already a global caption on the image?

If there's already a global caption, and also if the same image is used in multiple carousels in a site. Not sure if that is a common (or even ever) usage, but if so, the latter carousel use would overwrite the former.

I wonder if we might be hitting a point where it'd be helpful to audit current carousel usage to get a better idea what we're working with?

**Comment by cory-skeers** [comment]
> Just encountered this error while doing a conversion:
> 
> ```
> Warning: Undefined array key 0 in sitenow_p2lb_process_section() (line 241 of modules/custom/sitenow_p2lb/sitenow_p2lb.module)
> ```

Hrm...The line it's referencing is `$formatter = $w2d[$num_cols] ?: 'one';` and it's resolving to `'one'` in that case (with the additional warning).

I think this means that we have a single extra 'fluid' paragraph in the paragraph section we're processing, and so resolving to 'one' and creating a single column section is the expected behavior according to the current logic.

Would be good to track down and example and confirm though, and either update to account for that (maybe define `0` as `one` explicitly in `$w2d`), or update the logic in the section column processor to prevent this condition.

**Comment by pyrello** [comment]
> I wonder if we might be hitting a point where it'd be helpful to audit current carousel usage to get a better idea what we're working with?

I was wondering the same thing.

**Comment by bspeare** [comment]
<img width="1044" alt="Screenshot 2023-07-28 at 5 01 20 PM" src="https://github.com/uiowa/uiowa/assets/1036433/d3e65840-c34c-4488-b8cd-3aa62d640f30">


> Cards previously did not have buttons. Are we ok with all P2LB cards having buttons?

It seems like we should ignore migrating the link text for cards?  Since it was required but never displayed I don't think we should automatically add a button to each card.  

Card conditions:

- If there's a link + link text, and a title - link the title only and delete the link text?
- If there's a  link + link text, and no title - display circle button?

**Comment by pyrello** [comment]
> It seems like we should ignore migrating the link text for cards? Since it was required but never displayed I don't think we should automatically add a button to each card.

Oh, this would be a good question for Sondra!

I'm wondering if we should make this configurable? We could have a config setting that indicates whether this text should be kept and displayed or ignored, and incorporate that setting into the logic that determines how to process the card. That way, a site owner could decide ahead of time and not have to lose those button labels if they want them.

For the first pass, we could create the config setting without adding a UI for setting it. Then we could just set it via the Config Import UI or via drush for early adopter sites. 

Either way, I think we should turn #6714 into an issue to handle the variety of potential outcomes for cards and make sure we have all our cases covered.

**Comment by pyrello** [comment]
> How do we handle videos in V2 card body?

I'm adding this as a consideration in #6714 and changing the wording to reflect the underlying issue: 

> V2 card body format is less restrictive than V3 card excerpt format

**Comment by bspeare** [comment]
@pyrello can we migrate the video into the media field or are these cards with images and videos?

**Comment by bspeare** [comment]
@pyrello good idea of making it configurable!

**Comment by bspeare** [comment]
Reminder that we do have HMB stage site that @joewhitsitt set up for card testing which has https://hawkeyemarchingband.stage.drupal.uiowa.edu/test-page. 

```
ddev blt sync --site hawkeyemarchingband.uiowa.edu --define drush.aliases.remote=hawkeyemarchingband.test && ddev drush @hawkeyemarchingband.local config-split:activate p2lb -y && ddev drush @hawkeyemarchingband.local uli admin/content/sitenow-converter
```

**Comment by pyrello** [comment]
> Background images/banners: Do we need to convert these to image blocks if there is no text area in use? The default gradient gets in the way.

- If a section has a background image:
  - If the section has only a text area AND the text area's contents can be convert to the minimal format without data loss:
    - Create a banner block with the section's background image and the text areas text inside a 1-column section
 - Otherwise:
   - Convert the section's background image into an image block inside a 1-column section.
   - If there are any paragraphs create an additional section or sections to place the blocks inside.

**Comment by joewhitsitt** [comment]
Is anyone else encountering `Trying to access array offset on value of type null in sitenow_p2lb_process_paragraph() (line 571 of modules/custom/sitenow_p2lb/sitenow_p2lb.module).`

```php
// Link isn't required. Check for one, or set to null.
      $link = $paragraph->field_card_link?->value[0] ?: NULL;
```

**Comment by bspeare** [comment]
@joewhitsitt Yes, maybe work for that should happen in https://github.com/uiowa/uiowa/pull/6713?

**Comment by pyrello** [comment]
> Is anyone else encountering `Trying to access array offset on value of type null in sitenow_p2lb_process_paragraph() (line 571 of modules/custom/sitenow_p2lb/sitenow_p2lb.module).`
> 
> ```
> // Link isn't required. Check for one, or set to null.
>       $link = $paragraph->field_card_link?->value[0] ?: NULL;
> ```

I reverted this change in this PR.

**Comment by cory-skeers** [comment]
For reference, these are all paragraph entities on a v2 site, along with their fields. It might be useful to use to create a YAML or something similar along with mappings of where fields are going in v3, but also can be used as a general reference.

To get this, I essentially used
```
$bundles = array_keys(\Drupal::service('entity_type.bundle.info')->getBundleInfo('paragraph'))
```
to get all the bundles of paragraphs (includes 'v3' bundles like timeline item)
and then
```
foreach ($bundles as $bundle) { $fields[$bundle] = array_keys(\Drupal::service('entity_field.manager')->getFieldDefinitions('paragraph', $bundle));}
```
to grab the fields attached to each of the given bundles.

<details>
<summary>
Paragraph Bundle => [fields]
</summary>

```
[
    "accordion" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_accordion_item",
      "field_uip_classes",
      "field_uip_colwidth",
      "field_uip_display_title",
      "field_uip_id",
      "field_uip_title",
    ],
    "accordion_item" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_accordion_item_body",
      "field_accordion_item_title",
      "field_uip_id",
    ],
    "articles" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_articles_more",
      "field_articles_more_path",
      "field_reference",
      "field_uip_classes",
      "field_uip_colwidth",
      "field_uip_display_title",
      "field_uip_id",
      "field_uip_items",
      "field_uip_pager",
      "field_uip_title",
    ],
    "blockquote" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_blockquote_cite",
      "field_blockquote_content",
      "field_blockquote_footer",
      "field_uip_classes",
      "field_uip_colwidth",
      "field_uip_id",
    ],
    "card" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_card_body",
      "field_card_image",
      "field_card_link",
      "field_card_subtitle",
      "field_card_title",
      "field_uip_classes",
      "field_uip_colwidth",
      "field_uip_id",
    ],
    "carousel" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_carousel_item",
      "field_uip_classes",
      "field_uip_colwidth",
      "field_uip_display_title",
      "field_uip_id",
      "field_uip_title",
    ],
    "carousel_image" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_carousel_image_caption",
      "field_carousel_image_image",
      "field_uip_classes",
      "field_uip_id",
    ],
    "events" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_events_audiences",
      "field_events_department",
      "field_events_event_types",
      "field_events_gen_interests",
      "field_events_keywords",
      "field_events_more",
      "field_events_more_path",
      "field_events_past",
      "field_events_results",
      "field_uip_classes",
      "field_uip_colwidth",
      "field_uip_display_title",
      "field_uip_id",
      "field_uip_title",
    ],
    "featured_content" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_featured_content",
      "field_uip_classes",
      "field_uip_colwidth",
      "field_uip_display_title",
      "field_uip_id",
      "field_uip_title",
    ],
    "image_gallery" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_image",
      "field_uip_classes",
      "field_uip_colwidth",
      "field_uip_display_title",
      "field_uip_id",
      "field_uip_title",
    ],
    "people" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_people_more",
      "field_people_more_path",
      "field_people_sort",
      "field_reference",
      "field_uip_classes",
      "field_uip_colwidth",
      "field_uip_display_title",
      "field_uip_id",
      "field_uip_items",
      "field_uip_pager",
      "field_uip_title",
    ],
    "section" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_section_alignitems",
      "field_section_container",
      "field_section_content_block",
      "field_section_image",
      "field_section_justifycontent",
      "field_section_title",
      "field_uip_classes",
      "field_uip_id",
    ],
    "text" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_text_body",
      "field_uip_classes",
      "field_uip_colwidth",
      "field_uip_id",
    ],
    "uiowa_collection_item" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_automatically_open",
      "field_collection_body",
      "field_collection_headline",
    ],
    "uiowa_contact" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_uiowa_contact_address",
      "field_uiowa_contact_label",
      "field_uiowa_contact_phone",
    ],
    "uiowa_slide" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_collection_headline",
      "field_uiowa_slide_content",
      "field_uiowa_slide_image",
      "field_uiowa_slide_link",
    ],
    "uiowa_timeline_item" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_timeline_body",
      "field_timeline_date",
      "field_timeline_heading",
      "field_timeline_icon",
      "field_timeline_link",
      "field_timeline_media",
    ],
    "webform" => [
      "id",
      "uuid",
      "revision_id",
      "langcode",
      "type",
      "status",
      "created",
      "parent_id",
      "parent_type",
      "parent_field_name",
      "behavior_settings",
      "default_langcode",
      "revision_default",
      "revision_translation_affected",
      "field_uip_classes",
      "field_uip_colwidth",
      "field_uip_display_title",
      "field_uip_id",
      "field_uip_title",
      "field_webform",
    ],
  ]
  ```
</details>

**Comment by cory-skeers** [comment]
> It might be useful to use to create a YAML or something similar along with mappings of where fields are going in v3

FWIW, In retrospect, if I were writing this today, the general paragraph section to layout builder section would be much the same, but the actual paragraph item to block conversion would be written more in line with this as a concept, in matching things like migration patterns. It would also allow for _some_ test coverage.

That said, it would require a fairly significant refactor, and some field to field mappings are not straightforward and require some processing, so it would also entail a bit of preprocess logic (like in migrations) that would need to be taken into account as part of the refactor.

So...might not be warranted at this point, but at least the field list can give us a reference to audit against.

**Comment by bspeare** [comment]
A few outstanding questions from Eod on https://hawkeyemarchingband.stage.drupal.uiowa.edu/test-page:

- Should people and articles using "Masonry" and "Grid" styles be converted to use the "Display as Grid - 3 columns" option on the list block?
- Should articles using "Masonry" and "Grid" styles be converted to use the "Display as Grid - 3 columns" option on the list block?  
  - If so, we need something like https://github.com/uiowa/uiowa/issues/5180.

**Comment by pyrello** [comment]
> Should people and articles using "Masonry" and "Grid" styles be converted to use the "Display as Grid - 3 columns" option on the list block?

Yes

> - Should articles using "Masonry" and "Grid" styles be converted to use the "Display as Grid - 3 columns" option on the list block?
>   - If so, we need something like https://github.com/uiowa/uiowa/issues/5180.

I'm interested in doing a small amount of probing to see how much effort might be involved in getting the V3 featured content to the point where it could support this.

**Comment by pyrello** [comment]
Something I'm noticing while I test #6713 is that when the node is converted or reverted to a previous revision, if there were any LB changes in the tempstore, those are retained and that is what the user sees when they visit the Layout tab. I think this behavior is confusing and I'd be inclined to clear the tempstore when these actions happen to prevent the user seeing results that don't match up and potentially saving the old layout (which could be the pre-conversion version of the page). All you have to do to cause the tempstore to have a value is visit the Layout tab, so a user could potentially visit that tab (out of curiosity), then convert the node, then visit the Layout tab again and see the old representation of the page.

**Comment by pyrello** [comment]
> - Sidebar menus: All pages need the Page w/ left sidebar layout with the Main navigation block set to Vertical that sidebar menus will work for converted pages.
>   - See https://hawkeyemarchingband.uiowa.ddev.site/drumhawk/drumline-auditions as an example - Ben

My best idea about how to handle this reflects one of the realities about how P2LB already works. In V2, you could effectively have a section that contains rows with different numbers of columns. Layout Builder doesn't work like that, so instead we create a new section every time we encounter a new row with a different column counts. If a page displays a  sidebar menu (has a child menu item + remove sidebar regions is unchecked), we insert a page w/ sidebar layout as the first section and place a menu block in the sidebar region. If the content in the first section is a full-width element, we place it in the content slot of the page w/ sidebar layout. When we encounter a row with more than one column, we create a new section (which is what would have happened anyways).

This approach means that most pages with menus will look different, but hopefully most will not look broken. We can add a warning to the reporting tool.

Here is a potential way to tell whether a node has a menu link: https://api.drupal.org/api/drupal/core%21modules%21menu_ui%21menu_ui.module/function/menu_ui_get_menu_link_defaults/9

**Comment by pyrello** [comment]
> Clear tempstore on conversion and reversion

I think this will be relevant: https://drupal.stackexchange.com/questions/311236/programmatically-adding-block-into-layout-builder-layout

**Comment by bspeare** [comment]
As I mentioned in planning today, I think the dev team should run P2LB conversions on sites and offer them to customers to review on stage and give them a time period to review the changes.  We could provide a list of items that didn't convert like carousel captions, etc and explain why they are not available in v3.     This could either be planned for each sprint or done by the support person during their shift.   I think this would help get us moving a lot faster and allow us to bypass the remaining issues, training, documentation, and governance.

**Comment by bspeare** [comment]
If we did do that, are we in a position to email the remaining 80 V2 site owners something like this below?  What steps would be left on our end to get P2LB to this type of implementation? 

> Dear owner of `sitename.uiowa.edu`, As you may know, `sitename.uiowa.edu` is on an older version of SiteNow V2 and will need to be upgraded to V3 of SiteNow in order to get the latest updates from the SiteNow platform. This past month we have finished a tool that will convert your V2 site to V3 for you.   As a part of this process, we are offering to convert your `V2` to `V3` and set it up for you at `sitename.stage.drupal.uiowa.edu` to review.    Would you be interested in this site conversion or would you prefer to build a completely new site within the SiteNow V3 platform?

**Comment by cory-skeers** [comment]
> If we did do that, are we in a position to email the remaining 80 V2 site owners [...] What steps would be left on our end to get P2LB to this type of implementation?

I think the primary thing for us to check is that, after turning off the p2lb and V2 splits, the sites they are reviewing in stage or essentially V3. Things like can't revert to a V2 version of a page and accidentally break things... the actual cleanup of databases can happen later, but I think we at least need it in a reasonably v2-less state at that point, and not confusing them with leaving p2lb tools or v2 revisions active and available to stumble upon.

So... comfortable

1. Syncing site to stage or dev
2. Turning on P2LB
3. Running the convert
4. Turning off P2LB
5. Turning off V2
6. Removing (or removing access to) reverting to V2 revisions

**Comment by joewhitsitt** [comment]
i am trying not to sound negative about the progress the team has made on this. from what i see it looks very promising. i get that we want to move fast with this but I feel we have moved away from the end goal of "we will automatically convert your site by this date" to the "there is a new tool available to convert and check pages against. let us know when you think you are in a good spot so that you can benefit from the rest that v3 has to offer."

>are we in a position to email the remaining 80 V2 site owners something like this below

I don't think so, but I could be persuaded with a couple low-friction conversions.

I think you are also assuming that it isn't intuitive enough or that the training/documentation cost will be huge. we don't know until we have some folks try it.

i mentioned DEV/STAGE in planning because i wasn't sure were could call things stable yet without some actual conversions. ideally, after some pilot tests, i'd love to run the rest in PROD so that we aren't tasked with syncing.

if i was tasked with this, i am not as comfortable making content/layout builder tweaks to other peoples' websites.

**Comment by bspeare** [comment]
I still think this is a tool for "we will automatically convert your site by this date", and people might find it super easy to use too.  I just think it would be easiest to completely convert the site, make slight adjustments that we know are necessary (like sidebar menus, or card updates) and turn off V2 and let users build and review from there.   For some customers like brand, I think it would make sense for us to convert it and update the layouts as needed.    It just seems like the single page conversions will really slow the process down.

**Comment by pyrello** [comment]
Had a conversation with Sondra about next steps for enabling P2LB on the Brand website. I think we are ready to go ahead with turning it on for them whenever. I explained the caveat about drafts newer than the last published page identified in #6859. They are going to look at what they have coming up to decide how soon they could take this on. We discussed a timeframe of up to 2-4 months for them to have it turned on. This would allow them some time to get familiar with Layout Builder and new possibilities for putting content together, see how that intersects with content that needs to be updated, and request changes where they are not able to find a new/better alternative for the things that are changing between V2 and V3. That will also allow some time for us to be able to work on their requests without immediately dropping everything.

**Comment by pyrello** [comment]
IMO, I think we can close this issue. We have already enabled P2LB on Brand, which was our main test case. We have 6 sites that have completed the conversion. I don't think we are going to have an explicit customer testing phase as we once may have envisioned.
