### ISSUE TITLE
Images using the wrong aspect-ratio size

### ISSUE THREAD

**Issue by bewoldt** [uiowa/uiowa#6710]
# Problem
I'm seeing different images used depending on whether I'm logged in vs logged out. The images should be using the 16:9 widescreen size and not the square.

Page: https://dos.uiowa.edu/about-us/staff

**Logged in**
![Screen-Shot-2023-07-28-at-1 08 42-PM](https://github.com/uiowa/uiowa/assets/731952/685bef5e-c408-4667-a8cc-c026631cc449)

**Logged out**
![Screen-Shot-2023-07-28-at-1 09 56-PM](https://github.com/uiowa/uiowa/assets/731952/4b809717-b921-4f22-a27c-855f4b17f00d)

# Proposed Solution

```[tasklist]
### Tasks
- [ ] try and reproduce the issue
- [x] Recreate the page without replicate and see if the issue remains
- [x] Review https://github.com/uiowa/uiowa/pull/6452 and the issue it resolved and see if that fix is still working
- [ ] Sync to stage if needed and if we can reproduce the issues there truncate cache tables to see if that fixes the issue
```

# Contact

Update Jessica B of  https://iowalionseyebank.org if this is fixed.

**Comment by bspeare** [comment]
I flushed the image-cache on 8/9/23 at 9:43am and this appeared to fix it.   I will check back in on this tomorrow to see if it has reverted back.

**Comment by bspeare** [comment]
Checking this on 8/10 and the images are back to the wrong format for anonymous users.   Any cache clearing does not appear to solve this issue.

**Comment by joewhitsitt** [comment]
I brought up in grooming what might have been a similar issue https://github.com/uiowa/uiowa/issues/6383. I'd love to know if this is reproducible elsewhere.

**Comment by bspeare** [comment]
Just checked this again and the images appear to be rendering as expected.

**Comment by bspeare** [comment]
Just check this again and the squares are back.  Still an issue.

**Comment by joewhitsitt** [comment]
Just pull this site down with rsynced public files, interacting with the site using the `main` branch and could not reproduce the issue highlighted by the screenshot. Quite a bit of cache tables are truncated on sync that aren't always covered by a `cr` so I am wondering if there is just something that isn't getting cleared out in PROD.

**Comment by briand44** [comment]
Grooming conversation...This started after card 4.x. People have square profile images but these are showing as widescreen. Seems like caching may be involved here. set some breakpoints to see if things are being cleared appropriately https://github.com/uiowa/uiowa/pull/6452. Could sync to stage if needed and if we can reproduce the issues there truncate cache tables. So far this is the only site/page that has reported this. Could recreate the page manually and see if the issue happens on the new page?

**Comment by joewhitsitt** [comment]
Not currently seeing the issue in prod. One person's original photo does not crop well for widescreen, the rest look as expected.

We could see if similar testing instructions from #6452 reproduces the issue.

**Comment by joewhitsitt** [comment]
Seeing the issue again today. Going to look at this while it is fresh again.

**Comment by joewhitsitt** [comment]
At this point I wonder if @bewoldt would give us permission to recreate this page and contents and update the menu link and link from the about page to point to a new page.

I tried to replicate the page locally and got a WSOD error related to UUIDs. It just seems like this page got corrupted somehow.

Though I saw the issue again today, I have not been able to manually reproduce the issue which has made it difficult to diagnose any differences with xdebug.

**Comment by joewhitsitt** [comment]
Website has been updated with a new page. Formerly node/107. Now https://dos.uiowa.edu/node/201. Menu and about page link have been updated.

**Comment by joewhitsitt** [comment]
Going to wait and monitor the page to see if this it is resolved by just recreating the page.

**Comment by joewhitsitt** [comment]
I reproduced the issue this morning. 😞

**Comment by bewoldt** [comment]
I saw the same issue on a different website today. Url is https://imu.uiowa.edu/meetings-and-events/contact-event-services.

**Comment by bewoldt** [comment]
FYI, In case anyone was trying to check on the Dean of Students site, we have switched over to use the Profiles Directory on that page.

**Comment by joewhitsitt** [comment]
thanks for letting us know

**Comment by bspeare** [comment]
Looks like this is currently happening with https://iowalionseyebank.org/donor-tributes with an articles list block.

**Comment by bspeare** [comment]
https://iowalionseyebank.org/donor-tributes found a workaround for the issue by resizing the images to a height of 480.

**Comment by bspeare** [comment]
Looks like the workaround for https://github.com/uiowa/uiowa/issues/6710#issuecomment-2794794489 did not last long.  The wrong aspect ratio is back.

**Comment by briand44** [comment]
Grooming conversation... Previously suspected the media was getting cached for something else and rendering that version. We are setting a max-age of 0 in media preprocess. That gets looped through multiple times. 

Could create workaround page examples that use different image aspect ratios and watch them and see if we can propose them as a workaround. Could try with featured content as well as people list block. May need to keep an eye on these pages for  awhile since it seems to come and go, maybe related to deployments. Noting that the latest example are articles not people.

Any relation to https://github.com/uiowa/uiowa/issues/8616?

Discussed scoping this to identifying and solving the issue but if we identify the issue and determine the fix will take quite an effort, we can slice that off separately.

**Comment by bspeare** [comment]
It sounds like we might want to prioritize this work because they want the automated feed from the articles list so that older content will drop off as new content is added. 

Workarounds proposed:

- The featured content block won't work for this because there isn't an option to adjust the image aspect ratio and that it is a manual feed.  And you can't hide the article published date. 
- Square and Circle crops on the article list block create the same size results. 
- Widescreen crops the images too much. 
- Grid of single cards

Customer will use a manual grid of cards for now but is waiting for us to fix the issue.

**Comment by joewhitsitt** [comment]
Updated the IS to contact the customer once fixed.

**Comment by joewhitsitt** [comment]
i am going to poke around and see if I can reliably reproduce. i'll setup an example on sandbox but also plan to step through the render process.

**Comment by joewhitsitt** [comment]
I've setup a test page at https://sandbox.prod.drupal.uiowa.edu/image-aspect-ratio-bug-test

Just to confirm I have this right: people list using grid widescreen and article list using grid circle switch back to the image format defaults square, widescreen respectively?

**Comment by joewhitsitt** [comment]
Ack! reproduced but reverse? logged in, the square version is being served instead of the set widescreen format.

<img width="1243" alt="Image" src="https://github.com/user-attachments/assets/072a33ac-da43-4cea-88f8-b43f9a6fb152" />

So far the steps to reproduce were to clear varnish for the grid page (widescreen) then the profile page (square), visit anonymously the profile first, then the grid. then logged in i see the grid page with a square format. WAT?! 🤷

**Comment by bspeare** [comment]
@joewhitsitt you can view another example at https://iowalionseyebank.org/donor-tributes-test, the second article list lower down on the page.

**Comment by joewhitsitt** [comment]
Thanks @bspeare. Was there a particular image that was doing it there? i'll keep this in mind but so far i have been unable to reproduce it the same way i did on sandbox.

the other difference i notice here is that they aren't using the person profile image but rendering a body image no-crop for the article and then using the articles list to display square/circle

**Comment by bspeare** [comment]
<img width="511" alt="Image" src="https://github.com/user-attachments/assets/9e4212a0-4af3-4053-8723-682fec2bced2" />

Yes, these zoomed in ones are doing it when I visit the page when not logged in.

**Comment by joewhitsitt** [comment]
Starting to think we can move our `layout_builder_custom_preprocess_media` `$referring_item` stuff where we attempt to set the viewmode (which actually happens early in the pipeline) to later in the process where the view mode can be applied "just in time" during `template_preprocess_card`

This stuff was untouched/assumed during the card_4x work.

Reason being, there are several steps between where field_image called in with the default view mode and is mapped to the card as-is causing a potential issue during the card render process. Another benefit would be removing the max-age=0 if I can make sure caching is not affected by moving this logic (pagers, focal point, file replace, media reference)

Till monday.

**Comment by joewhitsitt** [comment]
okay. i encountered the lionseyebank issue. i think it was because I had loaded the /news page where the images were widescreen. will try to reproduce it consistently.
