### ISSUE TITLE
safety.uiowa.edu launch tasks for Aug 9

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6720]
* Hayley says they are good to launch Safety on the 9th.  
```[tasklist]
### Tasks
- [x] Remove the redirect from safety to police
- [x] Clery integration: small pdf is not being attached to CSA form - they are ok with launching with a buggy form. -Clery is working on a "fix"
- [x] Update CSA form error text to include special email address for submitting a report - check with Hayley for this
- [x] Make sure that the lost and found embeds are removed  - check with Hayley on this
- [x] Create issue to deprovision https://hawkalert.uiowa.edu and redirect to https://safety.prod.drupal.uiowa.edu/emergency-notifications
- [x] Adjust no results text for firelog "No fires reported in on-campus residences in the last 60 days." for on load
```

**Comment by bspeare** [comment]
I updated with a task list after getting some clarification from Hayley.

**Comment by joewhitsitt** [comment]
>Remove the redirect from safety to police

This will be handled by the domain switch from 703

**Comment by joewhitsitt** [comment]
Added `Adjust no results text for firelog "No fires reported in on-campus residences in the last 60 days." for on load` task that we might want to do ahead of launch day if we have capacity

**Comment by joewhitsitt** [comment]
Changed to "No fires reported in on-campus residences during this date range." to work for both on load and a specified date range. Asking Hayley if it is okay.

**Comment by e-marie-w** [comment]
Followup: #6764
