### ISSUE TITLE
Initiate conversations with staff council and probe converting using P2LB if they are open to it

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6771]
Added some comments for this at https://github.com/uiowa/uiowa/issues/6706#issuecomment-1673939064. (@bspeare)
```[tasklist]
### Tasks
- [x] Continue converting the site locally and surface and fix any problems that come up
- [ ] https://github.com/uiowa/uiowa/issues/6814
- [x] ~Clone prod to dev and run the conversion and verify that there are no errors that occur outside of our local testing~ We are testing directly in prod
- [ ] https://github.com/uiowa/uiowa/issues/6841
```

**Comment by bspeare** [comment]
Makur and Kellie from Staff Council are OK with us setting up a stage site with converted P2LB pages. How should we proceed?

**Comment by bspeare** [comment]
Staff council does use a lot of "featured content" blocks.  It would be great if we could do something with https://github.com/uiowa/uiowa/issues/5180 or at least introduce the grid and list functionality. 

<img width="1149" alt="Screenshot 2023-08-11 at 3 22 49 PM" src="https://github.com/uiowa/uiowa/assets/1036433/ca1ecf93-dd1f-438f-a7b1-200bd0c4ad7c">
<img width="1538" alt="Screenshot 2023-08-11 at 3 23 38 PM" src="https://github.com/uiowa/uiowa/assets/1036433/c933adb7-c473-4db3-91a3-2f609e4d5636">

**Comment by bspeare** [comment]
With the probe work in https://github.com/uiowa/uiowa/pull/6775, we could update these featured content blocks to use our grid classes, however they would be left aligned cards. 

<img width="1630" alt="Screenshot 2023-08-14 at 11 50 59 AM" src="https://github.com/uiowa/uiowa/assets/1036433/2061895e-c3ff-4a08-ba88-ac96a131bc53">

**Comment by pyrello** [comment]
> however they would be left aligned cards

Why is that?

**Comment by bspeare** [comment]
@pyrello we don't have the all the "card" alignment styles available on the block.
