### ISSUE TITLE
Setup uiowa06

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6797]
# Story

As a web team, we need to setup uiowa06 application so that we can use it to put CCOM sites on it t

# Additional Info

- Waiting for Acquia to provision
- I will make sure the appropriate teams have access to the application once it's provisioned.

# Proposed solution

- [x] Grant appropriate teams permissions to this application
- [x] Follow docs here https://wiki.uiowa.edu/display/drupaldev/Acquia+Applications - now here https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/Acquia%20Cloud/Acquia%20Cloud.aspx

```[tasklist]
### Tasks
- [x] Ensure RA's Update process is set to "Do not inform".
- [x] Create and install a new SSL certificate in production.
- [x] PHP settings
- [x] New Relic app ID
- [x] Enable production mode on prod
- [x] New Relic variables on prod
- [x] Enable Log Forwarding
- [x] Enable Platform Email from configuration for each environment.
- [x] Contact Nikki about log forwarding
- [x] Added secrets.settings.php to each environment
- [x] Add slack webhook variable to all ENV
- [x] Create release
- [x] Ensure that teams have the necessary access to the new application - working session for ddev?
- [x] Switch the code branch to develop-build for develop, main-build for stage, and after a release the build tag for prod.
- [x] Install the default site on each environment - stage install failed
- [x] Scheduled task for cron and prod site counts.
- [x] Delete the WELCOME tag that a new application ships with.
```

**Comment by briand44** [comment]
Blocked until the application is provisioned and I grant the appropriate teams permissions to this app.

**Comment by briand44** [comment]
This has finished provisioning. I will grant permissions to the application.

**Comment by briand44** [comment]
I updated the ITS team name to OSC and added access to the appropriate teams.

**Comment by briand44** [comment]
We'll want to make this visible to UIHC MarCom devs when this work starts

**Comment by joewhitsitt** [comment]
not sure if it is in the docs yet (lazy sharepoint user), but app.applications on data.its will need to be updated with this application as well

https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/blob/main/config/app.php?ref_type=heads

**Comment by joewhitsitt** [comment]
It looks like uiowa06.prod has been registered in new relic so there is an app id to use: https://onenr.io/0Zw0bkBvejv

**Comment by bspeare** [comment]
This should be done, hopefully.
