### ISSUE TITLE
Figure out how to remove P2LB and V2 from a site after its owners have signed off on the conversion

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6814]
# Proposed solution

```[tasklist]
### Tasks
- [x] Create `sitenow_p2lb` uninstall hook that can be triggered by `drush pm:uninstall sitenow_p2lb`
- [x] Remove protected revision field content
- [x] Remove every revision for page up to and including the protected revision
- [x] Investigate whether `sitenow_v2` entry in sites blt file is used anywhere in automated commands or other code
- [x] If not, update all site's blt files manually to remove the `sitenow_v2` entry
- [x] Turn off P2LB split
- [x] Turn off V2 split
- [x] Identify any other things that need to be addressed
```

**Comment by briand44** [comment]
Grooming conversations...

Need to account for:

- Turn off P2LB split
- Turn off V2 split
- Remove protected revision field content
- Remove every revision prior to the protected revision and remove protected revision
- Identify any other things we have yet to identify and discuss
- Make sure `sitenow_v2` split removed from site’s blt file - this may need to happen at a different time?

**Comment by joewhitsitt** [comment]
sitenow_v2 blt file instances: https://github.com/search?q=repo%3Auiowa%2Fuiowa%20%22split%3A%20sitenow_v2%22&type=code

I think we should leave the related code however for future use: [postDrupalInstall](https://github.com/uiowa/uiowa/blob/main/blt/src/Blt/Plugin/Commands/MultisiteCommands.php#L996-L1004)

**Comment by pyrello** [comment]
I updated the IS to include a proposed solution based on the grooming conversation during planning yesterday.

**Comment by briand44** [comment]
thank you @pyrello

**Comment by joewhitsitt** [comment]
Going to get caught up on this and see where I can help move it forward
