### ISSUE TITLE
Ability for webmaster to create landing page experience

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6838]
# Story

As a marketer crafting a landing page experience, I can create my page without having to get the assistance of a developer / add custom and non-supported html to the page.
```[tasklist]
### Tasks
- [ ] Maybe a custom "background image" layout that only offers 67/33 where you can upload a background image and we limit the amount of blocks available for placement?  Text area and webform to start?
- [ ] Allow `<br>` in BASIC_HTML text format for blockquotes
- [ ] Size modifier classes in UIDS to allow for larger heading sizes https://github.com/uiowa/uids/issues/721
```

**Comment by briand44** [comment]
Is this a duplicate of #2665?

**Comment by bspeare** [comment]
I think this is a duplicate of https://github.com/uiowa/uiowa/issues/2665.  I'm fine with closing https://github.com/uiowa/uiowa/issues/2665 and starting fresh with this issue.

**Comment by bspeare** [comment]
Closing this and consolidating at https://github.com/uiowa/uiowa/issues/6773.
