### ISSUE TITLE
Probe to determine what it will take to get to D10

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#6856]
# Story

As a web team, we can understand what it is going to take for us to update to Drupal 10 so that we can plan, slice and prioritize accordingly to meet the November 1st timeline.

# Additional Info

Suggested that [uiowa_auth](https://github.com/uiowa/uiowa_auth) be handled separately so that any changes are complete so that it is clear to others using the module that it is d10 ready. We could have a separate branch for d10 so that d9 sites could still use it.

# Proposed Solution

Probe to understand what all needs to happen to get us to D10. 
Outline necessary steps so we can tackle them as separate slice(s). 
Update custom module's .info.yml files to be compatible with D9/10 rather than D8/9.

- [ ] Update our modules to be d10 compatible
  - [ ] Change uiowa_auth 2.x to a stable release and check authentication in DEV with drupal 10.
- [ ] Change to contrib versions for deprecated core modules/themes. https://github.com/uiowa/uiowa/issues/6856#issuecomment-1721807413
- [x] #6901
  - [ ] Remove unused modules? [entity_embed](https://github.com/uiowa/uiowa/issues/5312)?
- [ ] Upgrade blt-project and update BLT to apply the changes from acquia/drupal-recommended-project minus the acquia CMS stuff
- [ ] [Try upgrading to drupal 10 through composer](#6537).

**Comment by joewhitsitt** [comment]
Welp...

```
ddev composer prohibits drupal/core 10
Info from https://repo.packagist.org: #StandWithUkraine
drupal/acquia_purge                  1.2.0         requires          drupal/core (^8.9 || ^9)                                 
drupal/administerusersbyrole         3.0.0         requires          drupal/core (^8 || ^9)                                   
drupal/allowed_formats               1.5.0         requires          drupal/core (^8.8 || ^9)                                 
drupal/better_normalizers            1.0.0-beta5   requires          drupal/core (^8.7.7 || ^9)                               
drupal/big_pipe_sessionless          2.0.0         requires          drupal/core (^9)                                         
drupal/components                    2.4.0         requires          drupal/core (^8.7.7 || ^9)                               
drupal/config_filter                 2.2.0         requires          drupal/core (^8.8 || ^9)                                 
drupal/config_ignore                 3.0.0-beta1   requires          drupal/core (^8.8 || ^9)                                 
drupal/core-recommended              9.5.9         requires          drupal/core (9.5.9)                                      
drupal/crop                          2.2.0         requires          drupal/core (^8.8 || ^9)                                 
drupal/cshs                          3.6.0         requires          drupal/core (^8 || ^9)                                   
drupal/ctools                        3.7.0         requires          drupal/core (^8.8 || ^9)                                 
drupal/devel                         4.1.5         requires          drupal/core (^8.8 || ^9)                                 
drupal/draggableviews                2.0.1         requires          drupal/core (^8 || ^9)                                   
drupal/editor_advanced_link          2.0.0         requires          drupal/core (^9.2)                                       
drupal/embed                         1.5.0         requires          drupal/core (^8.7.7 || ^9)                               
drupal/entity_embed                  1.2.0         requires          drupal/core (^8.8 || ^9)                                 
drupal/entity_print                  2.6.0         requires          drupal/core (^8 || ^9)                                   
drupal/entity_reference_unpublished  1.3.0         requires          drupal/core (^8 || ^9)                                   
drupal/externalauth                  1.4.0         requires          drupal/core (^8 || ^9)                                   
drupal/field_delimiter               1.1.0         requires          drupal/core (^8 || ^9)                                   
drupal/focal_point                   1.5.0         requires          drupal/core (^8.8 || ^9)                                 
drupal/fragments                     2.0.2         requires          drupal/core (^8.7.7 || ^9)                               
drupal/fullcalendar                  1.0.0-alpha3  requires          drupal/core (^8 || ^9)                                   
drupal/google_analytics              4.0.0         requires          drupal/core (^8.9|^9.0)                                  
drupal/google_tag                    1.5.0         requires          drupal/core (^8.8 || ^9)                                 
drupal/hal                           1.0.3         requires          drupal/core (^9)                                         
drupal/heading                       1.6.0         requires          drupal/core (^8 || ^9)                                   
drupal/iframe_title_filter           1.1.0         requires          drupal/core (^8 || ^9)                                   
drupal/jquery_ui                     1.4.0         requires          drupal/core (^8 || ^9)                                   
drupal/jquery_ui_datepicker          1.2.0         requires          drupal/core (^8 || ^9)                                   
drupal/jquery_ui_slider              1.1.0         requires          drupal/core (^8 || ^9)                                   
drupal/jquery_ui_touch_punch         1.0.0         requires          drupal/core (^8 || ^9)                                   
drupal/layout_builder_restrictions   2.14.0        requires          drupal/core (^8.8.0 || ^9.0)                             
drupal/layout_builder_shortcuts      1.0.1         requires          drupal/core (^8.8 || ^9)                                 
drupal/lazy                          3.11.0        requires          drupal/core (^8.8 || ^9)                                 
drupal/mailsystem                    4.3.0         requires          drupal/core (^8.7.7 || ^9)                               
drupal/media_entity_facebook         3.0.0-beta2   requires          drupal/core (^8 || ^9)                                   
drupal/media_entity_file_replace     1.0.0         requires          drupal/core (^8.7.7 || ^9)                               
drupal/media_entity_twitter          2.7.0         requires          drupal/core (^8.8 || ^9)                                 
drupal/media_library_theme_reset     1.1.0         requires          drupal/core (^8 || ^9)                                   
drupal/media_thumbnails              1.0.0-alpha6  requires          drupal/core (^8 || ^9)                                   
drupal/menu_breadcrumb               1.16.0        requires          drupal/core (^8 || ^9)                                   
drupal/menu_link_weight              1.0.0-beta5   requires          drupal/core (^8 || ^9)                                   
drupal/migrate_plus                  5.2.0         requires          drupal/core (^9.1)                                       
drupal/migrate_tools                 5.1.0         requires          drupal/core (^9.1)                                       
drupal/mimemail                      1.0.0-alpha4  requires          drupal/core (^8.8.2 || ^9)                               
drupal/node_view_permissions         1.5.0         requires          drupal/core (^8 || ^9)                                   
drupal/oembed_providers              2.0.2         requires          drupal/core (^9.0)                                       
drupal/override_node_options         2.6.0         requires          drupal/core (^8 || ^9)                                   
drupal/paragraphs                    1.14.0        requires          drupal/core (^9.2)                                       
drupal/photoswipe                    3.1.1         requires          drupal/core (^9.3)                                       
drupal/private_content               2.0.0-rc3     requires          drupal/core (^8 || ^9)                                   
drupal/purge_queuer_coretags         3.2.0         requires          drupal/core (^8.7.7 || ^9)                               
drupal/rabbit_hole                   1.0.0-beta10  requires          drupal/core (^8 || ^9)                                   
drupal/replicate                     1.0.0         requires          drupal/core (^8 || ^9)                                   
drupal/replicate_ui                  1.0.0         requires          drupal/core (^8 || ^9)                                   
drupal/reroute_email                 2.1.1         requires          drupal/core (^8.8 || ^9)                                 
drupal/responsive_table_filter       1.2.0         requires          drupal/core (^8 || ^9)                                   
drupal/robotstxt                     1.4.0         requires          drupal/core (^8.0 || ^9.0)                               
drupal/schema_metatag                2.3.0         requires          drupal/core (^8.0 || ^9.0)                               
drupal/simplei                       1.2.0         requires          drupal/core (^8 || ^9)                                   
drupal/siteimprove                   1.12.0        requires          drupal/core (^8 || ^9)                                   
drupal/superfish                     1.4.0         requires          drupal/core (^8 || ^9)                                   
drupal/swiftmailer                   2.2.0         requires          drupal/core (^8.9.11 || ^9.0.10)                         
drupal/theme_permission              2.0.0-beta1   requires          drupal/core (^8 || ^9)                                   
drupal/tvi                           1.0.0-rc4     requires          drupal/core (^8 || ^9)                                   
drupal/webform                       6.1.3         requires          drupal/core (^8.8 || ^9)                                 
drupal/workbench_email               2.2.1         requires          drupal/core (^8 || ^9)                                   
drupal/core                          10.0.0        requires          symfony/console (^6.2)                                   
acquia/blt-project                   dev-main      does not require  symfony/console (but v4.4.49 is installed)               
drupal/core                          10.0.0        requires          symfony/dependency-injection (^6.2)                      
acquia/blt-project                   dev-main      does not require  symfony/dependency-injection (but v4.4.49 is installed)  
drupal/core                          10.0.0        requires          symfony/event-dispatcher (^6.2)                          
acquia/blt-project                   dev-main      does not require  symfony/event-dispatcher (but v4.4.44 is installed)      
drupal/core                          10.0.0        requires          symfony/http-foundation (^6.2)                           
acquia/blt-project                   dev-main      does not require  symfony/http-foundation (but v4.4.49 is installed)       
drupal/core                          10.0.0        requires          symfony/http-kernel (^6.2)                               
acquia/blt-project                   dev-main      does not require  symfony/http-kernel (but v4.4.50 is installed)           
drupal/core                          10.0.0        requires          symfony/mime (^6.2)                                      
acquia/blt-project                   dev-main      does not require  symfony/mime (but v5.4.13 is installed)                  
drupal/core                          10.0.0        requires          symfony/routing (^6.2)                                   
acquia/blt-project                   dev-main      does not require  symfony/routing (but v4.4.44 is installed)               
drupal/core                          10.0.0        requires          symfony/serializer (^6.2)                                
acquia/blt-project                   dev-main      does not require  symfony/serializer (but v4.4.47 is installed)            
drupal/core                          10.0.0        requires          symfony/validator (^6.2)                                 
acquia/blt-project                   dev-main      does not require  symfony/validator (but v4.4.48 is installed)             
drupal/core                          10.0.0        requires          symfony/process (^6.2)                                   
acquia/blt-project                   dev-main      does not require  symfony/process (but v4.4.44 is installed)               
drupal/core                          10.0.0        requires          symfony/yaml (^6.2)                                      
acquia/blt-project                   dev-main      does not require  symfony/yaml (but v4.4.45 is installed)                  
drupal/core                          10.0.0        requires          twig/twig (^3.4.3)                                       
acquia/blt-project                   dev-main      does not require  twig/twig (but v2.15.5 is installed)                     
drupal/core                          10.0.0        requires          guzzlehttp/guzzle (^7.5)                                 
acquia/blt-project                   dev-main      does not require  guzzlehttp/guzzle (but 6.5.8 is installed)               
drupal/core                          10.0.0        requires          guzzlehttp/psr7 (^2.4)                                   
acquia/blt-project                   dev-main      does not require  guzzlehttp/psr7 (but 1.9.1 is installed)                 
drupal/core                          10.0.0        requires          asm89/stack-cors (^2.1)                                  
acquia/blt-project                   dev-main      does not require  asm89/stack-cors (but 1.3.0 is installed)                
drupal/core                          10.0.0        requires          psr/log (^3.0)                                           
acquia/blt-project                   dev-main      does not require  psr/log (but 1.1.4 is installed) 
```

**Comment by joewhitsitt** [comment]
Oye. Our composer file is `acquia/blt-project` https://github.com/acquia/drupal-recommended-project is the replacement but BLT is not in it. We might be able to compare the output (d10 by default, separate step for BLT) of that and update bits in ours as needed.

**Comment by joewhitsitt** [comment]
Besides version constraints and library checks, here are some of the things our modules need:

~sitenow_events, sitenow_alerts, uiowa_search, uids_base:~ Done
```
The core/jquery.once asset library is deprecated in Drupal 9.3.0 and will be removed in Drupal 10.0.0. Use the core/once library instead. See https://www.drupal.org/node/3158256
```

~uids_base:~ Done
```
themes/custom/uids_base/theme-settings.php	202	Missing explicit access check on entity query.
The core/jquery.cookie asset library is deprecated in Drupal 9.0.0 and will be removed in Drupal 10.0.0. Use the core/js-cookie library instead. See https://www.drupal.org/node/3104677
```

~layout_builder_custom:~ Done
```
modules/custom/layout_builder_custom/css/layout_builder_custom.overrides.css	0	The #drupal-off-canvas selector is deprecated in drupal:9.5.0 and is removed from drupal:10.0.0. See https://www.drupal.org/node/3305664.
```

~sitenow_migrate:~ Done
```
modules/custom/sitenow_migrate/src/Plugin/migrate/CreateMediaTrait.php (in context of class Drupal\sitenow_migrate\Plugin\migrate\source\Articles)	262	Missing explicit access check on entity query.
modules/custom/sitenow_migrate/src/Plugin/migrate/CreateMediaTrait.php (in context of class Drupal\sitenow_migrate\Plugin\migrate\source\Pages)	262	Missing explicit access check on entity query.
modules/custom/sitenow_migrate/src/Plugin/migrate/CreateMediaTrait.php (in context of class Drupal\sitenow_migrate\Plugin\migrate\source\People)	262	Missing explicit access check on entity query.
```

~sitenow_p2lb:~ Done
```
modules/custom/sitenow_p2lb/src/Commands/P2LbCommands.php	93	Missing explicit access check on entity query.
```

~uiowa_area_of_study:~ Done
```
modules/custom/uiowa_area_of_study/uiowa_area_of_study.install	37	Missing explicit access check on entity query.
```

~uiowa_core:~ Done
```
modules/custom/uiowa_core/src/EntityProcessorBase.php	189	Call to deprecated constant REQUEST_TIME: Deprecated in drupal:8.3.0 and is removed from drupal:10.0.0. Use Drupal::time()->getRequestTime();
modules/custom/uiowa_core/src/Form/RegionSettings.php	75	Missing explicit access check on entity query.
modules/custom/uiowa_core/src/Form/RegionSettings.php	189	Missing explicit access check on entity query.
```

~sitenow_people:~ Done
```
modules/custom/sitenow_people/sitenow_people.install	39	Missing explicit access check on entity query.
modules/custom/sitenow_people/sitenow_people.install	81	Missing explicit access check on entity query.
```

~uiowa_aggregator:~ Done
```
modules/custom/uiowa_aggregator/uiowa_aggregator.module	182	Missing explicit access check on entity query.
```

~sitenow:~ Done
```
profiles/custom/sitenow/sitenow.install	212	Missing explicit access check on entity query.
profiles/custom/sitenow/sitenow.install	279	Missing explicit access check on entity query.
profiles/custom/sitenow/sitenow.install	436	Missing explicit access check on entity query.
profiles/custom/sitenow/sitenow.install	1001	Missing explicit access check on entity query.
profiles/custom/sitenow/sitenow.install	1160	Missing explicit access check on entity query.
profiles/custom/sitenow/sitenow.install	1448	Missing explicit access check on entity query.
profiles/custom/sitenow/sitenow.install	2408	Missing explicit access check on entity query.
```

**Comment by joewhitsitt** [comment]
>Deprecated or obsolete core extensions installed. These will be removed in the next major version.	[Aggregator (read more)](https://www.drupal.org/node/3223395#s-aggregator), [CKEditor (read more)](https://www.drupal.org/node/3223395#s-ckeditor), [Classy (read more)](https://drupal.org/node/3223395#s-classy), [Stable (read more)](https://www.drupal.org/project/drupal/issues/3308890)

We have these issues thus far:

Aggregator: https://github.com/uiowa/uiowa/issues/5064
Ckeditor: https://github.com/uiowa/uiowa/issues/5667 (we may need to use cke4 contrib at first)
Classy: https://github.com/uiowa/uiowa/issues/6277

**Comment by joewhitsitt** [comment]
It is complaining about the `access metatag site_verification__google` permission for webmaster. https://www.drupal.org/node/3193348

update: I think we could try removing this from config, re-saving metatag config and people permissions to see if it has been replaced by something else.

**Comment by joewhitsitt** [comment]
> Oye. Our composer file is `acquia/blt-project` https://github.com/acquia/drupal-recommended-project is the replacement but BLT is not in it. We might be able to compare the output (d10 by default, separate step for BLT) of that and update bits in ours as needed.

Been poking at this. It doesn't look like there is too much difference between blt-project and drupal-recommended-project and could be something we layer in as part of this. Some things we will obviously not want `acquia/acquia-cms-starterkit`

**Comment by joewhitsitt** [comment]
Started an uiowa_auth 2.x branch and PR https://github.com/uiowa/uiowa_auth/pull/9 for Drupal 10 support

Update: cut a 2.0.0 release and added it to the related PR

**Comment by joewhitsitt** [comment]
I done did mess up regarding uiowa_auth - https://github.com/uiowa/uiowa_auth/issues/10

**Comment by joewhitsitt** [comment]
Closing with merge of https://github.com/uiowa/uiowa/pull/6892. Further slices have been created.
