### ISSUE TITLE
 OSC Search Campaign Landing Page

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6860]
OSC is looking to create a focused landing page experience that continues the narrative started in the ad creative. OSC wants to give visitors an opportunity to fill out a form and explore some deeper topic areas like admission requirements, live in Iowa City, or majors.

## Current pages

Landing page: https://uiowa.edu/go/university-ranking-3
Thank you page: https://uiowa.edu/go/university-ranking-3/thank-you
Auto-response email: https://uiowa.edu/admin/structure/webform/manage/landing_page_introduce_yourself_/handlers

```[tasklist]
### Tasks
- [x] Get thank you page redirect working https://uiowa.edu/go/university-ranking-3/thank-you
- [x] Hide icon images on mobile for https://uiowa.edu/go/university-ranking-3
- [x] Fix uneven mobile form spacing for https://uiowa.edu/go/university-ranking-3
- [x] Try different background image variations provided by the brand team for top banner on https://uiowa.edu/go/university-ranking-3
- [x] Adjust mobile appearance of stat blocks so that they are centered
- [x] Finish auto-response email
```

**Comment by bspeare** [comment]
This page is now in a campaign and complete.
