### ISSUE TITLE
D10 Contrib updates continued

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6957]
When you take a task below, add your initials to the end. Check the box when it's completed. If you open a separate PR, replace the task below with the PR.

```[tasklist]
### Tasks
- [x] `drupal/editor_advanced_link` - JW
- [x] `drupal/focal_point` - BS
- [x] https://github.com/uiowa/uiowa/pull/6958
- [x] Remove `drupal/fullcalendar` module - JW
- [x] https://github.com/uiowa/uiowa/pull/6970
- [x] `drupal/layout_builder_restrictions` - BS
- [x] `drupal/media_entity_facebook` - BS
- [x] `drupal/media_entity_file_replace` - JW
- [x] `drupal/media_entity_twitter` - BS
- [x] `drupal/media_thumbnails` GAR
- [x] `drupal/migrate_plus` - JW
- [x] `drupal/migrate_tools` - JW
- [x] `drupal/mimemail` - JW
- [x] https://github.com/uiowa/uiowa/pull/6975
- [x] Remove `oembed_providers` module
- [x] https://github.com/uiowa/uiowa/pull/6954
- [x] https://github.com/uiowa/uiowa/pull/6963
- [x] `drupal/reroute_email` GAR
- [x] `drupal/schema_metatag` GAR
- [x] `drupal/simplei` - BS
- [x] `drupal/siteimprove` - BS
- [x] `drupal/stage_file_proxy` - BS
- [ ] https://github.com/uiowa/uiowa/issues/4623
- [x] https://github.com/uiowa/uiowa/pull/6966
```

**Comment by bspeare** [comment]
For the `fullcalendar` removal, do we remove the config first and then have a followup issue to remove the module?  Or can both be done in the same pr?

**Comment by pyrello** [comment]
> For the `fullcalendar` removal, do we remove the config first and then have a followup issue to remove the module? Or can both be done in the same pr?

Uninstall and config removal go first.

**Comment by GaryRidgway** [comment]
Migrate plus was already transitioned, marked as done

**Comment by GaryRidgway** [comment]
After looking at the code diffs for `google_tag`, I'm starting to think that it is not really very low hanging fruit. Removing my assignment until other LHF are done.

**Comment by GaryRidgway** [comment]
[Made a new collective PR](https://github.com/uiowa/uiowa/pull/6967)

**Comment by pyrello** [comment]
> After looking at the code diffs for `google_tag`, I'm starting to think that it is not really very low hanging fruit. Removing my assignment until other LHF are done.

It seems like the transition to the 2.x version may require more scrutiny than we want to invest at this point. However, the 8.x-1.6 version is also compatible with D10 without as many changes to vet. I'm looking into that smaller task.

**Comment by pyrello** [comment]
I removed `google_analytics` and `migrate_plus` since they were completed in the last issue.

**Comment by pyrello** [comment]
The path list is changing in `google_tag`:

```diff
-  path_list: "/admin*\n/batch*\n/node/add*\n/node/*/edit\n/node/*/delete\n/user/*/edit*\n/user/*/cancel*"
+  path_list: "/admin*\n/batch*\n/node/add*\n/node/*/edit\n/node/*/delete\n/node/*/layout\n/taxonomy/term/*/edit\n/taxonomy/term/*/layout\n/user/*/edit*\n/user/*/cancel*\n/user/*/layout"
```

Do we want to update our path list to match?

**Comment by pyrello** [comment]
> Do we want to update our path list to match?

Discussed in EoD: let's inherit the changes.

**Comment by bspeare** [comment]
For Siteimprove, do we need to set something so that it is enabled locally for testing?  I see that we turned it off for local syncing way back in https://github.com/uiowa/uiowa/pull/2037/files.

**Comment by pyrello** [comment]
> For Siteimprove, do we need to set something so that it is enabled locally for testing? I see that we turned it off for local syncing way back in https://github.com/uiowa/uiowa/pull/2037/files.

I think you could potentially manipulate the local settings.php file to deactivate the local split and enable the prod split.

**Comment by joewhitsitt** [comment]
I think this has worked in the past:
```
$config['config_split.config_split.local']['status'] = FALSE;  
$config['config_split.config_split.prod']['status'] = TRUE;
```

**Comment by bspeare** [comment]
Thanks @joewhitsitt, that worked great.  There is a mysterious new checkbox on the Siteimprove configuration page.   

<img width="818" alt="Screenshot 2023-10-06 at 8 45 57 AM" src="https://github.com/uiowa/uiowa/assets/1036433/ce694697-836c-4c96-a774-13accd0a4646">

**Comment by bspeare** [comment]
Can I add https://github.com/uiowa/uiowa/pull/6977 to this work?

**Comment by pyrello** [comment]
> Can I add #6977 to this work?

Can it be done before we update core to D10? The reason I would think you couldn't is because of namespace collisions, but I haven't actually tried it.

**Comment by bspeare** [comment]
@pyrello the project page lists it for 9 or 10.

**Comment by joewhitsitt** [comment]
for migrate_tools, tested commands again using https://github.com/uiowa/uiowa/pull/6964 instructions. We are on Drush 11 so we should be good.

**Comment by joewhitsitt** [comment]
We need to wait for next release for oembed_providers to be removed from composer.json. It just missed the deadline today.

mimemail might need to wait till we get swiftmailer -> symfony mailer to a stable spot to reduce testing complexity

**Comment by pyrello** [comment]
> mimemail might need to wait till we get swiftmailer -> symfony mailer to a stable spot to reduce testing complexity

It seems like we are not using `mimemail`?
```
acquia/blt-project  dev-develop  requires  drupal/mimemail (^1.0@alpha)
```

**Comment by joewhitsitt** [comment]
ah. i thought brand was. interesting

**Comment by joewhitsitt** [comment]
Realized better_normalizers can be removed similar to fullcalendar, i updated to the wrong version of migrate_tools. looks like migrate_plus is also the wrong version for d10 compatibility. Also spotted stage_file_proxy.

Working on those now

**Comment by joewhitsitt** [comment]
Moved better_normalizers to #6959 as HAL was being removed as part of it. Need to look closer to see if that can be removed as well.

**Comment by pyrello** [comment]
It looks like everything is done here except #4623. I moved that into In Progress and I think we can consider that one separately so it doesn't hold this up.
