### ISSUE TITLE
Final step of D10 upgrade

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#6959]
Tasks that all need to happen at the same time as the last step to handling the upgrade.

```[tasklist]
### Tasks
- [x] Remove better_normalizers which should remove HAL
- [x] Verify that classy theme is working https://github.com/uiowa/uiowa/pull/6977
- [x] https://github.com/uiowa/uiowa/pull/6898
- [x] https://github.com/uiowa/uiowa/issues/5064
- [x] Remove schemadotorg module
- [x] Remove embed, entity_embed once 6898 is merged/deployed
- [x] https://github.com/uiowa/uiowa/issues/7001
- [x] https://github.com/uiowa/uiowa/issues/5589
- [x] #7003
- [x] #7009
- [ ] #7010
- [ ] #6537
- [x] Confirm rest of BLT project is ready
- [x] Update feature splits config
- [x] Update site splits config
```

**Comment by briand44** [comment]
Grooming Conversation... 

if we have any deprecated code that is still in use, we will need to account for that as part of this. Should already be handled but might not be a bad idea to double check.

May need a scheduled release, not sure yet.

**Comment by pyrello** [comment]
I'm removing #6931 in favor of listing out the individual items that were contained in it.

**Comment by pyrello** [comment]
Removed `block_content_permissions` from the list because I'm not seeing it listed in the `composer prohibits` output anymore.

**Comment by pyrello** [comment]
We have to decide how we are going to handle the `theme_permission` module. It doesn't have a D10 composer compatible version. I think there might be a way to instruct the composer.json file to override or ignore the compatibility issue. Or we could move a copy of the module into our repository. I'm kind of leaning towards the latter.

**Comment by joewhitsitt** [comment]
Move a copy local and then apply the patch? https://www.drupal.org/project/theme_permission/issues/3290027

**Comment by pyrello** [comment]
> Move a copy local and then apply the patch? https://www.drupal.org/project/theme_permission/issues/3290027

Patch was already applied in previous D10 work. The reason this is coming up now is that I didn't realize at the time that the patch wouldn't help with composer.

I'm kind of assuming we would just copy the patched version of the module from its current location in `contrib` to `custom`.

**Comment by pyrello** [comment]
Next up: Fixing all the new PHPCS errors.

**Comment by pyrello** [comment]
> Next up: Fixing all the new PHPCS errors.

I fixed all the issues that could be fixed automatically. Here is a list of the remaining issues: https://gist.github.com/pyrello/2f1896ec277cbdafa023fc7c4295e28c

**Comment by pyrello** [comment]
We have some config that is being reported as different after a fresh install, so I'm going to try a different tack for updating it. I think this is going to look like doing a fresh install on the `d10` branch, but not totally sure if that makes sense.

**Comment by pyrello** [comment]
Done with feature split config updates.
