### ISSUE TITLE
Webteam Launch Checklist for High Priority Sites

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#6969]
Adding some extra checks here that we might want to take when we are looking to launch high priority sites. 

```[tasklist]
### General
- [ ] Review "Pre-launch" checklist on https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/SiteNow%20Drupal%209/Launching%20a%20Site%20in%20Drupal%209/Launching%20a%20Site%20in%20Drupal%209.aspx
- [ ] Look for placeholder content or default content from the original install
- [ ] Check site information for site email
- [ ] Check find text for .prod links
- [ ] Spelling errors and typos
```

```[tasklist]
### Menus
- [ ] Check for consistent usage of vertical or horizontal menus on the site
- [ ] Check all breakpoints on the main navigation and recommend shortening the number of links if they are overflowing the page
- [ ] Check for hard-coded menu links
- [ ] Check to see if menu links were created manually, if they were, recommend attaching each page through the node menu settings
- [ ] Check footer menus
```

```[tasklist]
### Blocks
- [ ] Check for more than 2-3 custom block types per page and recommend the number of blocks types for readability and visual consistency
- [ ] Check for CTAs using "edge to edge" and recommend using the "normal" option for users on larger screens
- [ ] Check for usages of ALL CAPS on pages
- [ ] Check for stat component being used for page title/text areas instead of numbers and suggest that readability is reduced with capitalization
- [ ] Check if multiple cards are used in the same section and verify that they are all using the same card style for consistency
- [ ] Check for consistent use of similar blocks in layout rows
```

```[tasklist]
### Colors
- [ ] Check for generous use of background colors/patterns and offer recommendations to reduce the amount of background colors and patterns if page appears too busy
```

```[tasklist]
### Layout
- [ ] Check for spacing between sections - is there enough for readability?
- [ ] Check for extra whitespace at top of page or bottom, and recommend they update the section containers to "remove top spacing" or "remove bottom spacing"
- [ ] Check for content containers using "edge-to-edge" or "full-width containers" and provide recommendation to use "normal" or "wide" for accessibility line-length
```
