### ISSUE TITLE
Turn on OneTrust privacy notice on https://uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7012]
# Story

As a visitor to uiowa.edu, I can see the OneTrust notice.

# Additional Info

Follow up from #6492 

Once this is implemented on uiowa.edu, we'll need to communicate before turning this on for all sites using the University GTM container.

# Proposed solution

```[tasklist]
### Tasks
- [x] Edit "Onetrust banner" tag on https://tagmanager.google.com/#/container/accounts/1184129026/containers/6453475/workspaces/100/tags - Update our implementation to display on uiowa.edu rather than sandbox.prod.drupal.uiowa.edu and also place in new production script listed below.
- [x] Verify/update any settings and make sure we are using a production script - Implement production script in https://app.onetrust.com/cookies/script-integration/4c6d7f79-a493-45be-9427-7cfde461bfda/instructions will need to copied and pasted into Onetrust banner google tag
- [x] "Publish Production" in https://app.onetrust.com/cookies/script-integration/4c6d7f79-a493-45be-9427-7cfde461bfda/instructions
- [x] Publish default audience group in https://app.onetrust.com/cookies/consent-policy
- [x] Figure out how to remove green cookie button
```

**Comment by briand44** [comment]
Grooming conversation... Likely some work to do in OneTrust to make sure we are using a production script. Check with Michael about the settings that are currently configured in OneTrust.

**Comment by briand44** [comment]
Added blocked label because Ben wants to double check with Max on some geolocation settings as well as confirm existing settings with Michael.

**Comment by bspeare** [comment]
I have updated the proposed solution with more details on what we need to do to turn on the privacy notice.

**Comment by bspeare** [comment]
This is currently blocked because the persistent cookie button is back after publishing production scripts. 

<img width="279" alt="Screenshot 2023-10-18 at 1 42 45 PM" src="https://github.com/uiowa/uiowa/assets/1036433/373f8926-6c88-4208-acdd-833523f92e53">

**Comment by bspeare** [comment]
I worked through a few issues on this today:

- The "Default Audiences" geolocation rule had a "Global UIHC Audience" rule that was setting their template instead of ours. 
- As a way around this, I created a new "UIOWA Audience" group that is "GLOBAL" and assigned this to the uiowa.edu domain.  Our banner template is now showing after making this change. 

I think we are ready to move this live to uiowa.edu now.

**Comment by bspeare** [comment]
The notice is now live on uiowa.edu if anyone wants to test it out and confirm that it is working and not showing the green cookie when they click on the "okay" button.

**Comment by briand44** [comment]
Seems to be working for me. Saw the banner on uiowa.edu, once I clicked "okay" it went away and no green cookie. Closed browser and loaded uiowa.edu and no banner. Tested another website to make sure it was not showing there. Thanks!

**Comment by joewhitsitt** [comment]
My browser blocked it. Checks out for me 😄
