### ISSUE TITLE
Facilities Artwork

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7020]
```[tasklist]
### Tasks
- [ ] https://github.com/uiowa/uiowa/issues/7042
- [ ] https://github.com/uiowa/uiowa/issues/7026
- [ ] https://github.com/uiowa/uiowa/issues/7028
- [ ] https://github.com/uiowa/uiowa/issues/7113
- [ ] https://github.com/uiowa/uiowa/issues/7150
- [ ] https://github.com/uiowa/uiowa/issues/7144
```

**Comment by bspeare** [comment]
After a preliminary search, it appears that most campus art collections are either housed under a specific public art website or under the campus museum.   Before we do this work, is it worth considering seeing if this "Art on campus" should live somewhere else?

- https://wam.umn.edu/collection/public-art-on-campus/
- https://publicart.wisc.edu/
- https://www.museums.iastate.edu/visit/art-on-campus-collection
- https://www.davidsoncollegeartgalleries.org/campus-art/
- https://publicart.msu.edu/
- https://www.kemperartmuseum.wustl.edu/artoncampus
- https://artseverywhere.unc.edu/art-at-carolina/public-art-at-unc/
- https://museum.unc.edu/exhibits/show/public-art
- https://landmarks.utexas.edu/
- https://www.tamusa.edu/campus-art/index.html
- https://www.lamar.edu/public-art/index.html
- https://www.bu.edu/arts/public-art/
- https://publicart.northeastern.edu/

Also, https://www.facilities.uiowa.edu/campus-spaces/art-campus had only around 290 page views (#125) since GA4 conversion compared to Macbride Hall (#1) getting 20,000 page views.

**Comment by joewhitsitt** [comment]
>Before we do this work, is it worth considering seeing if this "Art on campus" should live somewhere else?

Having the building reference on the facilities side makes things easier for sure. I don't have a strong opinion otherwise. Short of it not being built in Drupal, it sounds maybe we press on until the "powers that be" say otherwise?

**Comment by mjoneill** [comment]
All, I think I completely missed the direction of @bspeare 's conversation yesterday.  What I heard was, "Should we build a new campus website for all/some campus art and move the facilities art to that?"  My thinking is that this is not something I would choose to invest in right now.  Big. Potentially messy. Lots of people to align around a vision.  Lots of complexity and complicatedness in the people space.

I have since understood that what @bspeare was actually asking about was more along the lines of, "Can we give this domain to [someone who is already solving for campus art needs](https://digital.lib.uiowa.edu/stanley)...and thereby avoid having to build any custom sauce for this?"

This is a different question than I was holding in my head...and much more tantalizing.

**Comment by briand44** [comment]
I brought up that most other University sites have a separate website for campus artwork and that it is not part of the Facilities website. Wendy stated she had asked about this on a few other occasions and that the feedback she got was that it was going to stay with Facilities for the forseable future. She did say she would check again though and get back to us soon. She also gave us a little background info on why this is with Facilities. I shared the link to Libraries Stanley collection as well as a link to the Stanley website.

**Comment by briand44** [comment]
There are some conversations happening around ^^.

> The likely outcome is that FM will continue to host the art website, and some other arrangement will be made for the stewardship/ownership of the pieces. If that is the case our work will not be impacted. I’ll confirm after their meeting.

**Comment by briand44** [comment]
>I checked back in with Lynne, and we are good to go on migrating the campus art pages.
Thanks!

**Comment by briand44** [comment]
Met with Facilities and showed progress on artist content, artwork displaying on buildings and artists and the artwork gallery.  Only issue that was found was that the artist filter shows all people when it should only show people of type artist. Otherwise feedback was positive! Going to close this epic as we have a card in PL related to the artist filter bug.
