### ISSUE TITLE
ITS specific fields part 2

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7058]
Follow up to https://github.com/uiowa/uiowa/issues/7035.

- Building field 
    - manually controlled taxonomy 
        - term name
        - description
        - abbreviation? - leftover from old Facilities Sims integration, probably not needed anymore.
        - pull these over as they are? - csv export/import? taxonomy migration?
        - rabbit hole
- Title logic - sounds like we can use same logic as they currently have
  - The current mockup adjusts the title construction a bit to put the type first and to consolidate multiple services/buildings when possible: `[alert type] - Multiple Services, Buildings - [additional details]`, `[alert type] - [service], [building] - [additional details]`, `[alert type] - Multiple Services, [building] - [additional details]`, `[alert type] - [service], Multiple Buildings - [additional details]` See https://sandbox.prod.drupal.uiowa.edu/mockup-its-alerts-landing-7 for a visual. Announcements don't have the alert type prepended. One could argue that these should be articles that are included in the alert digest.
- Closed field - [Background](https://github.com/uiowa/uiowa/issues/5952#issuecomment-1802511979)
  - End dates greater than start date that passes, should 'close' an alert (e.g. planned maintenance)
  - Manually closing an alert, should set the end date automagically, but this time around, the date should be editable for back dating/correction purposes.
  - Not to be confused with "unpublished" or "archived" as node still needs to be publicly viewable.

We should make sure building is output on the alert node, not linked
Can we output last updated date on the alert node?

https://github.com/uiowa/uiowa/issues/7058#issuecomment-1802708717

# Proposed Solution

```[tasklist]
### Tasks
- [x] Add building vocabulary
- [x] Building export/import
- [x] Rabbithole building terms
- [x] Add ER field to alert node for building
- [x] Add building name field to alert full node output (LB) displaying as the name, not linked
- [x] Add logic to presave to handle saving title according to the logic above
- [x] Output last updated date on alert node
- [x] Add an `isClosed` method to the Alert entity bundle class. The method returns true if the end date is different than the start date and has passed.
- [x] Make Alert Category field single-value and required in the ITS split
```

**Comment by briand44** [comment]
> - Buildings – Should this be a manually curated taxonomy like it is currently or is there a desire to see if we can pull in buildings from a Facilities API?
>     - We're ok keeping it as a manually curated list. HOWEVER, if we did pull from the facilities API, how long would it take and could we edit an individual building or add an individual building? (I'm guessing no on the last part). Jamie says it would be cool if folks could click on a building from an alert to see the map and building info (Example [Engineering Research Facility](https://www.facilities.uiowa.edu/building/0407)). 
>         - Our biggest consideration is networking issues. For an example, lot 4 parking lot is on our list but not on the facilities list, and there was just some network maintenance done on this building (found an alert from October 19). If we could add the random lots/buildings that aren't included on the facilities list in addition to pulling from their list, that would work. If not, we might have to stick with manual.
>         - Of note about selecting the building for an alert, Jamie said it's hard to find and select the right building. This is the case when selecting a service as well. HD staff will frequently open a separate tab and navigate to the service catalog and copy the title of a service and paste into the service field in order to populate the correct service. Searching "guest" for guest wifi doesn't work. Same with "DeviceNet". 
> 
> - Any clarity on how the closed field needs to function?
>     - This is the current workflow for closing an alert: 
>         - Go to the[ IT Service Alerts page ](https://its.uiowa.edu/alerts)to find the alert in question (HD staff do not use the list of pages in the Content tab in Drupal because the alerts are too hard to find, it's too many clicks to use the filters, and/or the names are usually too similar "multiple services" or "multiple buildings" and you have to click each one to see which one you need)
>         - Click on the title of the alert, which expands additional content, an editing wheel, and "Add an Update". 
>         - Select "Add an update" and enter "The issue has been resolved" (99x out of 100 this is the exact text used). 
>         - Save
>         - Click on the title of the alert and click on the editing wheel. Select Edit. Go into the field and select the "Closed" checkbox. (Once this is checked, an alert cannot be modified)
>         - Next enter the date/time. 
>         - Save again. After save, the alert is removed from the active alerts on the main IT Services Page. 
>         - Next, HD staff navigate to the Calendar view to find the alert that is no longer on the main view. From here, they can find the "Send Email Alert" button so that subscribers can be notified about the update and closure. This is not automatically done. 
>             - As you can see, this is kind of clunky. If we could combine steps when closing/updating/emailing, that would be great.
> 
> - Can you help us understand how the title should be generated? What should the title be if there are multiple services referenced as part of this alert? What should the title be if there are multiple buildings references?
>     - For these 3 questions, we are open to improving how the titles are displayed. Jamie and I both like the way it works now in daily digest form, but it is tricky when there are multiple services and multiple buildings selected. For example, if you take a look at the IT Service Alerts page right now, there are several alerts with "multiple services" and "multiple buildings" listed. It's impossible to know which is which unless you click on each one. I don't have a solution or idea for this.

**Comment by briand44** [comment]
Just dumping this^^ here for now.

**Comment by joewhitsitt** [comment]
In addition to https://github.com/uiowa/uiowa/issues/7059#issuecomment-1802694020, here is other feedback related to https://github.com/uiowa/uiowa/issues/7058#issuecomment-1791054504

- Building integration was turned off for a reason. Building existed but they IT service owners know it by a different name and they've wanted to change it. Instances where the building wasn't in Facilities' list yet, but alerts needed to be created for it.
- They like their manual list of buildings. Would be interested in bringing those over as-is and continuing to maintain it manually. Don't need ability to create buildings on the fly since everyone can create a draft alert, but might want to consider increasing access to the taxonomy.
- Can hold off on expanding the building functionality later (building info, map). They understand that would be manually managed as well since they don't want to go the API route.
- The alert workflow is the clunky part. Ways to clean that up so that they aren't doing some operations on the edit form, other operations on the full node, and making sure post operation, they are returned or sent to the next part would be helpful.
- The alert close part itself (outside of the overall workflow above) has only been and issue with updating the end date because service owners didn't tell them when it was resolved. They want it fairly accurate for the historic record.
- They plan on having internal conversations about allowing service owners the ability to close an alert instead of the current process of emailing. Reducing steps, complexity surrounding the workflow will be helpful for this.
- By showing the services/buildings affected at a glance with the mockups, they no longer have concerns about alert title construction.

**Comment by joewhitsitt** [comment]
Updated the IS a bit with possible direction and background.

Something I can't confirm and might just be my own thoughts is whether they wanted to tie an update message to the manually closed action and whether they want the ability to reopen this time around.

They did say that most of the time, the close update message that the helpdesk does enter in is the same. Perhaps canned message options or pre-populated field value on close?

**Comment by pyrello** [comment]
Added this for the title logic for now:
> Add logic to presave to handle saving title according to the logic above

@joewhitsitt We weren't totally clear on whether there are cases where we want to show the title without the alert type prepended to the rest of it. If that is the case, then we probably want to exclude that from our presave logic, and maybe it gets added via an extra field or something like that? Can you clarify when you have a chance?

**Comment by briand44** [comment]
Still need to get some more clarity/understanding around Closed field.

**Comment by joewhitsitt** [comment]
> Added this for the title logic for now:
> 
> > Add logic to presave to handle saving title according to the logic above
> 
> 
> 
> @joewhitsitt We weren't totally clear on whether there are cases where we want to show the title without the alert type prepended to the rest of it. If that is the case, then we probably want to exclude that from our presave logic, and maybe it gets added via an extra field or something like that? Can you clarify when you have a chance?

As we were grooming it, I had floated the idea that maybe we don't always want the title to be constructed that way and thus not presaved as the title. Compared to before we will be directing more traffic to the full node, and so do we want all of that attached the title? It makes sense for the teaser because we want as much info in a small digestible piece.

**Comment by briand44** [comment]
Grooming conversation... Try csv import for building taxonomy based on HR and Tippie examples.

**Comment by joewhitsitt** [comment]
Example term import https://github.com/uiowa/uiowa/blob/main/docroot/sites/hr.uiowa.edu/modules/hr_core/hr_core.install#L34

Example redirect import
https://github.com/uiowa/uiowa/issues/5265

views_data_export is enabled on its.prod
