### ISSUE TITLE
Writing paid campaign landing page(s)

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7100]
Looks like there will be a new paid campaign for writing.  

- Right now, it will have the same visual style as the current campaign, but different copy, imagery, etc...
- It will need a different form.
- We will need to confirm that conversion tracking works in GA
- We will need to confirm that the appropriate tracking pixels are deployed to these pages (via GTM)

Copy is currently being drafted.  On the current trajectory, copy will not be ready until Sprint starting the week of Nov 2, and they will likely want to launch that sprint.

```[tasklist]
### Tasks
- [ ] Join `#project-landingpages` in OSC Slack
- [ ] Clone https://uiowa.edu/go/university-ranking-3 as a draft
- [ ] Clone https://uiowa.edu/form/landing-page-introduce-yourself- and add it to the clone of the page above in replace of the current webform block
- [ ] Adapt layout to new copy
- [ ] Share layout in `#project-landingpages`  OSC Slack
```

**Comment by bspeare** [comment]
We are still waiting for copy to be approved.  I've added a task list to follow once the copy is ready.

**Comment by joewhitsitt** [comment]
Grooming convo: @bspeare added a task list for this issue and the team decided on medium sizing.

**Comment by joewhitsitt** [comment]
>We are still waiting for copy to be approved. I've added a task list to follow once the copy is ready.

Should we mark this as `blocked` for now?

**Comment by bspeare** [comment]
The copy for this has been approved and this is no longer blocked.   The copy can be found in the `#project-landingpages` OSC Slack channel.

**Comment by bspeare** [comment]
Timeline:

1. Layout first draft due Nov 17
2. Finalize layout between Nov 21-27
3. Set up no-follow and no-index, and publish Nov Wk 4 or Dec Wk 1
