### ISSUE TITLE
Develop communication plan for SiteNow v1 standard site owners

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7156]
# Story

As a webteam, we would like to have a communication that we can send to SiteNow v1 site owners letting them know the timeline and what is required of them to move to SiteNow v3 and how to respond with questions. 

# Additional Info

Identify timeline?

Should it contain something about what to do if you no longer need your site?

Are we migrating anything?

# Proposed solution

```[tasklist]
### Tasks
- [x] Create a page/article for communicating details about the end of service for SiteNow V1
- [x] Develop a timeline that includes relevant dates and deadlines
- [x] Identify the audiences we will be targeting for communication
- [x] Identify the communication channels that will be used for each message
- [x] Articulate the intent of the messages that we would like to send to each audience
- [x] Create a schedule for when the messages should go out
- [x] Finalize and publish an initial message on V1 sites
- [x] Draft and finalize a first communication to be sent
```

**Comment by briand44** [comment]
Grooming conversation... should this be more about the communication plan vs the actual communication?

Who to send to?
Opt in vs opt out?
timelines?
rough idea of what we want to say in first communication

**Comment by bspeare** [comment]
A few thoughts:

**Communication:**

- Reduce as much technical jargon as possible and keep the communication extremely short with a distinct call to action (button)
- Create a "Keep my website" or "Yes" link that is pre-populated with webform fields
  - If we were able to do that, could we auto-submit the form as well?
- Allow users to respond to the email if they want?

**Plan:**

- Create a buffer before eol, where we could turn off the domain in Acquia Cloud and easily turn it back on if the user notices their site is down so they could have enough time to request a new V3 site?

**Comment by pyrello** [comment]
I started a draft timeline for a V1 standard service shutdown. Ping me for access.

https://iowa-my.sharepoint.com/:w:/r/personal/sadamshiett_uiowa_edu/Documents/Draft%20timeline%20for%20SiteNow%20V1%20standard%20service%20shutdown.docx?d=w5a9b208f418243f694574b643cd709a4&csf=1&web=1&e=12d8Cp

**Comment by bspeare** [comment]
Wondering if we might want to do an unbounce popup instead of or in addition to an email communication? Maybe the email communication is only for inactive sites and we rely upon an unbounce popup for active sites?

**Comment by pyrello** [comment]
> Wondering if we might want to do an unbounce popup instead of or in addition to an email communication? Maybe the email communication is only for inactive sites and we rely upon an unbounce popup for active sites?

I like this idea a lot!

**Comment by joewhitsitt** [comment]
I am interested in hearing more about what this would look like? Can it be scoped to look for our metatag `<meta name="web-author" content="SiteNow v1 Standard (https://sitenow.uiowa.edu)">`?

Displayed on the frontend for all users? Limited to the `logged-in` body class?

**Comment by pyrello** [comment]
> Limited to the `logged-in` body class?

I think this would be important.

**Comment by pyrello** [comment]
We had a meeting to discuss this and talked about the draft timeframe I put together. Some takeaways:
- There is a desire to shorten the timeframe in which people need to get in touch with us to request a v3 site.
- This is partly because of the reality that it will be harder to connect with some site owners after the spring semester ends.
- This is also partly because it allows more time on the backend for the actual migration of sites.
- I think we should make the ask in our communication just that they connect with us in some way (email, slack, site request form) to let us know that they want a v3 site.

**Comment by pyrello** [comment]
I updated the draft timeline document to reflect a more aggressive timeline to get to the deadline for contacting us

**Comment by pyrello** [comment]
I think for the initial batch of communications, our only goal should be to get people to request a site or at least let us know they want a site. We should focus on communicating that there is a deadline for requesting a v3 site and if we don't receive a request by the deadline, we'll queue their site for deactivation. We shouldn't try to use these communication to convey the date by which their site will be deactivated or when the service will be shut down. I think that people are less likely to be confused about what the actual deadline is if we just focus on their site not getting deactivated first. I also think it will be easier for people to comply if we are just asking them to send an email or fill out the site request form.

As a separate matter, after someone has requested a site that is a replacement for a current D7 standard site, we can have it be part of our plan to communicate with them when we deliver the site that there is also a separate deadline for how long they can have access to their existing site. At that point, the focus is on getting them through the process of getting their site migrated and launched.

**Comment by pyrello** [comment]
[Draft communication]

Subject: Request a SiteNow v3 website to avoid deactivation of your v1 website.

Site owner,

Our records indicate that you own or are affiliated with a SiteNow v1 Standard website. This service is being shut down in favor of SiteNow v3 in 2024. If you still need a SiteNow website, please contact us by 03/31/2024 using the [SiteNow request form](https://sitenow.uiowa.edu/request-site). Sites that we have not been contacted about by 03/31/2024 will be scheduled for deactivation starting on 04/01/2024. Deactivation will cause your site to be unavailable.

If you no longer need your v1 website, no further action is necessary. However, if you want to let us know that you no longer need the site, we would appreciate it.

Thanks,

The SiteNow team

**Comment by mjoneill** [comment]
HMU with access, plz

**Comment by briand44** [comment]
I'm still a little unclear why our focus is around a deadline to request a site rather than to transition their site? I was thinking something along the lines of the following:

> Hello [name],
> 
> This email is being sent to all active webmasters on the SiteNow v1 Standard service website [website url]. The active webmasters are: [webmasters].</p>
> 
> The SiteNow v1 Standard service is being retired 7/1/2024. If you wish to continue having a SiteNow website, you will need to [request a SiteNow v3 site](https://sitenow.uiowa.edu/request-site) and manually transition your content prior to 7/1/2024. On 7/1/2024, we will begin deactivating any remaining SiteNow v1 Standard sites.
> 
> Please allow us approximately, 1 week to process your SiteNow v3 request. Once processed, we will contact the site requestor with a link to your newly provisioned SiteNow v3 website and training resources to help aid in your content transition. When you have finished transitioning your content, email [its-web@uiowa.edu](mailto:its-web@uiowa.edu) and we can launch your new website for you. Please allow us at least 1 week to launch your website.
> 
> If you no longer need your SiteNow v1 Standard website, please respond to this email letting us know this site is no longer needed and we will remove your website.
> 
> Feel free to [contact us](https://sitenow.uiowa.edu/contact-us) if you have any questions or concerns.
> 
> Thanks,
> OSC Web Services

**Comment by pyrello** [comment]
@briand44 and I just had a conversation to talk through our differing ideas on what our goal should be with the communications we are developing. One thing that came out of that discussion is that we think it might be faster to get an unbounce popup in place faster than we could figure out how to get a list of email recipients and figure out the logistics of designing and sending an email. I think an email is still a good idea since there are users that we know don't log into their sites for long periods of time. But the popup could be our best option to get a message in front of people as soon as possible.

**Comment by mjoneill** [comment]
> One thing that came out of that discussion is that we think it might be faster to get an unbounce popup in place

I can help with this if it's something we want to explore.  Would you have a mechanism to place the code on all v1 sites that are in scope for this messaging, or would we be trying to finagle it with GTM (I'm not sure how we'd do that)?

**Comment by briand44** [comment]
Another thing that came up in conversation is that some SiteNow standard v1 sites could already be in process of transitioning to SiteNow v3 so we will want to be careful about having secondary communications only through the site request process.

**Comment by briand44** [comment]
Just throwing some thoughts on here:

- Draft message
- Create article - using finalized message
- Output short message on v1 standard sites with link to article
- initiate work to get appropriate list of email addresses and populate dispatch
- send email comms
- future comms?

**Comment by pyrello** [comment]
Related: https://github.com/uiowa/uiowa/issues/7187#issuecomment-1856914436

**Comment by pyrello** [comment]
I wanted to make another attempt at clarifying some thoughts about my vision for this work. It seems that the default for this work in some people's minds is that we treat all SiteNow v1 users exactly the same and send them one communication with one message. However, we already discussed (and decided?) that we would like to treat V1 standard vs. V1 custom sites as two groups with two separate deadlines. The v1 standard service we would like to shut down roughly by the PHP 7.4 EOL gratis expiration later in 2024. The custom sites we expect we will need the full time available until sometime in 2025 via an extended PHP 7.4 EOL. Therefore, we have to segment the messaging between these two groups because it doesn't make sense to send them both messages telling them that their current site will be shut down next year.

So we are already accepting that some segmenting of messaging will be necessary (possibly desirable) to accomplish our goals. My idea revolves around further segmenting our audience into:
1. V1 standard sites that have not requested a site (inform about deadline to request a site ASAP)
2. V1 standard sites that have already requested a site (no immediate communication)
3. V1 custom sites

My idea was to focus on segment 1 first, crafting a communication that is focused on the next action we want them to take. Since they have not yet requested a site, they are the furthest from being done and the urgency to get a communication out to them is the highest. I think the first message should just be focused on getting them to take the next step in the process. Completing that step will move them from segment 1 into segment 2.

Our message to segment 2 is that they have to have their site migrated by a certain time to ensure continuity. Ideally their V3 site is launched by a certain deadline, but the key thing we need them to be aware of is that their D7 site will get shut down by a certain date, so if they need that to finish their migration then they need to get the migration done before then.

Not sure what the messaging to segment 3 should look like yet or whether there might be other segments lurking within there that need to be accounted for.

**Comment by pyrello** [comment]
One of the things that has felt a little bit tricky about this has been defining a shutdown date for SiteNow v1 standard and communicating that. There has been some concern that customers will ignore everything except for the final date. However it is difficult to move forward with any comms without knowing the date because the question is inevitable.

The first thing I think we need to figure out is what we mean by shutdown date. I think the definition of it should be that we are no longer guaranteeing uptime for any site that is part of the V1 standard service starting on that date and going forward. It doesn't mean that we have to flip a switch and immediately turn off every site or that we have to spin down a container. It is just the end of our guarantee of service.

We are using the PHP 7.4 EOL gratis extension expiration as a guide for when we want to wrap things up. Based on that, I think we should plan on a shutdown date at least a month before that. This would be to allow for unforeseen issues that might come up and give us some amount of time to deal with them. I'm not sure that the actual PHP EOL will provide an actual technical imperative to have everything done on our end by that date, but for the purposes of planning, I think we should just assume that to be the case.

**Comment by pyrello** [comment]
I updated the proposed solution with some more clear deliverables.

**Comment by joewhitsitt** [comment]
I think if we ignore the upstream EOLs for a moment and understand that we don't have an SLA for this service, we can instead ask ourselves, when do we _want_ to be done with sitenow v1 standard? based on that we can move forward with that date and that is all sitenow standard customers really need to know. i think this can allow a more aggressive schedule which is ideal for our team so we can focus our efforts elsewhere. we can target just the standard service right now and continue to develop our plan for sitenow v1 custom. Something else to keep in mind, though we don't have anything official out there, we haven't provisioned a v1 standard site for years now and except for security fixes, everything has been in "maintenance mode" for quite a while. I don't think many will be shocked by this news, if we are even able to reach them at all.

Kind of an aside:
In terms of database sizes on 701, https://victorianfboos.studio.uiowa.edu/ as of 2021 is our largest standard site. ibl.law.uiowa.edu/etc.engineering.uiowa.edu was second/third but has moved. After that, there is a sharp drop in how big these sites are. I don't know the database to content conversion. Some may have more pages but less bytes overall. This is an average 18 MB site: https://buchanan.lab.uiowa.edu/ ([source](https://iowa.sharepoint.com/sites/CSI-Drupal2/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=0phl0q&cid=2e44e3e3%2Dcc7b%2D4c38%2Da07c%2D213d9b104f39&RootFolder=%2Fsites%2FCSI%2DDrupal2%2FShared%20Documents%2FAcquia%20Database%20Usage&FolderCTID=0x0120002F9851D81A9B1E4DB63DA70E38793599))

**Comment by pyrello** [comment]
> I think if we ignore the upstream EOLs for a moment and understand that we don't have an SLA for this service, we can instead ask ourselves, when do we _want_ to be done with sitenow v1 standard?

I don't think our plan really needs to be built around the EOLs, they just serve as a point of reference which is easier to use than just grasping a date out of thin air.

I think we do also want to consider what is best for our customers, which has come up in previous conversations. It was pointed out that some customers will leave over the summer. I think we want to make sure that we are leaving a reasonable amount of time for people actually do the work of migrating. 

Brian and I just discussed the idea of moving up the deadline for when people have to let us know they want a V3 site, potentially as early as 02/01. That means that we should feel reasonably confident that everyone that needs a V3 site to do their migration will have one by that point (or within a couple weeks for people who missed the comms). At a minimum, I think it would be nice to give people a couple months to do their migration so its not a drop everything and get this done situation in the middle of the semester. That means the earliest we could reasonably consider shutting the service down is early April. That would be good for us from a standpoint of that we would be done having to worry about those customers sooner. But its a pretty aggressive timeline and doesn't allow much wiggle room for folks whose schedules don't match up with that. There are some people for whom it would likely be convenient to be able to work on their site over the summer. If we're going to allow for some part of the summer, it seems like we should just allow for the whole thing. Which brings us back to the beginning of the fall semester, which is a little over a month before the gratis EOL.

This is all to say, the EOL is an arbitrary deadline to use in this case, but its not like the timing doesn't make some kind of sense.

**Comment by e-marie-w** [comment]
I think moving up the request deadline but still allowing all summer for migrations is a good idea. I'd rather have everything done sooner but I'm not sure it's feasible for a lot of our users. I guess we never discussed it, but I'm assuming we'll provide the rough timeline in the article/page. I've changed my mind on relaying ultimate final date and think we should include it in all our brief communications just to avoid a hundred emails about it. 

Obviously our first priority is communicating to v1 standard users who haven't requested a site. But I don't think we should wait too long before communicating to v1 users with a requested site about the EoL. 

I am wondering if we'll receive emails asking for assistance with migration and if we need to start discussing what, if any, options there are. I wouldn't mind working on site migrations in my profdev time but I am probably an outlier.

**Comment by e-marie-w** [comment]
Actually, I'm now wondering if August 1 would be a good date. It gives most of summer but avoids setting the deadline the week after classes start.

**Comment by mjoneill** [comment]
> I wouldn't mind working on site migrations 

I've artfully selected some text to quote.  Thanks for volunteering!  

Maybe there's an intersection here with interest, some tooling automation, and impending deadlines.

**Comment by mjoneill** [comment]
> when do we _want_ to be done with sitenow v1 standard? 

I'm grateful for this comment.  I think it's worth keeping in mind that this is in options portfolio.  Not everything has to be aligned 1:1 with service termination by our vendor, etc...

**Comment by joewhitsitt** [comment]
This inactive script can be modified to capture all authenticated and the URL for use with our comms. Sounded like @pyrello had an idea about how to filter out the sites we don't want to target.

```
<?php

$self_record = drush_sitealias_get_record('@self');

if (empty($self_record)) {
  drush_log('No bootstrapped site.', 'error');
}
else {
  // DNS hackery.
  // Check the cert CN against the app name. If they don't match, then either
  // DNS doesn't point to Acquia or the domain was moved to another app in Acquia.
  $g = stream_context_create([
    'ssl' => [
      'capture_peer_cert' => TRUE
    ],
  ]);

  $r = stream_socket_client("ssl://{$self_record['uri']}:443", $errno, $errstr, 30, STREAM_CLIENT_CONNECT, $g);

  if (!$r) {
    drush_log(dt('Cannot capture SSL certificate for site @site.', [
      '@site' => $self_record['uri'],
    ]), 'error');
  }
  else {
    $params = stream_context_get_params($r);
    $cert = openssl_x509_parse($params['options']['ssl']['peer_certificate']);
    $app = getenv('AH_SITE_NAME');

    // Local override. Requires app root be named APP-dev.
    if (!$app) {
      $app = basename(dirname(__DIR__));
      $app = explode('-', $app)[0];
    }

    $cn = explode('.', $cert['subject']['CN'])[0];

    if ($app == $cn) {
      // We need a full bootstrap to leverage the Drupal API.
      if (drush_bootstrap_max() >= 5) {
        $args = drush_get_arguments();

        if (isset($args[2]) && strtotime($args[2])) {
          $rel = $args[2];
        }
        else {
          $rel = '6 months ago';
        }

        $query = new EntityFieldQuery();

        // Select active users above uid 1.
        $query->entityCondition('entity_type', 'user')
          ->propertyCondition('uid', 1, '>')
          ->propertyCondition('status', 1);

        $result = $query->execute();

        if (isset($result['user'])) {
          $roles = array_flip(user_roles(TRUE));
          $uids = array_keys($result['user']);
          $active = [];
          $webmasters = [];

          // Dispatch API data.
          $data = (object) [
            'members' => [],
            'includeBatchResponse' => TRUE,
          ];

          foreach ($uids as $uid) {
            $user = user_load($uid);

            // If this user is not an admin, check their last login time.
            if (!array_key_exists($roles['administrator'], $user->roles)) {
              // If the user has logged in recently, consider them active.
              if ($user->login >= strtotime($rel)) {
                $active[] = $user->mail;
              }
              else {
                if (array_key_exists($roles['webmaster'], $user->roles)) {
                  $webmasters[] = $user->mail;

                  $data->members[] = (object) [
                    'toName' => $user->name,
                    'toAddress' => $user->mail,
                    'website' => $self_record['uri'],
                    'webmasters' => [],
                  ];
                }
              }
            }
          }

          // If there are no active users, this site is INACTIVE.
          if (empty($active)) {
            if (!empty($data->members)) {
              foreach ($data->members as $key => $member) {
                $data->members[$key]->webmasters = implode(', ', $webmasters);
              }

              if (!drush_get_option('send-email')) {
                drush_log(dt('Skipping email to inactive site @site webmasters. Use --send-email option to send.', [
                  '@site' => $self_record['uri'],
                ]), 'ok');
              }
              else {
                // Post to Dispatch to send email.
                $response = drupal_http_request(
                  'https://apps.its.uiowa.edu/dispatch/api/v1/communications/932479972/adhocs',
                  [
                    'method' => 'POST',
                    'headers' => [
                      'accept' => 'application/json',
                      'x-dispatch-api-key' => getenv('dispatch_api_key'),
                    ],
                    'data' => drupal_json_encode($data),
                  ],
                );

                if (isset($response->error)) {
                  drush_log(dt('Error sending Dispatch communication for site @site. Error: @error', [
                    '@site' => $self_record['uri'],
                    '@error' => $response->status_message,
                  ]), 'error');
                }
              }
            }
            else {
              drush_log(dt('No active webmasters found for site @site. Cannot send email.', [
                '@site' => $self_record['uri'],
              ]), 'error');
            }
          }
        }
      }
      else {
        drush_log(dt('Cannot do full bootstrap for site @site.', [
          '@site' => $self_record['uri'],
        ]), 'warning');
      }
    }
    else {
      drush_log(dt('Domain @site does not point to @app application.', [
        '@site' => $self_record['uri'],
        '@app' => $app,
      ]), 'error');
    }
  }
}
```

**Comment by pyrello** [comment]
The comms committee had their first meeting. We discussed possible shutdown dates, who to target for initial communications, what to include in the initial communication, how to get the lists. I have updated the word document with relevant details. We have a meeting on the schedule for Monday morning to finalize necessary details with the team so we can be ready to send out a communication as soon as we have a list and the content.

**Comment by e-marie-w** [comment]
Rough draft of page: https://sitenow.uiowa.edu/sitenow-v1-standard-platform-shutdown. Is there anything else I should be adding? Right now it just feels like a rehash of the email.

**Comment by pyrello** [comment]
> Sounded like @pyrello had an idea about how to filter out the sites we don't want to target.

I did.

```php
/**
 * A helper function to fetch a list of sites on the
 * modern SiteNow platform.
 */
function _uiowa_bar_fetch_sitenow_modern_site_list() {
  $list = &drupal_static(__FUNCTION__);
  if (!isset($list)) {
    $cid = 'sitenow_modern_site_list';
    // Try to get from cache.
    if ($cache = cache_get($cid)) {
      $list = $cache->data;
    } else {
      $list = array();
      // Grab the contents of modern SiteNow's sites.php.
      $contents = @file_get_contents('https://raw.githubusercontent.com/uiowa/uiowa/main/docroot/sites/sites.php');
      if ($contents) {
        // Split the file into chunks of data related to one site.
        $site_chunks = explode('// Directory aliases for ', $contents);
        array_shift($site_chunks);
        foreach ($site_chunks as $site_chunk) {
          // Just get the piece we want, which is the very beginning.
          $pieces = explode(".\n", $site_chunk);
          // Skip the default site.
          if ($pieces[0] === 'default site') {
            continue;
          }
          $list[] = $pieces[0];
        }
      }
      // Store in cache for one day.
      cache_set($cid, $list, 'cache', time() + 60 * 60 * 24);
    }
  }

  return $list;
}
```

Results in:
![Screenshot 2023-12-19 at 8 52 59 AM](https://github.com/uiowa/uiowa/assets/709009/41f00f89-5ecd-4872-91c6-a3399bc1fc4a)

**Comment by joewhitsitt** [comment]
> Rough draft of page: https://sitenow.uiowa.edu/sitenow-v1-standard-platform-shutdown. Is there anything else I should be adding? Right now it just feels like a rehash of the email.

Took a look this morning. Made a few tweaks. I think we should use "website" instead of our shorthand "site"

**Comment by briand44** [comment]
Looked at the draft article...

Do we have info anywhere about how to know what version of website you have? I'm wondering if folks seeing the article will know if they have a v1 standard vs v1 custom or something else. If they get the email communication, they should know but if someone comes across the article, I'm not sure. Thoughts?

**Comment by joewhitsitt** [comment]
Untested, but this is the rough chop I made of the inactive script to get site url and a list of user email addresses:

```php
<?php

$self_record = drush_sitealias_get_record('@self');

if (empty($self_record)) {
  drush_log('No bootstrapped site.', 'error');
}
else {
  // DNS hackery.
  // Check the cert CN against the app name. If they don't match, then either
  // DNS doesn't point to Acquia or the domain was moved to another app in Acquia.
  $g = stream_context_create([
    'ssl' => [
      'capture_peer_cert' => TRUE
    ],
  ]);

  $r = stream_socket_client("ssl://{$self_record['uri']}:443", $errno, $errstr, 30, STREAM_CLIENT_CONNECT, $g);

  if (!$r) {
    drush_log(dt('Cannot capture SSL certificate for site @site.', [
      '@site' => $self_record['uri'],
    ]), 'error');
  }
  else {
    $params = stream_context_get_params($r);
    $cert = openssl_x509_parse($params['options']['ssl']['peer_certificate']);
    $app = getenv('AH_SITE_NAME');

    // Local override. Requires app root be named APP-dev.
    if (!$app) {
      $app = basename(dirname(__DIR__));
      $app = explode('-', $app)[0];
    }

    $cn = explode('.', $cert['subject']['CN'])[0];

    if ($app == $cn) {
      // We need a full bootstrap to leverage the Drupal API.
      if (drush_bootstrap_max() >= 5) {

        $query = new EntityFieldQuery();

        // Select users above uid 1.
        $query->entityCondition('entity_type', 'user')
          ->propertyCondition('uid', 1, '>')
          ->propertyCondition('status', 1);

        $result = $query->execute();

        if (isset($result['user'])) {
          $roles = array_flip(user_roles(TRUE));
          $uids = array_keys($result['user']);
          $users = [];

          foreach ($uids as $uid) {
            $user = user_load($uid);

            // If this user is not an admin, get their email address.
            if (!array_key_exists($roles['administrator'], $user->roles)) {

              $users[] = $user->mail;

            }
          }

          $url = $self_record['uri'];

          drush_log(dt('@site, [@users]', [
            '@site' => $self_record['uri'],
            '@users' => implode(', ', $users),
          ]), 'warning');
        }
      }
      else {
        drush_log(dt('Cannot do full bootstrap for site @site.', [
          '@site' => $self_record['uri'],
        ]), 'warning');
      }
    }
    else {
      drush_log(dt('Domain @site does not point to @app application.', [
        '@site' => $self_record['uri'],
        '@app' => $app,
      ]), 'error');
    }
  }
}
```

**Comment by joewhitsitt** [comment]
> Looked at the draft article...
> 
> Do we have info anywhere about how to know what version of website you have? I'm wondering if folks seeing the article will know if they have a v1 standard vs v1 custom or something else. If they get the email communication, they should know but if someone comes across the article, I'm not sure. Thoughts?

Good point. I think all we do for v1 standard is modify the `web-author` meta tag: _SiteNow v1 Standard (https://sitenow.uiowa.edu)_

The toolbar does not differentiate between standard/custom.

Update: Maybe the popup should be deployed at the same time then and the resource page should include information about that.

**Comment by joewhitsitt** [comment]
In preparing for this ITS meeting, it sounds like we should make a service announcement on the ITS website

https://its.uiowa.edu/alert/128341

**Comment by briand44** [comment]
Would like to send on Jan 2nd rather than over the holidays.

**Comment by mjoneill** [comment]
We have a looker studio report that gives us referrer information on traffic to both the SNv1 Standard EoL info article and the Request a site form (when visited as a landing page)

https://iowaweb.slack.com/archives/C0164FNN1PV/p1703264853100689

**Comment by joewhitsitt** [comment]
Noticing that some users are identified for more than one website. Based on how the dispatch populations list might work I wonder if we can have "duplicates" or if we need to combine the users and handle multiple URLs.

For now, I have run the command and added the people as-is to https://apps.its.uiowa.edu/dispatch/populations/1278170398/members

**Comment by pyrello** [comment]
> Noticing that some users are identified for more than one website. Based on how the dispatch populations list might work I wonder if we can have "duplicates" or if we need to combine the users and handle multiple URLs.

I'm going to try to test this out.

**Comment by pyrello** [comment]
> > Noticing that some users are identified for more than one website. Based on how the dispatch populations list might work I wonder if we can have "duplicates" or if we need to combine the users and handle multiple URLs.
> 
> I'm going to try to test this out.

I tested this by replacing the list with a list that was just my email address twice and two different domains. I received both emails, so I think this should be fine.

The next issue I'm running into is that when I validate our list, I get 103 entries that do not validate. There is a warning message that says that if the addresses don't validate they won't get sent and will be logged as an error. I'm not sure how we want to handle these email addresses.

**Comment by joewhitsitt** [comment]
Can you spot check a few at https://iam.uiowa.edu/whitepages/search and if they don't come up as valid (return a result) maybe we just remove those from our list.

**Comment by e-marie-w** [comment]
I've updated the email template to use `domain` for the site like the population does. Since we're only grabbing that and the email address I've changed the starting address to just 'Hello,' for now. Do we want to do something like 'Hello Site User,' instead?

**Comment by pyrello** [comment]
> Can you spot check a few at https://iam.uiowa.edu/whitepages/search and if they don't come up as valid (return a result) maybe we just remove those from our list.

I spot checked and these all either don't exist or lack a routing address. We should definitely remove the ones that don't exist. Probably we should remove the others. I was able to copy/paste into a spreadsheet, so I'm going to see if I can do some quick python magic to process those out of the bigger list. 

As a side note, it would be nice if we could just hit an API service that does the same validation so we could just filter out the nonexistent addresses without the extra step.

**Comment by pyrello** [comment]
I have updated the population list to remove the invalid members.

**Comment by pyrello** [comment]
In a meeting this morning we discussed copy for the first email. We also decided to push back the deadline for requesting a V3 site to 2/14/2024. I'm going to update the email in Dispatch and send a test email.

**Comment by pyrello** [comment]
We discussed during planning today having a second email two weeks before the request deadline. Depending on how we want to interpret 2 weeks (inclusive or exclusive of the deadline) that would be either 1/31 of 2/1. I'll create a follow-up issue to address that.

**Comment by briand44** [comment]
Thanks @pyrello!

**Comment by mjoneill** [comment]
> We discussed during planning today having a second email two weeks before the request deadline. Depending on how we want to interpret 2 weeks (inclusive or exclusive of the deadline) that would be either 1/31 of 2/1. I'll create a follow-up issue to address that.

I'd like to lobby for the following for the "no response" audience:
- 2 weeks. "You have two weeks left.  Rest is pretty much the same as first email.
- Day before (or day of).  "Our records indicate that you do not want to keep your website at [url]. If you wish to keep a website at [url], you need to submit a web request form [here] before close of business tomorrow. If you believe this to be in error, please contact us as soon as possible. etc. etc. etc."
- Day after.  "You have elected not to keep your website at [url].  Access to your website will be removed on or after some future date (Aug 1?).  If you believe this to be in error, please contact us as soon as possible..."

**Comment by pyrello** [comment]
#7248 

@mjoneill Just to make sure I understand your feedback, you would like to send 3 additional emails (for a total of 4)?

**Comment by pyrello** [comment]
I'd consider this done.

**Comment by mjoneill** [comment]
> #7248
> 
> @mjoneill Just to make sure I understand your feedback, you would like to send 3 additional emails (for a total of 4)?

Yes, unless there is ongoing communications with this audience (who has not responded/indicated they want to keep their site) happening another way.

**Comment by mjoneill** [comment]
> I started a draft timeline for a V1 standard service shutdown. Ping me for access.
> 
> https://iowa-my.sharepoint.com/:w:/r/personal/sadamshiett_uiowa_edu/Documents/Draft%20timeline%20for%20SiteNow%20V1%20standard%20service%20shutdown.docx?d=w5a9b208f418243f694574b643cd709a4&csf=1&web=1&e=12d8Cp

I've tried to update the timeline and plan for SNv1 Standard comms.  I think we need to figure out when the email to local comms/web leadership happens for sites slated to be decommissioned.  The intent/expectation is that they have the option to intervene before a site is removed.

**Comment by pyrello** [comment]
> I think we need to figure out when the email to local comms/web leadership happens for sites slated to be decommissioned.

I think we need to talk about how we would even do this. My best answer is we generate the list of sites that is left and then we manually identify who would be emailed for each site. I don't think we have any data that would programmatically allow us to determine this.

**Comment by mjoneill** [comment]
> > I think we need to figure out when the email to local comms/web leadership happens for sites slated to be decommissioned.
> 
> I think we need to talk about how we would even do this. My best answer is we generate the list of sites that is left and then we manually identify who would be emailed for each site. I don't think we have any data that would programmatically allow us to determine this.

Yeah. I think a report is fine. This will have to be a manual process.  Maybe something like:

| url | original requester name/email | webmasters (other roles) name/email |

Humans will take it from there.
