### ISSUE TITLE
Epic - Shut down V1 service

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7161]
### Standard service tasks?
- [ ] https://github.com/uiowa/uiowa/issues/7156
- [x] draft and send communication based on plan outlined in #7156
- [ ] https://github.com/uiowa/uiowa/issues/7248
- [ ] https://github.com/uiowa/uiowa/issues/7296
- [ ] https://github.com/uiowa/uiowa/issues/7307
- [ ] https://github.com/uiowa/uiowa/issues/7314
- [ ] https://github.com/uiowa/uiowa/issues/7308
- [ ] #7329
- [ ] https://github.com/uiowa/uiowa/issues/7351
- [ ] https://github.com/uiowa/uiowa/issues/7355
- [ ] https://github.com/uiowa/uiowa/issues/7744
- [ ] https://github.com/uiowa/uiowa/issues/7859
- [ ] https://github.com/uiowa/uiowa/issues/7290
- [ ] https://github.com/uiowa/uiowa/issues/7743
- [ ] https://github.com/uiowa/uiowa/issues/7886
- [ ] https://github.com/uiowa/uiowa/issues/8006
- [ ] https://github.com/uiowa/uiowa/issues/8063
- [ ] https://github.com/uiowa/uiowa/issues/8018
- [ ] https://github.com/uiowa/uiowa/issues/8177
- [ ] https://github.com/uiowa/uiowa/issues/8277
- [ ] https://github.com/uiowa/uiowa/issues/8317
- [ ] https://github.com/uiowa/uiowa/issues/8342
- [ ] https://github.com/uiowa/uiowa/issues/8240
- [ ] https://github.com/uiowa/uiowa/issues/8465

### Custom service tasks?
- [x] https://github.com/uiowa/uiowa/issues/8465
- [x] #9224
- [x] have Acquia remove D7 apps
- [x] Revoke SSL certs for D7 apps 701, 702, 703 and dentistry done
- [x] Anything needed to make sure Hero Devs support goes away? - Sounds like it will just expire 12/31/2025
- [x] #9331 
- [x] Retire D7 metadata generator, ~let IAM know no longer need to consume those endpoints,~ signage routing, other data.its D7 stuff, etc. - https://github.com/uiowa/uiowa/issues/9355
- [x] assets.uiowa.edu should be able to go away - https://github.com/uiowa/uiowa/issues/3020
- [x] https://github.com/uiowa/uiowa/issues/9375
- [x] remove sitenow_migrate suite and related PRs, issues? - #9362 
- [ ] team cleanup of local environments (remove devdesktop, rvm, etc.?)
- [ ] remove d7 docs wiki, teams files/backups, confirm myweb and other stuff is captured in docs.prod?
- [x] retire mapbox https://github.com/uiowa/uiowa/issues/728

**Comment by joewhitsitt** [comment]
unpublished https://sitenow.uiowa.edu/sitenow-v1-standard-platform-shutdown

**Comment by pyrello** [comment]
Thanks for the helpful writeup, @joewhitsitt!
