### ISSUE TITLE
Registrar Epic

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7257]
Some items listed here are related to https://github.com/uiowa/uiowa/issues/2184

Academic Calendar - https://github.com/uiowa/uiowa/issues/4936 - https://github.com/uiowa/uiowa/issues/4937
- will need some tweaking
- want it to go out at least one more session
- https://registrar.uiowa.edu/academic-calendar
- is web display - 
- is reviewed/approved - don't display unless it is reviewed/approved
- Josh likes month and list view
- no longer have a print view from printing because they stopped doing that with COVID but would like that with some clarifying text saying "All dates subject to change, check [url] for most up to date info."

Five Year Calendar

- Not much change need here other than more up to date branding
- printer friendly version would be a nice to have but not likely a requirement
- https://registrar.uiowa.edu/five-year-calendar

Dates by Session

- Showing all dates related to a session regardless of month they occur in
- more used by departments so they don't have to scroll through each month
- is web display - similar to academic calendar
- is reviewed - similar to academic calendar
- https://registrar.uiowa.edu/dates-by-session

Course Deadlines

- Keep similar
- Would like the ability to make content edits that live on that page
- https://registrar.uiowa.edu/course-deadlines

GPA Calculator

- Same as it is currently
- https://registrar.uiowa.edu/gpa-calculator
- Asked if this is still needed based on comment https://github.com/uiowa/uiowa/issues/7257#issuecomment-2135855299 and they are leaning towards yes still needed but they are going to do some more research here. They think Admissions uses this quite a bit for potential/transfer students. Also like that it is not behind auth. Many other Registrar sites have one including UNI https://registrar.uni.edu/students/gpa-calculator.

Final Exam Schedules

- https://registrar.uiowa.edu/final-exam-schedules
- will still need this
- may need to work with Caroline

Correspondence

- Very slow to load
- Overall list of all correspondence
- Want some filters - Audience, session, type (commencement, etc.)
- https://registrar.uiowa.edu/correspondence?audience=student

Contact

- https://registrar.uiowa.edu/contact
- Can currently reference a Contact/Unit from a basic page and that contact info will be displayed on that page
- May not be a requirement for launch but would be really nice to keep this functionality

CeCredential Validation

- Still need this
- Vendor said having integration issues on latest version of Drupal
- https://registrar.uiowa.edu/credential-validation

Tuition and Fees

- Not required for launch but would be nice
- Maybe embed?
- https://registrar.uiowa.edu/tuition-fees
- https://tuition.ais.its.uiowa.edu/rates
- Could program specific fees be pulled in from MAUI?
- https://registrar.uiowa.edu/2023-24-common-and-program-specific-fees

Department Codes and Numbers

https://registrar.uiowa.edu/department-codes-and-numbers

Archiving

- https://registrar.uiowa.edu/general-catalog
- quite a few pages like this
- Add a file and then they give it a file archive type
<img width="511" alt="Screenshot 2024-01-08 at 10 30 58 AM" src="https://github.com/uiowa/uiowa/assets/1017022/6b79d12d-9d43-49aa-bb7c-b9cff868a2f8">

Glossary - no longer needed

UCR/SPS - No longer need any development related to this, they will just link to Classrooms site.
```[tasklist]
### Tasks
- [ ] https://github.com/uiowa/uiowa/issues/4937
- [ ] https://github.com/uiowa/uiowa/issues/7823
- [ ] https://github.com/uiowa/uiowa/issues/7824
- [ ] https://github.com/uiowa/uiowa/issues/4936
- [ ] https://github.com/uiowa/uiowa/issues/7724
- [ ] https://github.com/uiowa/uiowa/issues/7852
- [ ] https://github.com/uiowa/uiowa/issues/7899
- [ ] https://github.com/uiowa/uiowa/issues/7933
- [ ] https://github.com/uiowa/uiowa/issues/7788
- [ ] https://github.com/uiowa/uiowa/issues/7851
- [ ] https://github.com/uiowa/uiowa/issues/7897
- [ ] https://github.com/uiowa/uiowa/issues/7898
- [ ] https://github.com/uiowa/uiowa/issues/7885
- [ ] https://github.com/uiowa/uiowa/issues/7932
- [ ] https://github.com/uiowa/uiowa/issues/7843
- [ ] https://github.com/uiowa/uiowa/issues/4943
- [ ] https://github.com/uiowa/uiowa/issues/4965
- [ ] https://github.com/uiowa/uiowa/issues/4967
- [ ] https://github.com/uiowa/uiowa/issues/4964
- [ ] https://github.com/uiowa/uiowa/issues/8042
- [ ] https://github.com/uiowa/uiowa/issues/8090
- [ ] https://github.com/uiowa/uiowa/issues/8078
- [ ] https://github.com/uiowa/uiowa/issues/8077
- [ ] https://github.com/uiowa/uiowa/issues/8134
- [ ] https://github.com/uiowa/uiowa/issues/8122
- [ ] https://github.com/uiowa/uiowa/issues/8153
- [ ] https://github.com/uiowa/uiowa/issues/8157
- [x] ~tuition and fees (nice to have)~
- [ ] https://github.com/uiowa/uiowa/issues/8185
- [ ] https://github.com/uiowa/uiowa/issues/8186
- [ ] https://github.com/uiowa/uiowa/issues/8232
- [ ] https://github.com/uiowa/uiowa/issues/7962
- [ ] https://github.com/uiowa/uiowa/issues/8287
- [ ] https://github.com/uiowa/uiowa/issues/8371
- [ ] https://github.com/uiowa/uiowa/issues/8391
- [ ] https://github.com/uiowa/uiowa/issues/8233
- [ ] https://github.com/uiowa/uiowa/issues/8312
- [ ] https://github.com/uiowa/uiowa/issues/8544
```

**Comment by joewhitsitt** [comment]
>CeCredential Validation

UNI is currently trying to build support for this in D10 and would be a good contact to learn about gotchas before works starts. We provided them our D7 code to reference. Also since we last worked on this, our test data is no longer available (in the original dropbox shares) so we would need them to provide that again.

**Comment by joewhitsitt** [comment]
Noticed that the GPA calculator on the website is not the recommended tool.

>Current Students: We recommend using [the GPA calculator tool available in MyUI](https://myui.uiowa.edu/my-ui/student/records/advising/gpa-calculator.page) for accurate GPA calculations.
>Advisors: Please utilize the Advising GPA calculator tool within MAUI when providing guidance to your students.

Would they be willing to drop this feature from the website?

**Comment by briand44** [comment]
Academic Calendar
show current + 5 sessions.
would like calendar view + list view - start with list view to see if we can avoid a calendar view altogether since they are concerned with accessibility
category functionality
ability to show subsessions
make sure solution is accessible - sessions, etc. screen reader 
currently suppressing some date categories - let's start with categories that are currently being displayed
Need to look at the datelookup "Is Web Display" = Yes and "is reviewed" = yes - may be "is print" in MAUI
display web description
when session ends auto updates to show current session + 5 - Registrar was going to chat some more about this.

Dates by Session

More internally used
Exposed filter by session - same list of sessions we currently have
Filter by category - same as academic calendar categories

5 year calendar

"Five Year Date" in MAUI
Like existing 5 year calendar
No changes to what they have.

Course Deadlines
Off-cycle courses
data.its call? Joe's comment "course deadlines is calling a static list of building abbr. to building numbers for the table result output. we can do this outside of data.its"
