### ISSUE TITLE
Commencement Epic

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7259]
Ceremonies

- Fed in from content hub. - type "Commencement" and Unit "Commencement"
- https://commencement.uiowa.edu/ceremonies
- Have the ability to add additional ceremony information - sessions, other celebrations, live streams, individual ceremony information
- photo not providing much value
- tied to a venue based on location in content hub
- Feedback that top of ceremony looks too self-contained and people don't realize that there is additional information (watch live) below that
- Ensure that ceremony information is not required per https://github.com/uiowa/uiowa/issues/7259#issuecomment-2052500253
- Finish defining metatag config

Venues

- https://commencement.uiowa.edu/venue/hancher-auditorium
- Map - no longer need points of interest
- Finish defining metatag config

```[tasklist]
### To do
- [ ] https://github.com/uiowa/uiowa/issues/7627
- [ ] https://github.com/uiowa/uiowa/issues/7638
- [ ] https://github.com/uiowa/uiowa/issues/7637
- [ ] https://github.com/uiowa/uiowa/issues/7591
- [ ] https://github.com/uiowa/uiowa/issues/7649
- [ ] https://github.com/uiowa/uiowa/issues/7658
- [ ] https://github.com/uiowa/uiowa/issues/7672
- [ ] https://github.com/uiowa/uiowa/issues/7592
- [ ] https://github.com/uiowa/uiowa/issues/7628
- [ ] https://github.com/uiowa/uiowa/issues/7706
- [ ] https://github.com/uiowa/uiowa/issues/7707
- [ ] https://github.com/uiowa/uiowa/issues/7752
- [ ] https://github.com/uiowa/uiowa/issues/7785
```

```[tasklist]
### Sprint 1 - 04/12/2024
- [ ] https://github.com/uiowa/uiowa/issues/7559
- [ ] https://github.com/uiowa/uiowa/issues/7562
```

```[tasklist]
### Sprint 2 - 04/15/2024
- [x] Not completed in this sprint: Venue content type
```

```[tasklist]
### Sprint 3 - 04/16/2024
- [ ] https://github.com/uiowa/uiowa/issues/7574
- [ ] https://github.com/uiowa/uiowa/issues/7576
```

```[tasklist]
### Sprint 4 - 04/17/2024
- [ ] https://github.com/uiowa/uiowa/issues/7577
- [ ] https://github.com/uiowa/uiowa/issues/7566
- [x] Ceremony information paragraph widget needs to be optional
```

```[tasklist]
### Sprint 5 - 04/18/2024
- [ ] https://github.com/uiowa/uiowa/issues/7590
- [ ] https://github.com/uiowa/uiowa/issues/7589
```

```[tasklist]
### Sprint 6 - 04/19/2024
- [ ] https://github.com/uiowa/uiowa/issues/7600
- [x] Display map on venue full node view
- [x] Started but did not complete: Create event migration
```

```[tasklist]
### Sprint 7 - 04/22/2024
- [x] Disable scroll wheel zoom on map
- [x] Did not complete: Create event migration, converting two date fields into one, add deltas to section accordions
```

```[tasklist]
### Sprint 8 - 04/23/2024
- [x] Revisit date range vs two date fields OR display two date fields as one field
- [x] Add deltas to collection section accordions (reference: https://github.com/uiowa/uiowa/blob/main/docroot/sites/its.uiowa.edu/modules/its_core/its_core.module#L661-L697)
- [x] Initially committed to Venue theming, but pulled it at the midday check-in in favor of having both developers focus on the migration task
- [x] Continued migration work but did not complete it
```

```[tasklist]
### Sprint 9 - 04/24/2024
- [x] Worked on migration but did not complete it
- [x] Team committed to work on venue theming, but was not able to start it
```

```[tasklist]
### Sprint 10 - 04/25/2024
- [x] Team committed to work on venue theming, but was not able to start it
- [x] Worked on migration but did not complete it
```

```[tasklist]
### Sprint 11 - 04/26/2024
- [ ] https://github.com/uiowa/uiowa/issues/7567
- [x] Worked on the migration but did not complete it
```

**Comment by pyrello** [comment]
Grooming conversation...
## Ceremonies
- We think it makes sense to build commencement events as a new site-specific content type that can import events from content hub

## Programs
- Can get attached to overall ceremony and/or individual ceremonies. Need to figure out how to have this attached (and show on) multiple event nodes.

### Archive
- Possibly switch this to a view. Check with customer about whether this would work for them.

## Venues
- Probably do this as a node instead of a taxonomy term since we'll have to modify the output of events that reference a venue anyways to limit to not show events in the past.
- Points of interest are no longer needed? - Double check with customer.

**Comment by pyrello** [comment]
Grooming conversation...

- Programs represent potential complexity, thinking about this as a probe. Want to understand exactly how this works.
- Slice: Ceremony content type. Discussed naming as ceremony or event. Settled on event based on the possibility of eventually having to reconcile with platform-wide event content type. Going to attempt to get all fields + content type best practices done. If we need to, we can pivot to just fields needed for the API import.

**Comment by pyrello** [comment]
Grooming conversation...
- How do changes from content hub get picked up?
- Intention is to set up imports rather than manually dual entering events as customer expressed concern about discrepancies between the two systems.
- URL for pulling events currently: views/events_api.json?display_id=events&filters[enddate][value][date]=01-01-2100&filters[types]=355&filters[department]=7266&items_per_page=100

**Comment by pyrello** [comment]
Need to handle ceremony information properly not being required. Currently, it is not possible to save an event without filling in the headline for the first collection item. Not sure if we can figure out different form settings for the widget (I wasn't able to so far), or if we need a new Paragraph form mode, or to create a different Paragraph type.

**Comment by pyrello** [comment]
Normally, after writing a migration and testing it in dev, we would usually wait until close to launch to run the migration to minimize the amount of double entering of content that was necessary for the customer. In this case, because we have the importer, maybe we could run the migration fairly soon after its ready and then set up the scheduled job for the importer immediately after that so that new content gets imported. There would potentially still be some double entry of content necessary for the extra fields, so we'll want to check in with the customer about the implications of that.

Looking for feedback about why this might not work or downsides to this approach.

**Comment by briand44** [comment]
I think this would be ok if Josh is ok with the double entry of extra fields.
