### ISSUE TITLE
Comms plan for SiteNow v1 Custom sites that don't need custom development to migrate?

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7290]
# Story

As a web team, we would like to have a communications plan for SiteNow v1 Custom sites that don't need any custom development to transition to SiteNow v3 so they can be aware of migration timelines and expectations.

# Additional Info

We don't necessarily know for sure what sites need custom development and what sites don't, we are just making assumptions.

# Proposed Solution

```[tasklist]
### Tasks
- [ ] https://github.com/uiowa/uiowa/issues/7481
- [ ] https://github.com/uiowa/uiowa/issues/7482
- [ ] https://github.com/uiowa/uiowa/issues/7506
- [ ] https://github.com/uiowa/uiowa/issues/7484
- [ ] https://github.com/uiowa/uiowa/issues/7483
```

**Comment by briand44** [comment]
Meeting conversation....

- Need to have a timeline that ends prior to Nov 2025 so there is still time for us if any action needed after this date.
- Probably need to use existing spreadsheets to get the list of sites we think fall in this category. Also, will need to determine who are the contacts we want to communicate with for those sites.
    - Marie did some prep for this and thought maybe around 30 sites here. 
    - Determined we want to accurately reflect the number of standard sites + custom that can be standard + custom that need custom dev and compare with site counts.
- Determined we want to verify our site counts are accurate
    - We shouldn't send any comms until we have done this.
        - generate a list manually of site directories, hit url confirming site renders, databases & domains on 701-703
        - differentiate between buckets - v1 standard, v1 custom, v1 custom that can be standard

- We could also begin working on figuring out a comms draft - doesn't need to wait.
    - Do we ask them to request a site similar to how we handled v1 standard sites?
    - Was feedback that not having a name in the email made someone think it was phishing attempts.
    - Maybe have them tell us if they no longer need site so remove some ambiguity.
    - Explain we think they can migrate without us, have them let us know if we are incorrect
- Main points of a first comm:
    - Request a new site
    - Let us know if you don’t want your site
    - If you think it’s a mistake you’re included in this cohort…
    - Love, Michael and the OSC Web Team
