### ISSUE TITLE
Probe multiple exposed filters for list blocks

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7305]
# Story

As a web team, we would like to understand if we can expose multiple filters on list blocks and have them work together so that we can make a more informed decision on a shared feature that allows searching content by title and filtering content by multiple references.

# Additional Info

Previous work related to this was part of https://github.com/uiowa/uiowa/issues/3804

Alan previous proof of concept https://github.com/uiowa/uiowa/pull/7304

# Proposed Solution
Using the most recent versions of ctools and ctools views, Probe if it is possible to both allow users to expose and set multiple exposed filters on a single list block. Using people for this will be our starting point as we can expose both the tags and research areas taxonomies. The complexity of this probe lies in figuring out how to properly expose or not expose filters in a piecemeal fashion (ex: one filter is exposed to users, the other is not but is pre-filtered in the configure tray, etc).

```[tasklist]
### Tasks
- [ ] update ctools
- [ ] update ctools views
- [ ] look at  #3804 for ideas to move forward
- [ ] look at  #7304 for ideas to move forward
```

**Comment by briand44** [comment]
Grooming conversation... multiple different filters is an unknown currently. We could use the person list block and test with tags and research area taxonomies. We want to make sure those filters can be exposed and work together.

**Comment by briand44** [comment]
Sized as a medium because there is prior work based on Alans prof dev and previous work from Sean.

**Comment by joewhitsitt** [comment]
I'd add that we should use the latest stable of the dependencies (ctools, ctools_views) if we aren't already. It seems like we were previously battling issues of multiple forms on a page. Sean had mentioned that those modules have been progressing and that we should pull that in and adjust. https://github.com/uiowa/uiowa/issues/3804#issuecomment-1610095585

**Comment by GaryRidgway** [comment]
Question 1: Can we have multiple filters on a people block and have them work together.

A: yes but not with AJAX. It will load if you disable AJAX, but not if you have it on. Also images seem to be wigging out and not rendering on filter submit.
- For specificity, I was able to pre-filter, Pre-filter and expose, expose with default pre-filtered, and mix and match all of them.

Question 1.1: Is this a pain to implement? is the UI funky?

A: I think the UI is pretty clear as long as we don't offer exposing things that don’t listen (I’m looking at you “items per page” and “offset”!)

Question 2: If we shut off exposed filters, how does that translate? are there consequences? Specifically do this in people list block?

A.1: Removing the filters completely still leaves the items per page and offset no matter what, but only allows you to expose the offset for some reason. Also the number of items per page defaults to 9 when i had it set to 3 in the tray.

A.2: Removing/un-exposing and setting individual filters works as expected, removing them from the exposed filters options in the off canvas tray.

**Comment by pyrello** [comment]
Based on your findings, what is your recommendation, @GaryRidgway?

**Comment by GaryRidgway** [comment]
I think my recommendation is thus:
(For reference, my recommendation is based on [using the code here](https://github.com/uiowa/uiowa/pull/5951))

In my personal opinion, I think this would be a great addition to the platform, and I think we should do it. I think it would be worth it to invest in providing a patch as well, as giving back to the drupal community would be good too.

This is contingent on lift of fixing the following being worth it over investigating other ideas.
- AJAX is not currently working with this.
- The `items per page` and `offset` fields are being rendered as exposed filters no matter what options are chose.
- Images are not being properly rendered on filter.
- We will need to write an update hook to fix other views.

If we decide that these are acceptable, we should implement this using the same strategy we have for linkit media library. We should invest in fixing the errors we are seeing (Incorrect filters showing, AJAX, images not loading, etc) and create some code that works within the scope of ctools_views as a patch. 

EDIT: I also forgot about the multiple list blocks on the same page not working with exposed filters. That is also a complication that should be addressed, and seems to have [had some long standing conversation here.](https://www.drupal.org/project/drupal/issues/3163299)

**Comment by joewhitsitt** [comment]
Thanks for writing this up @GaryRidgway.

>AJAX is not currently working with this.

Did you try the patch from https://github.com/uiowa/uiowa/issues/3804#issuecomment-1063094300

>The items per page and offset fields are being rendered as exposed filters no matter what options are chose.

We have a hack for this for v2:
sitenow_people_form_views_exposed_form_alter
sitenow_articles_form_views_exposed_form_alter

>Images are not being properly rendered on filter.

I feel like we had to do something to get images to render with ajax pager. I assume this might be similar. Was that part of card_4x at the very end?

**Comment by GaryRidgway** [comment]
> Thanks for writing this up @GaryRidgway.
> 
> > AJAX is not currently working with this.
> 
> Did you try the patch from [#3804 (comment)](https://github.com/uiowa/uiowa/issues/3804#issuecomment-1063094300)

I did not, let me give it a go.

> > The items per page and offset fields are being rendered as exposed filters no matter what options are chose.
> 
> We have a hack for this for v2: sitenow_people_form_views_exposed_form_alter sitenow_articles_form_views_exposed_form_alter

Let me try adding this as well.

**Comment by GaryRidgway** [comment]
I tried both patch #110 and patch #104 from [here](https://www.drupal.org/project/drupal/issues/3163299) and both of them caused full page reloads even with AJAX enabled, so I don't think they are working currently.

**Comment by GaryRidgway** [comment]
For the form alters, it currently looks like we are just disabling the entire filter form, not just individual items in the filter form, which I don't think solves the issue currently. However, this may be a good place to start in the future

**Comment by GaryRidgway** [comment]
I was able to hide fields with this similar piece of code tacked into that function though:
```
if ($view->id() === 'people_list_block') {
  if (isset($form['items_per_page'])) {
    unset($form['items_per_page']);
  }
  if (isset($form['offset']);) {
    unset($form['offset']);
  }
}
```

<details><summary>My original code looked like this until @briand44 fixed it <a href='https://github.com/uiowa/uiowa/issues/7305#issuecomment-1954920999'>here</a></summary>

```
if ($view->id() === 'people_list_block') {
  if (isset($form['items_per_page'])) {
    unset($form['items_per_page']);
  }
  if (unset($form['offset']);) {
    unset($form['offset']);
  }
}
```

</details> 

<details><summary>And what's more, It seems to remove the other action buttons if there is no remaining filters.</summary>

<img src='https://github.com/uiowa/uiowa/assets/23122142/dd0af565-beea-4240-9ca7-9c73f77d0385'/>

</details>

**Comment by briand44** [comment]
Should this be changed

```
if (unset($form['offset']);) {
    unset($form['offset']);
  }
```
to

```
if (isset($form['offset'])) {
    unset($form['offset']);
  }
```

**Comment by GaryRidgway** [comment]
> Should this be changed
> 
> ```
> if (unset($form['offset']);) {
>     unset($form['offset']);
>   }
> ```
> 
> to
> 
> ```
> if (isset($form['offset'])) {
>     unset($form['offset']);
>   }
> ```

Ope, yes, thank you. I was adding some coding safety after testing and goofed the function call. Good catch!
