### ISSUE TITLE
IWP Epic

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7358]
# Story

As an IWP site owner, I would like to showcase writers and their sample works for those that attend a Fall residency or other auxiliary programs.

# Additional Info

They would like a filterable page where they can filter by year and country (ability to select just one year and/or one country). They would like the list to default to the most recent year, show photo, title, country, year, bio, writing samples as teaser sorted by family name.

They would like us to migrate the existing writers bio content. Bring over folks dating back to 1967

url pattern - writers/[session]/[title]

Fields
Title - name
Photo - 1 - not required
Photo credit - text - Rare but needed - example https://iwp.uiowa.edu/writers/ghayat-almadhoun
*Session/Status - taxonomy - years/sessions - no need to go to term page if taxonomy - single
*Countries - taxonomy - want ability to manage these and not have a default country list - permission to create/edit/remove - need to show countries as they were prior to a name change - can be flat hierarchy -  multi valued - ideally autocomplete filter on search page.
family name - need this for sorting but doesn't get output and can't be used to create title because some cultures have family name first.
given name - need this for sorting but doesn't get output and can't be used to create title
*Languages - taxonomy - multiple - no need to go to a term page
Bio - Filtered html
Writing sample - file upload - single
Writing sample - original language - file upload - single

On the map interview - they would like this to be a multi-valued link field with a title. Existing data would be migrated with the title text "On the map interview". This may change based on an upcoming conversation around media galleries.

Year of birth - want an export from existing site
Year of death - want an export from existing site
```[tasklist]
### Tasks
- [ ] https://github.com/uiowa/uiowa/issues/7549
- [ ] https://github.com/uiowa/uiowa/issues/7610
- [ ] https://github.com/uiowa/uiowa/issues/7653
- [ ] https://github.com/uiowa/uiowa/issues/7699
- [ ] #7703
- [ ] https://github.com/uiowa/uiowa/issues/7702
- [ ] https://github.com/uiowa/uiowa/issues/7795
- [ ] https://github.com/uiowa/uiowa/issues/7810
- [ ] https://github.com/uiowa/uiowa/issues/7783
- [ ] https://github.com/uiowa/uiowa/issues/7794
- [ ] https://github.com/uiowa/uiowa/issues/7825
- [ ] #7863
- [ ] https://github.com/uiowa/uiowa/issues/7920
- [ ] https://github.com/uiowa/uiowa/issues/7940
- [ ] https://github.com/uiowa/uiowa/issues/7973
```
