### ISSUE TITLE
Ability to search/filter lists of pages by multiple different taxonomies

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7385]
# Story

As a SiteNow site owner, I would like the ability to categorize my pages in multiple different ways and create lists of those pages that can be searched/filtered by the different categories so users can easily find the content they are interested in.

# Additional Info

Related to https://github.com/uiowa/uiowa/issues/6723#issuecomment-1673728276

A commitment to Well Being folks is driving this development with the idea this can be service wide functionality and reduce some custom development as we transition remaining v1 custom sites to v3.

Comment relate to Well Being - https://github.com/uiowa/uiowa/issues/6723#issuecomment-1675380234

We determined that an area of complexity here is understanding if we can expose multiple filters on list blocks and have them plan nicely together.

```[tasklist]
### Tasks
- [ ] https://github.com/uiowa/uiowa/issues/7305
- [ ] https://github.com/uiowa/uiowa/issues/7395
- [ ] https://github.com/uiowa/uiowa/issues/7407
- [ ] https://github.com/uiowa/uiowa/issues/6578
- [ ] Add additional taxonomies to page with ability to set/override labels
- [ ] Add ability to expose title search and taxonomy filters
```

**Comment by pyrello** [comment]
When we were working on #7305, I missed the importance of @GaryRidgway's [comment](https://github.com/uiowa/uiowa/issues/7305#issuecomment-1954566142) about exposed filters not working with multiple list blocks. I looked through that issue a bit and tried a couple patches, neither of which I could get to apply. I think this represents more complexity for us with regard to how we move forward. Since I'm not able to even get a patch to apply, I can't see how close the current patches are to actually solving the issue or not. The other thing I noticed is all the related issues that seem to be describing similar but different bugs that I think represents slight variations of how these views might be used and I think we need to understand how those intersect with our use case(s). Based on the above, it is my recommendation that this is the next thing that we focus on with regard to getting through this issue. I've added an item to the task list about it.

**Comment by GaryRidgway** [comment]
- The state of play for fixing AJAX on multiple exposed filters is really confusing. [Lots of Merge requests and patches are thrown around on the issues and it it kind of a mess.](https://www.drupal.org/project/drupal/issues/3163299)
    - This has to be addressed or we have to release with a known issue that you can't place multiple, which feels bad.
    - @pyrello tested patches and found that none worked immediately in an obvious way.
- The complexity is that it's not clear what is required to get a working solution.  
- One of the patches seems to work on UMAMI in a base install, so there seems to be something that is betting broken between the basic block display and the ctools views tools making it work in layout builder.
- Sean's next step is probably probing to see what would need to happen with `ctools_views` to make it work with the patch.

**Comment by briand44** [comment]
Grooming conversation... site split for well being was discussed as the next step here. The thought is we can get something to them quicker and easier and use that to learn if there are other folks who could benefit from this type of functionality. Do we use taxonomies from Iowa Now so we don't have a conflict later (audience and category)? We can use the existing config files possibly so we don't have a uuid conflict later on.

**Comment by cory-skeers** [comment]
> Do we use taxonomies from Iowa Now so we don't have a conflict later (audience and category)? We can use the existing config files possibly so we don't have a uuid conflict later on.

I misremembered here. Iowa Now had multiple vocabularies on the D7 site, and terms from multiple of these were brought over during migration, but they were _all_ put into the default `tags` vocabulary.

There's some extra code protections when it comes to news type terms and the auto-tagging stuff, but there are no other vocabularies in its split.

**Comment by cory-skeers** [comment]
> > Do we use taxonomies from Iowa Now so we don't have a conflict later (audience and category)? We can use the existing config files possibly so we don't have a uuid conflict later on.
> 
> I misremembered here. Iowa Now had multiple vocabularies on the D7 site, and terms from multiple of these were brought over during migration, but they were _all_ put into the default `tags` vocabulary.

I did a search for any other site splits that might have overlapping: brand has `orgs`, housing has multiple vocabs like `amenity_type`, hr has `faq_categories` and `units`, iisc has `colleges_and_departments`, home has `a_z_list`, and uipress has several book-related ones. None seemed like a great overlap with the ones being made here.

**Comment by pyrello** [comment]
I'm a bit confused by this issue as it is currently written. Is the idea that we would introduce a second vocabulary that is referenced by the page content type? Currently pages can reference tags and that's it. It seems like if we ever did this, we would need to add a second vocabulary and then define what it was called and what it was for. Or make its name configurable. Is that actually something that is broadly desired on the platform?

**Comment by briand44** [comment]
Yeah, the idea was that we would potentially add more than one additional taxonomy that is referenced by the page content type and allow configuring the labels for those taxonomies. Folks could then create pages of content, tag them and categorize them how they wish and then display them on a page with exposed filters to allow users to search and filter. Basically, a flexible feature that would allow folks to build these dynamic pages without requiring custom development from us.

We stopped short of adding additional taxonomies platform wide when working on a solution for well being site and just created those custom for that site.
