### ISSUE TITLE
ITS Support Article Feedback

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7462]
- They would like the category reference field to be a select list or radios rather than an autocomplete.
- They don't want the ability for folks creating support articles to set a custom url alias.
- They would like the url pattern to be `services/[service]/[support article title]`
- They would like the breadcrumb to output `Home / Services / [Service] / [support article title]`
- They would like to display the support article number and last udated date at the bottom of a support article rather than the sidebar. The service and category do not need displayed since the service will be available in breadcrumb and category link doesn't add value.
- Probably need to rabbit hole the category terms?

# Proposed Solution
```[tasklist]
### Tasks
- [x] Convert category reference field to use radios
- [x] Hide URL alias field group for non-admins
- [x] Update URL alias pattern to `/services/[service-title]/[article-title]`
- [x] Ensure that breadcrumbs display as `Home / Services / [Service Title] / [Article Title]`
- [x] Remove Category and Service from full node display
- [x] Move article number and last updated to the bottom of the page
- [x] Rabbit hole category vocab
```

**Comment by GaryRidgway** [comment]
url patterns
not completely sure that the URL patterns are set in stone. Adrian said that she felt like the current pattern is correct, but it is a big change so they want Tracy to sign off on it. Big agreement on the pattern, but want leadership signoff.
Support article number
Thought that service and category can be removed as the service will be in breadcrumbs, and category provides little value. Should display article number and last updated at the bottom of the article. We need to come up with some type of way for this to be Displayed.
Category term pages
We should rabbit hole the category term pages. there is no real reason to display it on the article itself because it is an antipattern for how to navigate the site. We only use them for internal categorization, so no desire to display them on the site.

**Comment by GaryRidgway** [comment]
For the breadcrumbs, in our tasklist here it says that they need to have the article title at the end. Since we would already be on the article, we could stop at the service, correct? that is how it is currently working

<img width="1369" alt="Screenshot 2024-03-19 at 10 58 08 AM" src="https://github.com/uiowa/uiowa/assets/23122142/a961fc5a-7bb2-48c8-ab5a-82bef9cb1d5a">

**Comment by cory-skeers** [comment]
> For the breadcrumbs, in our tasklist here it says that they need to have the article title at the end. Since we would already be on the article, we could stop at the service, correct? that is how it is currently working
>

That should be fine. Stuff in the menu includes the title, but we have a difference between the two methods.

There was a bit of convo in a previous issue that was similar https://github.com/uiowa/uiowa/pull/6984
