### ISSUE TITLE
Finalize and send draft of comms for SiteNow v1 custom that we believe don't need development

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7483]
# Story

As a web team, we would like to finalize and send our comms to SiteNow v1 custom sites that we believe can transition without development so we can make them aware of the need and timeline for their transitions and we can verify we've identified these site correctly.

# Additional Info

Make sure all dates, etc. in email draft are finalized

Get Dispatch ready

Send

# Proposed Solution
```[tasklist]
### Tasks
- [x] Ensure communication is finalized with dates and any other details
- [x] Create a communication in Dispatch under the existing campaign for V1 sites
- [x] Placeholders need to be formatted for Dispatch
- [x] Send test email
- [x] Send actual email
```

**Comment by briand44** [comment]
Grooming conversation... Make sure email communication is finalized with dates, etc. We will need to create the communication in Dispatch. Should have a campaign already. Should make sure placeholders are properly formatted. Schedule test email. Send

**Comment by bspeare** [comment]
The test email for this has been sent to its-web.  Please take a look. I have set May 31, 2024 as the response date.

**Comment by pyrello** [comment]
Sorry, I'm just now noticing this, but I think this partial sentence is kind of weird and maybe not necessary:

> ...at a temporary location we’ll provide you.

It just seems like maybe that its too much info or confusing info.

**Comment by bspeare** [comment]
Dispatch link for those that need it https://apps.its.uiowa.edu/dispatch/communications/1315926162.

**Comment by joewhitsitt** [comment]
Did I hear that Michael wanted to take one last look at this before it is sent? Should this be moved to blocked/waiting?

**Comment by bspeare** [comment]
He took a look and added some updates.   I'll send a preview to its-web one more time.

**Comment by bspeare** [comment]
This has been sent.
