### ISSUE TITLE
Identify contacts for v1 custom to v3 standard

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7484]
# Story

As a web team, we would like to identify contacts for each of the SiteNow v1 custom sites that we believe can transition so we can have the appropriate information to send the comms.

# Additional Info

Identify contacts and contact information related to each site and create a csv to use for the Dispatch populations. Need site name, site url, contact name(s), contact email(s).

# Proposed Solution
```[tasklist]
### Tasks
- [x] Deliverable: CSV/Excel sheet with URL and email columns, one row per contact (may have multiple rows per site)
- [x] Figure out a method to populate the above information (automated, manually checking sites, personal knowledge, asking Brian/Michael)
- [x] If any sites do not have at least one viable contact, generate a list of those sites for further processing
```

**Comment by briand44** [comment]
Grooming conversation... current spreadsheet is one site per row, if we identify more than one contact per sites, Dispatch will need one contact per row. Discussed how we should identify contacts. Mentioned existing spreadsheets have some contacts but could very well be out of date, could log in and look for webmasters who have been active most recently, some we may just know from familiarity with site, Brian willing to review. Reporting command could potentially be used but have to downgrade to get it to work, would need to tweak the command and also would want a manual review. Using the reporting command may take more time than what it is worth based on the number of sites we are talking about here. Email currently uses site name, site url, contact name and email would be needed. Discussed that we should be creating the file that Dispatch will use here rather than adding info to the new spreadsheet. If we can't identify a contact for a site, let's keep track of those and we can try and identify a unit/department leader to reach out to?

**Comment by joewhitsitt** [comment]
Brian mentioned yesterday that based on the current recommendations, many of the contacts will be same (Research and FO). We already know that CLAS and GRAD are working most of the MiscD7, but that we could bring up the current list with them to get an understanding of progress and bring up others that might not be on their list.

**Comment by joewhitsitt** [comment]
Here is the CSV based population for the next email: https://apps.its.uiowa.edu/dispatch/populations/1313271068/members

**Comment by joewhitsitt** [comment]
The rows in the All D7 sheet related to this work were updated with this info. Also updated miscd7 matching the same criteria as part of this.

**Comment by joewhitsitt** [comment]
Looking for review before closing

**Comment by briand44** [comment]
Some thoughts... I would probably include Wendy DeCora on all Athletics site emails in addition to Eddie and whoever else. See https://github.com/uiowa/uiowa/issues/7506#issuecomment-2040150716 related to iowalionseyebank. Not seeing Wendy Moorehead on treasury.fo and ubill.fo. Was she left off those on purpose? I can reach out to Wendy if we need to verfiy if she should be on all FO related sites?

**Comment by joewhitsitt** [comment]
Good eye. When I saw Laurie had accessed those sites recently I didn't even think of updating it. All FO should be updated with Wendy M. in the sheet and in the population.

Added Wendy D. to medforms and hawkeyespaces.

Updated lionseyebank.

**Comment by briand44** [comment]
I added the contacts for vandervelde.studio.uiowa.edu to the dispatch population.

**Comment by joewhitsitt** [comment]
Is this good to close now?
