### ISSUE TITLE
Update to Drupal 10.2

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7486]
# Motivation

To take advantage of a bug fix for external fonts to be loaded via add_css ajax command, it is necessary to get to Drupal 10.2.3.

# Proposed solution

To check if all our dependencies are compatible with Drupal 10.2, run the following command:

```
ddev composer prohibits drupal/core 10.2
```

Once all dependencies that need to be upgraded to be compatible and can be upgraded ahead of time have been upgraded, we can run the following command:

```
ddev composer require drupal/core-recommended:^10.2 drupal/core-composer-scaffold:^10.2 --update-with-all-dependencies
```

If there are problems with the above command, it is also possible to update the version constraints for the above packages in composer.json and then run

```
ddev composer update --lock
```

```[tasklist]
### Tasks
- [x] Fix deprecations
- [x] Fix PHPCS updates
- [x] Update default config
- [x] Fix tests
- [x] Update config split config
- [x] Review P2LB config updates to decide whether to keep or ignore them
```

**Comment by joewhitsitt** [comment]
It would be nice if we could address some clean up while we work on this if it ends up being fairly straightforward (knocking on wood).

https://github.com/uiowa/uiowa/pull/7492#issuecomment-2013628623
https://github.com/uiowa/uiowa/labels/dependencies
https://github.com/uiowa/uiowa/issues/7155
https://github.com/uiowa/uiowa/issues/7041
https://github.com/uiowa/uiowa/issues/7129
https://github.com/uiowa/uiowa/issues/6933

**Comment by briand44** [comment]
Grooming conversation... Be aware of https://github.com/uiowa/uiowa/issues/7486#issuecomment-2021269937 and size to accommodate but all will depend on how things go once we dive in. Likely will want more than one team member testing here.

**Comment by pyrello** [comment]
> Fix PHPCS updates

There were none, as far as I could tell.

> Fix deprecations

Looks like there are some deprecations here, which is surprising because I wouldn't expect there to be on a minor version upgrade. The deprecations are supposed to happen between the last minor version of a major release series and the first minor version of the next major release series.

> Call to deprecated function system_retrieve_file():              
> in drupal:10.2.0 and is removed from drupal:11.0.0. There is no  
> replacement.

Currently working on figuring out how to fix these.

Also, this issue is great! Reminders for all the things I tend to forget when I do these types of upgrades. We should consider making this into a template for future core update issues.

**Comment by pyrello** [comment]
I accidentally synced commencement while I still had composer dependency updates from this PR in place and saw a bunch of changes, so I'm going to take a moment to fix those in this PR.

**Comment by pyrello** [comment]
> I accidentally synced commencement while I still had composer dependency updates from this PR in place and saw a bunch of changes, so I'm going to take a moment to fix those in this PR.

Okay... nevermind. There were no changes. I guess I was just seeing this because of the mismatch between being on a branch forked from `main` with composer dependencies from this PR still in place. Good news is I checked and commencement config is up-to-date.

**Comment by joewhitsitt** [comment]
Scheduled an alert for the planned wednesday morning deployment: https://its.uiowa.edu/alert/129516
