### ISSUE TITLE
Emergency.uiowa.edu epic

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7487]
- hawk alert content type
    - title - will get populated from Rave - need ability to edit in case of a typo in Rave
    - complete
    - status - single valued - they want the ability to add new terms here. They only get output on the hawk alert node as text and don't get linked to. Rabbit hole. Want output higher up on hawk alert node rather than at bottom.
    - body - no summary needed - will get populated from Rave - need ability to edit in case of typo in Rave.
    - Situation Updates - Paragraph collection with date and details similar to ITS alert updates.
        - want to output the date first on the hawk alert node rather than last like it is currently.
        - want this to be a little easier to read
        - would like the date to default to now rather than empty
        - list these chronologically with most recent updates first similar to what we did with ITS
    - Don't need the notes field anymore
- Show active Hawk Alerts at top, stacked if multiple with most recent first
    - If no active Hawk Alerts, want to show the campus status Normal message with additional text as is currently
- Will want to show recent hawk alerts that are no longer active 3-5 on front page with link to all. They are checking on how many past hawk alerts they need to keep and how those should get added/imported
- job to check Rave every minute and create Hawk alert content from that feed. Do we want to revisit this to see about Rave pushing to us?
- Nice to have would be a way to relate a hawk alert to another hawk alert

# Questions

We should ask about e.uiowa.edu and www.emergency.uiowa.edu. I'm a little confused on www. The domain exists on 702 but not seeing it covered in the 702 cert.

e.uiowa.edu is covered in the 702 cert and the domain exists on the 702 application. We have an entry in sites.php for this which doesn't seem like how we have been handling things in SiteNow v3. May make more sense as a vulture redirect if it is still needed.

```
$sites['emergency.prod.drupal.uiowa.edu'] = 'emergency.uiowa.edu';
$sites['emergency.uiowa.edu'] = 'emergency.uiowa.edu';
$sites['e.uiowa.edu'] = 'emergency.uiowa.edu';
$sites['www.emergency.uiowa.edu'] = 'emergency.uiowa.edu';

```
```[tasklist]
### Tasks
- [ ] https://github.com/uiowa/uiowa/issues/7501
- [ ] https://github.com/uiowa/uiowa/issues/7502
- [ ] https://github.com/uiowa/uiowa/issues/7503
- [ ] https://github.com/uiowa/uiowa/issues/7520
- [ ] https://github.com/uiowa/uiowa/issues/7521
- [x] www.emergency.uiowa.edu SSL
- [ ] https://github.com/uiowa/uiowa/issues/7578
- [ ] https://github.com/uiowa/uiowa/issues/7586
- [ ] https://github.com/uiowa/uiowa/issues/7550
- [ ] https://github.com/uiowa/uiowa/issues/7654
- [ ] https://github.com/uiowa/uiowa/issues/7686
- [ ] https://github.com/uiowa/uiowa/issues/7687
- [ ] https://github.com/uiowa/uiowa/issues/7688
- [ ] https://github.com/uiowa/uiowa/issues/7818
- [ ] https://github.com/uiowa/uiowa/issues/7815
- [ ] #7582
- [ ] https://github.com/uiowa/uiowa/issues/7689
```

**Comment by joewhitsitt** [comment]
capturing some of my notes from the meeting:

- situation updates are not connected to rave so the date field could be an actual date field vs the string they currently have.
- they would appreciate an export of current data for redundancy purposes regardless of what legal says needs to be carried over to the new site.
- moderation should not be added or we need to make sure it doesn't interfere with the automated RAVE process or their manual update workflow.

>Nice to have would be a way to relate a hawk alert to another hawk alert

This relationship could make it easier to sort/group alerts in the order they desire.

**Comment by pyrello** [comment]
> title - will get populated from Rave - need ability to edit in case of a typo in Rave
> ...
>body - no summary needed - will get populated from Rave - need ability to edit in case of typo in Rave.

Do these get synced regularly? Or is it a one-time thing? If it is a regular occurrence, are we worried about preserving edits they've made to the title?

**Comment by pyrello** [comment]
> job to check Rave every minute and create Hawk alert content from that feed. Do we want to revisit this to see about Rave pushing to us?

I'm assuming we would need an endpoint with POST, which is kind of a big deal from a security standpoint. Something to keep us awake at night...

**Comment by briand44** [comment]
>Do these get synced regularly? Or is it a one-time thing? If it is a regular occurrence, are we worried about preserving edits they've made to the title?

@pyrello my understanding is it is a one time thing. Updates are manually made to a Hawk Alert on the Emergency site and if any changes are made to Rave it would create a new Hawk Alert
