### ISSUE TITLE
Hawk alert content type for emergency site

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7501]
# Story

As an Emergency site owner, I would like to be able to have Hawk Alert content on our site so that the campus community can be informed of emergency situations.

# Additional Info

- Site split
- Hawk Alert content type - https://iowa.sharepoint.com/sites/drupal-developer-documentation/SitePages/Miscellaneous/Content%20type%20creation%20notes/Content%20type%20creation%20notes.aspx
- moderation should not be added or we need to make sure it doesn't interfere with the automated RAVE process or their manual update workflow. - Joe's comment from https://github.com/uiowa/uiowa/issues/7487#issuecomment-2013184149
  - Title
  - Body field (summary won't be used)
- layout builder template for full node

Additional fields can be a separate slice - https://github.com/uiowa/uiowa/issues/7503

Title and body field get populated from Rave but can be a separate slice. - https://github.com/uiowa/uiowa/issues/7502

# Proposed Solution
```[tasklist]
### Tasks
- [ ] Establish site split with Hawk Alert content type following content type creation notes
- [ ] No moderation, permissions to toggle published status for the content type and override the checkbox
- [ ] Enable layout builder for the content type and include in split
```

**Comment by briand44** [comment]
Grooming conversation... Purposely left some fields out of this slice because they are not needed to integrate with Rave and we thought it would be good to get to that Rave integration slice early-ish in the process. Could be included or both issues pulled in a sprint if desired. Discussed leaving moderation off for now and potentially adding in down the road. Complete field was brought up to determine if there is anything we need to account for other than where it displays (do we output closed text in title). Decided to move complete field to the future slice of adding additional fields not required for the Rave integration.

**Comment by cory-skeers** [comment]
Couple items that came up while putting together the PR that I made assumptions on:

- Permissions? I matched Page content type
- URL pattern? I left this off, and it defaults to /title, which matches current site pattern: https://emergency.uiowa.edu/hawk-alert-fire-department-has-cleared-scene-gas-line-break-resume-normal-activity-more
- Metatags? I created a separate metatag pattern as well as enabled SEO settings, but these still inherit from global and content. At this time, I'm not sure there's any need to adjust these, but I imagine in the future we will want to, and it can be part of a #7503
