### ISSUE TITLE
Rave integration

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7502]
# Story

As an Emergency site owner, I would like the Emergency site to consume alerts from Rave since that is where Hawk Alerts are initiated.

# Additional Info

Establish test and prod connection with rave

Rave data should populate title and body field on Emergency. Both fields need to be editable in case there is a typo. Discussion https://github.com/uiowa/uiowa/issues/7487#issuecomment-2013664430 and https://github.com/uiowa/uiowa/issues/7487#issuecomment-2013675035

**Rave endpoints**
- stage - https://content.getrave.com/cap/uiowatest/channel1
- prod - https://content.getrave.com/cap/uiowa/channel1

# Proposed Solution
```[tasklist]
### Tasks
- [x] Fetch alert info from Rave endpoints, similar to Classrooms and Facilities API calls
- [x] Use Rave info to create a Hawk Alert and populate the title and body fields. Fields need to remain manually editable. Theming/display not in scope for this slice.
- [x] Set up scheduled job to check Rave for new alerts - D7 job checks every minute. No need to check for updates to existing alerts as all updates will happen manually on the emergency site.
```

**Comment by joewhitsitt** [comment]
It was mentioned that headline (title) and description (body) are the same thing from their end. We should probably just map it up as before, but wanted to bring it up.

**Comment by joewhitsitt** [comment]
Technically, the endpoint is configurable on the website through the feeds ui. Having the ability to temporarily switch endpoints for debugging might be _nice to have_ similar to content hub (config set).

**Comment by joewhitsitt** [comment]
We will have to setup a similar job to uiowa702.prod to fetch every minute. Any kind of differences for ACN (e.g. uiowa07 paths) will need to be accounted for.

**Comment by briand44** [comment]
Grooming conversation... D7 uses feeds and we have yet to use feeds with D10 so likely need to handle this similar to Classrooms/MAUI/Facilities. We don't have the ability to create additional test content in Rave so if we need changes to test content in Rave, we will have to ask Hayley/Anna. Scope is having a new hawk alert created on the new site, not displayed, themed, etc. We also want the scheduled job in scope for this. Just concerned with creation, updates don't happen through Rave, they are updated manually.

**Comment by e-marie-w** [comment]
For visibility: I plan to add an 'Alert Identifier' field that can't be edited to the content type, so that duplicate alerts aren't created due to manual updates changing the values of the title and body.

**Comment by joewhitsitt** [comment]
Information from 702.prod

```
log="/var/log/sites/${AH_SITE_NAME}/logs/$(hostname -s)/drush-cron.log"; /var/www/html/${AH_SITE_NAME}/scripts/hawkalert.sh &>> $log
```

```sh
#!/bin/bash

# The end timestamp is now + 300 seconds (5 minutes).
end=$(( $(date +%s) + 300 ))

while : ; do
start=$(date +%s)

# This is where you run the drush command, wget,
# curl, etc. that you would like to execute once a
# minute.
log="/var/log/sites/${AH_SITE_NAME}/logs/$(hostname -s)/drush-cron.log"
echo [HAWK ALERT IMPORT] `date` &>> $log
drush @${AH_SITE_GROUP}.${AH_SITE_ENVIRONMENT} -l emergency.uiowa.edu feeds-im rave_feed -y &>> $log

# Ensure it does not run more frequently than once
# per minute by sleeping if the command takes less
# than a minute to execute.
sleep $(( 60 - $(date +%s) + $start ))

# Exit the loop if the current timestamp exceeds the
# end timestamp.
[ $(date +%s) -lt $end ] || break
done
```

**Comment by joewhitsitt** [comment]
Got distracted by a growing log file on uiowa07.prod. Acquia doesn't clean/archive these files for ACN. Will need to adjust paths and such, but we may want to rely on the drush/drupal code to log messages related to this job and move away from drush-cron.log

**Comment by joewhitsitt** [comment]
Here is an adjusted call that outputs to the shared log that I think will work and not "cause issues." There are log messages in the script with descriptors and timestamps.

```sh
log="/shared/logs/drush-cron.log"; /var/www/html/${AH_SITE_NAME}/scripts/hawkalert.sh &>> $log
```

**Comment by joewhitsitt** [comment]
All of this has been deployed. PROD scheduled job is setup and triggering. DEV has been cleaned up. Separate PR to fix complete field here: https://github.com/uiowa/uiowa/pull/7587
