### ISSUE TITLE
ITS - Fix "Closed" designation logic and setup website in DEV for email testing

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7510]
# Problem

Alerts only get the "[Closed]" designation on the title during presave so planned maitenance items that close by a scheduled end date, fall off views and then never touched again, don't get the extra title text.

Additionally, ITS staff want the ability to test recent email functionality in DEV without worrying about spamming their listserv.

<details>
- they want the "Getting Started" support article category to be displayed first on services. They are still working to identify if there is a specific order for any others.
  - Ben's comment - we will need to wait until all categories have been added to set the weights.  If a new category is added, it appears at the top of the list.
- They mentioned the alert end date time field displays before the end date field whereas the start date time displays after the start date. They wondered if we could place the end date time after the end date to be consistent. This is nice to have and not needed if takes much effort.
- They want to verify that a planned maintenance alert with a known end date will automatically close after the end date passes.
  - Joes comment - Planned maintenance that ends falls off views, but the title is not updated to be [Closed] - need to move to preprocess_node instead of presave if we don't want to refactor it all.
- Adrienne would like to test the email functionality around alerts. Discussed doing this in a non-production environment.
- The email to Help Desk when an alert needs reviewed/published should also send to Teams (51923d18.iowa.onmicrosoft.com@amer.teams.ms).
  - addressed by https://github.com/uiowa/uiowa/pull/7508
  - I am curious if this actually happens currently. I have reached out to Adrienne/Jamie to see if they have some email fwd rule or something to handle this currently because I am not aware that we are currently doing anything to notify that Teams channel and want to avoid duplicate notifications if they are handling this in another fashion.
- Permissions for webmasters to create support article category terms
  - (addressed by https://github.com/uiowa/uiowa/pull/7508)
- moderation looked like it was missing when editors updating a service.
  - Joe's notes: my bad https://github.com/uiowa/uiowa/pull/7499/files#diff-ee315409599e4260135717434dc095950e0ddfb51167843a18d43150d263e994
    - addressed by https://github.com/uiowa/uiowa/pull/7508

Joe's additional notes/comments:

- Alert specific seo settings? ~~Currently using base content presets for fields that don't exist (e.g. featured image)~~. That just seems to be the way it is.
- No SEO settings for non-admins available for support articles?
  - addressed by https://github.com/uiowa/uiowa/pull/7508
- No results text views looks off balance and duplicative on alerts landing page
- They will review permissions work but might want the ability of editors to publish service content? This would result in a different workflow or removing moderation once again.
- Bump for content overview/moderation enhancements (showing moderation states in addition of unpublished/published)

Training Idea: When to Delete or Archive content?
</details>

# Proposed Solution
```[tasklist]
### Tasks
- [x] Building off of the existing work in https://github.com/uiowa/uiowa/pull/7508, move [Closed] text code to `preprocess_node` and test with planned maintenance scenario
- [x] Create the site in dev so Adrienne can test alert emails. Set the workbench_email template address to something else.
- [x] See if email specific logic can be removed https://github.com/uiowa/uiowa/blob/main/docroot/sites/its.uiowa.edu/modules/its_core/its_core.module#L285
```

**Comment by briand44** [comment]
Joe's notes

- Alert specific seo settings? Currently using base content presets for fields that don't exist (e.g. featured image).
- No SEO settings for non-admins available for support articles?
- No results text views looks off balance and duplicative on alerts landing page
- Planned maintenance that ends falls off views, but the title is not updated to be [Closed] - need to move to preprocess_node instead of presave if we don't want to refactor it all.
- Perms for support article categories (addressed by https://github.com/uiowa/uiowa/pull/7508)
- Send new alert email to 51923d18.iowa.onmicrosoft.com@amer.teams.ms as well  (addressed by https://github.com/uiowa/uiowa/pull/7508)
- They will review permissions work but might want the ability of editors to publish service content? This would result in a different workflow or removing moderation once again.
- Bump for content overview/moderation enhancements (showing moderation states in addition of unpublished/published)

Training Idea: When to Delete or Archive content?

**Comment by briand44** [comment]
>The email to Help Desk when an alert needs reviewed/published should also send to Teams

>I have reached out to Adrienne/Jamie to see if they have some email fwd rule or something to handle this currently because I am not aware that we are currently doing anything to notify that Teams channel and want to avoid duplicate notifications if they are handling this in another fashion.

Heard back from Adrienne and Jamie and there is an email forward rule in place so we do not need to send an email to notify the Teams channel, that would cause duplicate notifications.

**Comment by briand44** [comment]
Grooming conversation... We should give them the ability to order support article categories so they can do this when convenient for them. Should be done already based on the permissions changes in the PR. Discussed leaving the date time fields as they are. Agreed it makes sense to add the [Closed] text to planned maintenance by moving to preprocess_node. We discussed creating the site in dev so Adrienne can test alert emails since we will likely need the dev environment for when we run the service migration as well. If folks think stage makes more sense for some reason, please chime in. Other remaining items above seem to already be addressed in the existing PR. There were a couple items in Joe's comments we weren't familiar with so haven't included in this slice yet but can adjust if Joe weighs in.

**Comment by joewhitsitt** [comment]
>There were a couple items in Joe's comments we weren't familiar with so haven't included in this slice yet but can adjust if Joe weighs in.

I think the current proposed solution is appropriate based on the notes and what has already been done.

The bump for content overview enhancements is not a blocker. Just capturing it.

I guess this is just coming over as an eye sore in my opinion. They control the layout. They can include a headline with these block displays. No developer action I guess.

<img width="1337" alt="Screenshot 2024-03-27 at 4 17 03 PM" src="https://github.com/uiowa/uiowa/assets/4663676/8b0c7736-b9bc-45d7-b3e1-896f241a5b0f">

**Comment by joewhitsitt** [comment]
Initially looking at this, I don't think there is _one_ spot to override the title on the fly for everything. Probably why we have favored presave so much to date. Layout builder field page title gets the title differently than the rendered entity teaser, etc.

**Comment by joewhitsitt** [comment]
Capturing some notes:

Extending Entity::label() in ItsAlert changes things like our card teaser.
Extending Node::getTitle() in ItsAlert changes things like tokens/metatag.
its_core_preprocess_field__node__title only seem to change the full node layout title.

`hook_ENTITY_TYPE_load` seems to cover all of these AND things like the content overview, node form title, etc.. So far the only gap I've seen is the post-save message.

Update: had to leave the send_alert_email isClosed logic in. I can see the value here, $entity->values['title']['x-default'][0]['value'], but any attempts to get this with $entity->get('title') or $entity->label() or $entity->getTitle() or $entity->title->value aren't returning it without loading the entity. It is so close!

**Comment by joewhitsitt** [comment]
I setup its.dev and initially configured sendmail as transport and adjusted the email variables to my address. Emailed Adrienne to see what addresses we should use for their testing.
