### ISSUE TITLE
Migrate ITS Support Articles

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7519]
# Story

As an ITS site owner, I would like to have our support articles migrated from our D7 site to our new site so that we do not have to manually re-create each one.

# Additional Info

Migrate all published D7 support articles to D10 support articles ~1000

**Mappings - D10 - D7**

- Title - title
- Short Description - field_short_description
- Summary - body summary
- Body - filtered html - body
- Service - single - entity reference - field_info_center
- Category - single - reference - field_sa_category
- Faqs - multiple - field collection to paragraph - field_sa_faq
- Authored On date

Url Alias - no need to map and migrate custom url aliases that have been set for support articles.
Redirects - create redirects from the previous url alias to the content on the new site.

# Questions

Are they going to create support article category terms prior to migration or do we need to create on import if they do not exist?

# Proposed solution

```[tasklist]
### Tasks
- [x] Referencing recent migrations, attempt to use yaml mapping for most of this content migration, and string match lookups for the reference fields.
- [x] Reference and setup a redirect migration
- [ ] Given that there are 1000+ items, consider batching
- [ ] Consider establishing a paragraphs processing plugin if one does not already exist
```

**Comment by briand44** [comment]
Grooming conversation... if they manually create terms for categories, they would need to match the old site for them to wire up correctly. Brian to chat with Adrienne to confirm they will create these and to have them let us know if any terms will be changing. Around 1000 records to migrate so we may need to set batch sizing accordingly. Scope to getting migration working locally and reviewed, running migration in dev can happen in a separate slice. If we have any examples of a field collection to paragraphs mapping that could be helpful here. Sean mentioned If we don’t have a process plugin figured out for paragraphs, might try to get something written for that as part of this.

**Comment by joewhitsitt** [comment]
Going to see if I can start on this without too much trouble. I see that https://github.com/uiowa/uiowa/pull/7524 will be beneficial in establishing the module and the content for the services reference. I'll see how far I can get before asking @GaryRidgway if I can merge into that branch.

**Comment by joewhitsitt** [comment]
I need to double check, but I think I have everything accounted for. Need to run through and find examples for each field to make sure. I believe the images are coming in for the FAQs but I am getting several `Could not load metadata from ... because it does not exist.` type errors that I need to investigate.

There also seems to be an issue with how the moderation was removed from the content type. Getting a lot of `The "extra_field_block:node:support_article:content_moderation_control" was not found` warnings. I plan to clean that up somehow too.

**Comment by joewhitsitt** [comment]
The `Could not load metadata from ... because it does not exist.` errors were related to its.prod assets that I didn't have locally.

Learned from the meeting today, that the migration should not create support article categories that don't already exist. This means that some articles will be moved over without a category and will need to be assigned one the next time they are saved. (e.g. software)

I think I fixed the moderation block issue as well.

What I have currently for body summary is not working I don't think.

**Comment by joewhitsitt** [comment]
Possible broken links:

<details>

```
- Possible broken links found in node 56: .: node&quot; data-entity-uuid=&quot;d8039b7a-4381-4a1c-aa4f-b7e866d75229&quot; href=&quot;/node/46
- Possible broken links found in node 76: email alias: node&quot; data-entity-uuid=&quot;b742c90f-4ff7-44fa-aaae-007f08370d85&quot; href=&quot;/node/136,how to log in and access your email through a web browser: node&quot; data-entity-uuid=&quot;2383762a-dcc2-4773-811c-280bc0f74a87&quot; href=&quot;/node/131,how to set up Outlook on your Windows or Mac machines: node&quot; data-entity-uuid=&quot;b3519003-159f-493f-9245-75b7b277b21c&quot; href=&quot;/node/141,download and install Office: node&quot; data-entity-uuid=&quot;d00dcea1-7a65-41b9-957b-25d663454679&quot; href=&quot;/node/146,instructions for downloading and installing Outlook on your mobile phone: node&quot; data-entity-uuid=&quot;7029c3e8-3f02-4649-8456-bf2a76703ea6&quot; href=&quot;/node/151,how to recognize and avoid phishing scams: node&quot; data-entity-uuid=&quot;66aba033-d1ef-4475-b867-584eecb52e9f&quot; href=&quot;/node/156,how to report any suspected phishing you might receive to ITS: node&quot; data-entity-uuid=&quot;e8f12731-796c-440b-bc22-cec376fb8e64&quot; href=&quot;/node/161,make a change to your name or email address: node&quot; data-entity-uuid=&quot;019f935b-cbbf-4efd-9a8f-9c452b6b0c85&quot; href=&quot;/node/166,Calendar Combiner: Add your course meeting times and locations to your calendar: node&quot; data-entity-uuid=&quot;53af49a0-283b-474d-b102-e11c40f92f8d&quot; href=&quot;/node/171&quot; media_library=&quot;Media Library,Adding University Calendars (Board of Regents Calendars, Holiday files, etc) to your Outlook calendar: node&quot; data-entity-uuid=&quot;386b4492-9bae-449b-bee2-c3157a4944aa&quot; href=&quot;/node/176&quot; media_library=&quot;Media Library,Add BMindful Holy Days to your calendar: node&quot; data-entity-uuid=&quot;38d9c8a1-38c6-4895-be7a-d2faf68a446e&quot; href=&quot;/node/181&quot; media_library=&quot;Media Library,r: node&quot; data-entity-uuid=&quot;b651f129-6627-4633-9e65-5ffa3cb7f031&quot; href=&quot;/node/186&quot; media_library=&quot;Media Library
- Possible broken links found in node 81: installing an antivirus program: node&quot; data-entity-uuid=&quot;23df283b-fba6-4978-b366-a490217174b5&quot; href=&quot;/node/196,Suggested Computer Configurations for Students: node&quot; data-entity-uuid=&quot;567e9330-00cc-4e7f-bc33-06fc2e0ee1c7&quot; href=&quot;/node/201,Request help with Technology: node&quot; data-entity-uuid=&quot;ff5f6b7c-624a-406f-bc93-c4aaa9a1fdff&quot; href=&quot;/node/226,Buying a computer and local repair options: node&quot; data-entity-uuid=&quot;b79cd47b-50d4-4e2b-82c8-941aaf54d27b&quot; href=&quot;/node/206
- Possible broken links found in node 86: outdoor and drive-up wireless support page: node&quot; data-entity-uuid=&quot;76933d0a-5a25-4ba9-b16e-af5f2de57a2e&quot; href=&quot;/node/231,eduroam Configuration Assistant Tool (CAT): node&quot; data-entity-uuid=&quot;253815a8-0abb-44eb-8dfa-d1aa188fafb2&quot; href=&quot;/node/236,ResNet: node&quot; data-entity-uuid=&quot;aa79d243-0983-4325-9c04-19ac0f0250df&quot; href=&quot;/node/241,Forget the network: node&quot; data-entity-uuid=&quot;c65bd31a-1779-4fbd-858a-4f20e203bd70&quot; href=&quot;/node/251,trust the certificate: node&quot; data-entity-uuid=&quot;f1468102-0c58-4374-8ec0-c78dcb550a79&quot; href=&quot;/node/256&quot; media_library=&quot;Media Library
- Possible broken links found in node 91: Follow these meeting etiquette tips: node&quot; data-entity-uuid=&quot;1ce883f7-98da-4676-8b66-0f26fedd27e1&quot; href=&quot;/node/261&quot; media_library=&quot;Media Library
- Possible broken links found in node 96: Contact the ITS Help Desk: node&quot; data-entity-uuid=&quot;ff5f6b7c-624a-406f-bc93-c4aaa9a1fdff&quot; href=&quot;/node/226&quot; media_library=&quot;Media Library
- Possible broken links found in node 106: Qualtrics (survey) training&amp;nbsp;: node&quot; data-entity-uuid=&quot;b08dec98-079c-4044-a3ac-0e3d0523a8fb&quot; href=&quot;/node/266&quot; media_library=&quot;Media Library
- Possible broken links found in node 111: ITS Help Desk: node&quot; data-entity-uuid=&quot;ff5f6b7c-624a-406f-bc93-c4aaa9a1fdff&quot; href=&quot;/node/226
- Possible broken links found in node 116: costs and common questions about billing: node&quot; data-entity-uuid=&quot;af1df058-a5be-49c9-b188-e8b7e75d4ce9&quot; href=&quot;/node/271,instructions for how to use a print release station: node&quot; data-entity-uuid=&quot;880d64ac-336f-4056-837c-ad0e2f70dd1f&quot; href=&quot;/node/276&quot; media_library=&quot;Media Library,print from a personal laptop or mobile device: node&quot; data-entity-uuid=&quot;8b1fc90f-134f-4578-9434-79032e9d856a&quot; href=&quot;/node/281&quot; media_library=&quot;Media Library,how to restrict downloading and printing in OneDrive: node&quot; data-entity-uuid=&quot;05245ae9-ff3f-4540-98da-a2e3b8399f96&quot; href=&quot;/node/286&quot; media_library=&quot;Media Library
- Possible broken links found in node 121: ITS Help Desk: node&quot; data-entity-uuid=&quot;ff5f6b7c-624a-406f-bc93-c4aaa9a1fdff&quot; href=&quot;/node/226&quot; media_library=&quot;Media Library
- Possible broken links found in node 206: suggested Computer Configurations: node&quot; data-entity-uuid=&quot;567e9330-00cc-4e7f-bc33-06fc2e0ee1c7&quot; href=&quot;/node/201,our purchasing page: node&quot; data-entity-uuid=&quot;678d78c7-5985-45dd-b303-015f84806d6c&quot; href=&quot;/node/216,list of local computer hardware repair providers: node&quot; data-entity-uuid=&quot;409150f8-a942-4510-998c-8f3151cdfa4e&quot; href=&quot;/node/211,find the most popular mobile device instructions: node&quot; data-entity-uuid=&quot;ecb85fb3-045b-44ed-b0a1-0e3f34dcbd04&quot; href=&quot;/node/221
- Possible broken links found in node 321: Contact the ITS Help Desk: node&quot; data-entity-uuid=&quot;ff5f6b7c-624a-406f-bc93-c4aaa9a1fdff&quot; href=&quot;/node/226
- Possible broken links found in node 456: ITS Human Resources: node&quot; data-entity-uuid=&quot;f6f62db8-e47f-4a28-ac0c-b9ebf25d4ef5&quot; href=&quot;/node/466
- Possible broken links found in node 696: ITS website: node&quot; data-entity-uuid=&quot;2121bdcf-4b39-46a0-95f8-f9dd3704e94b&quot; href=&quot;/node/691
- Possible broken links found in node 978: Learn more about this change.: node/125971
- Possible broken links found in node 982: VPN (UI&amp;nbsp;Anywhere): node/247,Virtual Desktop: node/294
- Possible broken links found in node 994: Two-Step Login authentication: node/115421,alternative authentication methods: node/115421
- Possible broken links found in node 1009: VPN support center: node/247
- Possible broken links found in node 1023: More information on getting a Drupal Digital Sign: node/105225&quot; target=&quot;_blank
- Possible broken links found in node 1026: ITS Help Desk: node/100093
- Possible broken links found in node 1028: ITS Help Desk: node/100093
- Possible broken links found in node 1044: Large Scale Storage (LSS): node/103906,LSS: node/103906,HPC: node/100144,Data Classification Guide: node/110901
- Possible broken links found in node 1047: &lt;strong&gt;Web conferencing&lt;/strong&gt;: node/101197,Zoom privacy settings tips page: node/120661,Microsoft Teams: node/117101,on this support article: node/118416
- Possible broken links found in node 1057: Microsoft Azure support center: node/105611
- Possible broken links found in node 1069: see this FAQ.: node/127481
- Possible broken links found in node 1082: &lt;strong&gt;Research Data Storage Service (RDSS)&lt;/strong&gt;: node/103936,&lt;strong&gt;Large Scale Storage (LSS)&lt;/strong&gt;: node/103906,Iowa Health Data Resource (IHDR) data enclave: node/125121,Shared Drive: node/109,OneDrive: node/101613,Interactive Data Analytics Service (IDAS): node/115766,RDCS: node/100180,&lt;b&gt;Approved Data Classification Levels&lt;/b&gt;: node/110901,RDSS: node/103936,LSS: node/103906
- Possible broken links found in node 1092: learn more about getting started: node/106591
- Possible broken links found in node 1100: recent changes to the H drive service: node/125361,VPN (UI&amp;nbsp;Anywhere): node/247,Virtual Desktop: node/294
- Possible broken links found in node 1101: data classification levels: node/110901,VPN (UI Anywhere): node/247,Virtual Desktop: node/294,Research Data Storage Service: node/103936
- Possible broken links found in node 1103: Large Scale Storage Service (LSS): node/103906
- Possible broken links found in node 1122: Data Classification Guide to IT Services: node/110901,this support article for instructions on how to move your data and access the new RRDS: node/128891
- Possible broken links found in node 1124: data classification: node/110901
- Possible broken links found in node 1125: Need a New Charged&amp;nbsp;Print Queue or Make Changes to an Existing One?: node/113661
- Possible broken links found in node 1134: ListServ: node/982
- Possible broken links found in node 1140: Permitted Data Classifications: node/119861#PermittedDataClassifications
- Possible broken links found in node 1145: Two-Step Login set up instructions: node/106591
- Possible broken links found in node 1157: ITS Help Desk: node/100093
- Possible broken links found in node 1158: Interactive Data Analytics Service (IDAS): node/115766
- Possible broken links found in node 1161: this support article: node/128286
- Possible broken links found in node 1169: service level expectations: node/2790
- Possible broken links found in node 1170: HawkID password: node/3811,ITS Help Desk: node/100093,HealthcareID: node/216
- Possible broken links found in node 1171: HawkIDs: node/215,automatically sync: node/217
- Possible broken links found in node 1172: password requirements: node/3811,ITS Help Desk: node/100093
- Possible broken links found in node 1182: hardware repair service providers: node/316,located on the second floor of the University Capitol Centre: node/100093
- Possible broken links found in node 1185: Virtual Desktop Support Center: node/294
- Possible broken links found in node 1188: follow this guide to connect to eduroam: node/210,learn more about connecting to ResNet here: node/4024,Register your device and find instructions on connecting to UI-DeviceNet here: node/105671
- Possible broken links found in node 1189: LinkedIn Learning: node/2015
- Possible broken links found in node 1194: ITC Printing system billing: node/433
- Possible broken links found in node 1211: the VPN: node/247,add one that isn&#039;t there: node/897
- Possible broken links found in node 1213: wake up or power on your on-campus computer remotely: node/898,the VPN: node/247
- Possible broken links found in node 1214: Remote Desktop connections : node/306,register it in PowerUp&amp;nbsp;yourself: node/897
- Possible broken links found in node 1228: instructions on in our support guide: node/2567,contact the ITS Help Desk: node/100093
- Possible broken links found in node 1229: &lt;strong&gt;Blocked Attachments&lt;/strong&gt;: node/125986
- Possible broken links found in node 1238: ITS Rental Program: node/1421
- Possible broken links found in node 1253: Instructions for downloading and installing Microsoft Office: node/103142,additional information on using Microsoft Office and how to install: node/104827
- Possible broken links found in node 1256: host device (an on-campus work computer) is configured for Remote Desktop: node/1595,&lt;span&gt;PowerUp&lt;/span&gt;: node/117511
- Possible broken links found in node 1272: Contact the ITS Help Desk: node/100093
- Possible broken links found in node 1282: HawkID password requirements: node/3811
- Possible broken links found in node 1283: HawkID password requirements: node/3811,After changing your HawkID password, make sure to update your saved credentials: node/2568
- Possible broken links found in node 1284: GlobalProtect VPN client or the Cisco VPN client: node/247
- Possible broken links found in node 1285: connect to the VPN and follow these instructions to sync your passwords: node/2567,eduroam: node/681,your Office 365 clients (e.g., Outlook, iOS, Android) will prompt you for your new password: node/104970,contact the ITS Help Desk: node/100093,remove and re-add the eduroam network on all of your devices: node/102644,Remove any old credentials from your device in Keychain: node/1346,connect to the university VPN and lock the device to force the password to sync: node/2567
- Possible broken links found in node 1299: Qualtrics FAQs: node/2720
- Possible broken links found in node 1301: What Qualtrics training options are available to me?: node/2713
- Possible broken links found in node 1303: Article 2713: node/2713,Qualtrics FAQs: node/2720
- Possible broken links found in node 1313: Qualtrics Support Center: node/2723&quot; target=&quot;_self&quot; title=&quot;Qualtrics Support Center
- Possible broken links found in node 1379: learn more about compromised computers: node/3963,what you can do if you have a copyright violation on a UI network: node/475
- Possible broken links found in node 1380: information on where ITCs are located and what services are available in them: node/103787,how to get started using Web Print : node/102875,eduroam: node/209,UI-DeviceNet: node/105671
- Possible broken links found in node 1383: instructions for connecting to ResNet: node/4024,Find more information on using UI DeviceNet.&amp;nbsp;: node/109456,Read more about our policies regarding unauthorized access points.: node/2775
- Possible broken links found in node 1384: wireless router policy: node/2775,wireless/network printer policy: node/3976
- Possible broken links found in node 1396: Find&amp;nbsp;brand-specific instructions here: node/109841
- Possible broken links found in node 1405: Managed Application and Platform Level Services: node/119846
- Possible broken links found in node 1448: Windows: node/1418
- Possible broken links found in node 1460: General Considerations for Using Cloud Services: node/104444,Cloud File Storage FAQ: node/101025,Compare Supported Storage and Sharing Options: node/103957,Campus Software Program Office: node/101388
- Possible broken links found in node 1475: complete login using Duo: node/106731
- Possible broken links found in node 1489: add terms to the Person Type taxonomy: node/102635,add/configure the panes: node/102479
- Possible broken links found in node 1490: Cropping Images: node/102768,configuring content to show on the homepage: node/103871#promote-to-front
- Possible broken links found in node 1492: support article about removing demo content: node/102640
- Possible broken links found in node 1504: check what type of Operating System you have: node/102333
- Possible broken links found in node 1506: previously generated a list of backup codes: node/102357,enroll another device (perhaps your office&amp;nbsp;phone, etc.): node/102357
- Possible broken links found in node 1512: Reusable custom content panes: node/102478
- Possible broken links found in node 1514: Creating and editing single-use custom content panes: node/102477,Changing the layout of a page: node/102480
- Possible broken links found in node 1528:  convert your PST files to your Office 365 account: node/103948
- Possible broken links found in node 1533: &lt;em&gt;Changing the order of menu links&lt;/em&gt;: node/102631,&lt;em&gt;Changing the order of menu links&lt;/em&gt;: node/102631
- Possible broken links found in node 1534: Files On-Demand set in your client: node/120336
- Possible broken links found in node 1536: &lt;em&gt;Changing the order of taxonomy terms&lt;/em&gt;: node/102638,&lt;em&gt;Changing the order of taxonomy terms&lt;/em&gt;: node/102638
- Possible broken links found in node 1540: Log in to the website: node/102832
- Possible broken links found in node 1542: here: node/104704
- Possible broken links found in node 1556: Access permissions on SiteNow: node/103154,Access permissions on SiteNow: node/103154
- Possible broken links found in node 1557: OneDrive for Business: node/101613
- Possible broken links found in node 1560: Changing the permissions of a user account: node/103157
- Possible broken links found in node 1561: Access permissions on SiteNow: node/103154
- Possible broken links found in node 1571: Sync SharePoint and Shared Libraries in OneDrive: node/110101
- Possible broken links found in node 1576: Repair your Office ProPlus&amp;nbsp;installation: node/103429&quot; target=&quot;_blank
- Possible broken links found in node 1585: &quot;Files On-Demand&quot; : node/120336,&quot;Known Folder Moves&quot;: node/120336,Create a new Shared Library: node/120391,Download the Teams client here: node/117291
- Possible broken links found in node 1607: Uploading to MyWeb through Dreamweaver CS5: node/100566
- Possible broken links found in node 1617: UI AnyWhere VPN: node/247
- Possible broken links found in node 1618: UI AnyWhere VPN: node/247
- Possible broken links found in node 1629: How to Report a Phishing Scam or a Spam Email: node/558
- Possible broken links found in node 1631: Find and edit content in SiteNow: node/102038
- Possible broken links found in node 1633: Adding Social Media Content: node/110816
- Possible broken links found in node 1641: change the path alias (URL) of a page on a SiteNow website: node/104241
- Possible broken links found in node 1642: support article about enabling and disabling apps: node/102041,Changing the general look and feel: node/102765
- Possible broken links found in node 1643: contact the ITS Help Desk: node/100093
- Possible broken links found in node 1671: Skype for Business Meeting: node/2783
- Possible broken links found in node 1677: Webform: node/102037,Background Image (Stellar theme only): node/104335,Creating a menu link to a page: node/102630
- Possible broken links found in node 1688: Hardware and Operating System Recommendations: node/105221&quot; target=&quot;_blank
- Possible broken links found in node 1690: support article on content guidelines: node/110396
- Possible broken links found in node 1698: ITS Service Catalog page: node/104694
- Possible broken links found in node 1708: Using SFTP with MyWeb: node/103827
- Possible broken links found in node 1717: how to manage your Two-Step profile and devices: node/102357
- Possible broken links found in node 1722: &lt;em&gt;Advanced webform configuration&lt;/em&gt;: node/107376
- Possible broken links found in node 1726: how to find your MAC address: node/105676,XBOX 360 S Console Model 1439: node/113211,ITS Help Desk: node/100093
- Possible broken links found in node 1759: using the media browser library: node/103207#media-library
- Possible broken links found in node 1771: How to connect your mobile device to UI Wireless eduroam: node/283,How to set up email and calendar on your mobile device: node/101199,Installing Skype for Business on a mobile device: node/3766,Set up : node/106591,Two-Step: node/106591, login: node/106591,Download the HawkTools&amp;nbsp;app: node/105218
- Possible broken links found in node 1773: directions to place a content pane on a page: node/102479
- Possible broken links found in node 1784: &lt;span&gt;&lt;span&gt;&lt;span&gt;NIST 800-171&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;: node/110266,ITS-Managed Hosting Services for Export-Controlled Data: node/110261
- Possible broken links found in node 1785: ITS-Managed services: node/110261,&lt;span&gt;&lt;span&gt;&lt;span&gt;Safeguarding Export-Controlled Technical Data for System Administrators&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;: node/110256,&lt;span&gt;&lt;span&gt;&lt;span&gt;Safeguarding Export-Controlled Technical Data for System Administrators&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;span&gt;&lt;span&gt;&lt;span&gt;.&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;: node/110256
- Possible broken links found in node 1786: ITS-Managed services: node/110261,NIST 800-171 requirements: node/110266,&lt;span&gt;&lt;span&gt;&lt;span&gt;Safeguarding Export-Controlled Technical Data for Researchers&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;: node/110251,ITS-managed datacenters are hosting systems: node/110261
- Possible broken links found in node 1787: non-US Persons: node/110761,US Person: node/110761,How to Begin Working with Export-Controlled Technical Data: node/110246
- Possible broken links found in node 1793: GitLab Academic: node/115436,Large Scale Storage (LSS): node/103906,Microsoft SQL Server: node/100128,On-Premise Datacenter Hosting: node/110261,Office 365 GCC High: node/122191,Research Data Storage Service (RDSS): node/103936,Research Remote Desktop Service: node/110071,Secure Device Service: node/116601,Virtual Server: node/100415,NIST 800-171: node/110266
- Possible broken links found in node 1794: connect to eduroam for the first time: node/210,remove and reconfigure the eduroam wireless network: node/102644,detailed instructions on using the eduroam CAT: node/104876,Check the ITS Alerts website: node/100311,please contact the ITS Help Desk: node/100093
- Possible broken links found in node 1805: ITS Help Desk: node/100093
- Possible broken links found in node 1808: Critical - Export-Controlled: node/110246,Apple iCloud: node/101025,AWS Cloud Enterprise: node/105606,Box: node/101025,Dispatch: node/105791,Dropbox: node/101025,Globus: node/100180,Google Drive &amp;amp; Gmail: node/101025,Home Drives (Files@Iowa): node/103888,HPC Systems: node/100144,Large Scale Storage (LSS): node/103906,ICON: node/2053,Interactive Data Analytics Service: node/115766,Iowa Health Data Resource (IHDR) Data Enclave: node/125121,Microsoft Azure Cloud Services Enterprise: node/105611,Microsoft Copilot - UI Enterprise License: node/127866,Microsoft OneDrive for Business: node/101613,Microsoft SharePoint Online (O365): node/102716,Microsoft Teams: node/117101,Personal Cell Phones: node/280,Personal Devices (e.g. laptops, USBs, personal cloud services, etc.): node/233,Qualtrics: node/1771,R: Drive: node/100924,REDCap: node/100181,Research Data Storage Service (RDSS): node/103936,Research Remote Desktop Service: node/110071,Secure Device Service: node/116601,Shared Drive (Files@Iowa): node/109,Skype for Business: node/6,UICapture: node/2474,Zoom: node/101197
- Possible broken links found in node 1811: these instructions: node/558,tips to recognize phishing scams: node/3716
- Possible broken links found in node 1831:  wired ResNet connection: node/4024
- Possible broken links found in node 1833: main RRDS&amp;nbsp;support page: node/113296,Duo Two-Step Authentication: node/102315,VPN access for connections off-campus: node/1876
- Possible broken links found in node 1834: main RRDS&amp;nbsp;support page: node/113296
- Possible broken links found in node 1842: grant them access to the RDSS space: node/114376
- Possible broken links found in node 1863: ITS Help Desk: node/100093,ITS Help Desk: node/100093
- Possible broken links found in node 1879: contact the ITS Help Desk: node/100093,How to Grant or Revoke Access to Your RDSS Space: node/114376
- Possible broken links found in node 1884: System Monitoring and Alerting: node/115176
- Possible broken links found in node 1903: Virtual Desktop: node/294,departmental IT support staff: node/2697
- Possible broken links found in node 1909: GitLab Periodic Update Schedule: node/114586,GitLab Backup Schedule: node/114736,GitLab Security Update Schedule: node/114576
- Possible broken links found in node 1924: video conferencing options and when to use Skype for Business, Microsoft Teams, and Tools: node/118416,resources for internet options : node/118201,Drive-up wifi: node/118316,these online meeting etiquette tips: node/118196,OneDrive for Business: node/101613,home drive: node/103888,shared drive: node/109,types of data that can be used with different IT services and tools: node/110901,Virtual Private Network (VPN): node/247,how to configure a Windows computer for remote access: node/1595,how to use screen sharing to connect to your Mac: node/118091,contact us: node/100093,Drive-up Wifi Locations page: node/118316,list of internet options that might be available to you: node/118201,information about Two-Step Login and switching to the app: node/102315,instructions on how to use Outlook Web Access (OWA) for Office 365: node/104670,learn how to install Outlook: node/103142,get Outlook on your phone: node/101199,Remote Desktop: node/306,learn how to install Skype for Business: node/103142,Skype quick start guide for Windows machines: node/108271,Microsoft Teams: node/117101,When to use Skype for Business, Microsoft Teams, and Zoom: node/118416,meeting etiquette tips: node/118196,downloading and configuring Cisco AnyConnect: node/1876,how to log in to the VPN with Two-Step Login: node/115421,how to log in, create and share files, and more with the OneDrive: node/102633,Connect to your home drive from off-campus: node/104047,Connect to your shared drive from off-campus: node/104043,install Microsoft Office using these instructions: node/103142,how to configure a Windows computer for remote access: node/1595,how to use screen sharing to connect to your Mac: node/118091,Connecting to email and calendar on your device: node/101199,Download Skype for Business on your mobile device: node/3766,Updating your Windows operating system: node/1418,Updating your Mac operating system: node/1266,phishing tips and best practices: node/3716,antivirus protection for home use&amp;nbsp;: node/100582,Software resources for individuals impacted by COVID-19 campus closures: node/118296,move mail from your .pst files (personal folders) to your Office 365 account: node/103948,your IT representative: node/2697
- Possible broken links found in node 1925: Configuring Your Email App for Microsoft 365: node/104970,Connect to Microsoft 365 Email and Calendar on Your Mobile Device: node/101199
- Possible broken links found in node 1930: Microsoft Teams: node/117101
- Possible broken links found in node 1931: Review the Drive-up Wifi Locations page: node/118316,Turn your phone into a mobile hotspot: node/118306,Find more resources for working at home: node/118001
- Possible broken links found in node 1938: eduroam service: node/209,connect to the eduroam network: node/210,connect to the eduroam network: node/210
- Possible broken links found in node 1942: Skype for Business: node/6
- Possible broken links found in node 1945: UI OneDrive: node/101613,RDSS: node/103936,LSS: node/103906,H: drive: node/103888
- Possible broken links found in node 1951: delegates: node/119191
- Possible broken links found in node 1959: grant and revoke access to the LSS share: node/118771&quot; target=&quot;_blank,added as a &quot;member&quot;: node/118771&quot; target=&quot;_blank
- Possible broken links found in node 1963: https://its.uiowa.edu/node/122411: node/122411,Zoom Pronouns: node/122611,Zoom Minimum Client Version Requirement: node/122411,learn more about this update and the changes it applies at the ITS support site: node/119346,More information on the passcode requirement is available on the ITS support site: node/119201
- Possible broken links found in node 1980: GitLab Academic: node/115436
- Possible broken links found in node 1982: download the correct Zoom app for your device: node/119291
- Possible broken links found in node 1984: Zoom Add-In for Outlook Desktop: node/122356
- Possible broken links found in node 1987: Zoom - Waiting Rooms: node/119736,Zoom Info Center: node/101197
- Possible broken links found in node 1993: non-U.S. persons: node/110761,services: node/110491
- Possible broken links found in node 1997: UI VPN: node/247,Recommended antivirus software&amp;nbsp;: node/100582,General computer security recommendations: node/265,Working from home guidance: node/118381,this page: node/104109,ITS Data Classification Guide: node/110901,click here: node/100924,UI OneDrive: node/101613,&lt;span&gt;&lt;span&gt;Zoom&lt;/span&gt;&lt;/span&gt;: node/101197&quot; style=&quot;text-decoration:underline,Comparison of Video Conferencing Options: node/118416,Technology Review: node/101551,Data Classification Guide to IT Services: node/110901,please click here: node/232,UI Password Policy: node/2028
- Possible broken links found in node 1998: data&amp;nbsp;classification: node/110901
- Possible broken links found in node 2000: this&amp;nbsp;webpage: node/110901
- Possible broken links found in node 2001: OneDrive for Business (Office 365): node/101613,Groups (Office 365): node/120391,SharePoint Online (Office 365): node/102716,Teams (Office 365): node/117101
- Possible broken links found in node 2010: &quot;Files On-Demand&quot;: node/120336,&quot;Known Folder Moves&quot; : node/120336,Create a new Shared Library: node/120391,Teams client here: node/117291
- Possible broken links found in node 2011: Skype for Business Location Information FAQ support article: node/120291&quot; style=&quot;color:#0563c1; text-decoration:underline
- Possible broken links found in node 2019: ITS-EI-SAS: node/119841,ITS-EI-SAS: node/119841,Backup and Recovery of Virtual Server: node/116066,FAQ page: node/123716
- Possible broken links found in node 2021: PST files to Office 365: node/103948,OneDrive Automatic sign-on and backup: node/120791,Quick Start Guide: node/102633,Training: node/120576,Best Practices: node/117881
- Possible broken links found in node 2024: Faculty and Staff lose access to OneDrive on your last day of employment. : node/118086,Retirees lose access to OneDrive on your last day of employment.: node/1539,Students have access for 2 years following graduation or leaving the University.: node/117911
- Possible broken links found in node 2037: this support article on how to set the homepage: node/127596
- Possible broken links found in node 2058: here: node/122251
- Possible broken links found in node 2071: Connect to the Cisco AnyConnect Secure Mobility Client: node/1876
- Possible broken links found in node 2072: Teams: node/117101,OneDrive: node/101613
- Possible broken links found in node 2073: moving these files to Office 365: node/103948
- Possible broken links found in node 2088: following these directions: node/120391
- Possible broken links found in node 2116: copy&amp;nbsp;your data to OneDrive for Business: node/119721,move your mail to Office365: node/103948,Sign-up for OneDrive training: node/104794
- Possible broken links found in node 2117: Two-Step Login with Duo Security: node/102315
- Possible broken links found in node 2149: See this support article: node/1876
- Possible broken links found in node 2157: alerts page: node/100311, contact the Help Desk: node/100093,how to set up rules for email messages: node/1056,how to add a service alert or planned maintenance announcement: node/107561
- Possible broken links found in node 2159: managed services information: node/119846,cloud services information page: node/124001
- Possible broken links found in node 2179: Connect using a Windows PC: node/113321,Connect using a Mac: node/113341
```
</details>
