### ISSUE TITLE
Add parent org to page title meta tags if set

### ISSUE THREAD

**Issue by ethan-fry** [uiowa/uiowa#7522]
May 4th  we will be changing the College of Medicine branding over to the block Iowa brand these changes can't be made prior to the 4th.  All current branding changes to the current ccom brand remain other than changing from the healthcare logo to block Iowa and the link of the block Iowa going to uiowa.edu instead of uihealthcare.org
```[tasklist]
### Proposed Solution
- [ ] Possibly create new token for parent org https://github.com/uiowa/uiowa/issues/7522#issuecomment-2061950265
- [ ] Add parent org to page title meta tags if set
- [ ] Should be able to deploy this in advance of May 4th timeline because it won't affect the CCOM brand just the Iowa brand
```

**Comment by ethan-fry** [comment]
@briand44

**Comment by briand44** [comment]
Just noting that May 4th is a Saturday. Changes to CCOM sites on SiteNow v3 can happen anytime May 6th-8th.

**Comment by briand44** [comment]
@ethan-fry @maxwell-freund What about the favicon? Is that updating to the block I as well? Currently looks like it is the dome.

**Comment by ethan-fry** [comment]
@briand44 per our conversation today the favicon will use the block I as well. Just wanted to add this for visibility

CC: @maxwell-freund

**Comment by briand44** [comment]
Just mentioning that it would be preferred to continue having Carver College of Medicine in the title meta tag.

`<title>Summer Health Professions Education Program at the University of Iowa | Carver College of Medicine</title>`

My understanding is that this currently is part of the theme setting so if the idea was to just switch the brand theme setting from CCOM to Iowa, we would want to understand if there is a way to retain that.

They do have the parent org set to `Carver College of Medicine` for all these sites.

**Comment by briand44** [comment]
Grooming conversation... Only issue with switching from CCOM brand to Iowa brand currently is the title meta tag. Could add parent org to title metatag in addition to The University of Iowa for the service. May need to create a separate token for the parent organization. Any concerns with character length with including parent org. Shouldn't negatively affect SEO but Google could truncate. Decided to move forward with a service level change to include parent org in the page title metatags and not worry about the length right now or the schema.org output. We can come back to schema.org. Max confirmed they can manually make the switch from CCOM brand to Iowa Brand in the theme settings. Should be able to deploy this in advance because it won't affect the CCOM brand just the Iowa brand.

**Comment by joewhitsitt** [comment]
Not opposed to a separate token to represent this data, but the logic of handling leading and following spaces and or characters might still need massaging elsewhere to strip/trim.

**Comment by GaryRidgway** [comment]
I've been a bit confused, so I'm going to write some things down just so i can straighten out my thoughts.

Had some conversations [here](https://iowaweb.slack.com/archives/C0164FNN1PV/p1713558577783179) and [here](https://iowaweb.slack.com/archives/C0164FNN1PV/p1713800853622909) about this issue.

Currently the Org name token is defined by looking at whether CCOM is selected as the 'Branding option' or not, so my intent is to create a new `parent_org` token in uiowa core that doesn't care about CCOM being selected as the 'Branding option'.

~~I am however seeing that `MODULE_hook_tokens()` is [setting the values for tokens](https://github.com/uiowa/uiowa/blob/d24f6c51bac8b42163397a9b25278bd3307cd84c/docroot/modules/custom/uiowa_core/uiowa_core.module#L1069-L1095) in a lot of places, but I also had a conversation with @pyrello in which he thought I didn't need to look up or set any values in code, and that the code should only be used to define the token, [like so](https://github.com/uiowa/uiowa/blob/d24f6c51bac8b42163397a9b25278bd3307cd84c/docroot/modules/custom/uiowa_core/uiowa_core.module#L1049-L1064).~~
**EDIT: The above was clarified to me, and the token SHOULD be set in code, but the METATAG should be set in config.**

I plan to define the `parent_org` token like above, but then I will look for examples of config that is setting that value instead of code.

Additionally, Formatting is an issue that is important here, as some sites do not have a set `parent_org` value, so I will need to figure out how to do that as well (Omitting extra dashes, spaces, whatnot).

**Comment by GaryRidgway** [comment]
I will need to try to get the config for whether a parent org is set, and what the parent org is at a base level. to do this, I will try to use something like `$config = $config_factory->getEditable('uiowa_core.settings');` to get it, and go from there. First, I must find what value to use in the `getEditable()` function.

**Comment by GaryRidgway** [comment]
I found that it was `$config_factory->getEditable('system.site');` from [this article.](https://www.drupal.org/docs/drupal-apis/configuration-api/configuration-override-system)

**Comment by joewhitsitt** [comment]
Thanks for capturing your thoughts on the issue. With that bit you crossed out clarified it sounds like a good path forward. For the spaces and such, we could probably get by and incorporating that into the value token value until a separate use-case comes up or we could create a plain `[uiowa_core:parent_org]` and "formatted" or "metatag" version `[uiowa_core:parent_org:formatted]`.

`title: '[current-page:title] | [site:name] - [uiowa_core:parent_org:formatted][uiowa_core:org_name]'`

`$replacements[$original] = $site_config->get('parent.name') . ' | ' ?? '';`

**Comment by pyrello** [comment]
My suggestion was that we should add a token, something like `[uiowa_core:combined_org]`, that would resolve to `Parent Org - University of Iowa` or just `University of Iowa` if the parent org wasn't set. It could potentially use the existing tokens.

**Comment by GaryRidgway** [comment]
I am having trouble changing the tag and having it do anything. If I set it in a block 
<details><summary>like so, </summary>

```php
/**
 * Implements hook_tokens().
 */
function uiowa_core_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];
  if ($type === 'uiowa_core') {
    $config_factory = \Drupal::configFactory();
    $config = $config_factory->getEditable('uiowa_core.settings');
    $theme_config = $config_factory->getEditable('uids_base.settings');
    $ccom_site = ($theme_config->get('header.branding_options') == 'ccom');

    foreach ($tokens as $name => $original) {
      // Find the desired token by name.
      switch ($name) {
        case 'org_name':
          $org_name = $ccom_site ? 'Carver College of Medicine' : 'The University of Iowa';
          $replacements[$original] = $config->get('uiowa_core.org_name') ?? $org_name;
          break;

        case 'favicon_assets_path':
          $favicon_path = $ccom_site ? '/profiles/custom/sitenow/assets/uihc_favicons/' : '/profiles/custom/sitenow/assets/';
          $replacements[$original] = $config->get('uiowa_core.favicon_assets_path') ?? $favicon_path;

          break;

        case 'parent_org':
          $config_factory->getEditable('system.site');
          $replacements[$original] = 'doggy';
          break;
      }
    }
  }
  return $replacements;
}

```

</details> 



I would expect it to reflect on a page if the title was set to `doggy` if I have set the content title metatag option to `[uiowa_core:parent_org]`. I am however, not experiencing this.

**Comment by GaryRidgway** [comment]
I created a new node and changed its `title` attribute in the `SEO settings` options to be some random text. Then, after I saved it back to being `[uiowa_core:parent_org]`, it worked. perhaps old pages need to be saved?

**Comment by joewhitsitt** [comment]
Not sure again what might be up with your local. Token values and metatags are part of the cached render though.

What about @pyrello's comment about combining and replacing https://github.com/uiowa/uiowa/issues/7522#issuecomment-2073024964

And then all of our config would just be updated to this new token name. Max mentioned that all of their sites already have the parent org filled out so the loss of the CCOM stuff here wouldn't affect things.

```diff
jwhitsit@ITS-02342 uiowa % git diff docroot/modules/custom/uiowa_core/uiowa_core.module
diff --git a/docroot/modules/custom/uiowa_core/uiowa_core.module b/docroot/modules/custom/uiowa_core/uiowa_core.module
index 690b03230..02b7018db 100644
--- a/docroot/modules/custom/uiowa_core/uiowa_core.module
+++ b/docroot/modules/custom/uiowa_core/uiowa_core.module
@@ -1052,9 +1052,9 @@ function uiowa_core_token_info(): array {
     'name' => t('UIowa Core'),
     'description' => t('Tokens for UIowa Core.'),
   ];
-  $info['tokens']['uiowa_core']['org_name'] = [
-    'name' => 'Organization Name',
-    'description' => 'A token to override the default University of Iowa organization name.',
+  $info['tokens']['uiowa_core']['combined_org'] = [
+    'name' => 'Combined Organization Name',
+    'description' => 'A combined parent organization and organization token.',
   ];
   $info['tokens']['uiowa_core']['favicon_assets_path'] = [
     'name' => 'Favicon assets path',
@@ -1072,19 +1072,26 @@ function uiowa_core_tokens($type, $tokens, array $data, array $options, Bubbleab
 
     $config_factory = \Drupal::configFactory();
     $config = $config_factory->getEditable('uiowa_core.settings');
-    $theme_config = $config_factory->getEditable('uids_base.settings');
-    $ccom_site = ($theme_config->get('header.branding_options') == 'ccom');
+    $site_config = $config_factory->getEditable('system.site');
 
     foreach ($tokens as $name => $original) {
       // Find the desired token by name.
       switch ($name) {
-        case 'org_name':
-          $org_name = $ccom_site ? 'Carver College of Medicine' : 'The University of Iowa';
-          $replacements[$original] = $config->get('uiowa_core.org_name') ?? $org_name;
+        case 'combined_org':
+          $parent_org = $site_config->get('parent.name');
+          $org_name = $config->get('uiowa_core.org_name') ?? 'The University of Iowa';
+          if (!empty($parent_org)) {
+            $combined_org = $parent_org . ' | ' . $org_name;
+          }
+          else {
+            $combined_org = $org_name;
+          }
+
+          $replacements[$original] = $combined_org;
           break;
 
         case 'favicon_assets_path':
-          $favicon_path = $ccom_site ? '/profiles/custom/sitenow/assets/uihc_favicons/' : '/profiles/custom/sitenow/assets/';
+          $favicon_path = '/profiles/custom/sitenow/assets/';
           $replacements[$original] = $config->get('uiowa_core.favicon_assets_path') ?? $favicon_path;
 
           break;
```

**Comment by GaryRidgway** [comment]
you posted this literally as I pushed the code LOL. I think one thing we should keep in mind is that if we change the favicon stuff, I think that will go out on release, not when they change the appearance setting. as it currently is, I think we will have to have a second pass to remove the CCOM stuff either way?

**Comment by joewhitsitt** [comment]
Ah good point about the favicons. i got delete happy.
