### ISSUE TITLE
Acquia - deployment test

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7547]
> Hi team,
> 
> We are hoping you can help us run a test for us to help troubleshoot the on-going cloud hooks conversation. Details below:
>  
> Please choose an application with a large multisite and cloud hooks that has previously timed out on code deploys.
> 
> Please deploy code on an ACN environment, and a Cloud Classic environment. Tell us which environments you did this on, and the day/time of deployment. If you are able to supply task ID of the deployments, even better, but if not, day/time/environment will suffice. We will then dig into this and see if we can uncover any additional information.

Ticket - https://acquia.my.site.com/s/case/500Pb00000AdNySIAV/cloud-hooks-troubleshooting

# Proposed Solution
```[tasklist]
### Tasks
- [x] Wait till https://github.com/uiowa/uiowa/pull/7545 is ready for merge/deployment, assumes database updates and configuration imports make it a bigger than normal deployment
- [x] Once we know when this is going out, communicate the tag contents, schedule with the open Acquia ticket
- [x] Include information about last known deployment that required re-triggering to finish: https://github.com/uiowa/uiowa/issues/7547#issuecomment-2042981661
- [x] Note that we do not keep the same amount of sites in DEV/STAGE as we do in PROD so a straight comparison of STAGE ACN, PROD Cloud Classic is not realistic
- [x] Once deployment happens, pass along task ids from uiowa->uiowa07 mentioning that uiowa07 is ACN and the others are cloud classic
```

**Comment by briand44** [comment]
Comment from Joe:

Perhaps this info would be beneficial to Acquia in tracking down a task:

https://iowaweb.slack.com/archives/C0164FNN1PV/p1712154297125239?thread_ts=1659720855.472699&cid=C0164FNN1PV

_August 5, 2022 - Tag 3.16.20 (https://github.com/uiowa/uiowa/releases/tag/3.16.20) - uiowa02.prod -  Re-triggered about 1 PM CT_

**Comment by briand44** [comment]
Grooming conversation... May want to share with Acquia the scheduled deployment for the 10.2 update. We can also provide the info ^^ related to a previous deployment that failed. We probably want to let Acquia know that dev/stage environments don't have the number of sites prod environments have so that isn't very comparable. uiowa07 prod is on cloud next other prod apps are on cloud classic. Sized as small, if Acquia comes back and requests more info we can always adjust or carve a new slice.

**Comment by briand44** [comment]
Blocked until https://github.com/uiowa/uiowa/issues/7486 is scheduled for deployment

**Comment by joewhitsitt** [comment]
Looks like we are nearing approval on the [d10_2](#7486 ) pr. If we can get our ducks in a row, we could roll this out Tuesday or Wednesday in the early hours.

**Comment by joewhitsitt** [comment]
The team is okay with a Wednesday early AM deployment.

**Comment by joewhitsitt** [comment]
Updated the ticket with the information known at this time. Will follow-up Wednesday with task ids.

**Comment by joewhitsitt** [comment]
Responded this morning with some of the task ids. They had previously responded about the possibility of parallelization on ACN and I said we would take a look at that.
