### ISSUE TITLE
Run ITS migrations in dev

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7552]
# Story

As an ITS website owner, I would like to see our services and support article content in our dev environment so we can review.

# Additional Info

We sliced the migration work to include local migrations and testing/review. This is the follow up to get it out to dev.

We'll want to sync from prod prior to running. 

We may need to remove existing support articles and services prior to running the migration so we don't have duplicates.

# Proposed solution

```[tasklist]
### Tasks
- [x] Sync a fresh db and files down from PROD
- [x] Reference the PL card for details about re-establishing the email overrides for alert email testing
- [x] Delete existing services and support article content
- [x] Run the support articles migration in batches of 100 `--limit=100`
- [x] Report broken links information to customers. Mention service overview, quick links aren't included in the report due to technical reasons
```

**Comment by briand44** [comment]
Grooming conversation... We did identify some test nodes that should be removed prior to communicating this is available in dev. Joe has been batching support article migrations to 100. May want to reference test instructions on that PR.

**Comment by briand44** [comment]
Blocked label until the migrations are reviewed and approved.

**Comment by bspeare** [comment]
This is done, I have added the broken link notices below in a details. 

**Update:** also emailed Adrienne. 

<details>

```
        [notice] Possible broken links found in node 56: .: node&quot; data-entity-uuid=&quot;d8039b7a-4381-4a1c-aa4f-b7e866d75229&quot; href=&quot;/node/46
        [notice] Possible broken links found in node 76: email alias: node&quot; data-entity-uuid=&quot;b742c90f-4ff7-44fa-aaae-007f08370d85&quot; href=&quot;/node/136,how to log in and access your email through a web browser: node&quot; data-entity-uuid=&quot;2383762a-dcc2-4773-811c-280bc0f74a87&quot; href=&quot;/node/131,how to set up Outlook on your Windows or Mac machines: node&quot; data-entity-uuid=&quot;b3519003-159f-493f-9245-75b7b277b21c&quot; href=&quot;/node/141,download and install Office: node&quot; data-entity-uuid=&quot;d00dcea1-7a65-41b9-957b-25d663454679&quot; href=&quot;/node/146,instructions for downloading and installing Outlook on your mobile phone: node&quot; data-entity-uuid=&quot;7029c3e8-3f02-4649-8456-bf2a76703ea6&quot; href=&quot;/node/151,how to recognize and avoid phishing scams: node&quot; data-entity-uuid=&quot;66aba033-d1ef-4475-b867-584eecb52e9f&quot; href=&quot;/node/156,how to report any suspected phishing you might receive to ITS: node&quot; data-entity-uuid=&quot;e8f12731-796c-440b-bc22-cec376fb8e64&quot; href=&quot;/node/161,make a change to your name or email address: node&quot; data-entity-uuid=&quot;019f935b-cbbf-4efd-9a8f-9c452b6b0c85&quot; href=&quot;/node/166,Calendar Combiner: Add your course meeting times and locations to your calendar: node&quot; data-entity-uuid=&quot;53af49a0-283b-474d-b102-e11c40f92f8d&quot; href=&quot;/node/171&quot; media_library=&quot;Media Library,Adding University Calendars (Board of Regents Calendars, Holiday files, etc) to your Outlook calendar: node&quot; data-entity-uuid=&quot;386b4492-9bae-449b-bee2-c3157a4944aa&quot; href=&quot;/node/176&quot; media_library=&quot;Media Library,Add BMindful Holy Days to your calendar: node&quot; data-entity-uuid=&quot;38d9c8a1-38c6-4895-be7a-d2faf68a446e&quot; href=&quot;/node/181&quot; media_library=&quot;Media Library,r: node&quot; data-entity-uuid=&quot;b651f129-6627-4633-9e65-5ffa3cb7f031&quot; href=&quot;/node/186&quot; media_library=&quot;Media Library
        [notice] Possible broken links found in node 81: installing an antivirus program: node&quot; data-entity-uuid=&quot;23df283b-fba6-4978-b366-a490217174b5&quot; href=&quot;/node/196,Suggested Computer Configurations for Students: node&quot; data-entity-uuid=&quot;567e9330-00cc-4e7f-bc33-06fc2e0ee1c7&quot; href=&quot;/node/201,Request help with Technology: node&quot; data-entity-uuid=&quot;ff5f6b7c-624a-406f-bc93-c4aaa9a1fdff&quot; href=&quot;/node/226,Buying a computer and local repair options: node&quot; data-entity-uuid=&quot;b79cd47b-50d4-4e2b-82c8-941aaf54d27b&quot; href=&quot;/node/206
        [notice] Possible broken links found in node 86: outdoor and drive-up wireless support page: node&quot; data-entity-uuid=&quot;76933d0a-5a25-4ba9-b16e-af5f2de57a2e&quot; href=&quot;/node/231,eduroam Configuration Assistant Tool (CAT): node&quot; data-entity-uuid=&quot;253815a8-0abb-44eb-8dfa-d1aa188fafb2&quot; href=&quot;/node/236,ResNet: node&quot; data-entity-uuid=&quot;aa79d243-0983-4325-9c04-19ac0f0250df&quot; href=&quot;/node/241,Forget the network: node&quot; data-entity-uuid=&quot;c65bd31a-1779-4fbd-858a-4f20e203bd70&quot; href=&quot;/node/251,trust the certificate: node&quot; data-entity-uuid=&quot;f1468102-0c58-4374-8ec0-c78dcb550a79&quot; href=&quot;/node/256&quot; media_library=&quot;Media Library
        [notice] Possible broken links found in node 91: Follow these meeting etiquette tips: node&quot; data-entity-uuid=&quot;1ce883f7-98da-4676-8b66-0f26fedd27e1&quot; href=&quot;/node/261&quot; media_library=&quot;Media Library
        [notice] Possible broken links found in node 96: Contact the ITS Help Desk: node&quot; data-entity-uuid=&quot;ff5f6b7c-624a-406f-bc93-c4aaa9a1fdff&quot; href=&quot;/node/226&quot; media_library=&quot;Media Library
        [notice] Possible broken links found in node 106: Qualtrics (survey) training&amp;nbsp;: node&quot; data-entity-uuid=&quot;b08dec98-079c-4044-a3ac-0e3d0523a8fb&quot; href=&quot;/node/266&quot; media_library=&quot;Media Library
        [notice] Possible broken links found in node 111: ITS Help Desk: node&quot; data-entity-uuid=&quot;ff5f6b7c-624a-406f-bc93-c4aaa9a1fdff&quot; href=&quot;/node/226
        [notice] Possible broken links found in node 116: costs and common questions about billing: node&quot; data-entity-uuid=&quot;af1df058-a5be-49c9-b188-e8b7e75d4ce9&quot; href=&quot;/node/271,instructions for how to use a print release station: node&quot; data-entity-uuid=&quot;880d64ac-336f-4056-837c-ad0e2f70dd1f&quot; href=&quot;/node/276&quot; media_library=&quot;Media Library,print from a personal laptop or mobile device: node&quot; data-entity-uuid=&quot;8b1fc90f-134f-4578-9434-79032e9d856a&quot; href=&quot;/node/281&quot; media_library=&quot;Media Library,how to restrict downloading and printing in OneDrive: node&quot; data-entity-uuid=&quot;05245ae9-ff3f-4540-98da-a2e3b8399f96&quot; href=&quot;/node/286&quot; media_library=&quot;Media Library
        [notice] Possible broken links found in node 121: ITS Help Desk: node&quot; data-entity-uuid=&quot;ff5f6b7c-624a-406f-bc93-c4aaa9a1fdff&quot; href=&quot;/node/226&quot; media_library=&quot;Media Library
        [notice] Possible broken links found in node 206: suggested Computer Configurations: node&quot; data-entity-uuid=&quot;567e9330-00cc-4e7f-bc33-06fc2e0ee1c7&quot; href=&quot;/node/201,our purchasing page: node&quot; data-entity-uuid=&quot;678d78c7-5985-45dd-b303-015f84806d6c&quot; href=&quot;/node/216,list of local computer hardware repair providers: node&quot; data-entity-uuid=&quot;409150f8-a942-4510-998c-8f3151cdfa4e&quot; href=&quot;/node/211,find the most popular mobile device instructions: node&quot; data-entity-uuid=&quot;ecb85fb3-045b-44ed-b0a1-0e3f34dcbd04&quot; href=&quot;/node/221
        [notice] Possible broken links found in node 321: Contact the ITS Help Desk: node&quot; data-entity-uuid=&quot;ff5f6b7c-624a-406f-bc93-c4aaa9a1fdff&quot; href=&quot;/node/226
        [notice] Possible broken links found in node 456: ITS Human Resources: node&quot; data-entity-uuid=&quot;f6f62db8-e47f-4a28-ac0c-b9ebf25d4ef5&quot; href=&quot;/node/466
        [notice] Possible broken links found in node 696: ITS website: node&quot; data-entity-uuid=&quot;2121bdcf-4b39-46a0-95f8-f9dd3704e94b&quot; href=&quot;/node/691
        [notice] Possible broken links found in node 996: Learn more about this change.: node/125971
        [notice] Possible broken links found in node 1016: VPN (UI&amp;nbsp;Anywhere): node/247,Virtual Desktop: node/294
        [notice] Possible broken links found in node 1076: Two-Step Login authentication: node/115421,alternative authentication methods: node/115421
        [notice] Possible broken links found in node 1151: VPN support center: node/247
        [notice] Possible broken links found in node 1221: More information on getting a Drupal Digital Sign: node/105225&quot; target=&quot;_blank
        [notice] Possible broken links found in node 1236: ITS Help Desk: node/100093
        [notice] Possible broken links found in node 1246: ITS Help Desk: node/100093
        [notice] Possible broken links found in node 1326: Large Scale Storage (LSS): node/103906,LSS: node/103906,HPC: node/100144,Data Classification Guide: node/110901
        [notice] Possible broken links found in node 1341: &lt;strong&gt;Web conferencing&lt;/strong&gt;: node/101197,Zoom privacy settings tips page: node/120661,Microsoft Teams: node/117101,on this support article: node/118416
        [notice] Possible broken links found in node 1391: Microsoft Azure support center: node/105611
        [notice] Possible broken links found in node 1451: see this FAQ.: node/127481
        [notice] Possible broken links found in node 1516: &lt;strong&gt;Research Data Storage Service (RDSS)&lt;/strong&gt;: node/103936,&lt;strong&gt;Large Scale Storage (LSS)&lt;/strong&gt;: node/103906,Iowa Health Data Resource (IHDR) data enclave: node/125121,Shared Drive: node/109,OneDrive: node/101613,Interactive Data Analytics Service (IDAS): node/115766,RDCS: node/100180,&lt;b&gt;Approved Data Classification Levels&lt;/b&gt;: node/110901,RDSS: node/103936,LSS: node/103906
        [notice] Possible broken links found in node 1566: learn more about getting started: node/106591
        [notice] Possible broken links found in node 1606: recent changes to the H drive service: node/125361,VPN (UI&amp;nbsp;Anywhere): node/247,Virtual Desktop: node/294
        [notice] Possible broken links found in node 1611: data classification levels: node/110901,VPN (UI Anywhere): node/247,Virtual Desktop: node/294,Research Data Storage Service: node/103936
        [notice] Possible broken links found in node 1621: Large Scale Storage Service (LSS): node/103906
        [notice] Possible broken links found in node 1716: Data Classification Guide to IT Services: node/110901,this support article for instructions on how to move your data and access the new RRDS: node/128891
        [notice] Possible broken links found in node 1726: data classification: node/110901
        [notice] Possible broken links found in node 1731: Need a New Charged&amp;nbsp;Print Queue or Make Changes to an Existing One?: node/113661
        [notice] Possible broken links found in node 1776: ListServ: node/982
        [notice] Possible broken links found in node 1806: Permitted Data Classifications: node/119861#PermittedDataClassifications
        [notice] Possible broken links found in node 1831: Two-Step Login set up instructions: node/106591
        [notice] Possible broken links found in node 1891: ITS Help Desk: node/100093
        [notice] Possible broken links found in node 1896: Interactive Data Analytics Service (IDAS): node/115766
        [notice] Possible broken links found in node 1911: this support article: node/128286
        [notice] Possible broken links found in node 1951: service level expectations: node/2790
        [notice] Possible broken links found in node 1956: HawkID password: node/3811,ITS Help Desk: node/100093,HealthcareID: node/216
        [notice] Possible broken links found in node 1961: HawkIDs: node/215,automatically sync: node/217
        [notice] Possible broken links found in node 1966: password requirements: node/3811,ITS Help Desk: node/100093
        [notice] Possible broken links found in node 2016: hardware repair service providers: node/316,located on the second floor of the University Capitol Centre: node/100093
        [notice] Possible broken links found in node 2031: Virtual Desktop Support Center: node/294
        [notice] Possible broken links found in node 2046: follow this guide to connect to eduroam: node/210,learn more about connecting to ResNet here: node/4024,Register your device and find instructions on connecting to UI-DeviceNet here: node/105671
        [notice] Possible broken links found in node 2051: LinkedIn Learning: node/2015
        [notice] Possible broken links found in node 2076: ITC Printing system billing: node/433
        [notice] Possible broken links found in node 2161: the VPN: node/247,add one that isn&#039;t there: node/897
        [notice] Possible broken links found in node 2171: wake up or power on your on-campus computer remotely: node/898,the VPN: node/247
        [notice] Possible broken links found in node 2176: Remote Desktop connections : node/306,register it in PowerUp&amp;nbsp;yourself: node/897
        [notice] Possible broken links found in node 2246: instructions on in our support guide: node/2567,contact the ITS Help Desk: node/100093
        [notice] Possible broken links found in node 2251: &lt;strong&gt;Blocked Attachments&lt;/strong&gt;: node/125986
        [notice] Possible broken links found in node 2296: ITS Rental Program: node/1421
        [notice] Possible broken links found in node 2371: Instructions for downloading and installing Microsoft Office: node/103142,additional information on using Microsoft Office and how to install: node/104827
        [notice] Possible broken links found in node 2386: host device (an on-campus work computer) is configured for Remote Desktop: node/1595,&lt;span&gt;PowerUp&lt;/span&gt;: node/117511
        [notice] Possible broken links found in node 2466: Contact the ITS Help Desk: node/100093
        [notice] Possible broken links found in node 2516: HawkID password requirements: node/3811
        [notice] Possible broken links found in node 2521: HawkID password requirements: node/3811,After changing your HawkID password, make sure to update your saved credentials: node/2568
        [notice] Possible broken links found in node 2526: GlobalProtect VPN client or the Cisco VPN client: node/247
        [notice] Possible broken links found in node 2531: connect to the VPN and follow these instructions to sync your passwords: node/2567,eduroam: node/681,your Office 365 clients (e.g., Outlook, iOS, Android) will prompt you for your new password: node/104970,contact the ITS Help Desk: node/100093,remove and re-add the eduroam network on all of your devices: node/102644,Remove any old credentials from your device in Keychain: node/1346,connect to the university VPN and lock the device to force the password to sync: node/2567
        [notice] Possible broken links found in node 2601: Qualtrics FAQs: node/2720
        [notice] Possible broken links found in node 2611: What Qualtrics training options are available to me?: node/2713
        [notice] Possible broken links found in node 2621: Article 2713: node/2713,Qualtrics FAQs: node/2720
        [notice] Possible broken links found in node 2671: Qualtrics Support Center: node/2723&quot; target=&quot;_self&quot; title=&quot;Qualtrics Support Center
        [notice] Possible broken links found in node 3001: learn more about compromised computers: node/3963,what you can do if you have a copyright violation on a UI network: node/475
        [notice] Possible broken links found in node 3006: information on where ITCs are located and what services are available in them: node/103787,how to get started using Web Print : node/102875,eduroam: node/209,UI-DeviceNet: node/105671
        [notice] Possible broken links found in node 3021: instructions for connecting to ResNet: node/4024,Find more information on using UI DeviceNet.&amp;nbsp;: node/109456,Read more about our policies regarding unauthorized access points.: node/2775
        [notice] Possible broken links found in node 3026: wireless router policy: node/2775,wireless/network printer policy: node/3976
        [notice] Possible broken links found in node 3086: Find&amp;nbsp;brand-specific instructions here: node/109841
        [notice] Possible broken links found in node 3131: Managed Application and Platform Level Services: node/119846
        [notice] Possible broken links found in node 3346: Windows: node/1418
        [notice] Possible broken links found in node 3406: General Considerations for Using Cloud Services: node/104444,Cloud File Storage FAQ: node/101025,Compare Supported Storage and Sharing Options: node/103957,Campus Software Program Office: node/101388
        [notice] Possible broken links found in node 3481: complete login using Duo: node/106731
        [notice] Possible broken links found in node 3551: add terms to the Person Type taxonomy: node/102635,add/configure the panes: node/102479
        [notice] Possible broken links found in node 3556: Cropping Images: node/102768,configuring content to show on the homepage: node/103871#promote-to-front
        [notice] Possible broken links found in node 3566: support article about removing demo content: node/102640
        [notice] Possible broken links found in node 3626: check what type of Operating System you have: node/102333
        [notice] Possible broken links found in node 3636: previously generated a list of backup codes: node/102357,enroll another device (perhaps your office&amp;nbsp;phone, etc.): node/102357
        [notice] Possible broken links found in node 3666: Reusable custom content panes: node/102478
        [notice] Possible broken links found in node 3676: Creating and editing single-use custom content panes: node/102477,Changing the layout of a page: node/102480
        [notice] Possible broken links found in node 3746:  convert your PST files to your Office 365 account: node/103948
        [notice] Possible broken links found in node 3771: &lt;em&gt;Changing the order of menu links&lt;/em&gt;: node/102631,&lt;em&gt;Changing the order of menu links&lt;/em&gt;: node/102631
        [notice] Possible broken links found in node 3776: Files On-Demand set in your client: node/120336
        [notice] Possible broken links found in node 3786: &lt;em&gt;Changing the order of taxonomy terms&lt;/em&gt;: node/102638,&lt;em&gt;Changing the order of taxonomy terms&lt;/em&gt;: node/102638
        [notice] Possible broken links found in node 3806: Log in to the website: node/102832
        [notice] Possible broken links found in node 3816: here: node/104704
        [notice] Possible broken links found in node 3886: Access permissions on SiteNow: node/103154,Access permissions on SiteNow: node/103154
        [notice] Possible broken links found in node 3891: OneDrive for Business: node/101613
        [notice] Possible broken links found in node 3906: Changing the permissions of a user account: node/103157
        [notice] Possible broken links found in node 3911: Access permissions on SiteNow: node/103154
        [notice] Possible broken links found in node 3961: Sync SharePoint and Shared Libraries in OneDrive: node/110101
        [notice] Possible broken links found in node 3986: Repair your Office ProPlus&amp;nbsp;installation: node/103429&quot; target=&quot;_blank
        [notice] Possible broken links found in node 4031: &quot;Files On-Demand&quot; : node/120336,&quot;Known Folder Moves&quot;: node/120336,Create a new Shared Library: node/120391,Download the Teams client here: node/117291
        [notice] Possible broken links found in node 4141: Uploading to MyWeb through Dreamweaver CS5: node/100566
        [notice] Possible broken links found in node 4191: UI AnyWhere VPN: node/247
        [notice] Possible broken links found in node 4196: UI AnyWhere VPN: node/247
        [notice] Possible broken links found in node 4251: How to Report a Phishing Scam or a Spam Email: node/558
        [notice] Possible broken links found in node 4261: Find and edit content in SiteNow: node/102038
        [notice] Possible broken links found in node 4271: Adding Social Media Content: node/110816
        [notice] Possible broken links found in node 4311: change the path alias (URL) of a page on a SiteNow website: node/104241
        [notice] Possible broken links found in node 4316: support article about enabling and disabling apps: node/102041,Changing the general look and feel: node/102765
        [notice] Possible broken links found in node 4321: contact the ITS Help Desk: node/100093
        [notice] Possible broken links found in node 4461: Skype for Business Meeting: node/2783
        [notice] Possible broken links found in node 4491: Webform: node/102037,Background Image (Stellar theme only): node/104335,Creating a menu link to a page: node/102630
        [notice] Possible broken links found in node 4546: Hardware and Operating System Recommendations: node/105221&quot; target=&quot;_blank
        [notice] Possible broken links found in node 4556: support article on content guidelines: node/110396
        [notice] Possible broken links found in node 4596: ITS Service Catalog page: node/104694
        [notice] Possible broken links found in node 4646: Using SFTP with MyWeb: node/103827
        [notice] Possible broken links found in node 4691: how to manage your Two-Step profile and devices: node/102357
        [notice] Possible broken links found in node 4716: &lt;em&gt;Advanced webform configuration&lt;/em&gt;: node/107376
        [notice] Possible broken links found in node 4736: how to find your MAC address: node/105676,XBOX 360 S Console Model 1439: node/113211,ITS Help Desk: node/100093
        [notice] Possible broken links found in node 4901: using the media browser library: node/103207#media-library
        [notice] Possible broken links found in node 4961: How to connect your mobile device to UI Wireless eduroam: node/283,How to set up email and calendar on your mobile device: node/101199,Installing Skype for Business on a mobile device: node/3766,Set up : node/106591,Two-Step: node/106591, login: node/106591,Download the HawkTools&amp;nbsp;app: node/105218
        [notice] Possible broken links found in node 4971: directions to place a content pane on a page: node/102479
        [notice] Possible broken links found in node 5026: &lt;span&gt;&lt;span&gt;&lt;span&gt;NIST 800-171&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;: node/110266,ITS-Managed Hosting Services for Export-Controlled Data: node/110261
        [notice] Possible broken links found in node 5031: ITS-Managed services: node/110261,&lt;span&gt;&lt;span&gt;&lt;span&gt;Safeguarding Export-Controlled Technical Data for System Administrators&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;: node/110256,&lt;span&gt;&lt;span&gt;&lt;span&gt;Safeguarding Export-Controlled Technical Data for System Administrators&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;span&gt;&lt;span&gt;&lt;span&gt;.&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;: node/110256
        [notice] Possible broken links found in node 5036: ITS-Managed services: node/110261,NIST 800-171 requirements: node/110266,&lt;span&gt;&lt;span&gt;&lt;span&gt;Safeguarding Export-Controlled Technical Data for Researchers&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;: node/110251,ITS-managed datacenters are hosting systems: node/110261
        [notice] Possible broken links found in node 5041: non-US Persons: node/110761,US Person: node/110761,How to Begin Working with Export-Controlled Technical Data: node/110246
        [notice] Possible broken links found in node 5071: GitLab Academic: node/115436,Large Scale Storage (LSS): node/103906,Microsoft SQL Server: node/100128,On-Premise Datacenter Hosting: node/110261,Office 365 GCC High: node/122191,Research Data Storage Service (RDSS): node/103936,Research Remote Desktop Service: node/110071,Secure Device Service: node/116601,Virtual Server: node/100415,NIST 800-171: node/110266
        [notice] Possible broken links found in node 5076: connect to eduroam for the first time: node/210,remove and reconfigure the eduroam wireless network: node/102644,detailed instructions on using the eduroam CAT: node/104876,Check the ITS Alerts website: node/100311,please contact the ITS Help Desk: node/100093
        [notice] Possible broken links found in node 5131: ITS Help Desk: node/100093
        [notice] Possible broken links found in node 5146: Critical - Export-Controlled: node/110246,Apple iCloud: node/101025,AWS Cloud Enterprise: node/105606,Box: node/101025,Dispatch: node/105791,Dropbox: node/101025,Globus: node/100180,Google Drive &amp;amp; Gmail: node/101025,Home Drives (Files@Iowa): node/103888,HPC Systems: node/100144,Large Scale Storage (LSS): node/103906,ICON: node/2053,Interactive Data Analytics Service: node/115766,Iowa Health Data Resource (IHDR) Data Enclave: node/125121,Microsoft Azure Cloud Services Enterprise: node/105611,Microsoft Copilot - UI Enterprise License: node/127866,Microsoft OneDrive for Business: node/101613,Microsoft SharePoint Online (O365): node/102716,Microsoft Teams: node/117101,Personal Cell Phones: node/280,Personal Devices (e.g. laptops, USBs, personal cloud services, etc.): node/233,Qualtrics: node/1771,R: Drive: node/100924,REDCap: node/100181,Research Data Storage Service (RDSS): node/103936,Research Remote Desktop Service: node/110071,Secure Device Service: node/116601,Shared Drive (Files@Iowa): node/109,Skype for Business: node/6,UICapture: node/2474,Zoom: node/101197
        [notice] Possible broken links found in node 5161: these instructions: node/558,tips to recognize phishing scams: node/3716
        [notice] Possible broken links found in node 5261:  wired ResNet connection: node/4024
        [notice] Possible broken links found in node 5271: main RRDS&amp;nbsp;support page: node/113296,Duo Two-Step Authentication: node/102315,VPN access for connections off-campus: node/1876
        [notice] Possible broken links found in node 5276: main RRDS&amp;nbsp;support page: node/113296
        [notice] Possible broken links found in node 5316: grant them access to the RDSS space: node/114376
        [notice] Possible broken links found in node 5421: ITS Help Desk: node/100093,ITS Help Desk: node/100093
        [notice] Possible broken links found in node 5501: contact the ITS Help Desk: node/100093,How to Grant or Revoke Access to Your RDSS Space: node/114376
        [notice] Possible broken links found in node 5526: System Monitoring and Alerting: node/115176
        [notice] Possible broken links found in node 5621: Virtual Desktop: node/294,departmental IT support staff: node/2697
        [notice] Possible broken links found in node 5651: GitLab Periodic Update Schedule: node/114586,GitLab Backup Schedule: node/114736,GitLab Security Update Schedule: node/114576
        [notice] Possible broken links found in node 5726: video conferencing options and when to use Skype for Business, Microsoft Teams, and Tools: node/118416,resources for internet options : node/118201,Drive-up wifi: node/118316,these online meeting etiquette tips: node/118196,OneDrive for Business: node/101613,home drive: node/103888,shared drive: node/109,types of data that can be used with different IT services and tools: node/110901,Virtual Private Network (VPN): node/247,how to configure a Windows computer for remote access: node/1595,how to use screen sharing to connect to your Mac: node/118091,contact us: node/100093,Drive-up Wifi Locations page: node/118316,list of internet options that might be available to you: node/118201,information about Two-Step Login and switching to the app: node/102315,instructions on how to use Outlook Web Access (OWA) for Office 365: node/104670,learn how to install Outlook: node/103142,get Outlook on your phone: node/101199,Remote Desktop: node/306,learn how to install Skype for Business: node/103142,Skype quick start guide for Windows machines: node/108271,Microsoft Teams: node/117101,When to use Skype for Business, Microsoft Teams, and Zoom: node/118416,meeting etiquette tips: node/118196,downloading and configuring Cisco AnyConnect: node/1876,how to log in to the VPN with Two-Step Login: node/115421,how to log in, create and share files, and more with the OneDrive: node/102633,Connect to your home drive from off-campus: node/104047,Connect to your shared drive from off-campus: node/104043,install Microsoft Office using these instructions: node/103142,how to configure a Windows computer for remote access: node/1595,how to use screen sharing to connect to your Mac: node/118091,Connecting to email and calendar on your device: node/101199,Download Skype for Business on your mobile device: node/3766,Updating your Windows operating system: node/1418,Updating your Mac operating system: node/1266,phishing tips and best practices: node/3716,antivirus protection for home use&amp;nbsp;: node/100582,Software resources for individuals impacted by COVID-19 campus closures: node/118296,move mail from your .pst files (personal folders) to your Office 365 account: node/103948,your IT representative: node/2697
        [notice] Possible broken links found in node 5731: Configuring Your Email App for Microsoft 365: node/104970,Connect to Microsoft 365 Email and Calendar on Your Mobile Device: node/101199
        [notice] Possible broken links found in node 5756: Microsoft Teams: node/117101
        [notice] Possible broken links found in node 5761: Review the Drive-up Wifi Locations page: node/118316,Turn your phone into a mobile hotspot: node/118306,Find more resources for working at home: node/118001
        [notice] Possible broken links found in node 5796: eduroam service: node/209,connect to the eduroam network: node/210,connect to the eduroam network: node/210
        [notice] Possible broken links found in node 5816: Skype for Business: node/6
        [notice] Possible broken links found in node 5831: UI OneDrive: node/101613,RDSS: node/103936,LSS: node/103906,H: drive: node/103888
        [notice] Possible broken links found in node 5861: delegates: node/119191
        [notice] Possible broken links found in node 5901: grant and revoke access to the LSS share: node/118771&quot; target=&quot;_blank,added as a &quot;member&quot;: node/118771&quot; target=&quot;_blank
        [notice] Possible broken links found in node 5921: https://its.uiowa.edu/node/122411: node/122411,Zoom Pronouns: node/122611,Zoom Minimum Client Version Requirement: node/122411,learn more about this update and the changes it applies at the ITS support site: node/119346,More information on the passcode requirement is available on the ITS support site: node/119201
        [notice] Possible broken links found in node 6006: GitLab Academic: node/115436
        [notice] Possible broken links found in node 6016: download the correct Zoom app for your device: node/119291
        [notice] Possible broken links found in node 6026: Zoom Add-In for Outlook Desktop: node/122356
        [notice] Possible broken links found in node 6041: Zoom - Waiting Rooms: node/119736,Zoom Info Center: node/101197
        [notice] Possible broken links found in node 6071: non-U.S. persons: node/110761,services: node/110491
        [notice] Possible broken links found in node 6091: UI VPN: node/247,Recommended antivirus software&amp;nbsp;: node/100582,General computer security recommendations: node/265,Working from home guidance: node/118381,this page: node/104109,ITS Data Classification Guide: node/110901,click here: node/100924,UI OneDrive: node/101613,&lt;span&gt;&lt;span&gt;Zoom&lt;/span&gt;&lt;/span&gt;: node/101197&quot; style=&quot;text-decoration:underline,Comparison of Video Conferencing Options: node/118416,Technology Review: node/101551,Data Classification Guide to IT Services: node/110901,please click here: node/232,UI Password Policy: node/2028
        [notice] Possible broken links found in node 6096: data&amp;nbsp;classification: node/110901
        [notice] Possible broken links found in node 6106: this&amp;nbsp;webpage: node/110901
        [notice] Possible broken links found in node 6111: OneDrive for Business (Office 365): node/101613,Groups (Office 365): node/120391,SharePoint Online (Office 365): node/102716,Teams (Office 365): node/117101
        [notice] Possible broken links found in node 6156: &quot;Files On-Demand&quot;: node/120336,&quot;Known Folder Moves&quot; : node/120336,Create a new Shared Library: node/120391,Teams client here: node/117291
        [notice] Possible broken links found in node 6161: Skype for Business Location Information FAQ support article: node/120291&quot; style=&quot;color:#0563c1; text-decoration:underline
        [notice] Possible broken links found in node 6201: ITS-EI-SAS: node/119841,ITS-EI-SAS: node/119841,Backup and Recovery of Virtual Server: node/116066,FAQ page: node/123716
        [notice] Possible broken links found in node 6211: PST files to Office 365: node/103948,OneDrive Automatic sign-on and backup: node/120791,Quick Start Guide: node/102633,Training: node/120576,Best Practices: node/117881
        [notice] Possible broken links found in node 6226: Faculty and Staff lose access to OneDrive on your last day of employment. : node/118086,Retirees lose access to OneDrive on your last day of employment.: node/1539,Students have access for 2 years following graduation or leaving the University.: node/117911
        [notice] Possible broken links found in node 6291: this support article on how to set the homepage: node/127596
        [notice] Possible broken links found in node 6396: here: node/122251
        [notice] Possible broken links found in node 6461: Connect to the Cisco AnyConnect Secure Mobility Client: node/1876
        [notice] Possible broken links found in node 6466: Teams: node/117101,OneDrive: node/101613
        [notice] Possible broken links found in node 6471: moving these files to Office 365: node/103948
        [notice] Possible broken links found in node 6546: following these directions: node/120391
        [notice] Possible broken links found in node 6686: copy&amp;nbsp;your data to OneDrive for Business: node/119721,move your mail to Office365: node/103948,Sign-up for OneDrive training: node/104794
        [notice] Possible broken links found in node 6691: Two-Step Login with Duo Security: node/102315
        [notice] Possible broken links found in node 6851: See this support article: node/1876
        [notice] Possible broken links found in node 6891: alerts page: node/100311, contact the Help Desk: node/100093,how to set up rules for email messages: node/1056,how to add a service alert or planned maintenance announcement: node/107561
        [notice] Possible broken links found in node 6901: managed services information: node/119846,cloud services information page: node/124001
        [notice] Possible broken links found in node 7001: Connect using a Windows PC: node/113321,Connect using a Mac: node/113341
```

</details>
