### ISSUE TITLE
Ceremony content type

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7559]
# Stories

As a commencement site owner, I want to be able to display ceremony information on the commencement website that comes from Content Hub.
As a commencement site owner, I want to be able to add additional information to the ceremony events that are pulled into my site.

```[tasklist]
### Tasks
- [x] Work with customer to determine necessary fields
- [x] Create commencement.uiowa.edu site split
- [x] Create event content type
- [x] Add fields necessary for API import
- [x] Add remaining fields
- [x] Content type best practices: content moderation?, path alias pattern, permissions, metatag, etc.
```

**Comment by pyrello** [comment]
Per conversation with Josh, we are going to add the following structured data fields in lieu of using Layout Builder for additional content:
- Livestream - remote video media field for YouTube videos
- Commencement information - Paragraph reference field for displaying accordions of title/content
- Additional information - A textarea with filtered HTML format
