### ISSUE TITLE
Probe program functionality, come up with plan, execute?

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7562]
# Stories

As a commencement site owner, I can attach program PDFs to one or multiple ceremonies.

```[tasklist]
### Tasks
- [x] Work with customer to understand relationship between programs and events
- [x] Develop a plan for how programs will work going forward
- [x] Build a prototype or the actual thing if that makes sense
```

**Comment by pyrello** [comment]
After discussing with Josh, we agreed that the Program media field will be placed on the Session term. The Order of Events media field will be placed on the event content type.

**Comment by pyrello** [comment]
I think this is completed now with the work represented in #7563. I'll let that PR close this.
