### ISSUE TITLE
Create migration for past ceremony events

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7567]
```[tasklist]
### Tasks
- [x] Migration module scaffolding
- [x] Creating mapping config for redirects
- [x] Create mapping config for events
- [x] Custom code to handle situations not handled by a plugin/mapping (document any specific fields as separate items)
- [x] If custom code is necessary, create migration class file for Event
- [x] ~Figure out why Pictures on the Pentacrest taxonomy term is not being added to events (but all other celebrations are)~ fixed, I had added old term from dev site instead of newer one from prod site.
- [x] Check if we need to pull unique id - we don't
```

```[tasklist]
### D10 fields that haven't been mapped (and need to be)
- [x] field_event_ceremony_information - only pulling accordions
- [x] field_event_livestream
- [x] start/end date
- [x] field_event_session
- [x] field_event_order_of_events
- [x] ~field_event_additional_info~ - not needed, not in source
```

**Comment by e-marie-w** [comment]
The D7 site has a field_event_imported boolean field. We do not have an equivalent in d10, do we need one or is that safe to skip? I am skipping the ID field on the d10 site as it is used by the event importer and does not exist in D7.

**Comment by pyrello** [comment]
> The D7 site has a field_event_imported boolean field. We do not have an equivalent in d10, do we need one or is that safe to skip? I am skipping the ID field on the d10 site as it is used by the event importer and does not exist in D7.

Let's skip this. If it turns out we need it, we'll add it in later.

**Comment by pyrello** [comment]
Some notes for myself for tomorrow:
- Livestreams in the current site are placed in a text area using a media embed.
- The `ProcessMediaTrait` seems to contain code oriented towards converting a media embed from the old style format to how it would be placed in a current SiteNow text area.
- In this case, we want to do everything that currently happens in `ProcessMediaTrait::entityReplace` except for returning the rendered markup for a media embed for current SiteNow.
- Instead, we want to just create the local media item (in this case a YouTube remote video) and then return the ID of the media item so we can assign it as a `target_id` for the new dedicated livestream field.
- Since I'm not finding any functionality like what I am looking for in the `ProcessMediaTrait`, I'm inclined to believe that this functionality doesn't exist yet. I would love a second opinion by @cory-skeers.
- https://commencement.uiowa.edu/node/961/edit is an example of an event node that has text both before and after the video. Need to check with Josh about how to handle that.
- Based on the fact that text area is one of the possible blocks that can be added below a section, it is possible that not all livestream videos are implemented in the same way. I don't think it is worth the effort to make the code smart enough to delve deeper than checking the top level.
- A better investment might be a post migration report that identifies any nodes that did not have a livestream associated with them.

**Comment by pyrello** [comment]
I came across this event, which makes more extensive use of the section blocks widget: https://commencement.uiowa.edu/ceremony/spring-2022/celebration-graduates

The way we have the event content type structured on the new site, it was not immediately clear how to accommodate the extra sections and headers. I talked this through with Josh and he said there are only a handful of instances where they did something like this and he thinks it was primarily because there wasn't a way to use the individual accordions as direct anchor links. After talking it through, we are going to move ahead with essentially the same structure we have now with some minor updates for display, labels, and form order. This migration will still pull any accordions it finds and populate them but is going to ignore other text areas like this. Josh will go back through and fill in anything that needs to be recreated.

**Comment by pyrello** [comment]
Noting here that I kept seeing this notice that didn't seem to affect functionality:
` [notice] Scheduler settings cannot be migrated due to RequirementsException: No database connection configured for source plugin variable, , line 200 in /var/www/html/docroot/core/modules/migrate/src/Plugin/migrate/source/SqlBase.php`

**Comment by pyrello** [comment]
Currently stuck on:
We're creating paragraphs on the fly as part of the migration: 
https://github.com/uiowa/uiowa/blob/8b053703113cf1397ccfa6bf0631553b875f373a/docroot/sites/commencement.uiowa.edu/modules/commencement_migrate/src/Plugin/migrate/source/Event.php#L144-L151
https://github.com/uiowa/uiowa/blob/8b053703113cf1397ccfa6bf0631553b875f373a/docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/ProcessFieldCollectionTrait.php#L64-L75
And to make sure we don't leave a mess behind if we have to roll back and run the migration again, we're performing a cleanup.
https://github.com/uiowa/uiowa/blob/8b053703113cf1397ccfa6bf0631553b875f373a/docroot/sites/commencement.uiowa.edu/modules/commencement_migrate/src/EventSubscriber/MigrateEventSubscriber.php#L66-L76

I noticed when checking the count of paragraphs of bundle `uiowa_collection_item` that I would start with 1 item. After migrating, I'd have 141. After rolling back, I'd have 71. @cory-skeers took and look and discovered that there are two sets of Paragraphs being created. The first set are correctly associated with the parent event node and `$paragraph->parent_field_name === 'field_event_ceremony_information_coll'` evaluates to `TRUE` ('field_event_ceremony_information_coll' being the field that references this paragraph type in the content type being migrated). The second set doesn't have a parent entity and `$paragraph->parent_field_name === 'field_event_ceremony_information_coll'` evaluates to `FALSE`.

I don't understand how this second set of paragraphs are getting created. I've been able to confirm what Cory was seeing but I have no idea how to work around it.

**Comment by joewhitsitt** [comment]
have you inspected the db to see what these others are tied to? does this loop and create another revision of the paragraph? does delete orphaned entities clean them up?

**Comment by pyrello** [comment]
> have you inspected the db to see what these others are tied to?

The other paragraphs are not tied to anything.

> does this loop and create another revision of the paragraph?

This does happen in a loop, but it doesn't seem to be happening more times than would be expected. I will check if the IDs are duplicated (with more than one revision).

> does delete orphaned entities clean them up?

Is this a drush command? Or something through the UI?

**Comment by joewhitsitt** [comment]
admin/config/system/delete-orphans or what we did in p2lb cleanup

```
// Delete orphaned paragraphs, three-levels deep (section > block > item).
  $purger = \Drupal::service('entity_reference_revisions.orphan_purger');
  for ($i = 0; $i < 3; $i++) {
    $purger->setBatch(['paragraph']);
    drush_backend_batch_process();
  }
```

**Comment by pyrello** [comment]
> does this loop and create another revision of the paragraph?

This does happen in a loop, but it doesn't seem to be happening more times than would be expected. I will check if the IDs are duplicated (with more than one revision).

Looking at the `uiowa_collection_item`s in the `paragraphs_item` table, every one has a unique ID, so it is not an issue where an additional revision is being created.

**Comment by pyrello** [comment]
Current best idea about how to move this forward is to find a debugging breakpoint that will let me see what is triggering the creation of the additional paragraph items.
