### ISSUE TITLE
Commencement program archive

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7577]
- Needs to show just programs? Or order of events also?
- Is customer okay with table or list format instead of drop-down?
- Most recent shown first (sort reverse chronologically)
```[tasklist]
### Tasks
- [x] Build a view block to display a list of programs by session
- [x] Break the title field into year and season
- [x] Format link using "View program" text instead of URL
- [x] Auto label session terms from year + season fields and hide title
- [x] Populate year select options
```
