### ISSUE TITLE
Miscellaneous commencement updates

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7589]
```[tasklist]
### Tasks
- [x] Switch back to having events unpublished by default when imported
- [x] Rename Session term season field to session
- [x] Sort program archive by year + season
- [x] Finish defining ceremonies and venue metatag config
```

**Comment by pyrello** [comment]
I removed the task to switch the start/end dates to using a range because it had significant downstream effects on updating the importer. We'll revisit later.
