### ISSUE TITLE
Theme commencement venues

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7591]
# Additional Info

They mentioned that they plan to use the body field to add content similar to the Information and Polices on https://commencement.uiowa.edu/venue/carver-hawkeye-arena. This and the additional information collection sections and items is the most important info.

Address info, map and directions link would be next most important info.

List of upcoming events is more for internal use and can be lower on page.

Have some concerns about the potential for lots of scrolling and if so would like some sort of built in anchor links to the address/map/directions section and the upcoming events section. These could possibly exist on the featured image banner if necessary?

```[tasklist]
### Tasks
- [x] Display image as featured image banner
- [x] Content above additional information sections (body)
- [x] Ceremony information
- [x] Map
- [x] Venue Directions link
- [x] Upcoming events
- [x] Confirm/Address any issues with heading structure
```
