### ISSUE TITLE
Theme commencement event/ceremony nodes

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7592]
# Story

As a visitor to commencement ceremony pages, I can see a fully themed page with the most important information first.

# Additional Information

Date,Venue,Body is important info that should be easy to get to. Details can be long in some cases. Should output a message with the time that says times listed are in Central Time.

Manually added ceremony information is important and should be able to get to easily.

Livestream is important and should be easy to get to.

No photo for now.

Program is tied to session so if a session is set for a ceremony, the appropriate program for that session should be displayed. The session does not need to output on the ceremony.

Don't need to display college or other celebration info on ceremony page.

Possibly work in presidential seal if possible (Josh mentioned he liked that on the current site at one point). https://brand.uiowa.edu/logos/secondary-logos#seal

```[tasklist]
### Tasks
- [x] Output date - start time & end time - output note about times are in Central Time
- [x] Link to venue
- [x] Output room if exists as part of address
- [x] Address from Venue
- [x] Output body - can get long
- [x] Do not display label for Ceremony information collections field and display this field after Ceremony information field
- [x] Display Ceremony information field label as h3 - make sure proper heading structure
- [x] Livestream info
- [x] Order of events file upload
- [x] Display program on ceremony
- [x] event link to Events Calendar
- [x] Contact name, email, phone
- [x] Website
- [x] Work in presidential seal somewhere
```

**Comment by briand44** [comment]
Grooming conversation... Sean mentioned he believes the session teaser is already configured to display the program. Sean also mentioned that the not displaying label for ceremony information collections is done already. Question came up about the seal. Should that be included in UIDS and pulled from there? Do we need to account for CDT/CST or just Central Time? I can try and get some clarification from Josh here but I would default to not overcomplicating it.

**Comment by GaryRidgway** [comment]
> Output room if exists as part of address

Do we need to link this to anything?

**Comment by briand44** [comment]
We don't need to link the room to anything but the Venue would link similar to https://commencement.uiowa.edu/ceremony/spring-2024/pictures-pentacrest-0
