### ISSUE TITLE
Initial event theming tasks

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7600]
```[tasklist]
### Tasks
- [ ] Entity bundle class scaffolding
- [ ] Card/teaser styling
- [ ] Create LB template for event
- [ ] Display program (via session field) on event
```
