### ISSUE TITLE
Facilities post launch updates

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7607]
**Art**
- Have "Status" filter default to "Active" on Art on Campus Gallery - https://facilities.uiowa.edu/art-campus/art-campus-gallery
- Move "Status" filter below "Medium"
- Remove artist photo
  - Probably need to move the Artist website link as well
  - https://github.com/uiowa/uiowa/issues/6588
- Change the order of info on the individual art page:
  - Artist (1st)
  - Artist website (2nd)
  - Building (3rd)
  
**Building Information Pages**
- On the [Building Information webpage](https://facilities.uiowa.edu/buildings), previously, when you typed a building acronym or name, it would start to populate the search and you could click on the building instead of continuing to type. Could this feature be re-implemented?

**Alerts**
- They would like to grant collaborators the ability to edit and delete any alert rather than just edit and delete own alerts.
```[tasklist]
### Tasks
- [x] Investigate setting a default filter value on the gallery view
- [x] Adjust display settings from the IS above
- [x] Adjust the display settings for person on Facilities only to remove the person photo. Account for any remaining fields in the sidebar
- [x] Change the order of info on the individual art page
- [x] Buildings view should autosubmit
- [x] Update permissions for alerts so that collaborator role can edit/delete any alert
```

**Comment by briand44** [comment]
Grooming converstaion... Haven't yet set a default value for exposed filters so that is a unknown territory. Are the display settings for Facilities already split? How much additional work to do this for the service. One idea brought up was to just change the layout of person nodes for Facilities and not tackle this for the service. We may need to verify they don't have any people nodes that aren't artists. We could turn on autosubmit on the building search page. Brian to check if that is what they are looking for or if that will meet their needs. Sized as medium but we can adjust once we get feedback on people pages and ajax autosubmit.

**Comment by briand44** [comment]
Got a response from Facilities confirming they are only using the person content type to create artists so they would be fine if we just didn't display the person photo on person nodes for this site.

They also believe that autosubmit on the building search page should resolve their issues with that page.

**Comment by GaryRidgway** [comment]
Upon working on perms, I added the ability to delete any revisions, view revisions, and revert revisions to the collaborator as well, as being able to edit and delete any without those would feel a bit restrictive. Any specific thoughts on that from anyone keeping up?

**Comment by briand44** [comment]
Seems like that makes sense. Those are all limited to alerts, correct?

**Comment by GaryRidgway** [comment]
Correct, only on alerts
