### ISSUE TITLE
ITS email safeguards

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7617]
# Story

As an ITS site owner, I would like some safeguards in place for our alert emails that are sent so we can avoid damage control in the case an email is accidentally sent to subscriber lists.

# Additional Info 

There has already been one alert email that was sent to the production population accidentally while testing.

# Proposed solution

```[tasklist]
### Tasks
- [ ] Establish a site specific configuration form
- [ ] Create a separate input for alert email, digest email that can take multiple values, comma separated
- [ ] Prevent errors if inputs are blank
- [ ] Update the email logic to call the config values, remove the hardcoded emails and the Env protection
- [ ] Wait to hear whether a separate input for the alert creation email to helpdesk staff is needed. If so, figure out a way to override the workbench_email template email
```

**Comment by briand44** [comment]
Grooming conversation... D7 work was probably a little overkill. Possibly create a site specific config page where webmaster can set the email value. There are three different emails. Digest emails, alert creation email to notify help desk, alert email sent to subscriber list. There may be some trickiness related to overriding the workbench email via config set elsewhere. Discussed not investing in additional warning messages as part of this slice. We can add those in future slice if they end up being needed. Do we need to put safeguards around the Help Desk Notify email since that is contained to the Help Desk? Brian can get clarification here.

**Comment by briand44** [comment]
Asked Adrienne about the Help Desk Notify email and she isn't as concerned about this one but still thinks there is value in adding safeguards around it for testing purposes.

**Comment by joewhitsitt** [comment]
So, this one can be overridden already and we can figure out how to ignore it so it doesn't revert on deployment if need be. Not sure if we need a separate input for it.

We don't have many site specific ignore rules though so it would nice if we didn't need to cover the revert possibility.
