### ISSUE TITLE
Content type updates

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7627]
```[tasklist]
### Tasks
- [x] Both: Ensure that no collection items are prepopulated
- [x] Event: Rename Ceremony information field to Ceremony information collections
- [x] Event: Rename Additional information field to Ceremony information and move ahead of the Ceremony Information collections field
```
