### ISSUE TITLE
Run commencement ceremony migration in dev

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7638]
# Story

As a web team, we would like to run the Commencement event migration in dev so that we can get feedback on that work and make sure everything is accounted for.

```[tasklist]
### Tasks
- [x] Setup a non-production environment for v3 site and sync prod v3 site to it.
- [x] Run migration in non-production environment.
- [x] Communicate to Josh so he can review.
- [x] anything else?
- [x] Review parking lot card for ITS stuff in DEV https://github.com/orgs/uiowa/projects/20/views/1?pane=issue&itemId=22614984
```

**Comment by briand44** [comment]
Grooming conversation.. ~250 nodes and about 70 paragraphs created and a couple dozen taxonomy terms.
