### ISSUE TITLE
Ceremony filterable list

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7649]
# Story

We would like to be able to display a list of all commencement ceremonies with the ability to filter so that users can quickly find the ceremony information they are looking for.

# Additional Info

- Ability to filter by Session
  - Default session to webmaster defined default session - On the live site, the session taxonomy has a default boolean field so the webmaster can choose which session the list should default to.
- Ability to filter by College - would like to choose multiple - nice to have would be a select all option.
- Ability to filter by Other Celebration type
- Ability to filter by Venue

**Info to Display**

- Title as a link
- date start and end time if exists
- venue

Theme

# Proposed Solution
```[tasklist]
### Tasks
- [x] Create view to display a list of all ceremonies.
- [x] Add way to set current session - developer's choice if via a form setting or a field on the entity. Either way only one session should be set at a time.
- [x] Add ability to filter by session, with default set to current session. Filter should be a select list.
- [x] Add ability to filter by college, with option to choose multiple. Nice-to-have would be a select all option. Filter should be a select list.
- [x] Add ability to filter by Other Celebration type, perhaps under an Advanced section. Filter should be a select list. Maybe have option to select none?
- [x] Add ability to filter by venue. May need to turn venue autocomplete into a select list.
- [x] Ceremony teaser should display title as a link, start date (and end date if it exists), and the venue.
- [x] Theme view
```

**Comment by briand44** [comment]
Grooming conversation... Default session conversation. Should we have a form setting for this or should it be a field on an entity type? If on an entity we may need to handle not having more than one set. Need to make sure we can display the list of sessions in an appropriate order. Some conversation about how to not show other celebrations. Two pages were discussed but we'll want to get feedback from Josh if we want to go that way. Having an advanced section for the filters with the ability to show and filter other celebrations was also discussed. All of these should be select lists. We may need to turn an autocomplete into select list for venue.

**Comment by briand44** [comment]
Talked with Josh. They would prefer to have all of the ceremonies on the same page rather than have the "Other Ceremonies" on a separate page. We discussed having the ability to filter by multiple colleges would solve for their need of a way to see only Collegiate ceremonies.

**Comment by pyrello** [comment]
Going to start working on this.

**Comment by briand44** [comment]
@pyrello We discussed the multi-select filter at EOD and the team likes the Well Being solution that uses the Chosen library. Sounded like Better Exposed Filters has the checkbox styling built in if you end up having to go with Better Exposed Filters for some other reason.

**Comment by pyrello** [comment]
I've got the logic for setting the default session working. I went the route of creating a commencement_core.settings config (virtually because its config ignored) because I didn't like the idea of having to actually save the term (and create a revision) each time the default is changed (it probably wouldn't matter much in this case because it happens so infrequently). My issue now is that the view gets cached and continues to display the previous default session after a new one has been saved. I tried adding logic to invalidate the cache tags for the term, but I suspect that views caching is not intelligent enough to invalidate the view caching based on the term cache being invalidated. I'm looking for ideas about how to get views to respond to the term cache invalidation.
