### ISSUE TITLE
Setup emergency endpoint in stage and communicate

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7654]
# Story

As a consumer of the Emergency endpoint, I would like to be notified of the new endpoint and have it available in a non-production environment so I can test against and be prepared to deploy when the new site launches.

# Additional Info

Should communicate with...
- app dev list
- web community list?
- ~campus communicators?~

# Proposed Solution
```[tasklist]
### Tasks
- [x] Remove stage domain from 702
- [x] Add stage domain to uiowa07
- [x] Draft single communication about new endpoint - may or may not need a page to link to
- [x] Get v3 Emergency site in stage environment with new endpoint
- [x] Point emergency.dev.drupal.uiowa.edu back to D7 application - Make sure import/rave_feed is set to http://content.getrave.com/cap/uiowatest/channel1
- [x] send communication to appropriate lists
```

**Comment by briand44** [comment]
Grooming conversation... If we don't have a launch date at this time we likely will need a follow up communication to let folks know when the new endpoint will be live and the old deprecated. Was mentioned that one communication for all would be preferred over separate communications for each group. Stage is where we should make this available. We will want to make the D7 site available in dev again.

**Comment by joewhitsitt** [comment]
Here is the documented changes https://github.com/uiowa/uiowa/issues/7550#issuecomment-2098621468 which in an effort to keep the communication audience pretty general could be a resource page somewhere else that is linked to.

**Comment by joewhitsitt** [comment]
Bummer. If we need to change the BASE_URL for the endpoint to the test Rave endpoint, that is a code change currently. So STAGE will only have the production Rave endpoint to start with. Maybe a small additional slice would be to make that configurable similar to content hub events settings.

If we switch from STAGE to DEV, the same kind of temp feature branch might need to be deployed to DEV to temporarily override this.

**Comment by briand44** [comment]
Team thought we should do ^^. Still kept it as a small.

**Comment by pyrello** [comment]
Working on this

**Comment by pyrello** [comment]
For making the endpoint configurable, are we intending to:
- Make it temporarily configurable via a temp branch?
- Make it configurable on the emergency site only?
- Make it configurable on all sites?

**Comment by joewhitsitt** [comment]
I wasn't in planning, but I assumed we would make it configurable on the emergency site (which rave endpoint to fetch from) and set that manually as needed.

https://github.com/uiowa/uiowa/blob/823fd555fd3a53330ed73deea699960b7d67025e/docroot/sites/emergency.uiowa.edu/modules/emergency_core/src/EmergencyAPI.php#L59

[The next slice](https://github.com/uiowa/uiowa/issues/7655) I would think would also continue to allow setting the endpoint for each site (which emergency environment to fetch from) as needed. https://github.com/uiowa/uiowa/blob/d06878a3062264b55d9fd8fa2490af780c991a80/docroot/modules/custom/uiowa_alerts/src/Form/SettingsForm.php#L34

**Comment by pyrello** [comment]
I'm currently trying to get clarification on whether this endpoint should be displaying more than one result: https://content.getrave.com/cap/uiowatest/channel1

**Comment by briand44** [comment]
Discussed checking to see if Ken and Patrick are on the web community list to determine if we need to send to them specifically or not. Decided to not sent to campus communicators.

**Comment by pyrello** [comment]
Article is published: https://sitenow.uiowa.edu/news/2024/05/upcoming-changes-hawk-alerts-api

**Comment by briand44** [comment]
Looks like Ken and Patrick are both subscribed to the web community list.

**Comment by briand44** [comment]
I sent the email to the UI-AppDev list.

**Comment by pyrello** [comment]
I set the config value for to the test endpoint for the stage website. I also copied the scheduled job we already had setup for prod to stage. I think this is done now.
