### ISSUE TITLE
Update signage/HC Signage and SiteNow v1/v2/v3 to work with new Emergency endpoint

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7655]
# Story

As a consumer of Hawk Alerts from the Emergency website, we would like to update our integrations to work with the new endpoint so that when the new Emergency site launches, folks can still be notified of Hawk Alerts on Signage and SiteNow websites.

# Additional Info

New endpoint - `/api/active`

- Signage
- HC Signage
- SiteNow v1 - only seeing the uiowa_alerts module enabled on Hawktools after searching 701-703.
- SiteNow v2/v3
```[tasklist]
### Tasks
- [ ] https://github.com/uiowa/uiowa/issues/7686
- [ ] https://github.com/uiowa/uiowa/issues/7687
- [ ] https://github.com/uiowa/uiowa/issues/7688
```

**Comment by cory-skeers** [comment]
Link to the endpoint changes with fewer clicks:
https://github.com/uiowa/uiowa/issues/7550#issuecomment-2098621468

> Removed the /api/active.xml endpoint option.
We couldn't determine significant usage for this endpoint. Consumers are encouraged to switch to the JSON format.
Changed the /api/active.json endpoint to /api/active
It is still JSON but without the file extension. The endpoint won't resolve with .json appended.

> The other changes are in order to follow the JSON 1.0 specification:
The outside wrapper uihphawkalert becomes data.
The inside wrapper hawkalert becomes attributes.
date changes from UNIX timestamp to ISO-8601 YYYY-MM-DDThh:mm:ssTZD
more_info_link has been updated to output the website URL with https:// prefix.
Public Safety would like to deprecate use of e.uiowa.edu going forward.

**Comment by briand44** [comment]
Grooming conversation... Discussed scoping the initial slice to Signage and HC Signage. This will help us understand the size of the work better. We don't want to deploy until launch of the Emergency site.

Related to v2/v3, Sean mentioned maybe there is a way we can make the endpoint configurable so the new code could be deployed in advance of the Emergency site launch. At launch we could do some sort of `blt ume cset`.

**Comment by briand44** [comment]
Closing this in favor of the individual issus in the task list
