### ISSUE TITLE
Ability for webform creators to add CAPTCHA Math Challenge to their webforms

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7657]
# Story

As a SiteNow v3 webform creator, I would like the ability to add additional spam prevention so we can better filter out spam submissions.

# Additional Info

Epic #6470 

Provide ability for webform creators to add a visible Math CAPTCHA to their webforms in addition to the default Honeypot and Antibot spam prevention measures.

A future slice could be to add https://www.drupal.org/project/riddler as another option.

What do we do with hCAPTCHA that is on Admissions?

# Proposed Solution
```[tasklist]
### Tasks
- [x] Leaving the hCAPTCHA bits in the Admissions split, move the other CAPTCHA config out to the default and changing the default challenge type.
- [x] Make sure webmasters the ability to select and implement the math challenge
- [x] Remove the following restriction from Admissions https://github.com/uiowa/uiowa/blob/main/docroot/sites/admissions.uiowa.edu/modules/admissions_core/admissions_core.module#L260-L265
- [x] Since Spam comes up a lot in support, establish some docs to point to on how to place/opt-in to this functionality
```

**Comment by briand44** [comment]
Grooming conversation... Let's leave the implementation of hCAPTCH on Admissions alone for now and move forward with Math CAPTCHA as an option for the service.

**Comment by joewhitsitt** [comment]
Added a draft doc here: https://sitenow.uiowa.edu/documentation/webforms/handling-webform-spam-submissions

**Comment by briand44** [comment]
Maybe we mention that the default challenge is the math challenge as part of the docs in case any folks are confused by the two options?
