### ISSUE TITLE
UI Health Care Branding - CSS Updates to Logo 

### ISSUE THREAD

**Issue by maxwell-freund** [uiowa/uiowa#7670]
Ryan Potter, our UI Health Care Art Director has reviewed the recently pushed code for the UI Health Care Brand on the SIteNow platform and has a few CSS adjustment requests.

The crux of his review and requests can be summarized by a desire to see the IOWA portion of the logo not change, between UIOWA branded sites, and UI Health Care branded sites.

He has followed this practice on other mediums and applications, but strives wherever possible to keep the IOWA in the logo equally weighted. 

This does mean the IOWA HEALTH CARE logo ends up being taller than the IOWA logo, with the second line of text below it, but we do not diminish the visual weight IOWA is given in this approach, and he says it is significantly less jarring visually when moving from an IOWA to an UI HEalth Care branded item, or visa versa.

You can see in screenshots below:

On Site Now with a parent and site org name:
CURRENT IOWA:
![Screenshot 2024-05-13 at 8 31 38 AM](https://github.com/uiowa/uiowa/assets/102074414/692fde29-0624-4172-84f0-0d2c3a7fa226)

CURREN UI HEALTH CARE:
![Screenshot 2024-05-10 at 3 50 12 PM](https://github.com/uiowa/uiowa/assets/102074414/96850d0f-cb2b-4958-9a59-d7cc3ff84868)

If instead of shrinking the IOWA HEALTH CARE Logo to fit within the constraints, we adjust the height of the tab enough to allow for the additional height of HEALTH CARE, we would have the word IOWA remain the same size, and the tab extend tall enough to allow for the word health care below.

Example:
![Screenshot 2024-05-10 at 3 51 37 PM](https://github.com/uiowa/uiowa/assets/102074414/589e6716-3db4-4060-b3ed-1f42656e6d88)

Ryan would like this same logic to be applied if possible to the site title/header design where the site name is in the gold bar.

Current Design Example:

![Screenshot 2024-05-13 at 8 33 36 AM](https://github.com/uiowa/uiowa/assets/102074414/2a8b2543-e83f-4147-bfaf-ecb733e85fe7)
![Screenshot 2024-05-13 at 8 33 22 AM](https://github.com/uiowa/uiowa/assets/102074414/2064fa2f-8a67-4159-b7c5-b26cf7e53612)

If the word IOWA can remain unchanged between the two in sizing, and the black tab extends in height to allow for the word health care, that would be preferred.

Happy to share any thoughts back to Ryan if there are challenges or issues with this requested adjustment. 

```[tasklist]
### Tasks
- [ ] Update branding bar component in UIDS to use UIHC logo
- [ ] Remove custom UIHC CSS from https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/logo.scss
- [ ] Top menu will need to be adjusted https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/menus/top.scss
- [ ] Toggle nav will need to be adjusted https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/menus/toggle-nav.scss
- [ ] Search toggle will need to be adjusted https://github.com/uiowa/uiowa/blob/main/docroot/themes/custom/uids_base/scss/components/search-toggle.scss
```

**Comment by maxwell-freund** [comment]
@briand44 per discussion on Friday, Notes from our Art Director Ryan Potter regarding the logo sizing and requested adjustments here.

**Comment by bspeare** [comment]
@maxwell-freund  Will this approach work?  The screenshots below show "IOWA" the same size and extend the gold bar height to make room for the UIHC logo.

**Logo with "Display inline with the IOWA bar"**

<img width="1543" alt="Screenshot 2024-05-13 at 2 41 12 PM" src="https://github.com/uiowa/uiowa/assets/1036433/bf062e77-4b94-4173-9265-a6bd2f87871d">



**Logo with "Display below the IOWA bar"**

<img width="1549" alt="Screenshot 2024-05-13 at 2 44 26 PM" src="https://github.com/uiowa/uiowa/assets/1036433/79678577-1181-4693-8d53-32877522593e">

**Comment by maxwell-freund** [comment]
@bspeare let me connect with Ryan Potter on these. As he is my green light / red light on all things visual brand, but my personal reaction is yes, thsi is much more in line with what he was saying. 
I will be back shortly.

**Comment by maxwell-freund** [comment]
@bspeare he was free! Yes. 100% the direction he was hoping to see it go. Thanks for the quick addressing. Looks great.

**Comment by bspeare** [comment]
@maxwell-freund thanks for checking!

**Comment by briand44** [comment]
Grooming conversation... We should do this in UIDS first but we can do all of this as part of this slice because likely some back and forth adjustments.
