### ISSUE TITLE
Investigate why entity_usage table on classrooms keeps growing

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7675]
https://iowaweb.slack.com/archives/C0164FNN1PV/p1715283733005369

2+ GB
```[tasklist]
### Tasks
- [ ] Inspect the entity_usage table for clues on how it differs from other websites
- [ ] Step through room import process to see if unecessary ineffieciencies exist
- [ ] https://github.com/uiowa/uiowa/issues/7768
```

**Comment by pyrello** [comment]
Some thoughts from EoD conversation: Classrooms was one of our first importers and its possible that we are showing nodes as needing updated even when no values have changed. I think we encountered this issue when we had to do some refactoring on the buildings importer. So, we could potentially investigate by stepping through an import and spot-checking values to make sure that nothing is getting marked as needing updated when nothing has changed.

**Comment by joewhitsitt** [comment]
Also poked through this a bit earlier and noticed that we inherited some default entity_usage configuration that probably doesn't need to be tracked (crop, aggregator item, url alias, etc.) and could be indirectly inflating the table on all sites.

Uninstalling the module and then running `cim` basically truncates the entity_usage table, but that running the batch update after that seems to cause it to grow again.

**Comment by briand44** [comment]
Grooming conversation... Revisit default configuration for entity usage as mentioned in https://github.com/uiowa/uiowa/issues/7675#issuecomment-2108843560. Import is also something worth digging into as Sean mentioned https://github.com/uiowa/uiowa/issues/7675#issuecomment-2108829405. Gonna take some investigation here to figure out best path forward.

**Comment by cory-skeers** [comment]
Initial glance, it's entity reference usage in particular that is blowing up.

Comparison between classrooms and facilities from a fresh sync:

![Image](https://github.com/uiowa/uiowa/assets/49074566/b7ca33c0-e72c-4a8a-a125-f3c939260b43)



![Image](https://github.com/uiowa/uiowa/assets/49074566/162fd11f-8707-4b61-805c-65dff8d93379)

**Comment by cory-skeers** [comment]
Classrooms entity reference usage by field:

![Image](https://github.com/uiowa/uiowa/assets/49074566/80d8a480-925e-44ff-ad67-186700fba5d9)

facilities as reference:

![Image](https://github.com/uiowa/uiowa/assets/49074566/4d064125-dd87-454f-a40c-0da0790d81a6)

biology as a non-importer reference:

![Image](https://github.com/uiowa/uiowa/assets/49074566/1c1aed73-414f-4156-8575-b16584dfbbf6)

Going to start looking through the importer first. This still may be a great time to look at our entity_usage config and see if we can reduce it across the board, but it looks like there is definitely something else going on with classrooms in particular.

Update: comparison of classrooms table after running an import.
<img width="916" alt="image" src="https://github.com/uiowa/uiowa/assets/49074566/a317523e-51f5-4ef3-947e-772111824fa5">
which seems to add about what we'd expect the whole table (in order of magnitude) to contain on top of what was there.

**Comment by pyrello** [comment]
> which seems to add about what we'd expect the whole table (in order of magnitude) to contain on top of what was there.

Am I understanding correctly that a single import seemed to add about 3K `entity_usage` entries for the `field_room_technology_features` alone?

Also noting here that the revisions UI is acting funky on this site:
![Screenshot 2024-06-03 at 12 53 45 PM](https://github.com/uiowa/uiowa/assets/709009/f1f124a7-f462-42af-a912-cc60e3638271)

**Comment by joewhitsitt** [comment]
>Also noting here that the revisions UI is acting funky on this site

When we turned revisions down to 3 from 10, I noticed that. I figured with enough cron jobs it would clear up, but apparently not.

**Comment by pyrello** [comment]
Also noting that the Classrooms import process doesn't entirely adhere to our established code design pattern. It implements an extending class for `Drupal\uiowa_core\EntityItemProcessorBase` but not `Drupal\uiowa_core\EntityProcessorBase`. This makes it a little harder to follow the logic and determine whether we might actually be updating the node when we don't need to. I suspect that is what is happening since I wouldn't expect classrooms to change to the tune of 3k updated room technology features per import.

**Comment by cory-skeers** [comment]
> > Also noting here that the revisions UI is acting funky on this site
> 
> When we turned revisions down to 3 from 10, I noticed that. I figured with enough cron jobs it would clear up, but apparently not.

So, we need to be looking at this too...

<img width="472" alt="image" src="https://github.com/uiowa/uiowa/assets/49074566/9982784d-5926-46f1-a054-fa1ec7f2c4ce">

In the current state, every room is being treated as needing update on every import (fixed in #7745), and it looks like in addition to that, old revisions are being kept around, along with their usage statistics. Re-generating usages after clearing it out still ends up blowing the table up pretty large as a result (not sure how large yet, because it is taking a very long time to generate...)

**Comment by cory-skeers** [comment]
Just adding a note here, the work in #7745 reduces the classrooms.uiowa.edu (locally synced) db size from 2095.46 MB to 214.81 MB. 🚀
