### ISSUE TITLE
Launch/Post-launch tasks for Emergency v3 site

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7689]
Launch planned for July 31st, 2024 in the am. There will be a production test Hawk Alert on Aug 1st at 10am.

```[tasklist]
### Tasks
- [x] Need to have hostmaster update DNS for e.uiowa.edu to point to Vulture
- [x] Need to deploy Signage code `update_signage_hawkalert` for both signage and healthcare signage to work with new endpoint - Update Signage/HC Signage to consume Hawk Alerts from new Emergency endpoint #7686
- [x] Need to deploy SiteNow v1 code `update_uiowa_alerts` to uiowa701-3 to work with new endpoint https://github.com/uiowa/uiowa/issues/7688
- [ ] https://github.com/uiowa/uiowa/issues/7772
- [x] Verify everything is working during the test Hawk Alert on Aug 1st
- [x] If test goes flawlessly, ask about removing the D7 site
- [ ] https://github.com/uiowa/uiowa/issues/7778
```

**Comment by briand44** [comment]
blocked until 7/31/24

**Comment by joewhitsitt** [comment]
With https://github.com/uiowa/uiowa/pull/7949 deployed this afternoon, I am no longer seeing CORS console errors as SiteNow and Signage try to ping emergency.uiowa.edu

Based on successful testing previously with each of the development pieces I believe this should resolve any remaining issues related to this work.

Reached out in #redesign-police to pitch the idea of another test soon to confirm.

**Comment by briand44** [comment]
Another test hawk alert happened and the hawk alert did appear on SiteNow sites and Signage. We should make a backup of the D7 site but then can remove. I'll add this to the site removal issue. Closing this as we can address #7778 separately.
