### ISSUE TITLE
June Dependency Updates

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7711]
We should try to review and merge in dependency updates on a monthly basis. Until this is automated more, here is a guide:

- Review the [outstanding dependency updates](https://github.com/uiowa/uiowa/pulls?q=is%3Aopen+is%3Apr+label%3Adependencies) as well as the Acquia report and add a list of current ones below.
- Dependencies related to our frontend build tools (not executed on the websites) are usually safe to merge as-is but might cause issue with other packages. Check travis build for messages related to `blt frontend`.
- Each @dependabot PR can be worked on separately. Each dependency PR you merge will cause merge conflicts with all the other ones. As long as you don't alter the branch (e.g. merge in `main`, push a commit), you can fix the merge conflicts by running `@dependabot rebase`.
- If a @dependabot PR does require some type of modification (e.g. removing a patch, updating incompatible code), it is okay to make those changes directly in relevant PR. However, it is a good idea to wait until you have merged all the other "easy" dependency PRs first because you will lose the ability to use `@dependabot rebase` to have the PR's merge conflicts resolved.
- Periodically check [locked dependencies](https://github.com/uiowa/uiowa/blob/main/README.md#locked-packages) for new versions. Make notes about why a dependency was/is locked in the repo Readme.
- Review the changelog for each version we are jumping to and the versions in-between. Make note of certain functionality in our codebase that is using the functionality for testing instructions later.
- It can also be helpful to review the git diff comparison between the old version and the new one to see how extensive the code changes are and to get an idea of what things you might need to test.
- Use https://github.com/uiowa/uiowa#updating-dependencies as a guide to test for update hooks, configuration changes and commit. This command is helpful if there are a lot of configuration changes across feature/site splits: https://github.com/uiowa/uiowa/blob/main/blt/src/Blt/Plugin/Commands/ConfigSplitCommands.php
- Dependency PR's with update hooks or requiring a cache rebuild may require off-hours deployment. If this is the case, add the appropriate label to the PR.
- Once this issue is completed, copy these notes to the next month's issue and introduce it in parking lot.

# Recent Acquia Report

| Package Name                          | Package Type  | Current Version | Installed Version | Security Version | Latest Version | Update Type | Notes     |
|---------------------------------------|---------------|-----------------|-------------------|------------------|----------------|-------------|-----------|
| drupal/core                           | drupal-core   |                 | 10.2.5            |                  | 10.3.0-beta1   | minor       | postponed |
| drupal/acquia_connector               | drupal-module | ^4.0            | 4.0.5             |                  | 4.0.6          | patch       |           |
| drupal/acquia_purge                   | drupal-module | ^1.0            | 1.3.0             |                  | 1.4.0          | minor       |           |
| drupal/antibot                        | drupal-module | ^2.0            | 2.0.2             |                  | 2.0.3          | patch       |           |
| drupal/better_exposed_filters         | drupal-module | ^6.0            | 6.0.3             |                  | 6.0.6          | patch       |           |
| drupal/big_pipe_sessionless           | drupal-module | ^2.0            | 2.1.0             |                  | 2.2.0          | minor       |           |
| drupal/config_filter                  | drupal-module | ^2.2            | 2.4.0             |                  | 2.6.0          | minor       |           |
| drupal/config_inspector               | drupal-module | ^2.0            | 2.1.4             |                  | 2.1.9          | patch       |           |
| drupal/config_split                   | drupal-module | ^2.0@RC         | 2.0.0-rc4         |                  | 2.0.1          | patch       |           |
| drupal/cshs                           | drupal-module | ^4.0            | 4.0.0             |                  | 4.0.2          | patch       |           |
| drupal/devel                          | drupal-module | ^5.1            | 5.1.2             |                  | 5.2.1          | minor       |           |
| drupal/diff                           | drupal-module | ^1.1            | 1.1.0             |                  | 1.3.0          | minor       |           |
| drupal/easy_breadcrumb                | drupal-module | ^2.0            | 2.0.5             |                  | 2.0.6          | patch       |           |
| drupal/entity_browser                 | drupal-module | ^2.4.0          | 2.9.0             |                  | 2.10.0         | minor       |           |
| drupal/entity_print                   | drupal-module | ^2.6            | 2.13.0            |                  | 2.14.0         | patch       |           |
| drupal/entity_reference_revisions     | drupal-module | ^1.5            | 1.10.0            |                  | 1.11.0         | patch       |           |
| drupal/externalauth                   | drupal-module |                 | 2.0.3             |                  | 2.0.5          | patch       |           |
| drupal/file_mdm                       | drupal-module | ^3.0            | 3.0.0             |                  | 3.1.0-beta2    | minor       | hold?     |
| drupal/focal_point                    | drupal-module | ^2.0            | 2.0.2             |                  | 2.1.0          | minor       |           |
| drupal/fragments                      | drupal-module | ^2.0            | 2.1.0-rc1         |                  | 2.1.0          | patch       |           |
| drupal/fullcalendar_view              | drupal-module | ^5.0            | 5.1.13            |                  | 5.1.14         | patch       |           |
| drupal/geofield                       | drupal-module | ^1.53           | 1.55.0            |                  | 1.57.0         | patch       |           |
| drupal/google_tag                     | drupal-module | ^1.6            | 1.6.0             |                  | 1.7.0          | minor       | [caution](https://github.com/uiowa/uiowa/issues/7538)   |
| drupal/imagecache_external            | drupal-module | ^3.0            | 3.0.1             |                  | 3.0.3          | patch       |           |
| drupal/imagemagick                    | drupal-module | ^3.6            | 3.6.0             |                  | 3.7.0          | minor       |           |
| drupal/inline_entity_form             | drupal-module | ^1.0.0-rc2      | 1.0.0-rc15        |                  | 1.0.0-rc17     | patch       | hold?     |
| drupal/layout_builder_lock            | drupal-module | ^1.1            | 1.2.0             |                  | 1.4.0          | minor       |           |
| drupal/layout_builder_restrictions    | drupal-module | ^2.6            | 2.19.0            |                  | 2.20.0         | minor       |           |
| drupal/leaflet                        | drupal-module | ^10.2           | 10.2.7            |                  | 10.2.14        | patch       |           |
| drupal/linkit                         | drupal-module | ^6.1@RC         | 6.1.2             |                  | 6.1.4          | patch       |           |
| drupal/media_entity_facebook          | drupal-module | ^4.0            | 4.0.2             |                  | 4.0.3          | patch       |           |
| drupal/media_entity_file_replace      | drupal-module | ^1.0@beta       | 1.1.0             |                  | 1.2.0          | minor       |           |
| drupal/menu_block                     | drupal-module | ^1.7            | 1.10.0            |                  | 1.11.0         | patch       |           |
| drupal/menu_per_role                  | drupal-module | ^1.2            | 1.5.0             |                  | 1.6.0          | minor       |           |
| drupal/migrate_plus                   | drupal-module | ^6.0            | 6.0.1             |                  | 6.0.2          | patch       |           |
| drupal/moderated_content_bulk_publish | drupal-module | ^2.0            | 2.0.29            |                  | 2.0.31         | patch       |           |
| drupal/node_revision_delete           | drupal-module | ^2.0@alpha      | 2.0.0-alpha2      |                  | 2.0.0-rc1      | patch       |           |
| drupal/override_node_options          | drupal-module | ^2.4            | 2.7.0             |                  | 2.8.0          | minor       |           |
| drupal/paragraphs                     | drupal-module | ^1.10           | 1.16.0            |                  | 1.17.0         | patch       |           |
| drupal/reroute_email                  | drupal-module | ^2.1            | 2.2.1             |                  | 2.3.0-rc1      | minor       | hold?     |
| drupal/scheduler                      | drupal-module | ^2.0            | 2.0.1             |                  | 2.0.3          | patch       |           |
| drupal/search_api                     | drupal-module |                 | 1.30.0            |                  | 1.34.0         | patch       |           |
| drupal/simple_sitemap                 | drupal-module | ^4.0            | 4.1.6             |                  | 4.1.9          | patch       |           |
| drupal/siteimprove                    | drupal-module | ^2.0            | 2.0.1             |                  | 2.0.2          | patch       |           |
| drupal/smart_date                     | drupal-module | ^4.0.3          | 4.0.3             |                  | 4.1.3          | minor       |           |
| drupal/smart_trim                     | drupal-module | ^2.0            | 2.1.0             |                  | 2.1.1          | patch       |           |
| drupal/sophron                        | drupal-module |                 | 2.0.2             |                  | 2.1.0-rc1      | minor       |           |
| drupal/stage_file_proxy               | drupal-module | ^2.1            | 2.1.1             |                  | 2.1.4          | patch       |           |
| drupal/symfony_mailer                 | drupal-module | ^1.3            | 1.3.2             |                  | 1.4.1          | minor       |           |
| drupal/token                          | drupal-module |                 | 1.12.0            |                  | 1.14.0         | patch       |           |
| drupal/views_bulk_operations          | drupal-module | ^4.1            | 4.2.5             |                  | 4.2.6          | patch       |           |
| drupal/webform                        | drupal-module | ^6.2@beta       | 6.2.0-rc2         |                  | 6.2.2          | patch       |           |

# Updates in-scope

```[tasklist]
### Contrib
- [ ] https://github.com/uiowa/uiowa/pull/7075
- [ ] https://github.com/uiowa/uiowa/pull/7079
- [ ] https://github.com/uiowa/uiowa/issues/4777
- [ ] https://github.com/uiowa/uiowa/pull/7321
- [ ] https://github.com/uiowa/uiowa/pull/7322
- [ ] https://github.com/uiowa/uiowa/pull/7507
- [ ] https://github.com/uiowa/uiowa/issues/7041
- [ ] https://github.com/uiowa/uiowa/issues/7709
- [x] [drupal/antibot](https://www.drupal.org/project/antibot/releases/2.0.3) apparently fixes recent issue that was letting some spam through @joewhitsitt
- [x] [drupal/smart_date](https://www.drupal.org/project/smart_date/releases/4.1.3) needed for brand date adoption @joewhitsitt
- [ ] https://github.com/uiowa/uiowa/pull/7751
- [ ] https://github.com/uiowa/uiowa/pull/7748
- [ ] https://github.com/uiowa/uiowa/pull/7747
- [ ] https://github.com/uiowa/uiowa/pull/7749
- [ ] https://github.com/uiowa/uiowa/pull/7758
- [ ] https://github.com/uiowa/uiowa/pull/7760
```

```[tasklist]
### NPM
- [ ] https://github.com/uiowa/uiowa/pull/7424
- [ ] https://github.com/uiowa/uiowa/pull/7641
```

**Comment by joewhitsitt** [comment]
I captured the dependabots at the time of issue creation and picked out a couple contrib projects that I think it would be good to focus on. Obviously there are more than what is in the task list, but most of them are patch type updates and can probably be addressed as needed and not be the main focus of this slice.

I put together a PR with the smart_date update, but given the snag I hit on Friday, it might make sense to separate that update out from the rest of that PR.

The NPM list is mostly JDI, but hit a snag with gulp-postcss with node versions and there might be more.

**Comment by briand44** [comment]
Grooming convo... We should avoid trying to use a single PR for all of this. Good issue for multiple devs and/or pairing. It might make sense to separate the smart date update out based on Joe's comment https://github.com/uiowa/uiowa/issues/7711#issuecomment-2135421102.

**Comment by joewhitsitt** [comment]
unassigning for the weekend.

**Comment by briand44** [comment]
holding on photoswipe and coding standards, gulp-postcss and can address separately.

**Comment by pyrello** [comment]
I think we meant to close this.
