### ISSUE TITLE
Remove memory limit increases for specific paths

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7716]
# Story

As a webteam, we would like to remove our specific menu path memory increases since we have updated our memory limit to 256 at the application level for each application.

Blocked until all apps are set to 256M php memory limit. #7525 

This is one place I found where we are updating memory. Not sure if there were any other places.
https://github.com/uiowa/uiowa/blob/fc59a99dc8283830bf94282804ede039d552d683/docroot/sites/settings/global.settings.php#L83-L85
```[tasklist]
### Tasks
- [x] Remove the code ^^
- [x] Search for any additional instances of "256M" in our codebase where we may be setting memory based on a path
- [x] Remove any additional instances found
- [x] Test Engineering menu system and possibly Whitman Web to ensure working as expected.
```

**Comment by briand44** [comment]
Grooming conversation... Not sure if there are other instances where we are setting memory in code based on a path but might be good to search the codebase for "256M" to see. Test engineering, possibly Whitman Web to make sure those are still working fine.

**Comment by bspeare** [comment]
Just tested on engineering.uiowa.edu and getting this log message after trying to edit a menu item `php-error web-33202 [15-Aug-2024 21:04:24 UTC] PHP Warning: Unknown: Input variables exceeded 3000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0 request_id="v-f30edb1e-5b49-11ef-af57-072e735bf571" `

Do we revert the change and deploy a hotfix?

**Comment by briand44** [comment]
>Do we revert the change and deploy a hotfix?

Not sure if that would resolve this. Do we know that this wasn't already an issue prior to the change?

**Comment by bspeare** [comment]
I helped with a support ticket last week and the engineering menu was working then.

**Comment by joewhitsitt** [comment]
I think reverting for now would be good. This was originally part of https://github.com/uiowa/uiowa/issues/1996 and the direct memory_limit fix here solved it for Engineering. Not sure the difference between the app memory_limit and this route specific memory_limit.

Our max_input_vars is already at 3000 for the app and I think I recall that we want to avoid going much beyond that.

**Comment by bspeare** [comment]
It looks like the same issue is happening on engineering after the deployment.   Try to adjust the menu position/weight of a menu item and save the page. 

<img width="1537" alt="Screenshot 2024-08-21 at 3 45 36 PM" src="https://github.com/user-attachments/assets/969a6f2d-2fed-4afc-8ddd-4a1227e9d2cf">

**Comment by joewhitsitt** [comment]
i feel like we can remove it again (knowing it wasn't the magic) and then refocus solving this back in https://github.com/uiowa/uiowa/issues/1996 (:cough: big_menu)

**Comment by bspeare** [comment]
Closing this now that the memory increase has been removed and https://github.com/uiowa/uiowa/issues/1996 is the issue for engineering.
