### ISSUE TITLE
Update Drupal Core 10.3.x

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7753]
https://www.drupal.org/project/drupal/releases/10.3.2

plus core-composer-scaffold

# Proposed solution

To check if all our dependencies are compatible with Drupal 10.3, run the following command:

```
ddev composer prohibits drupal/core 10.3
```

Once all dependencies that need to be upgraded to be compatible and can be upgraded ahead of time have been upgraded, we can run the following command:

```
ddev composer require drupal/core-recommended:^10.3 drupal/core-composer-scaffold:^10.3 --update-with-all-dependencies
```

If there are problems with the above command, it is also possible to update the version constraints for the above packages in composer.json and then run

```
ddev composer update --lock
```

```[tasklist]
### Tasks
- [x] Fix deprecations (only required, mark warnings for later issues.)
- [x] Update default config `ddev blt di --site=default && ddev drush @default.local cex`
- [x] Update config split config ⤵
- [x] - feature splits first `ddev blt uiowa:usplits:feature`
- [x] - Then site splits `ddev blt uiowa:usplits:site `
- [x] Review file changes to decide on necessary testing [Alan]
- [x] Review P2LB config updates to decide whether to keep or ignore them
- [ ] Fix tests (potentially not going to be needed) `ddev phpunit -c docroot/core/ --verbose --debug docroot/modules/custom/`
- [x] Fix PHPCS updates
```

```[tasklist]
### Updated patches to test
- [x] Responsive image: Go to https://sandbox.prod.drupal.uiowa.edu/small-and-medium-responsive-images and check the small image style and confirm that the fallback image sizes are `width="384" height="384" `
- [x] A patch, "Expose Layout Builder data to REST and JSON:API" was updated related to https://www.drupal.org/project/drupal/issues/2942975 This was introduced to provide layout builder flavored default content. To test, one should run a site install (it should be successful) and try exporting the default content again, there should be no major changes besides revision numbers and such. 
- [x] A patch, "ImageItem::getUploadValidators() should be the source of truth for validating uploaded images," was updated related to https://www.drupal.org/project/drupal/issues/3008292      This was introduced to enforce max image sizes. Media was skipping over it. To test, upload an image beyond our max image size. You should get the message it was sized down, but now inspect the original that was uploaded it should have actually been sized down.
- [x] A patch, "Support third party settings for components within a section," was updated related to https://www.drupal.org/project/drupal/issues/3015152      This was introduced to make our unique id field on blocks a reality and we have run with it since. To test, make sure you are still able to see/add/edit unique ids on our blocks.
- [x] Patch for "Breadcrumbs block within Layout Builder causes errors when moving blocks" or "Fix LB contextual links after dragging block to new section" https://www.drupal.org/project/drupal/issues/3160785 - Try editing https://sandbox.local.drupal.uiowa.edu/node/586/layout and move the block to a section above the section it's in and then move the block way below to the bottom region
- [x] Views Block Display skips preBlockBuild() call on ajax rebuild. Test list blocks with non-default LB style options and/or hidden fields and filters AND a pager to check that second "page" results match the expected block settings.
```

```[tasklist]
### Things to fix
- [x] Drupal messages no longer appear to be using alert component styles
- [x] Media library console error: `RuntimeException: linkit_media_library.opener.editor must be an instance of Drupal\media_library\MediaLibraryOpenerInterface in Drupal\media_library\OpenerResolver->get() (line 46 of /var/www/html/docroot/core/modules/media_library/src/OpenerResolver.php).` solved by https://www.drupal.org/project/linkit_media_library/issues/3461637
```
```[tasklist]
### Changes to check
- [x] Config now wants `true` or `false` instead of `1` or `0`. ([example](https://github.com/uiowa/uiowa/pull/8133/files#diff-7c611824bf25aa3ec43edddc7bb3388146a5a74ec54b814a18887c0e3a2ca4fdL4-L8)) [Alan]
- [x] Config now wants `null` instead of an empty string. ([example](https://github.com/uiowa/uiowa/pull/8133/files#diff-5f07830815dcda5db1ba1afcf7700bf5c47fcc9fa338451d974cc543d2df5d51L39-L45))
- [x] PHP no longer wants optional parameters in the middle of argument definitions. ([example](https://github.com/uiowa/uiowa/pull/8133/files#diff-c881dcdf122b0b68cea8d3731d01e360d728de9449c69e293767cb93ffd75d4bL93-L99))
```

```[tasklist]
### Weird config to check
- [x] SPAA - sync and export the site config. Completely deletes config_split.patch.* and replaces with full split. This happens on main as well. Documented at https://github.com/uiowa/uiowa/issues/8137.
- [x] Wellbeing - views page list block is being exported instead of config_split patch.  Documented at https://github.com/uiowa/uiowa/issues/8137.
- [x] HR -  Documented at https://github.com/uiowa/uiowa/issues/8137.
- [x] config/default/editor.editor.* config changes
- [x] P2lb
- [x] sitenow_intranet, uiowa.edu siteimprove permission changes
- [x] Admissions events split changes
- [x] Admissions areas of study view: plugin_id: numeric -> plugin_id: entity_target_id
- [x] ITS config changes
- [x] ITS views.view.service_related_articles.yml: plugin_id: numeric -> plugin_id: entity_target_id
- [x] Warning: Undefined array key "type" in Drupal\field_ui\Form\ITS alert: https://its.uiowa.ddev.site/admin/structure/types/manage/alert/form-display - EntityDisplayFormBase->buildFieldRow() (line 362 of core/modules/field_ui/src/Form/EntityDisplayFormBase.php).  This happens in 10.2 as well.
- [x] What to do about https://www.drupal.org/node/3223395#s-layout-builder-expose-all-field-blocks?
```

**Comment by joewhitsitt** [comment]
Thinking we might have to speed up our 10.3 upgrade, I started capturing all of the things I've heard from Higher-Ed Drupal and Drupal Slack communities about how the update went for others. Some notable changelog/issues we might want to check against:

- [x] https://www.drupal.org/node/3450770
- [x] https://www.drupal.org/project/drupal/issues/3456176
- [x] https://www.drupal.org/project/drupal/releases/10.3.0#known-issues
- [x] increased logging that captures user navigation within a site (authenticated)
- [x] ckeditor toolbar floats or is hidden behind three dots?!
- [x] linkit_media_library - https://www.drupal.org/project/linkit_media_library/issues/3329877#comment-15739496

**Comment by briand44** [comment]
Grooming conversation... See what composer yells at us about. It was mentioned we could update to php 8.2 in dev as part of this. Probably contrib updates needed but composer should let us know.

**Comment by joewhitsitt** [comment]
This just got fixed and ported to 10.3.x:

https://www.drupal.org/project/drupal/issues/3457781

We will be able to undo this change then: https://github.com/uiowa/uiowa/pull/8097

**Comment by GaryRidgway** [comment]
Lots of issues with [functions like this](https://stackoverflow.com/questions/65297279/required-parameter-xxx-follows-optional-parameter-yyy) right now, going to start to troll through and fix them.

I will start by making a regex string to find all instances of functions with default parameters before a comma, then search with find in files with that to get a list of functions that need to change.

**Comment by GaryRidgway** [comment]
> Lots of issues with [functions like this](https://stackoverflow.com/questions/65297279/required-parameter-xxx-follows-optional-parameter-yyy) right now, going to start to troll through and fix them.
> 
> I will start by making a regex string to find all instances of functions with default parameters before a comma, then search with find in files with that to get a list of functions that need to change.

This is now done, I used this regular expression (`function [[:alnum:]\_]*.*=.*,[^=]*\)`) to find all instances in uiowa.

**Comment by GaryRidgway** [comment]
getting a lot of config errors, trying to investigate what's going on.

**Comment by bspeare** [comment]
New experimental navigation bar looks good:

<img width="1717" alt="Screenshot 2024-10-09 at 10 49 19 AM" src="https://github.com/user-attachments/assets/c93f2f30-0439-4de8-b056-97cdd3e3da02">

**Comment by pyrello** [comment]
I'm going to take a look at the deprecation errors that are blocking the build to see if there is a way around having to fix them all to move ahead.

**Comment by pyrello** [comment]
This seems to suggest a possible path forward for ignoring deprecated code warnings temporarily: https://phpstan.org/error-identifiers/method.deprecated

**Comment by joewhitsitt** [comment]
capturing from Slack:

> i recently saw something that the sidebar menu settings changed and we might want to check to see that the contrib we layered on top is still functioning as expect menu_link_weight, cshs

anyone notice anything related to taxonomy revisions? https://www.drupal.org/project/drupal/issues/2936995 i thought i was d11 but I am seeing stuff about it in 10.3. https://github.com/uiowa/uiowa/pull/7801#issuecomment-2168184660

**Comment by pyrello** [comment]
> capturing from Slack:
> 
> > i recently saw something that the sidebar menu settings changed and we might want to check to see that the contrib we layered on top is still functioning as expect menu_link_weight, cshs
> 
> anyone notice anything related to taxonomy revisions? https://www.drupal.org/project/drupal/issues/2936995 i thought i was d11 but I am seeing stuff about it in 10.3. [#7801 (comment)](https://github.com/uiowa/uiowa/pull/7801#issuecomment-2168184660)

It would make sense that it applies to D10.3 because the first version of 11.0 and 10.3 should be functionally identical with the only difference being deprecated code that hasn't been removed. At least that was my understanding of their policy the last time I read it.

**Comment by GaryRidgway** [comment]
For the `Layout Builder Expose All Field Blocks` issue, I believe the we can just create a follow up issue to remove that module at a later time.[ It was added to ensure current functionality would not break](https://www.drupal.org/node/3223395#s-layout-builder-expose-all-field-blocks:~:text=The%20module%20is%20automatically%20installed%20on%20sites%20that%20have%20the%20Layout%20Builder%20module%20installed%20so%20that%20the%20existing%20behavior%20is%20preserved.), so its not needed to remove it right away.

**Comment by GaryRidgway** [comment]
I've fixed most of the deprecation errors, but we should at some point fix the `'#\Drupal calls should be avoided in classes, use dependency injection instead#'` warning.

You can find the instances of this by commenting out its line in the `ignore` section of the `phpstan.neon` file and run `ddev blt tests:deprecated`

**Comment by pyrello** [comment]
> I've fixed most of the deprecation errors, but we should at some point fix the `'#\Drupal calls should be avoided in classes, use dependency injection instead#'` warning.
> 
> You can find the instances of this by commenting out its line in the `ignore` section of the `phpstan.neon` file and run `ddev blt tests:deprecated`

Unless it become required to fix the dependency injection warning (it becomes an error), I don't think we need to fix it until we are ready to go through and understand what we are doing. "Fixing" these can require significant rewrites to class files to pull in services and utilize them instead of using a class directly.
