### ISSUE TITLE
LAW INRC Epic

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7755]
- Local Events
- Grants content type and filterable display
- The Iowa Register of Accountability - nonprofits - content type and filterable display

```[tasklist]
### Tasks
- [ ] https://github.com/uiowa/uiowa/issues/7821
- [ ] https://github.com/uiowa/uiowa/issues/7844
- [ ] https://github.com/uiowa/uiowa/issues/7846
- [ ] https://github.com/uiowa/uiowa/issues/7895
- [ ] https://github.com/uiowa/uiowa/issues/7896
- [ ] https://github.com/uiowa/uiowa/issues/7906
- [ ] #7900
- [ ] https://github.com/uiowa/uiowa/issues/7914
- [ ] https://github.com/uiowa/uiowa/issues/7915
- [ ] https://github.com/uiowa/uiowa/issues/7963
- [ ] https://github.com/uiowa/uiowa/issues/7974
- [ ] https://github.com/uiowa/uiowa/issues/7994
- [ ] https://github.com/uiowa/uiowa/issues/7907
- [ ] https://github.com/uiowa/uiowa/issues/8010
- [ ] https://github.com/uiowa/uiowa/issues/8007
- [ ] https://github.com/uiowa/uiowa/issues/7964
```

**Comment by briand44** [comment]
A few notes from meeting with LAWINRC.

**Events**
They would like to have a calendar display similar to their current site - https://inrc.law.uiowa.edu/events#!events-calendar
Map hasn't been as useful as they thought. Probably not needed going forward.

**Grants**
Existing functionality for Grants works well for them. Have a webform where visitors can submit grants and then copied over to grant content type. Site search is often used. They mentioned an import from a spreadsheet would be useful. They mentioned having to ctrl/cmd + click to select multiple not super easy for folks.
