### ISSUE TITLE
Academic Calendar list, take 2

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7788]
As a Registrar site owner, I would like the ability to display academic dates in a list format for better usability and accessibility.

# Additional Info

Epic https://github.com/uiowa/uiowa/issues/7257

They would like to have both #4936 and list display but also brought up accessibility and want to make sure this is an accessible solution. Joe asked if we could do away with the calendar display and they sounded like they would like to keep it if possible. Mentioned that some peer institutions only have list view. 

D7 implementation is using Full Calendar https://registrar.uiowa.edu/academic-calendar

Currently we are showing the current session + 4 sessions. Going forward they would like to display the current session + 5 sessions.

category filter - default to "All Student Dates" - Josh thought we are currently suppressing some date categories and wants to start with the same categories they have now.

Need ability to show subsessions

Need to look at the datelookup "Is Web Display" = Yes and "is reviewed" = yes - may be "is print" in MAUI
display date, web description, session/subsession

when session ends auto updates to show current session + 5 - Registrar was going to chat some more about this.

# Proposed Solution
```[tasklist]
### Tasks
- [ ] Review D7 implementation in 703 codebase in `docroot/profiles/sitenow/modules/custom/uiowa_maui`
- [ ] Add a controller class (see `uiowa_search` for an example)
- [ ] Add a method to the controller to handle calling the API, processing the results, and caching them for 24 hours. Method should be able to accept start/end dates to filter dates to between those bounds. Results should be return as JSON
- [ ] Add a `*.routing.yml` file with a route set up to point at the controller method
- [ ] Add a JS file for invoking fullcalendar and getting results from the route set up in previous steps. Add a `*.libaries.yml` file and add an entry for the JS file.
- [ ] Add a custom block class for rendering the calendar
```

**Comment by pyrello** [comment]
I think we should utilize a route controller to encapsulate logic to allow for filtering result sets based on a start and end date as a result set that can be cache. So, for example, if someone goes to June 2024, we would get a request to the route controller with the start date set to 06-01-2024 and the end date set to 06-30-2024. We could cache those results for an appropriate amount of time to speed up the display of the calendar and paging between months. The route + params would return a JSON result that can be parsed by FullCalendar's AJAX capabilities.

**Comment by briand44** [comment]
Grooming conversation... Sean is recommending an approach similar to D7 solution but with a route controller. Could cache for 24 hours. Scope this to list display by month using Full Calendar. Category filter and subsession options aren't required for this slice unless we learn we need them to produce a list. Limiting results to only certain categories can be a future slice as well. Several methods that pull data from the MAUI API already exist as part of the work to display "Upcoming Deadlines" we did for Grad College as part of the uiowa_maui port.

**Comment by pyrello** [comment]
I cleaned up #7781 so we can use that.

**Comment by bspeare** [comment]
What do we think about replacing the bootstrap popovers from D7 with the popover HTML element? https://caniuse.com/?search=popover.  It recently became part of Baseline 2024: https://web.dev/blog/popover-api.    There are certainly other libraries that we could incorporate as well, but this seems like pretty good timing to use popover.

**Comment by joewhitsitt** [comment]
I'd be fine with this, but wondering if you have considered using built-in fullcalendar stuff for this though. https://fullcalendar.io/docs/event-display

**Comment by bspeare** [comment]
Thanks @joewhitsitt, I will try that first!

**Comment by bspeare** [comment]
Looking at other University sites and I'm not seeing a lot of calendar displays.   

List:
- https://www.nyu.edu/students/student-information-and-resources/registration-records-and-graduation/academic-calendar.html
- https://registrar.temple.edu/academic-calendar/2024-2025-academic-calendar
- https://registrar.brown.edu/academic-calendar/current-academic-calendar#fall-2024
- https://www.registrar.vt.edu/dates-deadlines/academic-calendar.html
- https://registrar.unl.edu/academic-calendar/
- https://registrar.cornell.edu/calendar/2023-2024
- https://registrar.osu.edu/academic-calendar/
- https://onestop.umn.edu/calendar/academic-calendar?terms=Summer%202024
- https://registrar.tamu.edu/academic-calendar
- https://www.colorado.edu/academics/academic-calendar
- https://www.swarthmore.edu/academics/academic-calendar
- https://studentservices.stanford.edu/calendar/academic-dates/stanford-academic-calendar-2023-24
- https://www.kenyon.edu/academics/academic-calendar/
- https://ras.lehigh.edu/current-students/academic-calendar
- https://secfac.wisc.edu/academic-calendar/
- https://registrar.illinois.edu/academic-calendars/spring-academic-calendar-24/
- https://ro.umich.edu/calendars?field_calendar_type_target_id%5B1%5D=1&field_term_target_id=168&title=
- https://reg.msu.edu/roinfo/calendar/academic.aspx
- https://registrar.nd.edu/calendars/
- https://calendars.registrar.indiana.edu/official-calendar/

Calendar:
- https://registrar.princeton.edu/academic-calendar-and-deadlines
- https://www.evergreen.edu/academic-calendar

Ideally, I think what I would like us to do is move away from the calendar implementation and work on improving our list displays instead.  We could invest in https://github.com/uiowa/uiowa/issues/2727 and improving the display of our event lists like https://oniowa.uiowa.edu/events and event page designs. 

Full Calendar feels like a dated solution here and not a great solution for mobile first traffic.

**Comment by pyrello** [comment]
Some thoughts after looking through the above examples:
- If we are going to have a monthly calendar style view, we probably don't want it to be the default thing showing when you hit the page because it doesn't really work for mobile. https://www.evergreen.edu/academic-calendar gets this right (and also allows for seeing the bad mobile experience that FullCalendar creates)
- Based on the above, we would only be developing the monthly calendar view for non-mobile visitors, meaning we are getting less value for the time we spend on it vs. a good list view.
- I'm not sure who day and week views are for. If someone can find the information they are looking for in the list or a monthly calendar view, I doubt they are clicking into the day or week views to see it there.
- The monthly calendar view is not great for quickly finding what you are looking for. That format forces the information to be crunched into a tiny box and the default way that FullCalendar handles that is to truncate the text. This makes it harder to scan the page and quickly find what you are looking for. If you can't tell that an item is the item you are looking for then it forces you to hover or click on the item for more information, which isn't great considering that with a list you can just scroll until you find it.
- Conversely, the list view doesn't require any such tradeoffs and allows for a scannable list of items that shows all the relevant information.

*Edit:* To be clear, I'm for ditching Full Calendar and embracing a list-centric vision for displaying sets of dates going forward. If we must display a monthly calendar style rendering with a table of 7 days, then I think that should be a secondary display that people can get to from the main list display.

**Comment by joewhitsitt** [comment]
Good points. Add https://www.registrar.psu.edu/academic-calendars/index.cfm to the list group.

Seeing a lot of .ics/rss options with these as well so folks can can consume it in a calendar display.

Here is a full calendar issue that notes some of the concerns and a link to a milestone:
https://github.com/fullcalendar/fullcalendar/issues/2536 https://github.com/fullcalendar/fullcalendar/milestone/47

**Comment by bspeare** [comment]
I put together a local working mockup of what this might look like using a list that we could possibly use for next week. 

<img width="1144" alt="Screenshot 2024-06-21 at 2 25 15 PM" src="https://github.com/uiowa/uiowa/assets/1036433/355fa768-ca42-4b92-a04c-806485a99c11">

**Comment by joewhitsitt** [comment]
i appreciate the date duplication in this case. while the circle is a visual treat, my brain prefers reading the one line string.

**Comment by cory-skeers** [comment]
> i appreciate the date duplication in this case. while the circle is a visual treat, my brain prefers reading the one line string.

Agreed. I like the circle visually, and think it works well if the use case is scanning dates generally which is a bit more difficult when picking them out from the middle of cards. And then when looking at an individual item, everything is nestled together nicely.

I'm a fan.
