### ISSUE TITLE
Run ITS migrations in prod

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7791]
Run on 9/3/2024.

 
- Run Infocenter/Service migration in prod
  - James to delete service content Friday 9/30/24 after training.
- Run support article migration in prod
  - James to delete support article content Friday 9/30/24 after training.
```[tasklist]
### Tasks
- [x] review original PR for any notes https://github.com/uiowa/uiowa/pull/7524
- [x] run local just to refamilarize/test
- [x] Verify service and support article content removed from v3 prod
- [x] db backup v3 ITS prod
- [x] Notify Adrienne/James we are starting the migration
- [x] Run service and support article migrations in prod (no need for local sync)
- [x] Let Adrienne/James know the migration has finished and provide broken links report
```

**Comment by briand44** [comment]
blocked until closer to launch.

**Comment by briand44** [comment]
Run on 9/3/2024. James will delete services and support articles after training Friday the 30th afternoon. Adrienne would like a list of broken links (we provided this when we ran it in dev, can't remember which migration that is part of). Give Adrienne/James a heads up when we are starting the migration.

**Comment by briand44** [comment]
Grooming conversation... We may want to run this locally beforehand since it has been awhile since we ran this. Also may want to review the original PR for these to see if there were notes about batch sizes or anything like that.

**Comment by pyrello** [comment]
Enabled ITS Migrate module in prod.
