### ISSUE TITLE
redirects for Critical Incident Management Plan website

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7798]
redirects requested:
 

- https://critical-incident-plan.sites.uiowa.edu/incident-response-strategies
  - This would redirect to https://safety.uiowa.edu/emergency-response-guide
- All other pages under https://critical-incident-plan.sites.uiowa.edu/
  - These would all redirect to https://safety.uiowa.edu/emergency-management
```[tasklist]
### Tasks
- [x] request the vulture redirects be setup
- [x] Assuming vulture redirects are approved/created, request TTL be lowered for criticial-incident-plan.sites.uiowa.edu
- [x] locally test redirects
- [x] Once Campus Safety approves timing of the switch, make sure it has been at least 24 hours after TTL has been lowered and request DNS to be pointed to vulture.
- [x] remove critical-incident-plan.sites.uiowa.edu website (don't reclaim DNS)
- [x] have hostmaster set TTL back to default
```

**Comment by briand44** [comment]
Requested TTL be lowered. Will update once that is done.

**Comment by briand44** [comment]
TTL lowered at 11:45am 6/14/24

**Comment by briand44** [comment]
Reached out to Campus Safety to understand if they still need to do some comms around this or if they are ready for us to update DNS next week.

**Comment by briand44** [comment]
Waiting to get feedback on when to make the switch so proper comms can happen ahead of time.

**Comment by briand44** [comment]
Created https://github.com/uiowa/uiowa/issues/8091 to remove the v2 site.
