### ISSUE TITLE
Law P2LB issue

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7805]
May make sense to work directly with them on any of the issues they are seeing and help get them to the finish line. Cleanup may still require programmatic solution but we may be able to be more aggressive with our solution.
```[tasklist]
### Tasks
- [x] Meet with Law to establish the need to conclude the conversion ASAP
- [ ] Work with them to determine what pages are still in need of help
- [ ] Fix stuff that needs to be fixed
```

**Comment by joewhitsitt** [comment]
I can start to push this forward

**Comment by joewhitsitt** [comment]
Sent an email with its-web cc'd asking if we can schedule a meeting, where they think they are in the process and if they have a goal date in mind.

**Comment by joewhitsitt** [comment]
We got a response back saying they are on-track for mid/end July and that a meeting around there would be good. From standup, I got a sense there is more immediate concern about the website.

For Law, I can suggest a meeting sooner so we can explain the remaining gap(s) if known. I can also offer conversion help if they are okay with sharing the editorial load. In the first email I told them to pay attention to the previous list of pages identified and told them to let us know if they experience similar issues.

**Comment by joewhitsitt** [comment]
Responded with more detail of the remaining risks, our desire for a swift and issue free transition, proper steps to avoid issues and another offer to meet earlier/help with transition.

~~Will schedule a meeting for mid-July as requested.~~ Got an immediate response and have a meeting for tomorrow setup.

**Comment by joewhitsitt** [comment]
Met with Laura today and provided some clues for the remaining gaps:

- Needs converting list
- authored date after April
- empty content blocks when going into edit while layout tab has content

Laura might restrict access or brief other editors to get through remaining list, either avoiding those problematic pages or deleting and recreating them now that the new pages get a proper indicator.

Offered support from our team to complete conversions, work through problematic pages.

**Comment by joewhitsitt** [comment]
Going to see about scheduling that mid/end-july meeting with Laura to see about getting this to done.
