### ISSUE TITLE
Hawktools.uiowa.edu redirect

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7807]
A landing page is going to be created on the ITS website for the new University of Iowa mobile app. They are asking us to redirect all traffic going to hawktools.uiowa.edu to this landing page once it is live. My understanding is that will be live prior to the app being available.

The other thing worth noting is that at one time computers in ITC's were imaged with hawktools.uiowa.edu as the default webpage for the browser. Not sure if this is still the case but if so, any concerns with this?
```[tasklist]
### Tasks
- [x] Request vulture redirect
- [x] test redirect locally
- [x] ask hostmaster to lower TTL
- [x] ask hostmaster to point DNS to vulture 24 hours after TTL lowered
- [x] Add hawktools.prod.drupal.uiowa.edu to 701
- [x] Create reminder to check in after 1 month
- [x] Set TTL back to default
```

**Comment by briand44** [comment]
I put in the request for the redirect and reached out to Hostmaster to have TTL lowered. Will update this once TTL has been lowered.

**Comment by briand44** [comment]
notified TTL was reduced at 10:30am 6/14/24

**Comment by briand44** [comment]
redirect is in place and tested.
