### ISSUE TITLE
arts.uiowa.edu vulture redirect

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7832]
Redirect arts.uiowa.edu and remove D7 site July 1st.

Redirect to https://performingarts.uiowa.edu/events

```[tasklist]
### Tasks
- [x] request vulture redirect
- [x] have hostmaster lower TTL for arts.uiowa.edu to 5 minutes
- [x] Test vulture redirect locally once it has been created
- [x] make sure it has been at least 24 hours after TTL has been lowered and request DNS to be pointed to vulture on 7/1/24.
- [x] confirm redirect is working
- [x] deprovision arts.uiowa.edu D7 site
- [x] Have hostmaster set TTL back to default for arts.uiowa.edu
```

**Comment by briand44** [comment]
submitted the request for the redirect and also asked hostmaster to lower TTL. Will update when I hear anything.

**Comment by briand44** [comment]
TTL lowered at noon on 6/24/24

**Comment by briand44** [comment]
blocked until 7/1/24

**Comment by briand44** [comment]
Redirect is working, d7 site removed, let Hostmaster know they can set TTL back to default since the D7 site has been removed and I can't foresee any reason we would need to update DNS even if something did go wrong.
