### ISSUE TITLE
Create academic calendar list

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7851]
# Story

As a visitor to registrar.uiowa.edu, I can view a list of academic calendar dates for the next 5 sessions that I can toggle display options to group by month, view chronologically, and view subsessions as well as filter using search, session type, start date, end date, category so that I can precisely find academic calendar dates and deadlines.

# Proposed solution

Needs to:
- Group by month and display date legend
- View chronologically without month grouping
- Toggle on/off subsessions for each display
- Filter by search
- Filter by session type
- Filter by start date
- Filter by end date
- Filter by category 

Also:

- meet WCAG 2.1 AA
- Filter out categories that don't appear on the calendar for performance improvement, see OFFERINGS_COMPLIANCE as an example category.
- Adjust api to reduce amount of events pulled in, something like currentDate <= firstSessionStartDate so that it doesn't pull in all events from the first session date and are sometimes over a year old?
- Make sure we are only pulling dates that `Is Web Display = Yes` and `Is reviewed`. Not sure what the actual API key|values are.
-  Setup callback to announce calendar date changes in the block l
- Any other items that are still relevant from the IS in https://github.com/uiowa/uiowa/issues/7823

https://github.com/uiowa/uiowa/assets/1036433/b9c951a8-4fa1-4c19-b846-91651a3794af

```[tasklist]
### Tasks
- [ ] https://github.com/uiowa/uiowa/issues/7853
- [ ] https://github.com/uiowa/uids/issues/934
- [ ] https://github.com/uiowa/uiowa/issues/7854
```

**Comment by briand44** [comment]
Grooming conversation... 

- JS probably makes sense here for the filters and such. 
- We think they want two separate pages for Academic Calendar and Dates by Session and since they have separate audiences, let's keep them separate. Grouping and how many sessions are displayed and allowed to filter by are the differences between the two.
- Prototype has quite a bit of this functionality already
- Five year calendar (separate slice) can be similar as well but will use MAUI 5 year dates and won't need all the filters.
- Discussed showing current months dates for the current session and forward. If they need to show past months dates for the current session we can visit that later.
- UIDS work for dates on cards (Hours functionality may invoke card through JS)? 
- If we wanted to split we could split the API work out of this as a separate slice.
- We will need to strip out full calendar parts of existing PR since that already has route controller and such (Ben going to push up what he has since he has stripped out FC stuff already).

Sean proposal 
- we should take the time to do UIDS work for the date card stuff (Commencement wanted this as well). Possible one slice - medium if just date part of this - if included card implementation probably large.
- Slice for API tweaks to only pull correct dates categories, etc.
- Front end display/searchin/filtering meets wcag 2.1 aa - potentially larger of the slices

**Comment by pyrello** [comment]
FWIW, I think that working on the API/backend adjustments and the UIDS implementation first makes the most sense. I think the third slice to refine the frontend implementation and make it ready for production is the most likely to change based on the other two slices, so it might make sense to hold on that last one until the other two are done.

**Comment by bspeare** [comment]
I got some feedback from the brand team on these mockups that might be useful as we move forward:

- Move filters to the top of the page instead of the sidebar to be more like https://sandbox.prod.drupal.uiowa.edu/people 
- Simplify the filters to remove so many options (Start Date and End Date)
- Maybe we don't color code the session badges and keep them all cool gray because the badge colors visually overpower the list
  - Or maybe these are just badges with outlines instead of background colors? 
- Change the date circle to an outline instead of solid gold background
- Visually group repeating dates by only displaying the circle date for the first item (Screenshot below)

<img width="806" alt="Screenshot 2024-07-08 at 2 42 52 PM" src="https://github.com/uiowa/uiowa/assets/1036433/9b8ed52d-53c3-4cf1-b468-e2c8dc6056d6">

**Comment by pyrello** [comment]
> Maybe we don't color code the session badges and keep them all cool gray because the badge colors visually overpower the list
> * Or maybe these are just badges with outlines instead of background colors?

I think a lot of valuable information is lost if these are not color-coded. It makes it really easy to see that you've started looking at a different set of information. Making them all the same color is just one step away from removing them entirely.
