### ISSUE TITLE
humanitiesandpubliclife.uiowa.edu vulture redirect

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa#7856]
Vulture redirect from https://humanitiesandpubliclife.uiowa.edu/ to https://uipress.uiowa.edu/series/humanities-and-public-life.

```[tasklist]
### Tasks
- [x] request vulture redirect
- [x] have hostmaster lower TTL for humanitiesandpubliclife.uiowa.edu to 5 minutes
- [x] Test vulture redirect locally once it has been created
- [x] make sure it has been at least 24 hours after TTL has been lowered and request DNS to be pointed to vulture on 6/28/24
- [x] confirm redirect is working
- [x] deprovision humanitiesandpubliclife.uiowa.edu v2/v3 site (don't reclaim DNS)
- [x] Notify Jenna H that site has been removed and redirect is in place
```

**Comment by briand44** [comment]
I think there are a couple missing steps in the task list. We will want to have Hostmaster lower TTL for humanitiesandpubliclife.uiowa.edu and after we have confirmed the redirect is working locally and 24hrs after TTL has been lowered, we need to have Hostmaster update DNS for humanitiesandpubliclife.uiowa.edu to point to vulture.its.uiowa.edu for the redirect to start working.

**Comment by bspeare** [comment]
Tested redirect locally and it is working.  We can make DNS request tomorrow after 10am.

**Comment by cory-skeers** [comment]
DNS update request has been made.
