### ISSUE TITLE
SiteNow July 2024 Newsletter

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa#7880]
## Issue/Solution

Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

Step-by-step instructions: https://docs.prod.drupal.uiowa.edu/sitenow-drupal-10/monthly-newsletter

```[tasklist]
### Tasks
- [x] Create draft
- [x] Add link to project board
- [x] Add updates, bugs, notable site launches
- [x] Get a team member to review
- [x] Publish article
- [x] Send dispatch communication
- [x] Create next month's issue
```

**Comment by e-marie-w** [comment]
Done!
