### ISSUE TITLE
Generate list of sitenow v1 standard sites that didn't meet the deadline

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7886]
# Story

As a web team, we would like to generate a list of SiteNow v1 standard sites that missed the Aug. 1 deadline so that we can share this list with leadership to see if they want to weigh in on how we move forward with these sites.
```[tasklist]
### Tasks
- [x] Generate list of sites that missed deadline
- [x] Include any relevant metadata (extension granted, etc.)?
- [ ] Share list with leadership
```

**Comment by briand44** [comment]
Grooming conversation... Cohort is people who requested a v3 site but haven't launched or still have a active v1 site. If we do say "Do something by x date", lets not penalize these folks because there may be a valid reason they didn't reach out or meet the deadline. Do we need to be communicating with the site requestors again or should we be generating the unit leaders population and sharing with leadership at this point. Could send a message saying "We noticed you missed the deadline, did something come up? Do you know longer need the site? Are you still transitioning?"

Decided to push this back a bit after the deadline to account for any folks trickling in at the last minute. Also decided this slice would be generating the list of sites that missed the deadline and sharing and getting feedback from leadership on if they want to weigh in on next steps.

**Comment by briand44** [comment]
Grooming conversation.. Alan adding an extension column to the spreadsheet so we can track that info consistently between sites. Sean mentioned some of these aren't specific dates and that we will be checking in with them in a certain amount of time.

Should we wait to do this until all extensions have passed?

Do we include all sites to leadership even if we have granted extension or do we just include sites that we haven't heard from that missed the deadline?

Michael shared the following as a potential future communication after we have the list for leadership:

> “We notice that you have not completed your migration to SiteNow v3. At this point, your D7 site is at risk of failing/not supporting. We’d like to do what we can to keep it running until your complete your migration, but we need to know how quickly you can finish your migration…”
> 
> Audience is people who haven’t finished, and we have not heard from/made plans with?

**Comment by joewhitsitt** [comment]
Here are my initial findings based on the spreadsheet:

# No request and previously identified and represented in Michael's spreadsheet
~apo.org.uiowa.edu~
globalwealth.law.uiowa.edu
~hackiowa.org.uiowa.edu~
~hawkeyeoptimistchapter.org.uiowa.edu~
m-ashley-spies.lab.uiowa.edu
~maps.org.uiowa.edu~
~rugby.org.uiowa.edu~
~shepherdgroup.lab.uiowa.edu~
~sigmaalphaiota.org.uiowa.edu~
~sits.org.uiowa.edu~
~uiowaclubglax.org.uiowa.edu~
~yaf.org.uiowa.edu~

# Seemingly launched but not deprovisioned

~ncbc.medicine.uiowa.edu~ deprovisioned
~strack.lab.uiowa.edu~ deprovisioned

# Redirected but not deprovisioned
~drivingassessment.uiowa.edu~ deprovisioned

# Extension notes
~hultman.lab.uiowa.edu~ - 8/16
michaelson.lab.uiowa.edu - 8/16
~ncbc.medicine.uiowa.edu (see launched above) - 8/15~ launched/deprovisioned
~parekh.lab.uiowa.edu~ - 8/30
victorianfboos.studio.uiowa.edu - 9/18

# Requested but remaining

accessibility101.course.uiowa.edu
~anthony.lab.uiowa.edu~
atasoy.lab.uiowa.edu
blsa.org.uiowa.edu
brogden.lab.uiowa.edu
campbell.lab.uiowa.edu
celp.org.uiowa.edu
chen.lab.uiowa.edu
clp.law.uiowa.edu
cssa.org.uiowa.edu
cui.lab.uiowa.edu
econsent.lab.uiowa.edu
english-society.org.uiowa.edu
fab.law.uiowa.edu
fisher.lab.uiowa.edu
geerling.lab.uiowa.edu
~hultman.lab.uiowa.edu~
ieee.org.uiowa.edu
lira.lab.uiowa.edu
masongroup.lab.uiowa.edu
matthew-arndt.sites.uiowa.edu
michaelson.lab.uiowa.edu
mil.lab.uiowa.edu
nasa.org.uiowa.edu
nhlp.law.uiowa.edu
niciu.lab.uiowa.edu
orsc-colloquium.sites.uiowa.edu
~parekh.lab.uiowa.edu~
pcit.lab.uiowa.edu
perception.lab.uiowa.edu
quelle.lab.uiowa.edu
radley.lab.uiowa.edu
rahmouni.lab.uiowa.edu
richerson.lab.uiowa.edu
rohlman.lab.uiowa.edu
roman.lab.uiowa.edu
sebag.lab.uiowa.edu
tedabel.lab.uiowa.edu
~tlcp.law.uiowa.edu (email about launching in its-web)~ launched 8/20/24
turkish.org.uiowa.edu
uisrmsymposium.sites.uiowa.edu
uitransalliance.org.uiowa.edu
usachev.lab.uiowa.edu
victorianfboos.studio.uiowa.edu

I am going to dig through some emails, check a few other sites in the spreadsheet to see if things are misclassified, etc.

**Comment by joewhitsitt** [comment]
Updated the spreadsheet related to ncbc.medicine.uiowa.edu as it looks to have launched on 8/14 (domain added to uiowa06) but left the extension note on there.

**Comment by briand44** [comment]
I removed drivingassessment.uiowa.edu D7 site and updated the spreadsheet. Waiting to hear back on ncbc and then will remove it and strack.lab

**Comment by briand44** [comment]
Added dates to https://github.com/uiowa/uiowa/issues/7886#issuecomment-2296783668 in the extension notes

**Comment by joewhitsitt** [comment]
Waiting to understand what format these results should be in and where to send it to.

**Comment by briand44** [comment]
deprovisioned strack, ncbc.medicine and tlcp.law

**Comment by briand44** [comment]
i discussed this with @mjoneill . We don't need to make this visible to leadership as part of this slice but would like to audit more to understand how far along they are in the process. Did they request a site but never create any content or are they actively creating new content and close to launch? I discussed this with @joewhitsitt and he thought he could tackle that piece of this work as part of this slice and would add that info to the spreadsheet in some manner. We don't need to worry about the sites that never requested or those that we already provided an extension for.

I will create another slice to identify unit leaders so we have that information for future communications.

**Comment by joewhitsitt** [comment]
I was thinking I could tackle the "more to understand how far along they are," but it would be nice to identify a scale of sorts because in the first handful of sites there is variation about where they are at.

- Someone log in since it has been created
- Addition/modification of content
- Recent activity (logins or content updates) since email campaign
- Some progress within the site but homepage still has demo content
- Basic info of who/what the site is furnished so it could launch even if incomplete
- Looks potentially launch worthy and comparable to their v1 site
- Etc..

At EoD it sounded like whatever the groupings would be that it would be good to get this into a separate column for easier filtering/counting.

So @mjoneill I was curious if you had more specifics about what you want to do with the data and how granular we should go so that we can classify things appropriately.

**Comment by joewhitsitt** [comment]
Talked with Michael and Brian this morning and I am going to capture a couple of criteria and then an overall score based on those. I'll see how far I get today, but the PO thought that this could spill over to #8006 and this issue could close at the end of the sprint.

**Comment by joewhitsitt** [comment]
Established new columns (Noticable progress, Login since June 2024, Potentially launch-ready) on the D7 spreadsheet to help generate an overall score for the site's transition off v1. Also added an internal-domain url column for easy referencing and have some generalized notes for sites.

Still have about 17 sites to check.

**Comment by joewhitsitt** [comment]
Finished going through the sites. Just need to fix the remaining d7 dynamic sheet

**Comment by joewhitsitt** [comment]
I was able to fix and include more columns in the Remaining D7 sheets.

To clarify, this slice addressed standard/active sites of the remaining d7 sheet that had requested a site, so initial filtering should happen there.
