### ISSUE TITLE
Feedback on Grants

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7895]
# Stories

We would like the ability to easily select all counties when creating a grant so that we don't have to choose each county individually when the grant applies to all.

For grants that apply to all counties, we would like a nice way to display the counties so it doesn't just display a huge long list.

We no longer need to associate specific cities with grants, that field can be removed.

We would like the Grants search by name to also search the purpose/mission text area so that users can more likely find the appropriate grants if they can't remember the name.

# Additional Info

They started not selecting all counties because of how those are currently output. Instead they put text to say available to all counties. The problem with this is those grants won't display to end users filtering by a specific county. They would like to choose all counties when applicable and have them show up when filtering by an individual county.
```[tasklist]
### Tasks
- [x] Ability to easily select all counties
- [x] Make sure counties display nicely if all selected
- [ ] remove cities from grants
- [x] the search by name should also search the purpose/mission text area
```

**Comment by briand44** [comment]
Grooming conversation... https://github.com/harvesthq/chosen/issues/1001

**Comment by bspeare** [comment]
Here's what the select all option looks like for counties.   Is this the expected behavior?

https://github.com/user-attachments/assets/ec57cc8f-9f25-4ebc-bfd9-bb344fd2dcbf

**Comment by briand44** [comment]
Looks good to me. When filtering by any county, this grant would show up, correct?

**Comment by bspeare** [comment]
@briand44 that is correct.
