### ISSUE TITLE
sort subsessions in academic calendar

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7897]
# Story

As a Registrar site owner, I would like subsessions to display in the appropriate order in the academic calendar list display and in the filter.

# Additional Info

Subsessions should display in the following order:

- 4 wk
- 6 wk I
- 6 wk II
- 8 wk
- 12 wk
```[tasklist]
### Tasks
- [ ] Determine whether this sorting can be done in PHP in the controller
- [ ] Add logic to sort events by date, by subsession order (specified above) within each date, and finally by alphabetical order if there are multiple events that exist in the same date and subsession type (in the controller if possible)
- [ ] Refactor frontend JS to accommodate keeping the sort order intact, if necessary
```

**Comment by joewhitsitt** [comment]
I imagine this will also be tricky processing like https://github.com/uiowa/uiowa/issues/7898#issuecomment-2220837989 in that we would need to first group by date, then check if the string starts with a number followed by "wk," extract the number, sort and prioritizing strings without for the first.

**Comment by briand44** [comment]
Grooming conversation... Lots of different ways to handle this (custom sort function, etc.). Sounded like we felt the api controller could potentially hold most of this vs the JS so it can take advantage of caching, etc. This is not a must have for launch so if this gets real complex we can discuss.

**Comment by briand44** [comment]
Closing this as not planned since we discussed tackling this work alongside the brand recommendations in https://github.com/uiowa/uiowa/issues/7898
