### ISSUE TITLE
Accessibility review/enhancements for gpa calculator

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7899]
# Story

As a web team and module maintainer, we would like ensure the gpa calculator meets wcag 2.1 aa requirements.

# Additional info

https://github.com/uiowa/uiowa/pull/7892#issuecomment-2218014464

>It looks like this gpa calculator table is just made of divs with table classes on it. Could we update the module to use table markup to make this accessible? Also, should the "Add row" link be a button to make this more accessible as well?

# Proposed solution

```[tasklist]
### Tasks
- [x] use accessibility tools to test for wcag 2.1 aa accessibiltiy
- [x] add accessibility fixes/enhancements
- [x] Add any additional design improvements
```

**Comment by briand44** [comment]
Grooming conversation... Possibly not use table markup? If we do go a different direction, there is now a stable release so we may need to add update hooks. Maybe use core form API for the add more button.

**Comment by bspeare** [comment]
Here's a couple of table based gpa calculators I found:
- https://registrar.uni.edu/students/gpa-calculator
- https://www.wku.edu/bep/gpacalculator.php

I also did a quick Voiceover for https://github.com/uiowa/uiowa/pull/7892 on the form vs table and the useful part of the table Voiceover seemed that it told you that you were on a field that was in row 2 of 4 whereas with the divs it just announces the selectable field.

**Comment by joewhitsitt** [comment]
During grooming I kept suggesting using core functionality for these but then couldn't come up with an existing example to work from/reference. Started down the path with the idea here, but ran out of time: https://iowaweb.slack.com/archives/C0406A9VB5L/p1720811463690899

**Comment by joewhitsitt** [comment]
Been dipping my toes more into the Form API approach:

![Image](https://github.com/user-attachments/assets/5f71469a-2da8-4480-bb8d-8e482b7b1fbc)

Still not quite working.

**Comment by joewhitsitt** [comment]
@e-marie-w created the upstream issue with initial accessibility concerns: https://www.drupal.org/project/gpa_calculator/issues/3462133

**Comment by joewhitsitt** [comment]
Was able to come back and make some commits. I think it is working now. https://www.drupal.org/project/gpa_calculator/issues/3462133#comment-15691954

<img width="930" alt="Screenshot 2024-07-19 at 5 34 10 PM" src="https://github.com/user-attachments/assets/1c922bda-676d-4f34-a7b9-ad01d936c986">

**Comment by joewhitsitt** [comment]
So I am a bit biased, but this is looking good to me. WebAIM, SiteImprove, Lighthouse all come back clean on a default drupal install. Tried to scan for additional issues related to d11 compatibility but haven't found any. 

There is a noticeable improvement for VoiceOver. Added more descriptive text for the add more button and the result of the callback.

Tabbing through the inputs, I wonder if there should be so many inputs by default.

Also compared the math to the current d7 version of the module with the same config as the registrar website.

**Comment by e-marie-w** [comment]
> Tabbing through the inputs, I wonder if there should be so many inputs by default.
> 
> Also compared the math to the current d7 version of the module with the same config as the registrar website.

We had an EoD discussion around this I don't think is captured anywhere. Basically, we decided on four as that is usually the minimum number of classes to be considered a full-time student. Empty rows are ignored so there are no extra clicks needed for fewer classes, and users with more will most likely only need to click add once or twice. I'm open to further discussion though!

**Comment by joewhitsitt** [comment]
Thanks for chiming in. Yeah I think that is fair.

**Comment by pyrello** [comment]
Going to review and test this again.

**Comment by pyrello** [comment]
Is VoiceOver supposed to be saying the `Drupal.announce` messages? Maybe there is a better way than VoiceOver to test the `aria` and `Drupal.announce` stuff. If so, let me know.

**Comment by joewhitsitt** [comment]
Normally I just keep the inspector source open and navigate down to the announce section. https://www.drupal.org/project/devel_a11y will output messages to the console for you if you add/enable it.

**Comment by pyrello** [comment]
I ended up reworking the module to use form validation and not use custom JS for that purpose. I included logic to shift the `Drupal.announce` stuff to the backend as well. I'm wondering if either @e-marie-w or @joewhitsitt would be willing to test this again?

**Comment by joewhitsitt** [comment]
I can take a look

**Comment by joewhitsitt** [comment]
Hmm. Pulled and reinstalled the module, placed the block. my module settings are now empty for the grade map.

<img width="1249" alt="Screenshot 2024-08-15 at 9 53 12 AM" src="https://github.com/user-attachments/assets/d554678b-2d15-4972-a0d5-3e4f81f2bdcf">

Did you adjust to allow decimals for the cumulative?
Not quite sure yet the issue with the letter grades.

**Comment by pyrello** [comment]
I'll take a look.

**Comment by pyrello** [comment]
> Did you adjust to allow decimals for the cumulative?

I added a step to the field to allow up to 2 decimal places. Is that enough?

> Not quite sure yet the issue with the letter grades.

I think it makes sense that there is no settings for the grades to start. It has a default fallback, so you only actually need to add a grade mapping if its different than the default. However, I had not adjusted the code completely related to how the grades get pulled in, so I think it was failing because it wasn't falling back to the default.

This is ready for testing again.

**Comment by joewhitsitt** [comment]
> > Did you adjust to allow decimals for the cumulative?
> 
> I added a step to the field to allow up to 2 decimal places. Is that enough?

IMO yes, but I've seen GPAs with more. I just mentioned it because of the error in the screenshot related to the field. It seems the recent changes have solved both of those issues.

**Comment by pyrello** [comment]
> but I've seen GPAs with more

We'll start with 2 and see if anyone wants it to be adjusted.

**Comment by joewhitsitt** [comment]
Noticed the "success" message announcing the calculated result is no longer, but that might have just been extra on my part. Other than that I think this is looking good.

**Comment by pyrello** [comment]
@joewhitsitt and I discussed the importance of the "success" a11y announcement. Its not clearly understood whether this would be considered a best practice so we are going to hold off for now on implementing it and revisit when we know more.
