### ISSUE TITLE
Run grant migration in dev

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7906]
# Story

As a webteam, we would like to run the Grants migration in a dev environment so Law INRC stakeholders have a chance to review the migration before we run it in production.

```[tasklist]
### Tasks
- [x] Setup site in dev environment
- [x] Delete any content that needs removed prior to migration
- [x] run migration in locally and sync to DB and files to dev site
- [x] add note about this dev site on https://github.com/orgs/uiowa/projects/20/views/1?pane=issue&itemId=22614984
- [x] communicate with Law INRC partners that this has run in dev
- [ ] Change telephone field to text field
- [ ] Check fax field to see if it needs to be a phone field
```

**Comment by briand44** [comment]
blocked until #7896 is completed.

**Comment by bspeare** [comment]
@cory-skeers I did find a couple telephone entries with multiple numbers for grants:

- https://inrc.law.uiowa.edu/grants/think-iowa-city
- https://inrc.law.uiowa.edu/grants/alliant-energy-foundation
- https://inrc.law.uiowa.edu/grants/hubbell-waterman-foundation
- https://inrc.law.uiowa.edu/grants/united-healthcare-childrens-foundation-inc

**Comment by cory-skeers** [comment]
> @cory-skeers I did find a couple telephone entries with multiple numbers for grants:
> 
> * https://inrc.law.uiowa.edu/grants/think-iowa-city
> * https://inrc.law.uiowa.edu/grants/alliant-energy-foundation
> * https://inrc.law.uiowa.edu/grants/hubbell-waterman-foundation
> * https://inrc.law.uiowa.edu/grants/united-healthcare-childrens-foundation-inc

Dang.

<img width="376" alt="image" src="https://github.com/user-attachments/assets/f0600297-236a-4479-860b-95a355f44b94">

The good news is the content comes over, so there's no data loss. But I think we'll want to update the phone field to allow multiple and do a little processing in the migration to split these out (and formatting consistency would be nice too).

**Comment by cory-skeers** [comment]
Doing a little exploration, there are quite a few ways the field ends up with more than 12 characters (xxx-xxx-xxxx or xxx.xxx.xxxx formatting)

<img width="242" alt="image" src="https://github.com/user-attachments/assets/9e4b6e05-0e89-4c0f-8613-1247812c394f">
<img width="248" alt="image" src="https://github.com/user-attachments/assets/25217232-c550-4e59-a94d-63061abde764">

Some of these aren't readily suited for a telephone field (eg included contact name), and may either need some info dropped and/or moved to another section, or change the field to text and lose the added benefit of using a phone-specific fieldtype (click-to-call, accessible labeling).

**Comment by pyrello** [comment]
I'm going to start working on this.

**Comment by pyrello** [comment]
> Delete any content that needs removed prior to migration

Would this just be any test grant content?

**Comment by briand44** [comment]
>Would this just be any test grant content?

Yeah, I didn't check to see if there was any test content for this, just a step I add for all migrations we run.

**Comment by pyrello** [comment]
Noting some things here that were relevant to this migration test and possibly future dev migration tasks:
- It appears that AC classic and ACN are not able to communicate (at least access one another's DB servers). This means that it is not possible to actually run the migration in dev. Instead, it is necessary to run it locally and then sync it (DB and files) into a fresh install.
- I encountered some weird behavior after syncing which essentially forced me to uninstall the `inrc_migrate` module (and related migration modules) to get it into a state that won't cause errors for future deployments. More details here: https://iowaweb.slack.com/archives/C0164FNN1PV/p1722547397679889?thread_ts=1722535987.252289&cid=C0164FNN1PV

**Comment by pyrello** [comment]
This is not completely done, but it is done in terms of the migrated content being reviewable on the dev website.

**Comment by bspeare** [comment]
Here's the grant guide page to review the migrated content: https://lawinrc.dev.drupal.uiowa.edu/iowa-grants-guide.

**Comment by bspeare** [comment]
Noticed that some grants have "$0" listed for grant sizes: https://lawinrc.dev.drupal.uiowa.edu/grants/nebraska-iowa-kiwanis-district-foundation - https://inrc.law.uiowa.edu/grants/think-iowa-city.

**Comment by joewhitsitt** [comment]
it was a required field in d7 so i imagine there are several if they previously crowd-sourced the content.

**Comment by briand44** [comment]
Moving the tasks related to phone fields to a separate issue (https://github.com/uiowa/uiowa/issues/7963) since we have already ran the migration in dev. We will want to discuss/tackle that work prior to running the migration in prod.
