### ISSUE TITLE
Run grant and nonprofit migrations in prod

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7907]
In https://github.com/uiowa/uiowa/issues/7906 and https://github.com/uiowa/uiowa/issues/7994 we ran the migrations in dev. These are now approved to run the migrations in prod.

Should be able to migrate from prod->prod since both Cloud Classic

```[tasklist]
### Tasks
- [x] Delete nonprofit organization content - currently 3 nodes https://lawinrc.prod.drupal.uiowa.edu/admin/content?title=&type=nonprofit_org&status=All&field_tags_target_id=&uid=
- [x] run migrations in prod `mim —all`
- [x] communicate to stakeholders
```

**Comment by briand44** [comment]
Blocked until we get the green light

**Comment by briand44** [comment]
Grooming conversation... `mim —all` worked fine for DEV and team suggests running both together.

**Comment by bspeare** [comment]
This is complete.
