### ISSUE TITLE
searchable filterable display of nonprofit organizations

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7914]
# Story

As a site owner for LAWINRC, I would like to have the ability to search and filter nonprofit organizations so that our visitors can learn about and connect with these nonprofit organizations.

# Additional Info

Their existing functionality has been working well for them and they would like us to develop this feature very similar to their existing functionality.

They want us to eventually migrate the ~800 nonprofit organizations from their current site.

https://inrc.law.uiowa.edu/register-accountability

```[tasklist]
### Tasks
- [ ] Block component that can be placed on layout builder page
- [ ] Search by organization name
- [ ] Filter by category - select multiple
- [ ] Filter by city - this is a nice to have and something they currently do not have. City from address
- [x] Display teaser which should include Organization Name (link), contact name, contact title, email, phone, address, website
```
