### ISSUE TITLE
Concept3D base layer updates - Winter 2024?

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7916]
Concept3D support article - https://help.concept3d.com/hc/en-us/articles/360001865534-How-Do-I-Make-Map-Updates

>We have a process called map updates where you request changes, and then I get a quote for the cost of the work and I send you a Statement of Work (SOW). Once the SOW is signed we complete the work. Typically this process takes about 4-6 weeks. We can do it for one building, or if you know of more updates coming down the road we can do them all at one time. 

Facilities requested changes https://github.com/uiowa/uiowa/issues/6575#issuecomment-2206992970
```[tasklist]
### Tasks
- [x] Remove South Quad
- [ ] Add Health Sciences Academic Building in old Lot 14 location
- [ ] Remove Grand Ave CT and houses and add Lot 14 new location
- [ ] Add Lot 53 at 307 Melrose Court
- [ ] Change Building Labels to new UI Healthcare branding standards - https://uihealthcare.org/ui-health-care-launches-first-phase-brand-update
- [x] Add Lot 73 expansion
- [x] Add Lot 48 expansion
- [ ] Add University of Iowa Health Care Downtown Campus
- [ ] Add University of Iowa Health Care North Liberty Campus
- [ ] Add new roads and landscape elements for Newton/Fountain Drive roundabout
- [x] Remove Continuing Education Facility
- [ ] Add Nonfiction Writing House
- [ ] Add State Hygienic Lab Addition
- [ ] Add Xtream Arena
- [ ] Add Public Policy Research Building name
- [ ] Add High Strength Waste Treatment Building 1820
- [x] Remove 401 Westcor Drive
- [ ] Add UIHC 2nd Street Warehouse
- [ ] Add 9 Melrose Place
- [ ] Add UIHC Iowa City Northgate Drive
- [x] Add UIHC Iowa City First Avenue
- [x] Add UIHC Coralville Oakdale Road
- [ ] Add UIHC Coralville Heartland Drive
- [ ] Add UIHC Warehouse East
- [ ] Add UIHC Office Building East
- [x] Remove Grandview Office Plaza
- [ ] Update East ADA Ramp Access to Van Allen
- [ ] Update "For The Kids Way" to be "Hawkeye Wave Way".
```

```[tasklist]
### Aesthetic updates
- [ ] Hawkeye Recreation Fields painted lines have changed during conversion from grass to turf. A Tigerhawk has also been added to the west fields
- [ ] Relocate High Adventure Course to Hawkeye Recreation Fields
- [ ] Pearl Softball Field batting cages moved and updated branding on field
- [ ] Add Expansion onto UIHC Centralized Emergency Power Generation Facility
- [x] Remove Old Laundry Building and Landscape Garages – Buildings have been removed but are low impact for visitors
- [ ] ChildServe Building and parking lot expansion
- [x] Kirkwood Regional Center parking lot expansion
- [ ] Update Gibson Square layout
- [ ] Update Seashore Green layout
- [ ] Add Madison Street Patio
- [ ] Add Tiger Hawk logos at Jefferson St and Market St on T. Anne Cleary Walkway
```

## Proposed Solution
- Follow the linked article to make/mark the changes listed above, grabbing information from the facilities site when needed.

**Comment by pyrello** [comment]
Grooming conversation:
- Do images already exist for all updates? For previous round, yes. Joe was voluntold to bike around and take photos, if necessary.
- Items that are not point updates can be marked on the map per linked article to indicate the change to Concept3D.

**Comment by briand44** [comment]
A late addition from Tricia (OSC). For the Kids Way was changed to Hawkeye Wave Way earlier this week.

**Comment by GaryRidgway** [comment]
Grooming discussion...
- More on us this time, can use the article linked above to do the work.
- How do we get the needed data?
    - We could look on facilities
    - google satellite?
    - what fields do we need for each building?
    - can we ask facilities for help with constructing data?
    - building images for concept3d for their artists.

**Comment by GaryRidgway** [comment]
### Checklist for changes
- [x] Remove South Quad
- [x] Add Health Sciences Academic Building in old Lot 14 location
- [x] Remove Grand Ave CT and houses and add Lot 14 new location
- [x] Add Lot 53 at 307 Melrose Court
- [x] Add Lot 73 expansion
- [x] Add Lot 48 expansion
- [x] Add University of Iowa Health Care Downtown Campus
- [x] Add University of Iowa Health Care North Liberty Campus
- [x] Add new roads and landscape elements for Newton/Fountain Drive roundabout
- [x] Remove Continuing Education Facility
- [x] Add Nonfiction Writing House
- [x] Add Xtream Arena
- [x] Add High Strength Waste Treatment Building 1820
- [x] Remove 401 Westcor Drive
- [x] Add UIHC 2nd Street Warehouse
- [x] Add 9 Melrose Place
- [x] Add UIHC Iowa City Northgate Drive
- [x] Add UIHC Iowa City First Avenue
- [x] Add UIHC Coralville Oakdale Road
- [x] Add UIHC Coralville Heartland Drive
- [x] Remove Grandview Office Plaza
- [x] Update "For The Kids Way" to be "Hawkeye Wave Way".
- [x] Hawkeye Recreation Fields painted lines have changed during conversion from grass to turf. A Tigerhawk has also been added to the west fields
- [x] Remove Old Laundry Building and Landscape Garages – Buildings have been removed but are low impact for visitors
- [x] ChildServe Building and parking lot expansion
- [x] Kirkwood Regional Center parking lot expansion
- [x] Update Seashore Green layout
- [x] Add Tiger Hawk logos at Jefferson St and Market St on T. Anne Cleary Walkway

### More info needed
Move items here if we need more info
- [x] Change Building Labels to new UI Healthcare branding standards - https://uihealthcare.org/ui-health-care-launches-first-phase-brand-update
    - Not sure what labels are being referenced here? Unsure what buildings to change? What is the intended change?
- [x] Add Public Policy Research Building name
    - Not sure what name this is referencing? Was there a previous name? I can't find an address or visuals.
- [x] Add State Hygienic Lab Addition
    - Where is this addition? Do we have an address and visuals for this?
- [x] Add UIHC Warehouse East
    - Not info on facilities about this building, unsure of its location. Do we have an address? Do we have pictures or visuals?
- [x] Add UIHC Office Building East
    - Not info on facilities about this building, unsure of its location. Do we have an address? Do we have pictures or visuals?
- [x] Update East ADA Ramp Access to Van Allen
    - Do we have any pictures or visuals of the new ramp?
- [x] Relocate High Adventure Course to Hawkeye Recreation Fields
    - Can't find previous location, and can't find pictures of new location. What should the update add to the recreation fields? what type of render are we expecting? [Could only find this](https://recserv.uiowa.edu/ui-challenge-course#course-information)
- [x] Pearl Softball Field batting cages moved and updated branding on field
    - Can't find any visual confirmation of what this looks like, Do we have photos? locations?
- [x] Add Expansion onto UIHC Centralized Emergency Power Generation Facility.
    - Can't find any visuals of the expansion. Do we have anything for this?
- [x] Add Madison Street Patio
    - Is this the patio on the top of the Rec Center? Not sure of location.
- [x] Update Gibson Square layout
    - Does this update include new sidewalk structures? some more detail would be nice.

**Comment by briand44** [comment]
I let our client success manager know about the requested changes.

**Comment by briand44** [comment]
Closing this as we have submitted these to Concept3D. We can re-open or create a new issue if there are additional renders or imagery needed.
