### ISSUE TITLE
Setup uiowa08 Cloud Next application

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7929]
# Story

As a web team, we would like to setup a new application so that we can test out parallel deployments so that we can get our deployment times below an hour so we can update to Cloud Next for all our applications.

# Additional Info

Docs on setting up a new application - https://docs.prod.drupal.uiowa.edu/acquia-cloud

We will want to reference the docs but some adjustments will be needed since we want to use a fork of the codebase https://github.com/uiowa/uiowa/issues/7800#issuecomment-2168171602.

# Scope

Scope to getting app setup with forked repo. Additional work to run parallel updates can happen in a future slice as part of https://github.com/uiowa/uiowa/issues/7800
```[tasklist]
### Tasks
- [x] Setup uiowa08 similar to other applications
```

**Comment by pyrello** [comment]
Grooming conversation:
- Is this what we should be doing with this application (vs. just starting to populate sites). Yes
- We will need to get to an eventual point where we have multiple sites to test running things in parallel. We will nee3d to decide whether these are test sites or real sites. However, we don't need to figure this out yet for this slice.
- Discussed forked repo vs. feature branch. Feature branch would be easier maintenance (a workflow we are used to) to keep the branch in sync with a changing `main` branch. Forked repo introduces new workflows for staying in sync. Forked repo is cleaner and we could otherwise use our normal deployment process.

**Comment by briand44** [comment]
Additional points of conversation during grooming:

- Thinking more long term, can we swap repos on an application easily once we are done working on parallel deployments or will we need to blow up the app once we are done testing?
- We will need to update configuration so that deployments won't go out to other applications

**Comment by briand44** [comment]
Since this isn't something we've done before and with multiple senior devs out during grooming of this, we chose to keep the scope limited and not define a specific proposed solution to allow for feedback from folks when they return. We thought just setting up an app is a medium so we decided to size this as a large because of the unknowns.

**Comment by joewhitsitt** [comment]
Part of the reason I was thinking of forking instead of feature branch is because I imagine our work will ultimately go beyond #7800 to removing BLT (EOL) and possibly replacing Travis (cost compared to Github Actions and integration with BLT via blt-travis)

I think we should also limit what we setup for the application and we may want wipe the app fresh at some point and start putting real sites on it (log forwarding, ssl certs, new relic/slack)

**Comment by joewhitsitt** [comment]
Given that we will probably be touching \Uiowa\Blt\Plugin\Commands\ReplaceCommands::replaceDrupalUpdateAll to handle parallel processing of sites, I wonder if we should be tackling the BLT part too.

So far the guides of moving off BLT though have not been as much of a dive as we are deep in it..

**Comment by pyrello** [comment]
I'm not too concerned about the BLT EoL. Its not like other parts of our system that directly interface with outside systems. We don't have much, if any, security exposure from using it and as far as I can tell, it still works. Removing it is going to be a lot of work because its a lot of things we take for granted that will have to be replaced or we'll have to adopt new workflows. For what we are trying to do here, I think its not needed and maybe a bit of a distraction. Let's tackle this later.

**Comment by joewhitsitt** [comment]
If we don't expand to do more than parallelization at this time then I think this can just be a normal app setup and we can use a feature branch for https://github.com/uiowa/uiowa/issues/7800

**Comment by pyrello** [comment]
> If we don't expand to do more than parallelization at this time then I think this can just be a normal app setup and we can use a feature branch for #7800

I think we need some more discussion around this. I don't understand how we would test the whole deployment process with just a feature branch. I'm not saying it couldn't be done, but I think we would have to essentially create fake releases and make sure they only go to `uiowa08` so that they don't accidentally get triggered on another app.

**Comment by briand44** [comment]
Grooming conversation... If keeping this scoped to parallelization we may be able to get by with a feature branch, there should just be a few changes. Don't want to deploy to all apps just uiowa08. Could use develop for testing. 

Sounds like there is more discussion to figure out exact details on the parallelization but for now let's setup this application as normal and hold off on adding any sites to it until we have done some testing on parallelization. Brian also to check about the HC UCEDD application.

**Comment by joewhitsitt** [comment]
Noticed that uiowa07 prod didn't match advanced config set on uiowa so while adjusting uiowa08, i did uiowa07 too.

**Comment by joewhitsitt** [comment]
Can we delete the platform email config for icgov?

**Comment by joewhitsitt** [comment]
Seeking approval for https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/merge_requests/127 and https://github.com/uiowa/uiowa/pull/7952

**Comment by joewhitsitt** [comment]
Holding on log forwarding for a bit until we can move forward with https://github.com/uiowa/uiowa/issues/7929#issuecomment-2265983793

**Comment by joewhitsitt** [comment]
~~[Pending a successful push to develop via travis](https://app.travis-ci.com/github/uiowa/uiowa/builds/271726411#L8341)~~, I think remaining items are:

- [x] log forwarding
- [x] switch code to branches for dev/stage
- [x] tag release/deploy
- [x] install default site on each env

everything else in the doc should be covered.

**Comment by joewhitsitt** [comment]
setup log forwarding similar to uiowa07 prod and sent an email to its-splunk@uiowa.edu notifying them of the addition.

**Comment by joewhitsitt** [comment]
default sites have been installed. prod is using main-build until a tag is created/deployed

**Comment by joewhitsitt** [comment]
I believe this is done. As mentioned in EoD the real test would be provisioning a site on the application to see if everything is hunky-dory.

Log forwarding might need the secret cert added to work.
