### ISSUE TITLE
Redirect https://i3hsa.org.uiowa.edu/ to OEHSAI.org.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7939]
redirect needs to be set up on vulture, then we can de-provision this.

```[tasklist]
### Tasks
- [x] request the vulture redirects be setup
- [x] Request TTL be lowered for i3hsa.org.uiowa.edu
- [x] locally test redirects once created
- [x] make sure it has been at least 24 hours after TTL has been lowered and request DNS to be pointed to vulture.
- [x] communicate to customer in its-web thread
- [x] add i3hsa.org.uiowa.edu to site removal issue (don't reclaim DNS)
- [x] have hostmaster set TTL back to default
```

**Comment by briand44** [comment]
Vulture redirect in place, tested locally. Sent email to Hostmaster to update DNS.
