### ISSUE TITLE
run iwp media gallery migration in dev

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7940]
# Story

As a webteam, we would like to run the IWP media gallery migration in a dev environment so IWP stakeholders have a chance to review the migration before we run it in production.

```[tasklist]
### Tasks
- [x] re-sync prod to dev (dev site already exists from previous migration)
- [x] Delete any resource content that needs removed prior to migration
- [x] run migration in dev
- [x] add note about this dev site on https://github.com/orgs/uiowa/projects/20/views/1?pane=issue&itemId=22614984
- [x] communicate with IWP partners that this has run in dev
```

**Comment by briand44** [comment]
blocked until https://github.com/uiowa/uiowa/issues/7920 is closed.

**Comment by briand44** [comment]
Recently we've had to run migrations locally first and then sync to dev because of issues communicated from cloud classic to cloud next. Probably need to do that here as well.

**Comment by pyrello** [comment]
> Recently we've had to run migrations locally first and then sync to dev because of issues communicated from cloud classic to cloud next. Probably need to do that here as well.

More details about what happened with our last dev migration here: https://github.com/uiowa/uiowa/issues/7906#issuecomment-2264053049

We may want to update the proposed solution because it is not going to fit what actually needs to be done.

**Comment by cory-skeers** [comment]
This has been completed. 

https://iwp.dev.drupal.uiowa.edu/media-gallery
