### ISSUE TITLE
Upgrade v2/v3 to use PHP 8.3

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/uiowa#7955]
8.1 Security Support is until 31 Dec 2025. Active support ended in 25 Nov 2023

Drupal 10.3 supports 8.1, 8.2, 8.3

Drupal 11 does not support PHP 8.1

https://www.php.net/supported-versions.php

https://www.drupal.org/docs/getting-started/system-requirements/php-requirements
```[tasklist]
### Tasks
- [x] Change local `config.yml ` to new PHP version and restart ddev
- [x] Run `ddev blt tests:deprecated`
- [x] Possibly update `phpstan.neon` with level 2 setting
- [x] Run in PhpStorm `Code | Analyze Code | Run Inspection by Name | Deprecated`
- [ ] Check for what's changed in https://www.php.net/manual/en/migration82.php,  https://www.php.net/manual/en/migration82.incompatible.php, https://www.php.net/manual/en/migration82.deprecated.php.
- [x] Add PHP uptick for ddev config, composer and travis
- [x] Update the PHP version in the DEV environments and click through sites
- [x] Run `ddev blt validate:phpcs` - this should be checking 8.1 and higher already based on https://github.com/uiowa/uiowa/blob/main/phpcs.xml#L9
- [x] Update `acquia/coding-standards`
```

**Comment by briand44** [comment]
Grooming conversation... If there aren't too many deprecations we could consider going to 8.3 but it might make more sense to not tackle all at once and focusing on getting to 8.2 first. We'll want to update dev first before moving forward with other environments. Sean mentioned we could change the php version in ddev to help understand the number of changes. Size is largely unknown at this point of grooming but team suggested sizing as a medium and if we quickly learn it is larger we can resize.

**Comment by bspeare** [comment]
So far I've tested locally by adjusting `config.yml` to run 8.2:

-  `ddev blt tests:deprecated`
    -  Suggested updating `lazy` module
    - Errors on the rest of the code base are the same as when run with 8.1 with level 2 set on `phpstan.neon`
      - 500+ errors on modules/custom and sitenow profile
-  Run in PhpStorm `Code | Analyze Code | Run Inspection by Name | Deprecated`
    - Nothing marked as deprecated but it did find and example that I placed from https://www.php.net/manual/en/migration82.deprecated.php for testing purposes
- Synced a few sites and noticed `media_entity_facebook` errors and have updated that module

**Comment by joewhitsitt** [comment]
I don't know if we should increase scope but I noted on Friday that acquia/blt-phpcs which we use is deprecated and all of the dependencies within have been updated. `phpcompatibility/php-compatibility`, `acquia/coding-standards`, `squizlabs/php_codesniffer`

Did you run into the `drupal/config_inspector` errors on `drupal-sync`?

The PR should also contain the PHP uptick for ddev config, composer and travis.

>If there aren't too many deprecations we could consider going to 8.3

Since 8.2 doesn't seem so bad, should we up it to 8.3?

Have you updated the php version in the DEV environments?

**Comment by bspeare** [comment]
Thanks for the additional suggestions @joewhitsitt!  Do I just update the php version on the DEV environments and click through the sites there?

**Comment by joewhitsitt** [comment]
>Do I just update the php version on the DEV environments and click through the sites there?

Historically, we would do more development in DEV/STAGE (v1 custom) and set the php version early to naturally raise issues that might otherwise have been missed. Since we don't forward logs or even run cron, for anything to crop up outside of deployment, it will require site interaction. Ultimately, we will want them set for when the prod environment is also set, so it could just be a step in that direction for now.

**Comment by bspeare** [comment]
> Did you run into the drupal/config_inspector errors on drupal-sync?

Can you share what error you are seeing there and the command you are running?

**Comment by joewhitsitt** [comment]
my terminal history doesn't go that far back, but I think it was this: https://www.drupal.org/node/3394232

syncing the default or sandbox website

**Comment by bspeare** [comment]
Thanks.  I'm not seeing that error but I can update the module.

**Comment by bspeare** [comment]
@joewhitsitt can you point me to where/how I would update `phpcompatibility/php-compatibility`, `acquia/coding-standards`, `squizlabs/php_codesniffer`?

**Comment by joewhitsitt** [comment]
so anything that would be updated via updating acquia/blt-phpcs should be considered as that is what we are using to test `blt validate:phpcs`

https://github.com/acquia/blt-phpcs/blob/master/composer.json#L14

https://github.com/acquia/coding-standards-php/blob/develop/composer.json#L20-L23

Since acquia/blt-phpcs is a dev composer dependency they would be added with the --dev flag (e.g. ddev composer require  --dev ...)

I don't know what part all of these play, but I know that phpcompatibility/php-compatibility was not up to date last time we were sorting out issues.
