### ISSUE TITLE
academic dates block should display dates that are "reviewed" and "printDate"

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7962]
# Story

As a Registrar Office, we would like the academic dates block to display dates that are "reviewed" and "printDate" so that is aligns with the academic calendar.

# Additional Info

The Academic dates block component that we originally developed for Grad College as part of the uiowa_maui port should also be checking that dates are "reviewed" = TRUE and "printDate" = TRUE similarly to how the academic calendar is.

Josh brought this up as they are using this block on the [Commencement website](https://commencement.uiowa.edu) and noticed some dates shouldn't be displaying. They said this change should happen for the service knowing it will affect dates being displayed on Grad College and Housing websites.

Example of current academic dates block.
![Image](https://github.com/user-attachments/assets/16749451-23c4-4197-8f9b-900e19cdaa7c)

How it should appear, similar to academic calendar.
![Image](https://github.com/user-attachments/assets/6016fc50-fa85-4d82-b048-d764274d44cb)

```[tasklist]
### Tasks
- [x] Get a list of sites using this feature
- [x] Communicate the upcoming changes to the sites with this feature enabled
- [x] update to only display dates where `reviewed = true` and `printDate = true`
- [x] Give Josh a heads up before this gets deployed
```

**Comment by briand44** [comment]
Josh asked us to hold on this while they meet with the calendar team next week to discuss the downstream impact of this.

**Comment by joewhitsitt** [comment]
Confirmed by https://github.com/uiowa/uiowa/issues/8186

**Comment by briand44** [comment]
Grooming conversation... Change should be pretty small. Josh was supposed to send us some dates that he would expect not to show. Brian can follow up with Josh on this about examples and what if any communication has happened. Should we be communicating this to others using this? We should. Lets get a list of the sites the feature is enabled for and then we can send an email to those contacts.

**Comment by joewhitsitt** [comment]
`./vendor/bin/blt ume "config:get config_split.config_split.uiowa_maui status"` - reference: https://github.com/uiowa/uiowa/blob/main/blt/src/Blt/Plugin/Commands/MultisiteCommands.php#L71

SSH into each v2/v3 app (uiowa, uiowa01, ... uiowa09), `cd ../` and running this should fetch you the info for the list.

**Comment by briand44** [comment]
Added screenshots to the IS for examples to test against.

**Comment by james917** [comment]
List of results using UI Maui feature
registrar.uiowa.edu
basbls.uc.uiowa.edu
grad.uiowa.edu
commencement.uiowa.edu
housing.uiowa.edu

**Comment by joewhitsitt** [comment]
So next step is to identify these site owners and emailing them about the change and to contact Josh H. for more info correct @briand44?

Josh H. for commencement and registrar
Makur J. for grad.uiowa.edu
Annette B. for basbls.uc.uiowa.edu?
Josie N. for housing.uiowa.edu?

**Comment by briand44** [comment]
>and to contact Josh H. for more info

Not sure about this.

We won't need to contact Josh about Commencement and Registrar as he is aware these changes are coming. We just need to give him a heads up when we know when this is getting deployed. I am happy to do that.

We do want to communicate to the other sites using this though.

**Comment by joewhitsitt** [comment]
To be fair how are we supposed to communicate the changes here when we only really know the developer side of the terminology? I figured Josh would be able to explain what this means for content owners more.

"We are writing to inform you about upcoming changes to the Academic Dates block on your website. These changes were requested by the Office of the Registrar and it is our understanding that these adjustments are intended as a fix to improve the accuracy of the dates displayed. If you notice any dates missing after these changes are implemented that are important in the context of your website, please contact us."

Update: Tweaked the message above without calling out a contact at the Registrar ^^

**Comment by briand44** [comment]
Blocked until we know when our next deployment is. Once we know when the deployment will be occurring, Brian will communicate to  https://github.com/uiowa/uiowa/issues/7962#issuecomment-2486738639

**Comment by briand44** [comment]
Sent comms to Josh as well as contacts identified in https://github.com/uiowa/uiowa/issues/7962#issuecomment-2486753012
