### ISSUE TITLE
LAWINRC Updates to Grants and Nonprofits

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7963]
# Requested Updates

**Adjust phone fields for grant migration**
As part of https://github.com/uiowa/uiowa/issues/7906 we found there were some possible issues with the phone and fax fields. We should address these issues prior to running the migration in prod.

https://github.com/uiowa/uiowa/issues/7906#issuecomment-2237061156
https://github.com/uiowa/uiowa/issues/7906#issuecomment-2237245211

**Update placeholder text for Grant Search**
LAWINRC has asked if we can update the placeholder text on https://lawinrc.prod.drupal.uiowa.edu/iowa-grants-guide to say "Search Grants" rather than "Grantor Name".

**Training Notes on NPO's**
LAWINRC has asked if we can add an additional field to the Register by Completed Training section on NPO's for Traning Notes. This would be a text area and would be displayed on an NPO full node display.

**Submit an Update button on NPO and Grant nodes**
LAWINRC has asked if we can add a button on NPO nodes to "Submit an Update" which would link to their webform https://lawinrc.prod.drupal.uiowa.edu/form/submit-organization-update and pass in the url of the node that is requesting to be updated. Click the Submit an Update button on https://inrc.law.uiowa.edu/non-profit-organizations/abbe-center-community-mental-health for an example of how it is currently working.

Similar functionality needed on Grant nodes. "Submit an Update" button that links to https://lawinrc.prod.drupal.uiowa.edu/form/funder-update and passes in the node url to the webform.

```[tasklist]
### Tasks
- [x] Change telephone field to text field
- [x] Check fax field to see if it needs to be a phone field
- [x] Update placeholder text for Grant Search
- [x] Add training notes field on NPO content type and display on full node
- [x] Add Submit an Update button to NPO nodes
- [x] Add Submit an Update button to Grant nodes
```

**Comment by briand44** [comment]
Grooming conversation... We decided to leave the Submit your organization/Submit a new grant off the nodes for now and they have the ability to add these to the filterable landing pages. Brian to add the link to the grant webform.
