### ISSUE TITLE
SiteNow August 2024 Newsletter

### ISSUE THREAD

**Issue by e-marie-w** [uiowa/uiowa#7969]
## Issue/Solution

Provide a "release notes" type article of finished/done features/updates and publish to website, then send out dispatch email.

Step-by-step instructions: https://docs.prod.drupal.uiowa.edu/sitenow-drupal-10/monthly-newsletter

```[tasklist]
### Tasks
- [x] Create draft
- [x] Add link to project board
- [x] Add updates, bugs, notable site launches
- [x] Get a team member to review
- [x] Publish article
- [x] Send dispatch communication
- [x] Create next month's issue
```

**Comment by e-marie-w** [comment]
Draft: https://sitenow.uiowa.edu/news/2024/08/updates-august-2024

**Comment by joewhitsitt** [comment]
Looks fine to me. I was surprised at how little was general SiteNow facing this month. We did also focus on the standard sites, but with no outcome yet post deadline, I am not sure it is worth bringing up.

**Comment by pyrello** [comment]
Next month: #8044
