### ISSUE TITLE
run npo migration in dev

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7994]
# Story

As a webteam, we would like to run the LAWINRC NPO migration in a dev environment so LAWINRC stakeholders have a chance to review the migration before we run it in production.

```[tasklist]
### Tasks
- [x] re-sync prod to dev? (dev site already exists but has grant migration which prod does not)
- [x] Delete any nonprofit organization content that needs removed prior to migration
- [x] run migration in dev (will need to run locally and sync since cloud next to cloud classic)
- [x] add note about this dev site on https://github.com/orgs/uiowa/projects/20/views/1?pane=issue&itemId=22614984
- [x] communicate with INRC partners that this has run in dev
```

**Comment by briand44** [comment]
Grooming conversation... If we sync down before running we could run `migrate --all` so the grants migrated content won't get lost.

**Comment by briand44** [comment]
Blocked until #8002

**Comment by joewhitsitt** [comment]
Thinking about this a bit: 

- [x] Will need to get develop up to date with main.
- [x] I should then create a backup of inrc dev since we will be re-running the grant migration?
- [x] sync db and file inrc.prod to dev.
- [x] devdesktop sync prod to local.
- [x] enable migrate stuff
- [x] delete dummy content
- [x] then sync from v3 dev to local (sql-drop/cr first) without doing a cim. 
- [x] delete any existing local files and rsync files from dev. 
- [x] configure for local migration and run with --all flag.
- [x] spot check. 
- [x] sync db and files back up to dev. 
- [x] spot check

**Comment by joewhitsitt** [comment]
ack! and when getting develop up to snuff, include the ITS feature branch ✅

**Comment by joewhitsitt** [comment]
ran into the config diff issue when syncing from local to dev. going to try again, but this time enable the migrate stuff in dev before syncing down.

**Comment by joewhitsitt** [comment]
not sure if this was seen in development or testing earlier (inrc_nonprofit):

```
392/784 [==============>-------------]  50% [warning] foreach() argument must be of type array|object, string given NestedArray.php:327
 [warning] foreach() argument must be of type array|object, string given NestedArray.php:327
 [warning] foreach() argument must be of type array|object, string given NestedArray.php:327
 [warning] foreach() argument must be of type array|object, string given NestedArray.php:327
 [warning] foreach() argument must be of type array|object, string given NestedArray.php:327
 [warning] foreach() argument must be of type array|object, string given NestedArray.php:327

```

**Comment by joewhitsitt** [comment]
local to dev syncing had the same config diff errors related to the following config:

```
core.extension
migrate_drupal.settings
migrate_plus.migration.inrc_nonprofit_redirects
migrate_plus.migration.inrc_nonprofit
migrate_plus.migration.inrc_grant_redirects
migrate_plus.migration.inrc_grant
config_split.config_split.inrc_migrate 
```

But the content is there and the everything else seems to be working fine.

**Comment by joewhitsitt** [comment]
Communicated with Paul and Diane that the migration was run in DEV and cc'd Brian.
