### ISSUE TITLE
Vulture redirect - mentalhealth.uiowa.edu to wellbeing.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7997]
They want both sites to remain for ~one month, but eventually need a vulture redirect from mentalhealth.uiowa.edu to wellbeing.uiowa.edu. ITS-web calendar has a reminder to check in with them about the site on 9/16/24.

```[tasklist]
### Tasks
- [x] request the vulture redirects be setup
- [x] Assuming vulture redirects are approved/created, request TTL be lowered for mentalhealth.uiowa.edu
- [x] locally test redirects
- [x] Once Well Being approves timing of the switch, make sure it has been at least 24 hours after TTL has been lowered and request DNS to be pointed to vulture.
- [ ] deprovision or create deprovision issue for mentalhealth.uiowa.edu website (don't reclaim DNS)
- [ ] have hostmaster set TTL back to default
```

**Comment by briand44** [comment]
redirect has been created on vulture. Tested locally. Requested TTL be lowered.

**Comment by briand44** [comment]
TTL lowered as of 9/5 at 2pm

**Comment by joewhitsitt** [comment]
So sorry, I didn't connect the dots with this issue. @bewoldt had reached out separately to its-web about requesting Vulture redirects for policy.studentlife.uiowa.edu and mentalhealth.uiowa.edu. After the fact it sounds like Brandon had made these requests on top of our request. Anyway, the vulture redirects were put in place, DNS was re-pointed 9/5 and I setup a calendar reminder about the SiteNow internal-domains for 6-months (Mar 5). Since then it sounds like @benlewzz had some concerns about some printed URLs and was looking different options to handle some pages.

**Comment by briand44** [comment]
Closing based on ^^.
