### ISSUE TITLE
Vulture redirect - https://ace.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#7998]
Hello Web Team,

We are moving a service from the ITS-OTLT team to the Office of the Provost. OTLT is taking care of their own web presence for this, but I have been doing the https://ace.uiowa.edu/ website.

If possible, I’d like to do a redirect for this site to: https://provost.uiowa.edu/how-use-spot until October 31st, 2024. Beginning Sept. 9th. This will give people time to know that ACE is turning into SPOT and that the web presence is now on the Office of the Provost website. I have everything I need off of the site so I don’t think we need to keep any of it “live” except a redirect page.

Also, is there a way to scan the UI website and look for links to the ace website? Or when you do these things do you send something to the web listserv to tell people to do their own? Either way, we can’t do this until at least Sept. 9th because the communication will be broadly going out from Provost by then so we don’t want it to be done prematurely.

I may unpublish a bunch of pages on the current site. I have already deleted some.

If there is anything else you need or have questions if I didn’t explain very well, please let me know. Be glad to get on a call.

-----

Update 8/19/24: Redirect should point to https://provost.uiowa.edu/end-course-student-feedback/student-perceptions-teaching-spot and be set up for one year.

```[tasklist]
### Tasks
- [x] request the vulture redirects be setup to redirect ace.uiowa.edu and all subpages to https://provost.uiowa.edu/end-course-student-feedback/student-perceptions-teaching-spot
- [x] Assuming vulture redirects are approved/created, request TTL be lowered for ace.uiowa.edu
- [x] locally test redirects
- [x] Once partners are ready for the redirect to be live after 9/9/24, make sure it has been at least 24 hours after TTL has been lowered and request DNS to be pointed to vulture.
- [x] deprovision or create deprovision issue for ace.uiowa.edu (don't reclaim DNS)
- [x] have hostmaster set TTL back to default
```

**Comment by e-marie-w** [comment]
Sent request to lower TTL to 5 minutes for ace.uiowa.edu to hostmaster. The Cherwell ticket for the Vulture redirect is number 2271535.

**Comment by e-marie-w** [comment]
Just got an email that the Vulture redirect is set up!

**Comment by briand44** [comment]
I tested locally and it is redirecting.

**Comment by briand44** [comment]
blocked until 9/9

**Comment by briand44** [comment]
Evidently DNS was updated this morning. I created an issue to deprovision https://github.com/uiowa/uiowa/issues/8055.

**Comment by briand44** [comment]
Let hostmaster know it is probably safe to set TTL back to default. Closing.
