### ISSUE TITLE
ITS requests

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8005]
From James H.

> We have a few additional requests for the ITS website that came out of the training we had today.
> 
> Can you please remove the required alert title field from that template? It is confusing as the title is actually populated by the selected service / building / additional title details.
> We need draft state functionality on support articles and service pages. We wanted the 'review' state removed, but we still need the draft state and the published state. So...not a complete removal of the moderation state, but an alteration of the moderation state. Please let me know if I need to describe this better.
> 
> Thanks to those of you who joined us in the training today and thank you for your help with this.

-----

Joe's notes

> My notes from attending ITS editors training (8/21)
> 
> - Draft option desired for service and support articles. Wait for discussion with James/Adrienne
> - Alerts calendar is not displaying
> - Alert title field is showing again in form display settings...
> - Desire for building abbreviations to speed up entry (possibly append abbr to option label for autocomplete)
> - From its-web email related to ITS alerts workflow - Change alert workflow labels and/or transitions so that it is either "draft" or "submit" instead of "draft" or "review"?
> - UIDS syntax highlighting to make use of the CKEditor code block feature
```[tasklist]
### Tasks
- [x] Remove alert title field from displaying when adding/editing alert content
- [x] Add moderation for support articles and services with a "draft" and "published" state but no "review" state
- [x] Fix issue with alerts calendar not displaying
- [x] Change alert workflow labels/transitions to "draft" and "submit"
- [x] Create issue about code block
```

**Comment by briand44** [comment]
Grooming conversation... Sounds like the site improve error may not have anything to do with the calendar not showing. Decided to hold on the building abbreviations and the syntax highlighting since those requests didn't come from the ITS team. Likely some questions related to the moderation requests still. We removed moderation from services while adding the ability to replicate. They never answered Joe's question about transitioning alerts from "Published" to "Submit".

**Comment by joewhitsitt** [comment]
Realized I was the cause for the calendar no longer rendering... By removing the hardcoded footer legend in favor of the new block plugin in the previous round of updates, full calendar didn't have the right kind of views output to attach to.. Added a `&nbsp;` to always render for now.

**Comment by joewhitsitt** [comment]
So looking back at the moderation issue, we removed it because the needs review state was the point of friction.

https://github.com/uiowa/uiowa/issues/7930#issuecomment-2257060545

The way the task is worded/requested:

>Add moderation for support articles and services with a "draft" and "published" state but no "review" state

**We are looking at a third workflow for this site beyond the default editorial and alert workflows.**

The replicate stuff was just noise we wanted to test/confirm that an editor could not replicate a service even though they are able to do so for other content types.

**Comment by joewhitsitt** [comment]
Related to the alerts workflow, this seems to be the same friction described in https://github.com/uiowa/uiowa/issues/2879

**Comment by joewhitsitt** [comment]
Small slack discussion: https://iowaweb.slack.com/archives/C0164FNN1PV/p1724422745589649

In preparation for a meeting with ITS, I am going to push up a "draft/publish/archived" workflow to the PR to show/confirm that is what they need over the default editorial workflow.

**Comment by joewhitsitt** [comment]
Having issue with config/moderation on the entity_view_display. Can't remember what the trick is to getting moderation control blocks on these with a proper uuid

update: though I didn't figure it out, it seems to be working fine with `uuid: ''`

**Comment by joewhitsitt** [comment]
Had a meeting with ITS and based on issues with editor permissions and the default editorial workflow, the proposed third workflow seemed like a good idea.

**Comment by joewhitsitt** [comment]
Oops. Closed with the merge of https://github.com/uiowa/uiowa/pull/8009
