### ISSUE TITLE
run npo migration in prod

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8010]
In https://github.com/uiowa/uiowa/issues/7994, we ran the migration in dev. Once approved, we need to run the migration in prod.

Should be able to migrate from prod->prod since both Cloud Classic.
```[tasklist]
### Tasks
- [ ] Delete any content prior to running - currently 3 nodes https://lawinrc.prod.drupal.uiowa.edu/admin/content?title=&type=nonprofit_org&status=All&field_tags_target_id=&uid=
- [ ] Run migration in prod
- [ ] Communicate with stakeholders
```

**Comment by briand44** [comment]
Blocked until we get the green light

**Comment by briand44** [comment]
Combining into one issue https://github.com/uiowa/uiowa/issues/7907 so closing this.
