### ISSUE TITLE
Setup uiowa09 Cloud Next application

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8060]
# Story

As a web team, we would like to setup a new application so that we can provision sites on it.

# Additional Info

Docs on setting up a new application - https://docs.prod.drupal.uiowa.edu/acquia-cloud

https://github.com/uiowa/uiowa/issues/7929

Teams have been assigned permissions to this application.

```[tasklist]
### Tasks
- [x] Setup uiowa09 similar to other applications
- [x] work with ISPO on log forwarding for uiowa08 (likely have EIPs to allowlist)
- [x] Setup uiowa09.stage and follow the docs
```

**Comment by briand44** [comment]
We probably want to wait until we are notified by Acquia that this application is ready.

**Comment by briand44** [comment]
Grooming conversation...  Production EIPs will need allowlisted by ISPO for log forwarding (uiowa08 and uiowa09). Cert stuff will also need added in Acquia Cloud for log forwarding (not sure if uiowa08 is done or not).

**Comment by bspeare** [comment]
`uiowa09.stage` is ready to setup.  I have added a new checkbox to the tasklist and moving this out of blocked/waiting and back to top of backlog.

**Comment by joewhitsitt** [comment]
I see https://github.com/uiowa/uiowa/pull/8154 was merged. Looks like there are some other items (auth, cloud UI, etc.) to do.

**Comment by joewhitsitt** [comment]
https://git.uiowa.edu/its-web/data.its.uiowa.edu/-/merge_requests/130

**Comment by joewhitsitt** [comment]
It looked like some config/vars/stuff was retained or set up by someone else. Added the SSL cert, installed the default site, set up secrets file, updated auth. I think this is done and ready to go.
