### ISSUE TITLE
2+ week decommissioning plan for coronavirus website

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8089]
We have some key pages on the coronavirus website that we want to redirect to new destinations elsewhere on campus. The goal is that we add redirects to these pages, give Google 2 weeks to pick up the signal, then decommission the coronavirus website entirely.

2 week timer starts after pages are redirected and sitemap for coronavirus.uiowa.edu site is resubmitted in google search console.

* https://coronavirus.uiowa.edu/returning-campus/showing-symptoms redirects to https://studenthealth.uiowa.edu/covid-19
* https://coronavirus.uiowa.edu/testing-information redirects to https://studenthealth.uiowa.edu/covid-19
* https://coronavirus.uiowa.edu/vaccine-information redirects to https://studenthealth.uiowa.edu/covid-19

After 2 weeks:
* Decommission coronavirus website entirely
* vulture redirect all coronavirus traffic to https://studenthealth.uiowa.edu/covid-19.  Duration 1 year or whatever their standard is.

Tagging @briand44 and @mkyoder 

```[tasklist]
### Tasks
- [x] create the three redirects listed above in Drupal
- [x] resubmit sitemap to google
- [x] add reminder for 2 weeks to update DNS for the vulture redirect
- [x] submit request for vulture redirect
- [x] ask hostmaster to lower TTL for coronavirus.uiowa.edu
- [x] test vulture redirects locally once created
- [x] after the 2 week period, have hostmaster update DNS
- [x] ask hostmaster to set TTL to default
- [x] deprovision coronavirus website
```

**Comment by mkyoder** [comment]
I just set up all three of these redirects and they don't seem to be working. I tested them in Google Incognito mode and cleared my browser history. Did I do this incorrectly @briand44 ?

![Image](https://github.com/user-attachments/assets/f28254d0-d207-426c-ba3c-74cb37992838)

**Comment by briand44** [comment]
@mkyoder I created the redirects for those three pages using the rabbit hole functionality so that those pages don't have to be deleted. You should be good to submit the sitemap to Google. https://coronavirus.uiowa.edu/sitemap.xml

**Comment by mkyoder** [comment]
@briand44 Sitemap submitted on 9/23/24 at 10:50 a.m. 

![Image](https://github.com/user-attachments/assets/eb306147-e49f-495c-8453-fea5539567f0)

**Comment by briand44** [comment]
TTL lowered to 5 minutes
