### ISSUE TITLE
htaccess redirect for writinguniversity.uiowa.edu and www.writinguniversity.uiowa.edu

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8143]
These redirects currently live on the grad application. They want these redirects to remain once the grad app is gone.

Discussed in PL and since long term we would like the site to live at writinguniversity.uiowa.edu, we determined that it may make sense to redirect this using .htaccess rather than vulture so we don't need to update DNS multiple different times.

Michael mentioned no leadership capacity to have the conversations at this time to start moving to writinguniversity.uiowa.edu rather than writinguniversity.org.

```[tasklist]
### Tasks
- [x] cover writinguniversity.uiowa.edu and www.writinguniversity.uiowa.edu in uiowa01 ssl cert
- [x] add htaccess redirect that will redirect writinguniversity.uiowa.edu and www.writinguniversity.uiowa.edu to writinguniversity.org (might be able to copy from grad htaccess) - *note - currently if you go to writinguniversity.uiowa.edu/about it redirects to writinguniversity.org/about and not to the home page.
- [x] move www.writinguniversity.uiowa.edu and writinguniversity.uiowa.edu domains from grad app to uiowa01
```

**Comment by joewhitsitt** [comment]
Noticed `humanities.uiowa.edu` is still covered and pointing at acquia but was deprovisioned. https://github.com/uiowa/uiowa/issues/5286
Noticed `coronavirus.uiowa.edu` and `www.coronavirus.uiowa.edu` are covered but was deprovisioned/redirected.

Going to clean up as this app already has a lot of SANs

**Comment by joewhitsitt** [comment]
Sent an email to hostmaster to reclaim humanities.uiowa.edu

**Comment by joewhitsitt** [comment]
Always forget we patch htaccess. Can't remember if we have docs on that...

Update: We do now! https://docs.uiowa.ddev.site/development-workflow/updating-patched-htaccessdevelopmentservicesrobotstxt-files

**Comment by joewhitsitt** [comment]
Also, I think the old rule is covering writinguniversity.net. We don't need that anymore right?

```
RewriteCond %{HTTP_HOST} ^(www\.|)writinguniversity\.(net|uiowa\.edu)$ [NC]
RewriteRule ^(.*)$ https://www.writinguniversity.org/$1 [L,R=301]
```

```
RewriteCond %{HTTP_HOST} ^(www\.|)writinguniversity\.uiowa\.edu$ [NC]
RewriteRule ^(.*)$ https://www.writinguniversity.org/$1 [L,R=301]
```

**Comment by briand44** [comment]
>Also, I think the old rule is covering writinguniversity.net. We don't need that anymore right?

Correct, that points to Vulture.

**Comment by joewhitsitt** [comment]
Waiting for a deployment

**Comment by joewhitsitt** [comment]
@briand44 can I try re-pointing the domains anytime now that a deployment has gone out?

**Comment by briand44** [comment]
Go for it! Not sure if you saw this note previously or if you copied the .htaccess rule over...

>*note - currently if you go to writinguniversity.uiowa.edu/about it redirects to writinguniversity.org/about and not to the home page.

**Comment by joewhitsitt** [comment]
Yeah, supposedly that still works: https://htaccess.madewithlove.com?share=d3b59ae4-e928-4ceb-b550-ef9cf6e54e71

🤞

**Comment by joewhitsitt** [comment]
I think it still works!

https://www.writinguniversity.uiowa.edu/about-us/writing-iowa
https://writinguniversity.uiowa.edu/writers

also removed the .net domains from the grad app.
