### ISSUE TITLE
Redirect for dei.athletics.uiowa.edu/ to diversity.uiowa.edu/.

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8164]
Would redirecting the old https://dei.athletics.uiowa.edu/ to https://diversity.uiowa.edu/ Be a vulture redirect? And should I be waiting for the redirect to be created and the sea name to be repointed before the provisioning the old DEI site?

```[tasklist]
### Tasks
- [x] request the vulture redirect be setup to redirect dei.athletics.uiowa.edu and all subpages to https://diversity.uiowa.edu/
- [x] Request Hostmaster lower TTL for dei.athletics.uiowa.edu
- [x] locally test redirect once setup on Vulture
- [x] make sure it has been at least 24 hours after TTL has been lowered and request DNS to be pointed to vulture.
- [x] have hostmaster set TTL back to default for dei.athletics.uiowa.edu
- [x] deprovision or create deprovision issue for dei.athletics.uiowa.edu(don't reclaim DNS) (uiowa02)
- [x] Contact Wendy D that site has been removed
```

**Comment by GaryRidgway** [comment]
Issue [[ 2337457 ]](https://serviceagent-iowa.uiowa.edu/CherwellClient/Access?_=3151a08a#1)

**Comment by briand44** [comment]
TTL was lowered to 5 minutes on 10/29

**Comment by joewhitsitt** [comment]
Looks like 2337457 has been assigned but not completed.

**Comment by briand44** [comment]
tested the redirect locally and appears to be working for me. Going to move forward with the DNS request.

**Comment by joewhitsitt** [comment]
i can try to move this forward

**Comment by briand44** [comment]
I have a thread with hostmaster about TTL, I can follow up on that when we are ready.

**Comment by joewhitsitt** [comment]
I think TTL increase can happen now right? It has been a bit. Thanks!

**Comment by briand44** [comment]
Does Wendy know the redirect is in place and working now? Was hoping to wait until we had at least communicated with her in case there was some sort of WAIT NOOO.

**Comment by briand44** [comment]
I found a thread in its-web. I will email her and let her know the redirect is in place and we are moving forward with removing the site.

**Comment by joewhitsitt** [comment]
Okay, there was a ticket in cherwell too 2330681. I can close that when all is done and communicated.

**Comment by briand44** [comment]
Emailed her and got a thank you response so lets move forward.
