### ISSUE TITLE
Upgrade crow/vulture

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8173]
>Good morning, as part of the ongoing Ubuntu migration, we are currently ready to start working on crow.its.uiowa.edu and vulture.its.uiowa.edu.  When you have time, could you please start this process by going to https://workflow.uiowa.edu/form/request-server
>Please note that you will need a current MFK as part of this process.  Also the Active Directory group that you would like to use for this project will also be needed.
>If you have any questions, or if you wish to have anyone else added to this email list, please let me know.
>I look forward to working with you on this project!
>Trevor Youngberg

----

The form has been submitted for both Crow and Vulture.

----

> As you are aware, we are in the process of migrating our systems from CentOS 7 to Ubuntu. This migration is crucial due to the end of support for CentOS 7, which means it will no longer receive updates or security patches, leaving our systems vulnerable.
>  
> Background on the Migration:
> 1.      End of Support: CentOS 7 is no longer supported, meaning it won't receive updates or security patches, leaving systems vulnerable. We are mitigating this risk with third-party support, but our goal is to fully migrate to Ubuntu by January 1, 2025.
> 2.      Tool Compatibility: Many tools and platforms are deprecating support for CentOS 7, increasing the workload for our IT teams and hindering progress on new tools and features available in Ubuntu.
> 3.      Internal Resource Constraints: With many servers already migrated to Ubuntu, supporting multiple operating systems is hindering progress on other projects.
> 4.      We aim to have everything migrated and tested by the end of the year. The MAS team is targeting to hand systems off by the end of November, providing at least a month for your teams to finish testing. Our original target date was June 30th, 2024, so we greatly appreciate your cooperation in helping us reach our new target of January 1, 2025.
> We have identified your teams as key participants in this testing phase. Your team may or may not have testing in your queue at this time, but once we hand off systems for testing, your team’s cooperation and timely feedback is greatly appreciated. Please prioritize this task and allocate the necessary resources to complete the testing within the given timeframe.
>  
> If you have any questions or need further assistance, please do not hesitate to reach out.

---

Sounds like the Crow replacement (csi-005.its.uiowa.edu) and the Vulture replacement (csi-012.its.uiowa.edu) are ready for us.

```[tasklist]
### Tasks
- [ ] https://github.com/uiowa/uiowa/issues/8263
- [ ] https://github.com/uiowa/uiowa/issues/8348
- [ ] https://github.com/uiowa/uiowa/issues/8385
- [ ] https://github.com/uiowa/uiowa/issues/8428
- [ ] https://github.com/uiowa/uiowa/issues/8438
- [ ] https://github.com/uiowa/uiowa/issues/8439
- [ ] https://github.com/uiowa/uiowa/issues/8437
- [ ] https://github.com/uiowa/uiowa/issues/8440
- [ ] https://github.com/uiowa/uiowa/issues/8523
```

**Comment by briand44** [comment]
Grooming conversation... Try switching php version on local ddev to match version of new servers (php 8.1) to see what breaks? Any incompatible projects with that version of php, Composer should tell us. Then we can see if we need to update laravel or other dependencies. Probably won't be able to test scheduled deployments until in prod and probably not crucial that this is working flawlessly day 1. Will want to test local routes (documented in data.its readme) to make sure not white screening. First slice of testing against php8.1 size as medium so folks that don't have a working local of this can take the time to get that setup.

**Comment by briand44** [comment]
>We have added dataits to both servers and moved over the .ssh keys to the new servers and added that user to the ad group.   You should be able to use that user like you  used to for that service account.

**Comment by briand44** [comment]
Grooming conversation... Discussed possibly switch DNS for data-test.its.uiowa.edu to point to csi-005.its.uiowa.edu. We would want to test non-prod authentication there. We may need to check with IAM to understand if there is any concerns with the server move from their end being able to consume the metadata on the new servers. Thank You program is not on DEV to test so we can only test that on csi-012.its.uiowa.edu with local host file changes. Verify routes still work in dev environment (not expecting issues here). D7 metadata generator is only on csi-012.its.uiowa.edu so won't be able to test this if we update the data-test.its.uiowa.edu domain. Discussed sizing this slice as a medium for unknowns and previous experiences with this work.

**Comment by joewhitsitt** [comment]
Just stepped through the envoy deploy for csi-005. I don't think tests are working as they used to. I imagine we need to change up a bit with the move away from Lumen. That might be another slice:

`./vendor/bin/phpunit --exclude-group large`

```
An error occurred inside PHPUnit.

Message:  Class "Laravel\Lumen\Testing\TestCase" not found
Location: /local/www/vhosts/data-test.its.uiowa.edu/tests/TestCase.php:3
```

**Comment by joewhitsitt** [comment]
If we want to keep

```
php artisan config:cache
    php artisan route:cache
    php artisan view:cache
```

then we might need to implement per route cache limits. i had to hard refresh my browser to get the latest forecast

**Comment by joewhitsitt** [comment]
I can implement https://github.com/uiowa/uiowa/issues/8546#issuecomment-2767112607 before I close #8546, but I think some next steps would be:

- lower ttl for data.its, check prod routes post-deploy to make sure they are still running.
- understand the go-live with sys admins, hostmaster, vulture redirects (kept up to date?)
- go live, immediately test auth (d7, v2/v3, uihc), thank you program
- confirm schedule job is firing.
- try a low risk scheduled deployment.
- ??
- profit!

**Comment by briand44** [comment]
Scheduled some time to discuss the switchover with the EI-SAS folks. 

>lower ttl for data.its

I think we'll need to also understand what other DNS entries will need updating and get TTL lowered for those as well (vulture.its.uiowa.edu?, entries pointing to vulture.its.uiowa.edu for redirects?, anything pointing to the IP address 128.255.103.24)

Sounds like EI-SAS is willing to schedule changeover (along with TTL updates) with Hostmaster.

**Comment by briand44** [comment]
Closing this as we migrated to the new servers!!!
