### ISSUE TITLE
Enable contact feature on a few sites

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8175]
In sprint demo, the following sites requested that we enable the contact feature for them.

- dentistry.uiowa.edu - Viki
- intradent.dentistry.uiowa.edu - Viki
- education.uiowa.edu - Jean

```[tasklist]
### Tasks
- [x] enable contact feature on dentistry.uiowa.edu
- [x] enable contact feature on intradent.dentistry.uiowa.edu
- [x] Let viki know ^^ has been done
- [x] enable contact feature on education.uiowa.edu
- [x] communicate with Jean that ^^ is done.
```

**Comment by joewhitsitt** [comment]
Oops. could have proofread the dentistry email a bit more and cc'd myself on the education email, but this is done.
