### ISSUE TITLE
Send comms to remaining v1 standard sites

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8177]
# Story

As a member of the web team, we would like to communicate that any remaining v1 SiteNow Standard sites will be deactivated after our final deadline if they haven't finished their transition or let us know they no longer intend to transition.

# Additional Info

In #8018 we identified the list of sites, unit leaders and created a draft of the communication to share with leadership. If we get leadership approval, we should send this communication to contacts and unit leaders.
```[tasklist]
### Tasks
- [x] update draft comms to link to https://sitenow.uiowa.edu/sitenow-v1-standard-platform-shutdown https://github.com/uiowa/uiowa/issues/8018#issuecomment-2444894129
- [x] update deadline in draft comms to fall on a work day we are comfortable with (Dec 1st is a Sunday)
- [x] Create Dispatch population
- [x] Send test to its-web@uiowa.edu
- [x] send comms to contacts and unit leaders
```
