### ISSUE TITLE
Remove last updated functionality from Final exam schedule

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8185]
# Story

As a Registrar site owner, we no longer need the last updated date included in the Final Exam Schedule functionality.

# Additional Info

![Screenshot 2024-10-29 at 2 54 35 PM](https://github.com/user-attachments/assets/5c51d4cc-f08a-4cef-b4e6-19798166432d)

![Screenshot 2024-10-29 at 2 55 18 PM](https://github.com/user-attachments/assets/ef84c5d1-8772-4432-9c5b-da0f39319071)

```[tasklist]
### Tasks
- [x] Remove last updated date from display
- [x] Remove last updated field from block config
- [x] Remove any other code related to the last updated functionality for Final Exam Schedules
- [x] Probably need to re-save the block once we remove this field
```

**Comment by joewhitsitt** [comment]
Can this be closed? @cory-skeers ?

**Comment by cory-skeers** [comment]
> Can this be closed? @cory-skeers ?

Yes! I replaced the block in prod to get rid of the extraneous data, so this should be good to close now.
