### ISSUE TITLE
update to use v4 of actions/cache

### ISSUE THREAD

**Issue by briand44** [uiowa/uiowa#8339]
https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/

> Starting February 1st, 2025, Actions’ cache storage will move to a new architecture, resulting in the deprecation of v1-v2 of [actions/cache](https://github.com/actions/cache). Attempting to use a version of the action after the announced deprecation date will result in a workflow failure. Please note: if you are pinned to a specific version or SHA of the action, your workflows will also fail after February 1st. We strongly encourage you to update your workflows to begin using v3 or v4 of actions/cache as soon as possible.
```[tasklist]
### First slice
- [ ] https://github.com/uiowa/viewbook-law/issues/49
```

```[tasklist]
### Additional Slices
- [ ] https://github.com/uiowa/admissions-viewbook/issues/81
- [ ] https://github.com/uiowa/admissions-next-steps/issues/28
- [ ] https://github.com/uiowa/vuejs-site-template/issues/29
```

**Comment by joewhitsitt** [comment]
https://github.com/search?q=org%3Auiowa+actions%2Fcache%40v2&type=code

**Comment by briand44** [comment]
Grooming conversation.. Previous dependency updates related to Github actions went smooth and basically just changing version. It will apply to UIDS, brand icons, viewbooks. If no API changes, we may just be able to update the version and see if we have any issues. If we do need to do further testing it could take some time as we will need to trigger the actions. Let's not do uids first. Scope the first slice to viewbook-law.

**Comment by james917** [comment]
I believe these are all done.
